### ISSUE TITLE
[1.0.0-preview.3] NullReferenceException on PS4 controller buttons

### ISSUE THREAD

**Issue by Saucy** [Unity-Technologies/InputSystem#1001]
Hi. I get an exception and a null reference when I press the button(s) on a DualShock 4 controller I have connected to my computer on a new/empty scene using Player Input Manager.

`Exception 'NullReferenceException' thrown from state change monitor 'InputActionState' on 'Button:/DualShock4GamepadHID/buttonSouth'`
`NullReferenceException: Object reference not set to an instance of an object`

Unity version: 2019.3.0f3
InputSystem version: 1.0.0-preview.3

Steps to reproduce:
1. Have a controller connected
2. New scene, add an empty gameobject
3. Add Player Input Manager-script to the empty gameobject
4. Change "Join behavior" to "Join players when join action is triggered"
5. Check Use Reference
6. Add InputActionReference asset
  6.1. My input asset is setup as: Added an Action map "Player", added action "JoinGame"
  6.2 Set Action Type on the action to Button, add Press (Press Only) interaction
  6.3 Add binding: Button South [Gamepad]
7. Play game and press the south button on the gamepad
8. Errors occurs

![unity_error_input-system_200114](https://user-images.githubusercontent.com/2084555/72371738-462deb00-3705-11ea-9770-e44a78efee98.png)

**Comment by stefanunity** [comment]
I tried to rebuild this but didn't manage to trigger that exception you are seeing. Could you be so nice to submit a bug report with a repro project through the editor please and ping the case number here?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
