### ISSUE TITLE
Enable Custom InputPorcessor to use player data (camera)

### ISSUE THREAD

**Issue by WaynGames** [Unity-Technologies/InputSystem#1003]
Hello,

I'm experimenting with the new input system in making a little tank game.
To aim hte tank turret I use pointer (mouse) but I want to also support game pad and for me the best way to do so is to convert the Vector 2 output of the game stick and using a custom processor, I convert it to a screen pointer coordinate from the center of the screen using the camera.

```
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;
 
#if UNITY_EDITOR
[InitializeOnLoad]
#endif
public class ToPointerPosition : InputProcessor<Vector2>
{
 
#if UNITY_EDITOR
    static ToPointerPosition()
    {
        Initialize();
    }
#endif
 
    [RuntimeInitializeOnLoadMethod]
    static void Initialize()
    {
        InputSystem.RegisterProcessor<ToPointerPosition>();
    }
 
 
    Camera m_Camera;
 
    public override Vector2 Process(Vector2 value, InputControl control)
    {   if (m_Camera == null) m_Camera = Camera.main;
        value.x = (value.x + 1) * m_Camera.scaledPixelWidth / 2;
        value.y = (value.y + 1) * m_Camera.scaledPixelHeight / 2;
        return value;
    }
}
```

This works great as long as I have only one main camera.
For local multiplayer with split screen, I have no idea how to get the player's camera from there.

Any idea on how to solve that use case ?

I either need to access the camera from the processor or have a way, when consuming the InputAction.CallbackContext, to figure out that i'm not processing a pointer vector2 but a stick vector2.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
