### ISSUE TITLE
PS4 controller can't be detected in playstation. 

### ISSUE THREAD

**Issue by yangguosdxl** [Unity-Technologies/InputSystem#1004]
PS4 controller can't be detected in playstation. 

Editor 2019.1.14f1
InputSystem 1.0.0 preview 3
Project InputDeviceTester

the GamePad.current is always none.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!

**Comment by Rene-Damm** [comment]
@yangguosdxl Note that you need the PS4 package installed for the controller to work on PlayStation. The package is available from the Unity section on the PS4 DevNet forum accessible to license holders.

**Comment by Rene-Damm** [comment]
Sidenote: the core system should really spill a warning when building for a console and the console-specific package is not there. I've added a note to our backlog to that effect.
