### ISSUE TITLE
Could the PlayerInputEditor not be marked internal?

### ISSUE THREAD

**Issue by OscarAbraham** [Unity-Technologies/InputSystem#1005]
Hi. Thank you very much for your time. I know there are probably a lot of good reasons for the editors being defined as internal. I would love if the PlayerInputEditor could be inherited from. Here is my case: 

There have been a considerable amount of times where I've made things easier for myself by implementing a class that inherits from PlayerInput, even though I had to implement its own editor, because it can still be managed by the PlayerInputManager,  and it still can handle different users and maps. 

Right now, though, I need to be able to inherit from the editor too to make an idea work. I've been making a package that implements, among other things, the idea of parameter references as ScriptableObjects proposed in the famous 2017 talk by Ryan Hipple (https://youtu.be/raQ3iHhE_Kk). I'm adding the functionality of directly linking a parameter to an input action. It would be awesome if I could add that functionality to a class that inhereits from PlayerInput; it would be less clutter and I could make it more performant. 

The thing is, I want it to be useful to many users, so I need the interface to look the same (with some extras at the end) as the normal PlayerInput that everyone uses in many different ways. Only if I could inherit from the PlayerInputEditor, I could guarantee that the interface is going to be consistent in the future, plus it would be easier and cleaner. So, is there anyway it could not be internal? :)

I'll understand if it's not possible. Thank you very much for your time; this package is awesome. I hope you have a very nice day.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
