### ISSUE TITLE
mouse scroll/wheel, have half-axis buttons on the scroll axes

### ISSUE THREAD

**Issue by builder-main** [Unity-Technologies/InputSystem#1006]
We really need mouse wheel to be usable as buttons :) 

The team already tagged this as "REVIEW", is there an easy work around till next release ?
Best

Line 43 in Mouse.cs 
 ////REVIEW: have half-axis buttons on the scroll axes? (up, down, left, right)
```c#
  ////REVIEW: have half-axis buttons on the scroll axes? (up, down, left, right)
        /// <summary>
        /// Scroll-wheel delta of the mouse.
        /// </summary>
        /// <value>Scroll wheel delta.</value>
        /// <seealso cref="Mouse.scroll"/>
        [InputControl(displayName = "Scroll")]
        [InputControl(name = "scroll/x", aliases = new[] { "horizontal" }, usage = "ScrollHorizontal", displayName = "Scroll Left/Right")]
        [InputControl(name = "scroll/y", aliases = new[] { "vertical" }, usage = "ScrollVertical", displayName = "Scroll Up/Down", shortDisplayName = "Wheel")]
        [FieldOffset(16)]
        public Vector2 scroll;
```

**Comment by Rene-Damm** [comment]
Hi @MorphiksBuilder, could you give a few more details about your use case? Like, what kind of action you'd want to trigger from it and how?

I'm particularly interested in how you'd want to the buttons to behave. Would they go 1 as long as there is activity in the respective direction or would they be axes that reflect the actual *value* in the given direction? Another aspect is the resetting which will likely make the button behave somewhat surprisingly as deltas get reset at the beginning of every update.

For working around it, this kind of thing can usually be done easily with a "layout override" like, for example:

```CSharp
        // As on/off button.
        InputSystem.RegisterLayoutOverride(@"
            {
                ""name"" : ""AddScrollWheelButtons"",
                ""extend"" : ""Mouse"",
                ""controls"" : [
                    { ""name"" : ""scroll/up"", ""layout"" : ""Button"", ""useStateFrom"" : ""scroll/y"", ""parameters"" : ""clamp=1,clampMin=0,clampMax=1"", ""synthetic"" : true },
                    { ""name"" : ""scroll/down"", ""layout"" : ""Button"", ""useStateFrom"" : ""scroll/y"", ""parameters"" : ""clamp=1,clampMin=-1,clampMax=0,invert"", ""synthetic"" : true },
                    { ""name"" : ""scroll/left"", ""layout"" : ""Button"", ""useStateFrom"" : ""scroll/x"", ""parameters"" : ""clamp=1,clampMin=-1,clampMax=0,invert"", ""synthetic"" : true },
                    { ""name"" : ""scroll/right"", ""layout"" : ""Button"", ""useStateFrom"" : ""scroll/x"", ""parameters"" : ""clamp=1,clampMin=0,clampMax=99999"", ""synthetic"" : true }
                ]
            }
        ");

        // As value axis.
        InputSystem.RegisterLayoutOverride(@"
            {
                ""name"" : ""AddScrollWheelButtons"",
                ""extend"" : ""Mouse"",
                ""controls"" : [
                    { ""name"" : ""scroll/up"", ""layout"" : ""Axis"", ""useStateFrom"" : ""scroll/y"", ""parameters"" : ""clamp=1,clampMin=0,clampMax=99999"", ""synthetic"" : true },
                    { ""name"" : ""scroll/down"", ""layout"" : ""Axis"", ""useStateFrom"" : ""scroll/y"", ""parameters"" : ""clamp=1,clampMin=-99999,clampMax=0,invert"", ""synthetic"" : true },
                    { ""name"" : ""scroll/left"", ""layout"" : ""Axis"", ""useStateFrom"" : ""scroll/x"", ""parameters"" : ""clamp=1,clampMin=-99999,clampMax=0,invert"", ""synthetic"" : true },
                    { ""name"" : ""scroll/right"", ""layout"" : ""Axis"", ""useStateFrom"" : ""scroll/x"", ""parameters"" : ""clamp=1,clampMin=0,clampMax=99999"", ""synthetic"" : true }
                ]
            }
        ");
```

However, I found a bug in the layout system triggered by this that prevents it from working properly. Fixed by #1067. Should be in 1.0.0-preview.6.

**Comment by builder-main** [comment]
What we want to do is a predictable discret selection of element with mouse wheel. If I wheel one time up or down then I select previous/next element.

Where would I put this layout override, in my init process? So its runtime ? It can't be in the inputAction asset itself ?

Thanks

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
