### ISSUE TITLE
InputActionAsset.FromJson can create invalid bindings

### ISSUE THREAD

**Issue by jamre** [Unity-Technologies/InputSystem#1009]
When adding a binding to an InputActionMap, there is a check to make sure the binding's path is not null:
```cs
public static BindingSyntax AddBinding(this InputActionMap actionMap, InputBinding binding)
{
...
    if (binding.path == null)
        throw new ArgumentException("Binding path cannot be null", nameof(binding));
...
}
```

In order to add a placeholder binding that will be bound later, the path can be set to an empty string instead.

However, if the asset (or even just the map) is cloned through json, any empty strings in the bindings are converted to null when they are loaded.
This results in a map that has a binding with a null path, which isn't supposed to be allowed.

```cs
[Test]
public void AssetFromJsonHasValidBinding()
{
    var asset1 = ScriptableObject.CreateInstance<InputActionAsset>();
    var map1 = new InputActionMap("map1");
    var action1 = map1.AddAction("action1", InputActionType.Value);
    var binding1 = new InputBinding(string.Empty);
    action1.AddBinding(binding1);
    asset1.AddActionMap(map1);

    var asset2 = InputActionAsset.FromJson(asset1.ToJson());

    Assert.That(asset2.actionMaps.Count == 1);
    var map2 = asset2.actionMaps[0];
    Assert.That(map2.bindings.Count == 1);
    Assert.That(map2.bindings[0].path, Is.Not.Null);
}
```

Also note that `BindingSyntax` will allow changing a binding in a map to have a null path using either the `WithPath` or `To` method.

Most usages of path or effectivepath are checking for null anyway, so perhaps the restriction should just be removed from `AddBinding`.

**Comment by stefanunity** [comment]
Converted to fogbugz bug https://fogbugz.unity3d.com/f/cases/1231968/

Thanks for submitting the issue!
