### ISSUE TITLE
InputActionState.ProcessDefaultInteraction() hits assert after PlayerInput is destroyed (preview.3)

### ISSUE THREAD

**Issue by AtomicTroop** [Unity-Technologies/InputSystem#1010]
Unity version: 2019.2.12f1
Plugin version: 1.0.0 preview.3

Joining a PlayerInput through PlayerInputManager, destroying it, then joining again leaves the manager in a broken state where subsequent join attempts hit an assert and fail. This only seems to happen when Join Behaviour is set to "Join Players When Join Action Is Triggered" and Join Action is set via reference.

The issue can be reproduced easily:

1. Add a PlayerInputManager to a game object, set the Join Behaviour to "Join Players When Join Action Is Triggered", enable "Use Reference" in Join Action and set any action as the reference.
2. Create a prefab containing a PlayerInput and set this as the Player Prefab in the PlayerInputManager.
3. Press play, trigger the set action to join.
4. Destroy the created PlayerInput prefab instance via scene hierarchy or script.
5. Attempt to join again by triggering the set action. This will fail.

**Comment by AtomicTroop** [comment]
Updated to version 1.0.0 preview.4, still happening.

**Comment by Rene-Damm** [comment]
Cannot reproduce on latest `develop`. If this is still an issue with 1.0.0-preview.6 when release, plase file a ticket with the Unity bug reporter.
