### ISSUE TITLE
tvOS: Controllers register intermittently as Keyboard rather than GamePad

### ISSUE THREAD

**Issue by mikkelfredborg** [Unity-Technologies/InputSystem#1012]
PlayStation 4 DualShock controller is registered as Keyboard on tvOS (tested on 13.3). Using the latest version from git.

device.name = Keyboard
device.displayName = Keyboard
device.description = Keyboard (iOS)
device.path = /Keyboard
device.layout = Keyboard

**Comment by mikkelfredborg** [comment]
Further details:

The same goes for all other controllers, if both Keyboard and GamePad are enabled in the active ControlScheme in the InputActionAsset the device will be randomly reported as a Keyboard or Gamepad when checking
InputAction.activeControl.device directly or in a callback with InputAction.CallbackContext.control.device when using PlayerInput.

Current work around is to use a separate InputActionAsset for tvOS, where Keyboard is removed from the ControlScheme.

**Comment by Rene-Damm** [comment]
Hi @mikkelfredborg, could you file a ticket with the Unity bug reporter? The GitHub tickets easily get lost in the noise. Filing a ticket will make sure we won't be dropping this one on the floor.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
