### ISSUE TITLE
GC Spike in InputActionCallback, causes noticable glitches

### ISSUE THREAD

**Issue by schetle** [Unity-Technologies/InputSystem#1014]
Unity 2019.3.0f5
Input System 1.0 preview.3

Setup:
PlayerInput set to Invoke C Sharp Events, EventSystem, Input System UI Input Module
Default InputActionAsset (has Player and UI ActionMaps)

```
    void Start() {
        playerInput = GetComponent<PlayerInput>();
        
        // Plug in some wires
        InputAction lookAction = playerInput.actions.FindAction("Player/Look");
        lookAction.performed += OnLook;
        lookAction.started += OnLook;
        lookAction.canceled += OnLook;
    }

    private void OnLook(InputAction.CallbackContext obj) {
        // Store the value into a struct which we can read later
        // GC Spike happens whether this line is here or not
        inputState.Look = obj.ReadValue<Vector2>();
    }
```
![InputCallbackTest - Test - PC, Mac   Linux Standalone - Unity 2019 3 0f5  PREVIEW PACKAGES IN USE  _DX11_ 1_22_2020 11_15_02 AM](https://user-images.githubusercontent.com/3403983/72916917-80e8e200-3d08-11ea-80dd-318e7e4607a2.png)

The same GC spikes happen if I generate the C# Wrapper around the input asset, and plug in there as well.

My temporary solution is to not use callbacks at all, and just ReadValue in Update, which doesn't inflict these callback spikes and glitches.

Am I doing something wrong?

I've uploaded the test project that this happens in, which is a brand new project for the purpose of reproducing this issue. For ease, the Camera has this stuff attached to it. The camera is supposed to rotate with your Look movements, but given some amount of time of moving the mouse around, you can see noticeably large spikes causing the camera's rotation to glitch.

https://drive.google.com/file/d/1AGnyBPZqWq4vOZLB-58EkskIFB03fs5d/view?usp=sharing

**Comment by Rene-Damm** [comment]
Should be fixed by c2dbec311288e71f3faf0777d54355b37f114b10. Garbage was actually coming from the UI and not PlayerInput. Fix should be in 1.0.0-preview.5.
