### ISSUE TITLE
InputSystem Does Not Recognize Nintendo Joy-Con Gyroscope input

### ISSUE THREAD

**Issue by DuffyScottC** [Unity-Technologies/InputSystem#1016]
There is a default mapping for Joy-Con controllers, but it does not appear to have a way to read in the gyroscope motion. The "record" function doesn't recognize gyroscope motion, either.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
