### ISSUE TITLE
Xbox controller not detected on PC

### ISSUE THREAD

**Issue by demonixis** [Unity-Technologies/InputSystem#1017]
Hello,
After many tries with different xbox game controller, I'm not able to use it.

### How to reproduce it
- Create a new project with the new Input System (or selection both in player settings)
- Add the package from Package Manager
- Setup the Input System by creating an asset (inputSystem.inputSettings) with default values
- Add an Xbox controller on the PC
- Attach a script in a gameobject with the following code

```csharp
void FixedUpdate()
{
    var gamepad = Gamepad.current;

    if (gamepad == null) 
         Debug.Log("Gamepad not detected");
}
```
The gamepad variable is always `null`.

### Which version of Unity
- Unity 2019.3f5
- Unity 2020.1a19
- InputSystem 1.0.0-preview3

**Comment by ghost** [comment]
I am having a similar issue on MacOS with the xbox 360 controller, however it works OK on windows for me. Dumb question but does the controller work to control games out with unity? Have you also checked if it works with the old input system to confirm if the issue is specific to the new input system?

**Comment by m-talha** [comment]
I had a similar issue on Unity 2019.3.0f6. For me I think it was to do with multiple instances of Unity being opened across different versions. When I unplugged and plugged in the controller, the console on some instances would detect it but not on others. I just closed all instances and started again and it worked.

**Comment by popcron** [comment]
If you open the game controllers dialog in windows or device manager, do the controllers show up?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
