### ISSUE TITLE
Specific device names no longer labelled correctly as of preview.4

### ISSUE THREAD

**Issue by BHSPitMonkey** [Unity-Technologies/InputSystem#1021]
After updating from preview.3 to preview.4, "More Specific" device models now all appear under their more generic name. See below:

![image](https://user-images.githubusercontent.com/33672/73130435-2c19c580-3fad-11ea-99ba-e711ac26891c.png)

As a result, it's no longer possible to tell which bindings are which without toggling to the raw text path display for each entry.

Downgrading back to preview.3 restores the correct titles.

**Comment by Rene-Damm** [comment]
Argh, that one is embarrassing. Unfortunate side effect of a cosmetic change where the `XRController` now sets a display name so it reads "XR Controller". But display names are inherited and none of the derived layouts is overriding it. Fixing.

**Comment by Rene-Damm** [comment]
Thank you for reporting :)

**Comment by Rene-Damm** [comment]
Should be fixed as of #1035.
