### ISSUE TITLE
PlayerInputManager creates PlayerInputs with no input devices (preview.4)

### ISSUE THREAD

**Issue by AtomicTroop** [Unity-Technologies/InputSystem#1023]
Unity version: 2019.2.12f1
Package version: 1.0.0 preview.4

When adding a PlayerInput through PlayerInputManager's "Join Players When Join Action is Triggered" behavior, the PlayerInput passed to PlayerInputManager.OnPlayerJoined callbacks has no input devices (the PlayerInput.devices ReadOnlyArray has zero size). 
Tested using keyboard as the joining input device.

**Comment by AtomicTroop** [comment]
Might be related to issue #1021?

**Comment by JamhammerRob** [comment]
To add to this, https://forum.unity.com/threads/current-control-scheme-null-on-player-join.819723/

when added via player manager, our current control scheme is listed as null also. @Rene-Damm

**Comment by all-iver** [comment]
I am also experiencing this.  The player has no input devices, and any player created with another input device also controls the device-less keyboard player in addition to their own player.

**Comment by Rene-Damm** [comment]
Looking. Very much sounds like I regressed something here.

**Comment by Rene-Damm** [comment]
Fixed by #1037.
