### ISSUE TITLE
Pass Through mode never sends release events for keyboard inputs

### ISSUE THREAD

**Issue by Vectrobe** [Unity-Technologies/InputSystem#1026]
Any action set to pass-through mode will only ever send performed events of full-value for any given keyboard press, and never any event on release.

With pass-through currently being the only mode that works (tested fine with controllers), this makes keyboard input completely unusable...

Unity: 2019.3.0f5
Input System: preview.4

**Comment by fullheartgames** [comment]
I am having the same problem. I get the error below when pressing TAB on keyboard in an in-game menu. Setting said input to pass through stops this error from occurring but context.cancel on the input doesn't work.

XR actions should be pass-through actions, so the UI can properly distinguish multiple tracked devices. Please set the action type of 'Select' to 'Pass-Through'.
