### ISSUE TITLE
IMGUI doesn't respond to new input system in players,  Editor is fine

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#103]
Wondering what are the plans about this one, currently to use IMGUI you have to enable both Input Systems (old and new) to use it.

Are there any plans for IMGUI to respond to new input system?

**Comment by Rene-Damm** [comment]
That shouldn't be the case. IMGUI should be fed entirely from `UnityEngine.Event` meaning internally it should all be `InputEvent` which *should* be generated by code on each platform that is not affected by the native backends for `InputManager`.

If this isn't true for all platforms, we need to fix that. (In short, no `InputEvent` codepath should be affected by the input backend toggles in player settings)

In general, both IMGUI and uGUI will need a pass to ensure/implement functioning together with the new input system. For uGUI, we've been in talk with the team and are hashing out plans.

**Comment by todi1856** [comment]
So double checked that again... The issue is only with players (tested with Android and Windows Standalone player)

**Comment by todi1856** [comment]
Fixed internally, both iOS and Android will generate IMGUI events when old system is turned off
