### ISSUE TITLE
Critical bug: Not able to type in Chinese character (or any other non-English language) after install InputSystem

### ISSUE THREAD

**Issue by LawrenceHan** [Unity-Technologies/InputSystem#1038]
### How to reproduce:
1. Install InputSystem from package manager
2. In player settings `Active Input Handling`, change it to `Input System Package (New)` or `Both`
3. Close the project and reopen it. 
4. Switch IME to Chinese Pinyin (or any other non-English IME).
5. Find any text field, e.g: a UI Text editing field, or change a GameObject's name.
6. You will notice you can only type in English, it just ignores your IME.

### How to solve the problem:
1. In player settings `Active Input Handling`, change it to `Input Manager (Old)`.
2. Close the project and reopen it. 

### P.S:
I also tried to downgrade InputSystem to 1.0.0 (2019.Sep), the problem still exists, so I guess maybe it is somehow related to Unity Editor.
Please tell me where to change it from code, so I can use InputSystem asap without waiting for a new release.

**Comment by stefanunity** [comment]
This is currently a bug/not supported with the system. We'll be tracking this issue at https://issuetracker.unity3d.com/product/unity/issues/guid/1220893/ moving forward and are closing this case here for the time being.
Sorry to not have better news in this regard.

**Comment by LawrenceHan** [comment]
@stefanunity 
I sent an email to unity support last week, they told me it has been fixed in 2020.1

**Comment by stefanunity** [comment]
Sweet then!
