### ISSUE TITLE
[Android][Touch] touch.position.y and touch.delta.y are reversed (comparing to the old input)

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#104]
Found using: d3a060d running on Android
(iOS had correct values both using old and new input)

E.g. when rendering 2220x1080:
Old input reports top of the screen position.y as 1080 when in landscape mode while the new one reports it as 0
![player-unityplayeractivity-05142018160228](https://user-images.githubusercontent.com/39190411/40002738-41ab16d0-579a-11e8-8e3b-f1a0d86713ab.png)

**Comment by Rene-Damm** [comment]
Windows *should* already be oriented Y up. It's done in the backend. @todi1856 this is probably something that needs to be changed in the Android backend. iOS probably also worth checking.

**Comment by todi1856** [comment]
@Rene-Damm maybe it's worth doing this via value processor? I looked at the old system, and the value is both scaled and inverted, depending on screen/window size ratio.

**Comment by todi1856** [comment]
@renaldasrep check develop branch again, this should be fixed now

**Comment by renaldasrep** [comment]
Yeah it's fixed! #125 is related and remains active though
