### ISSUE TITLE
Cannot get the Accelerometer value through an Action

### ISSUE THREAD

**Issue by MLaroucheLaSalle** [Unity-Technologies/InputSystem#1041]
I don't know if it's me who does something wrong, but I never received any CallbackContext when I try to receive the value of the Accelerometer of my phone (Android) through an Action, but it work when I use the command: Accelerometer.current.acceleration.ReadValue();

I have configured an Action called _Acceleration_ in the Input Actions Assets, then I have added the component PlayerInput with the behavior: Invoke Unity Events and I call this method but on my device I never received a CallbackContext

![Action Acceleration](https://user-images.githubusercontent.com/46653065/74061545-3929b200-49ba-11ea-971d-79360fd0f134.PNG)

![image](https://user-images.githubusercontent.com/46653065/74061503-22835b00-49ba-11ea-80d9-6565a3c9b197.png)

![image](https://user-images.githubusercontent.com/46653065/74061594-5bbbcb00-49ba-11ea-9e5d-b3ff3c61f8d2.png)

` using UnityEngine;
using UnityEngine.UI;
using UnityEngine.InputSystem;

public class InputMobile : MonoBehaviour
{

    Vector3 acceleration = new Vector3();
    [SerializeField] private Text txtField;

    public void OnAcceleration(InputAction.CallbackContext context)
    {
        acceleration = context.ReadValue<Vector3>(); 
    }

    // Start is called before the first frame update
    void Start()
    {
    #if UNITY_ANDROID
        InputSystem.EnableDevice(Accelerometer.current);
    #endif 
    }
    
    
    // Update is called once per frame
    void Update()
    {
        txtField.text = "Acc X: " + acceleration.x.ToString ("F2") +
                        ", Y: "   + acceleration.y.ToString ("F2") +
                        ", Z: "   + acceleration.z.ToString ("F2") + "\n";
    }
}`

**Comment by mshagin** [comment]
@MLaroucheLaSalle Hello! I got the same issue on iPhone. Did you find a fix or a workaround for this? What I found is that it works fine at an empty project.

**Comment by MLaroucheLaSalle** [comment]
I used the old school Input Manager.

**Comment by mshagin** [comment]
> I used the old school Input Manager.

Sounds like a good workaround :)

And me just checking Accelerometer.current.acceleration in Update for now.
