### ISSUE TITLE
InputAction how to cancel phase

### ISSUE THREAD

**Issue by fullheartgames** [Unity-Technologies/InputSystem#1042]
One thing I noticed is you get the "Should not get here" error when changing action maps or destroying an object in the middle of a phase. I am trying to make an in game menu that goes back to the main menu. When I do this I destroy all players to allow new players to join. The problem is when looping back through the menu and back into the game it seems the PlayerInputManager is still holding onto context.performed possibly. I get the error and the controls are act as if InputAction was all ready in phase. disabling the action map or getting rid of anything having to do with PlayerInput seems to have no effect.

**Comment by Rene-Damm** [comment]
There's definitely a bug here. I'm looking into the repro provided by https://forum.unity.com/threads/correctly-change-action-map.825204/#post-5467824.
