### ISSUE TITLE
No gamepads detected on OsX

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/InputSystem#1043]
I am trying to use the new input system with a gamepad on MacOS but get no input from it. The Gamepad works in games and with the legacy input system.

The following code, when run, suggests that no gamepads have been detected:
```
var gamepads = Gamepad.all;
if (gamepads.Count == 0)
{
    Debug.Log("no gamepads");
}
```

Versions:
MacOS - 10.15.3
Unity Editor - 2019.3.0f6
Input System - 1.0.0-preview-4

**Comment by popcron** [comment]
Likely need drivers for the controllers themselves, have you looked into that?

**Comment by ghost** [comment]
Yes. Please note the part of my post that states `The Gamepad works in games and with the legacy input system`.

**Comment by popcron** [comment]
That doesnt necessarily mean that it will work out of the box, the gamepad has to have its data laid out and exposed as a Gamepad (for example, Gamecube controllers need to have a custom class). What controller is this?

**Comment by ghost** [comment]
Its a wireless xbox 360 controller- it works fine in unity's new input system on windows just not on osx. The driver I have installed has it working properly in osx in general and like I said it works for games and the old unity input system.
https://imgur.com/a/DTQXrt4

**Comment by popcron** [comment]
The input system doesnt support this controller if not wired, this is true for every XInput device on mac. The xbox one controller has bluetooth and can get hooked in natively though, this is the only exception.

**Comment by Rene-Damm** [comment]
>Its a wireless xbox 360 controller- it works fine in unity's new input system on windows just not on osx. The driver I have installed has it working properly in osx in general and like I said it works for games and the old unity input system.
https://imgur.com/a/DTQXrt4

Hmm, that looks like the Tattiebogle driver. If so, the Xbox controller is expected to work. Wired or not. In that case, could you file a report with the Unity bug reporter so that our QA department can have a look?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experiencing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
