### ISSUE TITLE
How to add custom binding path?

### ISSUE THREAD

**Issue by chengnay** [Unity-Technologies/InputSystem#1044]
I downloaded the InputSystem codebase and I found out that in this project I can see those custom device input as below image,
![image](https://user-images.githubusercontent.com/33050705/74129939-c91a6680-4c1b-11ea-85e6-4443731a50e1.png)
But, in my new project, I can only see them as XR Controller as below image,
![image](https://user-images.githubusercontent.com/33050705/74130059-1eef0e80-4c1c-11ea-8fe0-33054838a0c1.png)
Anyone knows how to do that?

**Comment by popcron** [comment]
They likely have the custom devices registered in onInitialize, search the solution (including packages) for `InputSystem.RegisterLayout` and you should be able to find the source for the controllers. Alternatively they might be an example package that you would import from the pacman.

**Comment by Rene-Damm** [comment]
This was a regression in 1.0.0-preview.4 which has been fixed in 1.0.0-preview.5. The display names for those devices weren't set correctly so all of them came out having the same "XR Controller" display name.
