### ISSUE TITLE
Functionality to simulate touch with mouse in player

### ISSUE THREAD

**Issue by eliphatfs** [Unity-Technologies/InputSystem#1045]
There's such an option in Input Debug window. Why not also in player? It is nice to have universal input handling logic between platforms.

**Comment by Rene-Damm** [comment]
Touch simulation is implemented by the `TouchSimulation` MonoBehavior. You can add that to your game or enable touch simulation through `TouchSimulation.Enable()` to get the same behavior in the player that you get in the editor with the switch in the input debugger.

**Comment by eliphatfs** [comment]
Thanks. Maybe this should be mentioned briefly in the documentation, hard to find :D

**Comment by Rene-Damm** [comment]
Indeed :) Fixed in #1067.
