### ISSUE TITLE
Dualshock4 not working on iOS while the app first start.

### ISSUE THREAD

**Issue by sableangle** [Unity-Technologies/InputSystem#1046]
Only tested the Dualshock4 gamepad, connect Dualshock4 via bluetooth.
Dualshock4 not working on iOS while the app first start.
But if the app switch to background and switch back to foreground Dualshock4 gamepad works!

Not sure is anything setting wrong?

Unity : 2019.3.0f6
iOS : 13.3
InputSystem:  from package manager 1.0.0 preview 4

**Comment by CodeNewWorlds** [comment]
Same issue with Xbox one controller.

**Comment by AKiniyalocts** [comment]
Seems to still be happening on the `1.0.0` release.
