### ISSUE TITLE
Access to the internal timeline with 'double' precision

### ISSUE THREAD

**Issue by eliphatfs** [Unity-Technologies/InputSystem#1047]
Hi there, I'm making a reacting game that needs touch time at a high precision. The touch system events are 'on the same timeline as Time.realTimeSinceStartup' but `Time.realTimeSinceStartup` is a `float` and can have frames of inaccuracy due to floating point error, after the game runs for a few hours (maybe in background).

**Comment by Rene-Damm** [comment]
You can query the current input time through `InputState.currentTime`. Admittedly not the most discoverable of places... We should probably add a getter somewhere else. Maybe it should just be `InputSystem.time`.

**Comment by eliphatfs** [comment]
Found that `InputState.currentTime` doesn't reset where `Touch.time` resets with `realTimeSinceStartup` in the editor. @Rene-Damm

**Comment by eliphatfs** [comment]
The problem described above also made `Touch.tapCount` unreliable as on Line 573 of TouchScreen.cs it sets `tapCount` according to `InputState.currentTime`.

**Comment by eliphatfs** [comment]
Where are the events generated? May expose an API somewhere native?
