### ISSUE TITLE
Compatibility with SteamVR

### ISSUE THREAD

**Issue by m-talha** [Unity-Technologies/InputSystem#1048]
Is there a way to get this to nicely talk with SteamVR? I am trying to develop an application with the input unified across all devices including XR. Although this system covers the popular input devices, Unity lacks the built-in features of VR present in SteamVR like the interaction system and ready-made prefabs which I would like to use to significantly reduce development time.

Does anyone have any idea on how to combine the VR input from this package with SteamVR or combine everything from SteamVR including input with the input from this package which I suspect might be easier? 

Thanks

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experiencing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
