### ISSUE TITLE
Generated C# classes' member name conflicted under certain circumstances.

### ISSUE THREAD

**Issue by DCTewi** [Unity-Technologies/InputSystem#1051]
This situation occurred in an accident: 

When **Your generated c# class' name** == **Any action map's name in InputActionAssets** + **"Actions"**, a CS0542 error will be occurred.

> CS0542  C# '': member names cannot be the same as their enclosing type.

### Example:

There is a action map in assets file named `Player`:
![pic](https://s2.ax1x.com/2020/02/12/17Z4UO.png)

When the generated c# class' name == `PlayerActions`:
![pic](https://s2.ax1x.com/2020/02/12/17ZhVK.png)

CS0542 occurred:
![pic](https://s2.ax1x.com/2020/02/12/17ZoPe.png)

This situation really confused me at first. Perhaps the generation logic could be improved or an warning in the inspector could be displayed in this situation?

**Comment by stefanunity** [comment]
Tracked here https://issuetracker.unity3d.com/product/unity/issues/guid/1212052/
