### ISSUE TITLE
Support more than 4 controllers

### ISSUE THREAD

**Issue by AdrienVR** [Unity-Technologies/InputSystem#1054]
I want to create a game with 8 players and 8 gamepads, could the input system support that?
For now I can only get 4 gamepads max in Gamepad.all, while 4, 5, 6, 7 or 8 are connected.
![image](https://user-images.githubusercontent.com/7657881/74375883-6e326c00-4de1-11ea-872d-86635f42c04a.png)

**Comment by Rene-Damm** [comment]
Unfortunately, this limit is hardwired into the XInput API. I suspect that eventually when the UWP and Win32 backends start sharing more code and we move over to the Windows.Gaming.Input API, that limit will disappear.

ATM with the classic Win32 backend, the only way to get to those controllers is through HID. However, the HID driver for XInput devices combines the left and right triggers into a single control and thus isn't really usable. ATM we suppress these HIDs at the native level (something we should probably move up to the managed code part which would allow users to opt into using them despite the limitation).

**Comment by popcron** [comment]
I believe a dirty work around for now (in dev time at least) is to have 4 xinput controllers and 4 ds4 controllers.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
