### ISSUE TITLE
PlayerInput - SendMessage() with spaces

### ISSUE THREAD

**Issue by tirbelain** [Unity-Technologies/InputSystem#1056]
I had some problems receiving messages from the PlayerInput. Some messages arrived, some did not. The reason I didn't receive those messages is this that the not received actions in my action map had spaces in their names, like "End Play" instead of "EndPlay". The SendMessage() call in PlayerInput.cs:1114 sends "OnEnd Play" in this case. The displayed message on the component in the inspector actually shows the correct name "OnEndPlay".

Inspector:
![image](https://user-images.githubusercontent.com/14891056/74451576-2282cf80-4e80-11ea-970a-a6057b1ac03b.png)

Action Map:
![image](https://user-images.githubusercontent.com/14891056/74451471-f8311200-4e7f-11ea-8ee8-239971483af6.png)

Debugger:
![image](https://user-images.githubusercontent.com/14891056/74451372-ce77eb00-4e7f-11ea-81bb-9a60b01c482a.png)

I am using Input System version 1.0.0-preview.3 with Unity 2019.2.12f1.

**Comment by BHSPitMonkey** [comment]
I think this duplicates #1022 (and is being fixed in #1101).

**Comment by stefanunity** [comment]
Neat. Closing.
