### ISSUE TITLE
[Android][Touch] touch.touchType is displayed as "-26" instead of "Direct"

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#106]
Found using d3a060d

iOS returns touchType correctly (Direct vs. Direct)

![player-unityplayeractivity-05142018160228](https://user-images.githubusercontent.com/39190411/40002527-b53262e4-5799-11e8-9c9c-705a022b14e5.png)

**Comment by todi1856** [comment]
Same happens on Windows it seems, probably because touchstates created on stack are not fully initialized... I'll fix on Android, but maybe there's a generic way to fix this

**Comment by todi1856** [comment]
@renaldasrep is this still a thing? I think it should be fixed now

**Comment by renaldasrep** [comment]
Yep, can no longer reproduce
