### ISSUE TITLE
Deleting an Action from Action Map causes error: "Cannot find action with ID"

### ISSUE THREAD

**Issue by effxiikc** [Unity-Technologies/InputSystem#1062]
Hi,

I'm trying to rearrange my Action Maps and when I delete an Action from an Action Map I get the following error. Any guidance what I'm doing wrong?

> Cannot find action 'Player/Dash[/Keyboard/shift]' with ID '610bf5bb-eb22-49c2-929d-5131c03b426f' in 'PlayerActions (UnityEngine.InputSystem.InputActionAsset)
> UnityEngine.InputSystem.PlayerInput:OnEnable() (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.5/InputSystem/Plugins/PlayerInput/PlayerInput.cs:1540)
> 

Thanks.

**Comment by Rene-Damm** [comment]
Going to the respective object and just reselecting it in the inspector and resaving should fix the error.

ATM we don't yet have a good way for PlayerInput to keep its data in sync if the asset is changed. All the work ATM happens in the inspector code which, however, requires the PlayerInput GameObject to be selected for the code to kick in.

We should probably just remove the error and have the code just ignore any entry that points to an action that no longer exists.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
