### ISSUE TITLE
How to get deviceId?

### ISSUE THREAD

**Issue by chengnay** [Unity-Technologies/InputSystem#1065]
Does anyone know how to get deviceId of HMD and controllers?
I tried using InputDevice.deviceId of left controller(Oculus Rift Touch), the deviceId is not fixed.
Everytime I relaunch the scene, it will give me a new number.

**Comment by Rene-Damm** [comment]
Could be what you're looking for is `XRDeviceDescriptor.deviceId`.

The persistent description for a device is found in `InputDevice.description`. `InputDeviceDescription.capabilities` is a type-specific JSON string with device information. For XR devices, this  corresponds to `XRDeviceDescriptor`.

```CSharp
var xrDescription = XRDeviceDescriptor.FromJson(xrDevice.description.capabilities);
```

**Comment by chengnay** [comment]
@Rene-Damm Thanks!
