### ISSUE TITLE
[Android?/iOS?][Touch] Inconsistent touch.touchId behaviour between platforms

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#107]
Found using d3a060d

On Android each tap is assigned an ID 0 to x and resets when the touchscreen is no longer being touched, e.g. tapping with one finger multiple times would only produce touches with ID - 0
![starltexxr16nwrenaldas05142018173749](https://user-images.githubusercontent.com/39190411/40004098-a2312da2-579d-11e8-93a1-a4504df9d192.gif)

On iOS each tap is assigned an incrementing touchId starting from 1, e.g. tapping with one finger multiple times would produce touches with IDs - 1, 2, 3, 4, 5,
![ios-recording-0514-172968](https://user-images.githubusercontent.com/39190411/40003719-b47e33ca-579c-11e8-82f7-118631a35e08.gif)

**Comment by todi1856** [comment]
I think that's by design. Would be nice to compare to Windows Desktop and UWP, can you ask other QA's how's doing that?

**Comment by renaldasrep** [comment]
Sure, will check that out 👍

**Comment by Rene-Damm** [comment]
Windows is producing incrementally numbered touches as well. I think the behavior of not reusing touch IDs is preferable and while ultimately touch ID allocation is up to the platform, would be nice to get somewhat consistent behavior there.

**Comment by renaldasrep** [comment]
This has been fixed for some time now
