### ISSUE TITLE
Mouse input not working on Linux

### ISSUE THREAD

**Issue by Mister-Muffin** [Unity-Technologies/InputSystem#1072]
If I move my mouse while the cursor is locked, I cannot turn my Camera. If I hit `ESC` and the mouse is visible I can turn the camera. Do you know how to fix that? On Windows it's working fine.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experiencing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
