### ISSUE TITLE
Mouse.current.position returns stale value

### ISSUE THREAD

**Issue by Decavoid** [Unity-Technologies/InputSystem#1073]
Mouse.current.position should return the latest mouse position but it returns the previous mouse position instead.

**Repro code:**
[mousetest.zip](https://github.com/Unity-Technologies/InputSystem/files/4233382/mousetest.zip)

```
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

public class Test : MonoBehaviour
{
    [SerializeField] Text textOldInputXY;
    [SerializeField] Text textInputSystemXY;
    [SerializeField] Text textOK;

    private void Update()
    {
        Vector3 oldSystemMousePos = Input.mousePosition;
        Vector2 inputSystemMousePos = Mouse.current.position.ReadValue();

        if (oldSystemMousePos.x == inputSystemMousePos.x && oldSystemMousePos.y == inputSystemMousePos.y)
        {
            textOK.color = Color.green;
            textOK.text = "ok";
        }
        else
        {
            textOK.color = Color.red;
            textOK.text = "fail";
        }

        textOldInputXY.text = $"{oldSystemMousePos.x} {oldSystemMousePos.y}";
        textInputSystemXY.text = $"{inputSystemMousePos.x} {inputSystemMousePos.y}";
    }
}
```

**Scenario 1**: Change mouse DPI to the lowest possible value. Slowly move the mouse (5px/s). Observed result: the text quickly changes: "ok/fail/..." for every pixel, new Input System's position lags behind by 1 px.
![screenshot0](https://user-images.githubusercontent.com/1127000/74986911-76c71a00-5453-11ea-9155-8a64d9dbf4d7.jpg)

**Scenario 2**: While moving the mouse relatively quickly, lift the mouse up. Keep the mouse in the air. Observed result: Text shows "fail". Old input system mouse position is correct. New Input System's mouse position is different by >10 pixels, showing the previous value.
![screenshot](https://user-images.githubusercontent.com/1127000/74986813-441d2180-5453-11ea-87ca-3488f177bbc9.jpg)

Unity: 2019.3.2f1
InputSystem: 1.0.0-preview.5
Windows 10
fogbugz Case 1221634.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

You can follow this issue at https://issuetracker.unity3d.com/product/unity/issues/guid/1221634/

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
