### ISSUE TITLE
Calling TouchSimulation.Enable in Player Script Start() is Useless

### ISSUE THREAD

**Issue by eliphatfs** [Unity-Technologies/InputSystem#1074]
Calling `TouchSimulation.Enable ()` in some `MonoBehaviour.Start ()` and `Touchscreen.current?.primaryTouch?.position?.ReadValue ()` still yields null. (Adding TouchSimulation Component to an Object works, in which case it yields `(0.0, 0.0)`)

**Comment by eliphatfs** [comment]
Seems that it's because after I enabled it in `Start ()`, `TouchSimulation.ReEnableAfterDomainReload` from `InputSystem.onBeforeUpdate` disabled it again.

**Comment by nykwil** [comment]
Also happens if you put it in OnEnable

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experiencing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
