### ISSUE TITLE
PlayerInput: Values of fields under "Actions" don't play well with serialization

### ISSUE THREAD

**Issue by Ramobo** [Unity-Technologies/InputSystem#1076]
The fields in question are `Default Scheme`, `Auto-Switch` and `Default Map`.

If you change the value of any of them...
• ...in a prefab file, changes apparently won't be propagated to instances, though it might just look like it due to what's explained in the next paragraph;
• ...in a prefab instance, you won't get a prefab override prompt.
Changes will be saved to the disk in both prefabs and scenes.

Changing the value of Default Map will be saved to the disk, but the dropdown value will go back to the first map the next time you open the inspector for that `GameObject`. This doesn't occur with the other two fields.

This is all weird and hard to describe, more so when considering the bug that setting Default Map to none fixed for me: `MissingMethodException`s when performing inputs. Yet, if I set it to Movement, the default value which was apparently the source of the errors, they don't come back. They do if I set the value to something other than none or the first map, but only if I do that in the prefab.
...maybe, sort of, occasionally, possibly, perhaps, somewhat... it didn't happen this time, it happens only when I'm not trying to make it happen... AAAAAAAAAAAAAAAAAAAAAH
(I use interfaces, so those methods indeed don't exist.)
You get the idea, it doesn't make the least bit of sense. Inexplicable errors. Business as usual with Unity. I wonder if deleting the Library folder would have fixed it.

I feel like the primary cause of all this is the inspector display/actual value mismatch.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
