### ISSUE TITLE
Buttons can depress without an Update where polling wasReleasedThisFrame will be true

### ISSUE THREAD

**Issue by cjacobwade** [Unity-Technologies/InputSystem#1079]
To test this:
- Create a script that logs something during Update only if ((ButtonControl)inputAction.activeControl).wasReleasedThisFrame is true
- Press that action on keyboard or Gamepad and note that this will log will never happen

**Comment by Rene-Damm** [comment]
That setup should lead to `NullReferenceException`s. Once the action has completed, there's no `activeControl` anymore so polling it in `Update` this way will not catch on release. So yeah, it won't log something this way. If you use the callback API, you should be able to observe the release this way, however.

We're looking at extended the polling API of `InputAction` itself to have `IsPressed`, `WasPressedThisFrame`, and `WasReleasedThisFrame`. Would this help your use case?

**Comment by cjacobwade** [comment]
Whoops, sorry for delayed response.  I'm happy with the callback workflow, but find that paradigm makes writing logic messy. So far everyone I've talked to has resorted to tracking input state themselves and using callbacks to update that state- this is bad because now there's more state and devs are working around the intended paradigm to get back to polling. Exposing those properties should definitely fix my use case, yes.

**Comment by filod** [comment]
> We're looking at extended the polling API of `InputAction` itself to have `IsPressed`, `WasPressedThisFrame`, and `WasReleasedThisFrame`. Would this help your use case?


same need here, do we have any roadmap on this?

**Comment by Rene-Damm** [comment]
It's in the works. There's a *chance* (no guarantee) it'll land in 1.1.

**Comment by crowhound** [comment]
What is the status of this request if you don't mind giving some info about it?

I been running into several scenarios where I need to see if an inputaction isPressed, WasPressedThisFrame, and WasReleasedThisFrame.
