### ISSUE TITLE
I can't type Korean in unity editor

### ISSUE THREAD

**Issue by tooOpen** [Unity-Technologies/InputSystem#1081]
Hello unity tech team

yesterday I realize I can't input Korean text at anywhere unity editor
literally I can't type Korean even search bar, only English
I remove package one by one.
and now I know cause is new inputsystem.

stpe 1. install inputsystem 
stpe2.  exit unity editor and launch unity editor
can't type korean!
please let me know how to solve this bug.

thank you unity tech team!

**Comment by stefanunity** [comment]
Hey, we made a backport to 2019.3 which should land in one of the next patch 2019.3.x releases.

It already works in the 2020.1 alpha builds if you want to test against that if our fix actually solves your issue.

**Comment by tooOpen** [comment]
thank you for answer! 
I expect new version!

**Comment by stefanunity** [comment]
Will be fixed for 2019.3 (already fixed in later versions)

**Comment by tooOpen** [comment]
I update 2019.3.8f1 but still there is bug.
I can't type Korean anywhere
not yet?

**Comment by stefanunity** [comment]
the upcoming 2019.3.9 has our fix. please try again with this once released.

**Comment by tooOpen** [comment]
thank you very much @stefanunity

**Comment by tooOpen** [comment]
I check that this bug fixed!
Thank you @stefanunity

**Comment by stefanunity** [comment]
Happy to hear!
