### ISSUE TITLE
Disabling VR module causes compile errors in input system

### ISSUE THREAD

**Issue by scottbilas** [Unity-Technologies/InputSystem#1086]
In a2-dots-shooter we're working on deleting the PhysX dependency, which VR depends on. So I'm disabling that too.

Problem: deleting VR from the project package manifest causes a bunch of compile errors from the input system. For the moment I have worked around it by internalizing the package and hacking ENABLE_VR's to ENABLE_VR_MODULE's where necessary (https://helix-swarm.prd.cds.internal.unity3d.com/changes/23474). I have no idea if this is the right choice, but it lets me move forward.

**Comment by Rene-Damm** [comment]
Hey @scottbilas, could you file a FogBugz ticket to make sure this won't fall under the table?

**Comment by scottbilas** [comment]
No prob @Rene-Damm 

https://fogbugz.unity3d.com/f/cases/1230225/

**Comment by Rene-Damm** [comment]
Thank you :)
