### ISSUE TITLE
Tracked Device unable to interact with DropDown List UI element.

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/InputSystem#1087]
Working with latest input system version (preview.6).

When using a tracked device, vive pro controllers, I am unable to interact with the options shown in the drop down list of a drop down UI element.

There are no issues with using mouse to interact with the same element (other than an odd cursor offset that existed in previous version as well).

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
