### ISSUE TITLE
Preview .6 - Getting phantom button press ( onClick )

### ISSUE THREAD

**Issue by JamhammerRob** [Unity-Technologies/InputSystem#1090]
button onClick automatically triggering when i pause my game. The pause screen has a bunch of buttons for resume, restart, etc. Whenever I pause the game, Preview.6 will automatically fire the first method attached to the first button in my scene. Downgrading to .5 solves the problem.

This only happens if I hit the a button and let go before pausing ( in my case, it's a multiplayer lobby where each player floats around and hits ready once they reach a collider denoting their team )

Any ideas?

**Comment by Rene-Damm** [comment]
@JamhammerRob could you file a ticket with the Unity bug reporter? Would like to take a closer look.

>This only happens if I hit the a button and let go before pausing

So, you press the button and then you pause and it triggers a second button press on the same button?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
