### ISSUE TITLE
EnhancedTouch starts with moved / stationary phase

### ISSUE THREAD

**Issue by KCFindstr** [Unity-Technologies/InputSystem#1102]
**Version**: Unity 2019 3.0f6 with InputSystem package 1.0.0 preview 6
**Device**: iPad Pro, iOS 13.3
**Update Mode**: Process events in dynamic update

I'm developing a rhythm game and handling user input accurately is essential to my game. I used the old InputManager and everything worked fine, but when I migrated to InputSystem, I noticed that I am missing user inputs infrequently (about once every thousand touches). I enabled both systems and compared their responses and found some strange behaviors of InputSystem.
For Input Manager, I'm using `Input.touches` in my `update()`.
For Input System, I'm using `InputSystem.EnhancedTouch.Touch.activeTouches` in my `update()`.
After playing the game for about 1 minute, I discovered a difference between their responses: They both reported a touch in the same screen position, but Input Manager has phase `TouchPhase.Began` while Input System has phase `InputSystem.TouchPhase.Moved / Stationary`. This caused my game to ignore this touch.
I then added a hashset to track all touchIDs and force a touch to be in state `Began` when its touchID first appears. After this, my game worked as expected.

Another thing is that I sometimes got a touch with `InputSystem.TouchPhase.None` in `activeTouches`. I don't know if it's expected, it's not affecting my game a lot, and I'm unable to find a way to reproduce it, so I'll just mention it here.

**Comment by Rene-Damm** [comment]
Hi @KCFindstr, could you file a ticket with the Unity bug reporter?

**Comment by eliphatfs** [comment]
Is it because, there are multiple events of the same touch in the event queue in the same frame, so the input system yields a `Moved` state on update?

**Comment by KCFindstr** [comment]
@Rene-Damm Sure, I filed case #1230756.

**Comment by Rene-Damm** [comment]
Great, thank you.

**Comment by stefanunity** [comment]
This is being tracked at https://issuetracker.unity3d.com/product/unity/issues/guid/1230756/ now.
Thanks!
