### ISSUE TITLE
Keyboard input recording replay doesn't work with InputField

### ISSUE THREAD

**Issue by dragorosson** [Unity-Technologies/InputSystem#1104]
I expected to be able to replay typing into an InputField. With the InputRecorder sample, I would expect the keys I pressed during recording while an InputField has focus to insert those characters into the InputField.

I have tried recording with the InputField starting unfocused, clicking on it, and typing; and with the InputField already focused and typing (and playing it back with the InputField still focused). I can see the keyboard keys being pressed during playback as I did them during recording but nothing happens. The clicks being played back do focus and unfocus the InputField as they should.

To reproduce, open the InputRecorder sample and add an InputField (right-click on Canvas > UI > InputField), then record inputs that insert text into it during playback.

**Comment by Rene-Damm** [comment]
Unfortunately, this isn't covered by the UI input module yet. We have it on the list for after 1.0.

To explain, input in uGUI isn't actually going through its input module but rather directly taps input in the Unity runtime. This means the input system has no way of feeding the UI system its own input and thus keyboard events are currently not affecting text input in the UI.

We have a work item in the list to overhaul this on the uGUI side and make it possible for the input system to take over UI text input entirely (including actual keyboards as well as on-screen keyboards).

**Comment by dragorosson** [comment]
@Rene-Damm Thanks for the quick response! Is there an issue we can track for progress on this?

**Comment by Rene-Damm** [comment]
Unfortunately not ATM. It's something we have recently started collaborating with the uGUI about and work is expected to happen after 1.0 final is out (which is going to happen shortly) and improvement/feature work is resuming. Unfortunately, no hard dates yet. Remains to be seen how this one goes. Unfortunately it does require changes to both uGUI and TextMesh Pro so will be a bit trickier to roll out.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experiencing this issue  please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
