### ISSUE TITLE
[UWP] mouse.position is not consistent with Input.mousePosition

### ISSUE THREAD

**Issue by JiaUnity** [Unity-Technologies/InputSystem#112]
The (0, 0) for old Input Manager is the lower left corner of the window, while for the new Input System, it is the upper left corner.

The X value for the mouse position is not consistent between the two systems. Though there is no effective way to compare the Y value, it is very likely to have an offset as well.

![mouseposition](https://user-images.githubusercontent.com/33637761/40209883-dbc5f664-59f6-11e8-9dc0-19edad6624fc.gif)
Blue text is for the Old Input Manager. Red text is for the New Input System.

**Comment by Rene-Damm** [comment]
ATM this is handled in platform backends. @JiaUnity please ping Tim (not sure what his GitHub account his).

**Comment by JiaUnity** [comment]
Yes. I'll pin him directly for UWP bugs. Sorry about it.

**Comment by Rene-Damm** [comment]
Filing all bugs including UWP ones here is good. Prefer to have it all in one place and visible to everyone.

**Comment by JiaUnity** [comment]
Fixed in 19.1.
