### ISSUE TITLE
Remote-Input not applied to Unity UI, when game has no focus.

### ISSUE THREAD

**Issue by tobias-stein** [Unity-Technologies/InputSystem#1121]
Hi,
I am currently working on an application using Unity UI and Input system with WebRTC. The idea is having a Unity application running on a server and clients can interact with that application remotely. Everything seems working great except for the UI. Remote send inputs, which are then queued into the InputSystem are not getting through the UI, **if the game has no focus**.

The issue seems the line pointed out in this post

https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-2#post-5096528

The InputSystemUIInputModule's Process() method has a check if the eventsystem has no focus it not process any input from devices. 

It would be nice to have a flag which omits this check, so remote input still will go through the UI even if the application has no focus.

I check the flag "Deselect on backgound click" for the ui input module, but this seems not the right flag.

Cheers,
Tobi

**Comment by Rene-Damm** [comment]
Allowing to force-override the input system respecting/reacting to focus changes makes sense I think. Made a note.

We have a batch of improvements to focus handling pending but decided to wait with them until after 1.0. I'll make sure we take the request here under consideration.

**Comment by tobias-stein** [comment]
Thats good news. Thanks :)

**Comment by stefanunity** [comment]
Closing this as per above comment.

For feedback on the new focus changes please to to  https://forum.unity.com/forums/new-input-system.103/ once we released them.

Thank you!
