### ISSUE TITLE
Change Mouse Primary Button to Left or Right in Windows 10

### ISSUE THREAD

**Issue by CodeNewWorlds** [Unity-Technologies/InputSystem#1123]
![image](https://user-images.githubusercontent.com/2429164/79452500-d2102580-801a-11ea-9db8-cb079fd8babb.png)

1.Check "Switch primary and secondary buttons".
2.When use uGUI's  EventSystem whith StandaloneInputModule Mouse' Left and Right button is switched ,but with InputSystemUIInputModule  primary and secondary button isn't switch.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

You can follow this bug soon at https://issuetracker.unity3d.com/product/unity/issues/guid/1242306/

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
