### ISSUE TITLE
InRange check always false with Apple Pencil

### ISSUE THREAD

**Issue by karlfdev** [Unity-Technologies/InputSystem#1129]
I have seen this issue on the 1st and 2nd gen iPad with 1st gen apple pencil
The inrange check always seems to return false?
I used the prefab tool which shows the debug info, everything else like tilt/pressure/presses work
Just InRange never does

I don't know if apple pencil supports in range, but my cheap tablet pen does and it works with the input system great!

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experiencing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback, questions and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
