### ISSUE TITLE
[Windows Standalone] mouse.scroll.y value is inverted

### ISSUE THREAD

**Issue by JiaUnity** [Unity-Technologies/InputSystem#113]
In Standalone Players, the value for mouse.scroll.y is negative when scrolling up, and positive when scrolling down.
In UWP build, the value is the opposite.
![mousescroll](https://user-images.githubusercontent.com/33637761/40210676-243d0776-59fb-11e8-8b6c-7cfb503bc22d.gif)
The blue arrow is showing how the mouse is scrolling. The red text is the y value from new Input System.

**Comment by Rene-Damm** [comment]
I think that what UWP does is actually better and probably what we want the other platforms to do as well. What's the orientation of values we get in the old input system?

Having Y up on the wheel (i.e. scrolling up increases Y, scrolling down decreases Y) fits with the orientation of the screen axis in play mode.

**Comment by JiaUnity** [comment]
Yeah. In the Old Manager, Up = positive value, Down = negative value

**Comment by JiaUnity** [comment]
The scroll direction on Mac is the same as UWP:
![macscroll](https://user-images.githubusercontent.com/33637761/40455134-6d44dc10-5ea0-11e8-9790-277dda4f9661.gif)
Is it the Windows Standalone reversed?

**Comment by Rene-Damm** [comment]
Yup, I think Windows (and other platforms if need be; Android?) should be changed to do the same as UWP and Mac.

**Comment by Rene-Damm** [comment]
BTW love the very visual bug reports :)

**Comment by Rene-Damm** [comment]
Fixed in 3abd1e283b32 in native. On its way into 2018.2 beta.

**Comment by JiaUnity** [comment]
This has been fixed somewhere along the fixing.
