### ISSUE TITLE
TUIO support request

### ISSUE THREAD

**Issue by dburongarcia** [Unity-Technologies/InputSystem#1131]
Hello, right now Touchscript is the only easy way to receive TUIO input in Unity 2019.3

Are there any plans to support TUIO in this new InputSystem? This will allow to use tangibles more easily within Unity.

**Comment by stefanunity** [comment]
If https://www.tuio.org/ is what you mean then we have no current plans to support this directly, sorry.

If you want to start a discussion on our dedicated forum you might get more interest from the wider community though and the developers. See https://forum.unity.com/forums/new-input-system.103/

We're going to close the git issues soon and keep communication to the forum and normal bug reports.

**Comment by dburongarcia** [comment]
Thanks. I'll ask there.
