### ISSUE TITLE
Multidisplay support for UI with multiple cursors

### ISSUE THREAD

**Issue by dburongarcia** [Unity-Technologies/InputSystem#1132]
Hello, do you have any news about multidisplay support with the new InputSystem? It seems Unity 2019.3 works now with just one cursor and UI in multiple displays, but multiple cursors don't work. Any tips to get it working? Thanks

**Comment by stefanunity** [comment]
Hello,

a better place for discussions such as this is our dedicated forum. See https://forum.unity.com/forums/new-input-system.103/

We're also closing the Git Issues soon and use the forum plus normal bug reports going forward.
Thanks!

**Comment by dburongarcia** [comment]
Thanks. I'll ask there.
