### ISSUE TITLE
Scrollbar value negative with Input System UI Input Module

### ISSUE THREAD

**Issue by David548219** [Unity-Technologies/InputSystem#1135]
**Description**
Using _Input System UI Input Module_ component instead of _Standalone Input Module_ causes scrollbar to not operate correctly. I have discovered this while using ScrollRect to implement chat history view. This happens only if you press LMB and don't move mouse pointer, once you move the pointer handle starts operating normally. This happens with clicks everywhere within the sliding area, even on the handle itself.

**Repro project**
1. Create empty project.
2. Import _Input System_ package 1.0.0-preview7.
3. Change _Active Input Handling_ to _Both_.
4. Create _EventSystem_ empty game object.
5. Add _Event System_ component to _EventSystem_.
6. Add _Standalone Input Module_ component to _EventSystem_ and disable it.
7. Add _Input System UI Input Module_ component to _EventSystem_ and disable it.

**To Reproduce**
Steps to reproduce behavior

Initial state scrollbar and _EventSystem_
![изображение](https://user-images.githubusercontent.com/34396308/80551625-6176ea80-89c4-11ea-8502-341770ad8ca3.png)

1. Enable _Standalone Input Module_ component.
2. Click on the scrollbar sliding area.

With _Standalone Input Module_
![изображение](https://user-images.githubusercontent.com/34396308/80551825-101b2b00-89c5-11ea-88df-5cbddbef2a47.png)
_As we can see value is correct with Standalone Input Module component_

3. Disable _Standalone Input Module_ component.
4. Enable _Input System UI Input Module_ component.
5. Reset scrollbar value to 0.
6. Click on the scrollbar sliding area.

With _Input System UI Input Module_ 
![изображение](https://user-images.githubusercontent.com/34396308/80551949-786a0c80-89c5-11ea-99ef-e62941409f47.png)
_We can see value is incorrect, because it must be within [0,1] and, as we have seen earlier, it should be 1_

**Expected behavior**
Scrollbar value changing according to mouse position (to 1).

**Actual behavior**
Scrollbar value turning negative and dropping continuously (-490 and dropping).

**Desktop**
OS: Windows 8.1 x64
Build target: Editor, Windows x86_64 Mono
Unity version: 2019.2.14f1, 2020.1.0b5
Input System package version: 1.0.0-preview7

**Comment by arosolino** [comment]
Just would like to note I am seeing the same issue

**Comment by stefanunity** [comment]
Hello,
this is already fixed for 20.2, 20.1 and will be fixed for 19.3 too soon.
Thanks for submitting this issue.

**Comment by arosolino** [comment]
Sorry for opening this back up but just wondering how would I track when this would be fixed in 19.3?
