### ISSUE TITLE
Causes tvOS build to fail

### ISSUE THREAD

**Issue by burningthumb** [Unity-Technologies/InputSystem#1138]
You can read about the problem and the fix here:
https://medium.com/@TETRA2000/use-inputsystem-package-for-tvos-in-unity-2019-acf810aa92c7

Basically since there is no support for vr on tvOS this file:
Packages/com.unity.inputsystem/InputSystem/Unity.InputSystem.asmdef

Needs to have this removed:

```
{
            "name": "com.unity.modules.vr",
            "expression": "1.0.0",
            "define": "UNITY_INPUT_SYSTEM_ENABLE_VR"
},
```

**Comment by stefanunity** [comment]
Hey, thanks for bringing this up. We are going to be tracking this here https://issuetracker.unity3d.com/product/unity/issues/guid/1245099/ soon.

**Comment by burningthumb** [comment]
No worries.

I’m confused though by your workaround:

> -workaround:
> --disable the VR module via the package manager

How can I do this with a built in package like VR?

**Comment by stefanunity** [comment]
You can do that as described under https://docs.unity3d.com/Manual/upm-ui-disable.html
