### ISSUE TITLE
Amazon Fire OS Menu

### ISSUE THREAD

**Issue by burningthumb** [Unity-Technologies/InputSystem#1144]
I'm using the Amazon Fire OS and the menu button is read using the Legacy input system with this code:

`Input.GetKeyDown(KeyCode.Menu) /* Amazon menu */`

I don't see (maybe I missed it?) any keycode for this using the new Input System.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
