### ISSUE TITLE
[Windows Standalone] The origin of the mouse position is not located correctly.

### ISSUE THREAD

**Issue by JiaUnity** [Unity-Technologies/InputSystem#115]
In Old Input Manager, the (0,0) is located at the lower left corner of the Player window. 
However in the New Input System, the origin point is near the middle on the left edge of the screen.
![mousepositionstandalone](https://user-images.githubusercontent.com/33637761/40211211-2f49000e-59fe-11e8-8709-c29ef97f27fd.JPG)

The difference between two systems:
![mouseorigin](https://user-images.githubusercontent.com/33637761/40211458-c2442266-59ff-11e8-8608-6bb70b3e99ab.gif)
Blue text = Old Input Manager. Red text = New Input System

**Comment by Rene-Damm** [comment]
Fixed in 1f1cf7936d62. On its way into 2018.2 beta.

**Comment by JiaUnity** [comment]
This has been fixed long time ago.
