### ISSUE TITLE
Control Scheeme Change Events in build

### ISSUE THREAD

**Issue by BryceStandley** [Unity-Technologies/InputSystem#1154]
I've been running into this issue with the new Input system on my Uni project. We can have the Control Scheme Changed event trigger with 0 issues in the editor. (we're using it to change the UI displayed between gamepad and pc) But in a build, it never works. no matter the way i set it up, using the PlayerInput on a game object and assigning the event to a script, subscribing to the event onEnable nothing. Works fine in the editor. I've attached some of the code we used to have it working last time we were trying to handle this issue but there's no errors or logs as there's no null references etc in the game from this.

`    
public PlayerInput playerInput;
private void OnEnable()
    {
        InputSystem.onEvent += InputSystem_onEvent;
    }
    private void OnDisable()
    {
        InputSystem.onEvent -= InputSystem_onEvent;
    }

    private void InputSystem_onEvent(UnityEngine.InputSystem.LowLevel.InputEventPtr arg1, InputDevice arg2)
    {
        if(playerInput.currentControlScheme.ToLower().Contains("gamepad"))
        {
            gamepad = true;
        }
        else
        {
            gamepad = false;
        }
        InputUISwitcher.instance.OnInputChange(gamepad);
    }`

**Comment by stefanunity** [comment]
You might be running into this issue https://issuetracker.unity3d.com/product/unity/issues/guid/1188222/

If the workaround provided there doesn't fix this for you please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

We're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
