### ISSUE TITLE
[Windows Standalone] mouse.scroll.y value does not return back to 0 after scrolling stops.

### ISSUE THREAD

**Issue by JiaUnity** [Unity-Technologies/InputSystem#116]
It either stays at 120 or -120 depends on the last scrolling direction.
![scrollvalue](https://user-images.githubusercontent.com/33637761/40211620-8019ac0c-5a00-11e8-89be-744a08f7fc45.gif)
Blue arrow show how the mouse scrolls from Old Input Manager. 
Red text is the value from New Input System.

**Comment by Rene-Damm** [comment]
Should be fixed in https://github.com/Unity-Technologies/InputSystem/commit/dd71b04aa2e8b7396748f8c78f74dc2f7b5f03f2.
