### ISSUE TITLE
Can I consume events in a thread?

### ISSUE THREAD

**Issue by sharpobject** [Unity-Technologies/InputSystem#1162]
Hello,

I'd like to use rollback netcode in a game, where the game believes that time is divided into discrete chunks, and the game state at any time is a function of all the inputs from all the players in each chunk up until that time. I would like for my game client to send its input events over the network to other game clients as soon as the input events are available, rather than sometimes waiting a few milliseconds for an update and render to happen, then checking inputs, then sending the input events over the network. With this in mind, can I subscribe to input events on some thread other than the main thread?

**Comment by Rene-Damm** [comment]
Hi @sharpobject, could you post the question over in https://forum.unity.com/forums/new-input-system.103/?

**Comment by StephenHodgson** [comment]
Why? This seems like the appropriate channel for this.

And the interface is much easier than that old clunky forum

**Comment by Rene-Damm** [comment]
@StephenHodgson We're in the process (well, have been for a rather long time now) of turning off GitHub issues on this project. We need a single place for bugs and our established bug reporting channels are working much better than GitHub issues for what we need.
