### ISSUE TITLE
Button press/release not persistent across Action Maps

### ISSUE THREAD

**Issue by kestrel-x86** [Unity-Technologies/InputSystem#1166]
Consider this quick and ugly example:
https://github.com/sawyersteven/UnityInputSystemExample

There are two action maps: `Main` and `Wheel`

The demo works somewhat similar to a weapon wheel in a fps. Hold `O` to open the wheel, press whatever direction you want to select with `wasd`, then release `O` to close the wheel and return to gameplay.

In this demo, opening the Wheel enables the Wheel Action Map, which contains the action that listens to `O`'s release. But the release of the button is only called if it is pressed *after* the Wheel action map is enabled.

**Comment by Rene-Damm** [comment]
Switch the action type to value. In the current design, button actions react only to presses happening after they are enabled. Value actions react immediately to a control already being actuated when they are enabled.

**Comment by stefanunity** [comment]
By current design then.
