### ISSUE TITLE
StepCounter not working on Xiaomi Mi9T

### ISSUE THREAD

**Issue by Szanik** [Unity-Technologies/InputSystem#1169]
Hi I am tring to access the StepCounter via the new  InputSystem.
For my app i need also the steps which are counted while the app is offline.
Interestingly the Steps are counted on my oneplus 3 but not on the xiaomi.
I also have a android plugin which tries the same thing.
The android plugin gets the same stepscount on the oneplus3  but on the xiaomi it gets way more.
(in comparision with the inputsystem)
On the xiaomi it only gets counted while the app is open.

The code is always the same.

Xiaomi: Miu11.0.5 Android 10
Oneplus3: Oxygen: 9.0.6 Android 9

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

It'd be super nice if you could file a bug report as described here https://unity3d.com/unity/qa/bug-reporting

For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
