### ISSUE TITLE
Errors upon initial import of plugin - Ambiguous call

### ISSUE THREAD

**Issue by rotter** [Unity-Technologies/InputSystem#117]
I have just tried installing this plugin and am getting 3 errors:

1) /myproject/Packages/com.unity.inputsystem/InputSystem/Controls/InputControlLayout.cs(541,40): error CS0121: The call is ambiguous between the following methods or properties: System.MissingExtensions.GetCustomAttribute<UnityEngine.Experimental.Input.InputControlLayoutAttribute>(this System.Reflection.MemberInfo, bool) and UnityEngine.Experimental.Input.Net35Compatibility.Net35Compatibility.GetCustomAttribute<UnityEngine.Experimental.Input.InputControlLayoutAttribute>(this System.Reflection.MemberInfo, bool)

2) /myproject/Packages/com.unity.inputsystem/InputSystem/Controls/InputControlLayout.cs(742,51): error CS0121: The call is ambiguous between the following methods or properties: System.MissingExtensions.GetCustomAttribute<System.Runtime.CompilerServices.FixedBufferAttribute>(this System.Reflection.MemberInfo, bool) and UnityEngine.Experimental.Input.Net35Compatibility.Net35Compatibility.GetCustomAttribute<System.Runtime.CompilerServices.FixedBufferAttribute>(this System.Reflection.MemberInfo, bool)

3) /myproject/Packages/com.unity.inputsystem/InputSystem/InputManager.cs(244,26): error CS0121: The call is ambiguous between the following methods or properties: System.MissingExtensions.GetCustomAttribute<System.SerializableAttribute>(this System.Reflection.MemberInfo, bool) and UnityEngine.Experimental.Input.Net35Compatibility.Net35Compatibility.GetCustomAttribute<System.SerializableAttribute>(this System.Reflection.MemberInfo, bool)

Steps to reproduce:
1) Downloaded Unity 2018.2b (was using 2017.x until this morning)
2) Opened my project on Unity 2018.2b to update/reimport assets on 2018 format
3) Made a small change to my project and saved it (to make sure it's saved on 2018 format)
4) Copied Packages/com.unity.inputsystem/ folder to the Packages folder in my project
5) Alt-tabbed to Unity and allowed it to process/import
(At this point the 3 errors already showed up on the console, but I proceeded)
6) Changed Active Input Handling to Both
7) Restarted Unity
(The 3 errors showed up again)

**Comment by rotter** [comment]
I've been doing some research on this, and it seems to be a conflict between this plugin and Google's Firebase plugin.

Firebase plugin imports some DLLs under a "Parse" folder which implements those same methods.

Google's Firebase is pretty much a standard nowadays for analytics on mobile, so it would be best to make them work together.

**Comment by rotter** [comment]
Further update:

I've changed the method name from "Net35Compatibility.GetCustomAttribute" to "Net35Compatibility.GetCustomAttributeInput", and changed all the calls to this new method name, and the errors are gone (not sure if the solution works yet)

**Comment by rotter** [comment]
The fix above seems to be working fine, couldnt notice any problems

**Comment by douglas-piconi** [comment]
@rotter what happens if you switch your Scripting Runtime Version in the player settings in the editor?  Do you get the error in 3.5 or 4.x  does one make the other go away?

**Comment by Rene-Damm** [comment]
@rotter Can you point me to what Firebase C# support you're using from where?

The Firebase C# code shouldn't make those extension methods public but rather mark them internal.

However, even then, this strikes me as something going wrong somewhere in our compilation pipeline. The input system DLL should not be referencing that MissingExtensions class from the Firebase C# code and thus there should not be a compilation error.

Please let me know where I can obtain the same libraries you're using and I'll give it a look.

**Comment by rotter** [comment]
@Rene-Damm I'm using FirebaseAnalytics.unitypackage from firebase_unity_sdk_4.5.2 : https://firebase.google.com/docs/unity/setup ("DOWNLOAD SDK" button)

I'd guess there's not much way around it other than renaming the method on one of the plugins. But I'm far from expert in making plugins, you mentioned of them making it "internal", maybe this could fix it. I think it's not marked as "internal" because they actually include a third party SDK (Parse SDK) which provides those extension methods to their main plugin, I dont know if Parse is open source or a Google product.

@piconid my Scripting Runtime Version is ".NET 3.5 Equivalent". It's hard to do that test as I'd have to roll back all those manual method renamings I did. On Firebase "Known Issues" page they mention something regarding Parse SDK on .NET 4.0, so if I do change to 4.0 I will probably face some other problems mentioned by them on their site.

**Comment by stewartmiles** [comment]
@rotter we at Firebase use a fork of Parse primarily for the Task implementation in .NET 3.x https://github.com/stewartmiles/Parse-SDK-dotNET/tree/master/Unity.Compat/Public it's all open source so you can recompile it.  We'll take a look at hiding some of the symbols in there that are causing issues.

**Comment by Rene-Damm** [comment]
Gave the FirebaseAnalytics.unitypackage a try and yeah, things are pointing towards our compilation pipeline. The problem seems to be that the methods are contained in a DLL rather than in source and that DLLs in the project automatically get injected into every compile done by the script compilation pipeline.

So, while the input system has its own .asmdef file and thus sits in its own DLL, the Parse DLLs automatically get linked into its build and the DLL ends up referencing stuff it shouldn't.

I'm talking to our scripting team about the issue.

However, regardless of that, the Firebase DLL setup there is a somewhat awkward. Ideally, Unity.Compat.DLL would have all those methods declared internal and use InternalsVisibleTo to give the Firebase DLLs access.

**Comment by Rene-Damm** [comment]
Ok, so there's a feature we're adding to .asmdef files in 2018.3 that allows getting rid of the precompiled references. This will solve the problem here.

We'll take a look at possibly adding a workaround in the meantime.

**Comment by stewartmiles** [comment]
Hi everyone, Firebaser here.  We've patched our copy of the Parse DLL to make these methods internal in our upcoming release which should be available this week.

**Comment by Rene-Damm** [comment]
@stewartmiles Awesome, thank you.

I'll keep this issue open until we've fixed the .asmdef referencing problem on our side that's part of the issue here.

**Comment by Rene-Damm** [comment]
Should be resolved by our removal of .NET 3.5 support.
