### ISSUE TITLE
When a list of supported devices is specified, binding path dropdown is empty

### ISSUE THREAD

**Issue by lordscales91** [Unity-Technologies/InputSystem#1170]
I've found what seems to be a bug. When you specify a list of supported devices through the Input System Package settings, the Input Actions editor shows only the generic "Usages" option for the input binding path dropdown. If you create a control scheme, it will show the options from the selected devices, but only when that control scheme is active. Below are some more detailed steps to reproduce.

1. Create a new Unity project.
2. Import the Input System package (I chose to not update the input settings when asked and manually set it up to "Both". Not sure if it's relevant).
3. On the project settings, add Keyboard, Mouse and Gamepad to the list of supported devices.
4. Create a new Input Actions asset.
5. Create a new Action Map.
6. Unfold the auto-generated action and the select its binding.
7. Open the binding path dropdown.

What I would expect to see is a filtered list of paths from the supported devices (Keyboard, Mouse and Gamepad) in addition to the Usages option. But instead only the Usages option is present.

For the second bug (starting from the state after reproducing the steps for the previous one): 

1. Add a new Control Scheme.
2. Add Keyboard, Mouse and Gamepad to the requirements list.

When switching to the newly added scheme, the binding path dropdown shows the expected items. But switching to the All Control Schemes cause those options to disappear again.

Definitely this is not a critical bug, but a bit annoying and confusing, specially when starting to learn this new system.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

The issue you reported should be already be fixed internally (https://issuetracker.unity3d.com/product/unity/issues/guid/1254150/) and will be released with the next patch release for the package.

If you are still experienceing using this future package version (it is on the "develop" branch here on git) please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
