### ISSUE TITLE
Random Android exceptions in production: Control AndroidSignificantMotion...

### ISSUE THREAD

**Issue by rotter** [Unity-Technologies/InputSystem#118]
I've rolled out an update with the new API and am getting some random exceptions in production. I can't reproduce, on my devices it's working fine.

I will paste the first one here (I've received hundreds of this exception in a few hours):

Exception: Control '/AndroidSignificantMotion' with layout 'AndroidSignificantMotion' has no size set and has no children to compute size from

UnityEngine.Experimental.Input.InputDeviceBuilder.ComputeStateLayout (UnityEngine.Experimental.Input.InputControl control)
UnityEngine.Experimental.Input.InputDeviceBuilder.InstantiateLayout (UnityEngine.Experimental.Input.InputControlLayout layout, InternedString variant, InternedString name, UnityEngine.Experimental.Input.InputControl parent, UnityEngine.Experimental.Input.InputControl existingControl)
UnityEngine.Experimental.Input.InputDeviceBuilder.InstantiateLayout (InternedString layout, InternedString variant, InternedString name, UnityEngine.Experimental.Input.InputControl parent, UnityEngine.Experimental.Input.InputControl existingControl)
UnityEngine.Experimental.Input.InputDeviceBuilder.SetupWithDescription (InternedString layout, InputDeviceDescription deviceDescription, InternedString variant)
UnityEngine.Experimental.Input.InputManager.AddDevice (System.String layout, Int32 deviceId, InputDeviceDescription description, Boolean isNative)
UnityEngine.Experimental.Input.InputManager.AddDevice (InputDeviceDescription description, Boolean throwIfNoLayoutFound, Int32 deviceId, Boolean isNative)
UnityEngine.Experimental.Input.InputManager.ReportAvailableDevice (InputDeviceDescription description, Int32 deviceId, Boolean isNative)
UnityEngine.Experimental.Input.InputManager.OnDeviceDiscovered (Int32 deviceId, System.String deviceDescriptor)
UnityEngineInternal.Input.NativeInputSystem.NotifyDeviceDiscovered (Int32 deviceId, System.String deviceDescriptor)
UnityEngineInternal.Input.NativeInputSystem:Update(NativeInputUpdateType)
UnityEngine.Experimental.Input.InputSystem:.cctor()

The exception isn't started by my code, this is the full stack trace, my app classes arent mentioned anywhere, so I have no idea where this is started.

If there is some way I can detect this situation or catch/avoid this exception please let me know!

If you need me to put any extra code to check this specific case let me know and I can put the code and roll an update in production.

**Comment by Rene-Damm** [comment]
@todi1856 ^^^^

**Comment by Rene-Damm** [comment]
@rotter While not a fix for the actual problem here, I've pushed a change (https://github.com/Unity-Technologies/InputSystem/commit/7b634434aaebb622a92917dbfa5154279924a455) that should make the system keep going even if some devices fail to be set up properly. There will still be an error in the log but the system should start up successfully with whatever devices do make it.

**Comment by rotter** [comment]
I can confirm that those crashes stopped after the update I rolled out with the mentioned push. Thanks!!

**Comment by rotter** [comment]
There was a third exception I was getting (hundreds) that I only noticed now, but it seems it was fixed as well with either this pushed change you mentioned or the other push you mentioned on the other issue I created yesterday.

The exception was:

LayoutNotFoundException: Cannot find control layout 'Float'

Shortened stack trace:
UnityEngine.Experimental.Input.InputControlLayout+Cache.FindOrLoadLayout (System.String name)
...
UnityEngineInternal.Input.NativeInputSystem:Update(NativeInputUpdateType)
UnityEngine.Experimental.Input.InputSystem:.cctor()


If I should open a separate issue for this let me know

**Comment by todi1856** [comment]
Issues with Android sensors should be fixed now. Can some resolve this bug?
