### ISSUE TITLE
How to do it like Input.GetAxis("Horizontal ") return float

### ISSUE THREAD

**Issue by zxt385189207** [Unity-Technologies/InputSystem#1182]
> Finally, if this is set to Mode.Analog, inputs are treated as analog (i.e. full floating-point values) and, other than down and left being inverted, values will be passed through as is.The default is Mode.DigitalNormalized.

Keyboard WASD
` var playerInput = m_Controls.Player.Move.ReadValue<Vector2>(); ` Always int. 

So I don't quite understand how to return float like the Input.GetAxis("Horizontal ") method

**Comment by byleththunder** [comment]
You are always getting a float, since a **vector2** is made of two floats (x and y). However, I do not think you can get decimal values from your keyboard. You are either pressing or not, there is no halfway press on the keyboard.
