### ISSUE TITLE
Random Android exception in production #2: Exception: Cannot find input control 'acceleration'

### ISSUE THREAD

**Issue by rotter** [Unity-Technologies/InputSystem#119]
Here is the full stacktrace I'm getting (I've received hundreds of this exception in a few hours):

UnityEngine.Experimental.Input.InputDeviceBuilder.GetControl[Vector3Control] (System.String path)
UnityEngine.Experimental.Input.LinearAcceleration.FinishSetup (UnityEngine.Experimental.Input.InputDeviceBuilder builder)
UnityEngine.Experimental.Input.InputControl.CallFinishSetupRecursive (UnityEngine.Experimental.Input.InputDeviceBuilder builder)
UnityEngine.Experimental.Input.InputDeviceBuilder.SetupWithDescription (InternedString layout, InputDeviceDescription deviceDescription, InternedString variant)
UnityEngine.Experimental.Input.InputManager.AddDevice (System.String layout, Int32 deviceId, InputDeviceDescription description, Boolean isNative)
UnityEngine.Experimental.Input.InputManager.AddDevice (InputDeviceDescription description, Boolean throwIfNoLayoutFound, Int32 deviceId, Boolean isNative)
UnityEngine.Experimental.Input.InputManager.ReportAvailableDevice (InputDeviceDescription description, Int32 deviceId, Boolean isNative)
UnityEngine.Experimental.Input.InputManager.OnDeviceDiscovered (Int32 deviceId, System.String deviceDescriptor)
UnityEngineInternal.Input.NativeInputSystem.NotifyDeviceDiscovered (Int32 deviceId, System.String deviceDescriptor)
UnityEngineInternal.Input.NativeInputSystem:Update(NativeInputUpdateType)
UnityEngine.Experimental.Input.InputSystem:.cctor()

Again, this is the full stacktrace, the stack isn't started by my code apparently.

If there is some way I can detect this situation or catch/avoid this exception please let me know!

If you need me to put any extra code to check this specific case let me know and I can put the code and roll an update in production.

**Comment by Rene-Damm** [comment]
Should be fixed by https://github.com/Unity-Technologies/InputSystem/commit/1411cb244199d2df06252774a21df29a36377a9f.

More graceful handling of exceptions during device creation is in the works.
