### ISSUE TITLE
Any plans on using the Message System?

### ISSUE THREAD

**Issue by StephenHodgson** [Unity-Technologies/InputSystem#12]
Just wondering if there's any plans on having the actions raise events via the Message System.

https://docs.unity3d.com/Manual/MessagingSystem.html

**Comment by Rene-Damm** [comment]
Good question. In light of the upcoming ECS features in Unity, we intend to not bind any part of the core system to GameObjects but that still leaves room for simply having an adapter that surfaces data from the system as messages. ATM no one has explored this option yet but I think we should.

**Comment by StephenHodgson** [comment]
ECS?

**Comment by Rene-Damm** [comment]
Sorry, Entity Component System. The stuff revolving around the new C# job stuff (https://www.youtube.com/watch?v=AXUvnk7Jws4).

**Comment by StephenHodgson** [comment]
I've been working on the [Mixed Reality Toolkit for Unity's input system](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit/Input/Scripts) for a while, and we use the Message System with custom event data's to get input from a few different sources.  It's very similar to the UI System where classes need to implement an interface to get the events. This is great because we also don't have the dependency on having the class inherit from `UnityEngine.Object` to get events. 

The system has very little to no allocations for input events as well, with the exception of the initial allocations.  There's some refactoring I was doing to clean it up a bit and make sure it's ready for this new Input System, and was doing a review to see the amount of work needed to get it ready.

**Comment by Rene-Damm** [comment]
From what I gather, you're thinking of having input events from the new input system surfaced as messages using the message system, right?

It's possible to implement that kind of translation but it will require a fair amount of interpretation. Input events in the system are very low-level. They are essentially just blocks of unmanaged memory transferred between backends and the device frontends. We intentionally went away from events that are represented as objects and from events that require interpretation and routing. So essentially, each input event is just a raw dump of device state that only InputControls now how to interpret correctly.
