### ISSUE TITLE
[iOS][Touch] Default value for pressure when using finger is 0 (old input & android (both old and new) is 1)

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#120]
Found using c798ef8
<img width="1336" alt="screen shot 2018-05-22 at 14 30 11" src="https://user-images.githubusercontent.com/39190411/40359832-c9a6fc6a-5dcc-11e8-9e41-8090584c4a87.png">

**Comment by todi1856** [comment]
assign to me please

**Comment by renaldasrep** [comment]
Verified as fixed
