### ISSUE TITLE
Not implemented SetMotorSpeeds(float lowFrequency, float highFrequency, float leftTrigger, float rightTrigger)

### ISSUE THREAD

**Issue by onighiri975** [Unity-Technologies/InputSystem#1206]
There is no way to intercept the SetMotorSpeeds function (float lowFrequency, float highFrequency, float leftTrigger, float rightTrigger) with the addition of trigger vibration

**Comment by onighiri975** [comment]
i tried with this code but it still doesn't work

` var gamepad = XInputController.current;
        if (gamepad is IXboxOneRumble rumble)
        {
            rumble.SetMotorSpeeds(0f, 0f, left, right);
        }`

**Comment by NiyahIsFine** [comment]
It still doesn't work

**Comment by pimvwieren** [comment]
Still doesn't seem to work.
