### ISSUE TITLE
[iOS][Touch][Stylus] Pressure value is not normalized

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#121]
Found using c798ef8
This is also the case with old Input on iOS, android seems to not support stylus on old input though (does not register touches made with it).
Pressure range is 0 -> 4.166667 on iOS with stylus (iPad pro + iPen):
<img width="999" alt="screen shot 2018-05-22 at 14 45 04" src="https://user-images.githubusercontent.com/39190411/40360447-ed982052-5dce-11e8-95d6-3abe1ff8a2d2.png">

Pressure range is 0 -> 1 on Android with stylus (Samsung Galaxy Note 8 SM-N950F):
<img width="544" alt="screen shot 2018-05-22 at 14 40 25" src="https://user-images.githubusercontent.com/39190411/40360452-f0f9b878-5dce-11e8-8a11-dbe32a962874.png">

**Comment by todi1856** [comment]
On both iOS and Android, the normal range is [0..1], value 1.0 is when you touch screen normally without applying extra weight,  you can go above 1.0 when you're putting pressure with heavy weight, like in the example above.

In short the behavior is expected.

**Comment by renaldasrep** [comment]
Quite a lot of weight needs to be applied to get 1.0 on android though, and that is the upper limit, you cannot go over it (at least not on the Galaxy Note 8), can this be tuned somehow or is there nothing that could be done?

**Comment by todi1856** [comment]
So there's a difference here, touch pressure and pen pressure.

I think we should agree on that touch pressure can go over 1.0, while pen pressure cannot go over 1.0

**Comment by todi1856** [comment]
@renaldasrep could you test latest develop branch, this should be fine now

**Comment by todi1856** [comment]
Fixed in 2018.3.0a12 @renaldasrep

**Comment by todi1856** [comment]
Also fixed in 2018.2.11f1. I think @renaldasrep already tested it, so this can be closed @Rene-Damm
