### ISSUE TITLE
Usages for child controls not getting matched with InputAction bindings

### ISSUE THREAD

**Issue by joelpryde** [Unity-Technologies/InputSystem#124]
Trying to bind an InputAction against a control with a usage that is a child of a parent control does not appear to work.  It finds the usage for the parent control but never recurses into the children to match with the child control usages.

This script will repro the issue for the following binding `<XRController>{RightHand}/{Position}`:

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Experimental.Input;
using UnityEngine.Experimental.Input.Controls;

public class XRInputTest : MonoBehaviour
{
    InputAction m_PositionAction;
    InputAction m_RotationAction;

    // Use this for initialization
    void Start () {
    }

    private void OnEnable()
    {
        m_PositionAction = new InputAction(binding: "<XRController>{RightHand}/{Position}");
        m_PositionAction.performed += OnPositionUpdate;
        m_PositionAction.Enable();

        m_RotationAction = new InputAction(binding: "<XRController>{RightHand}/{Rotation}");
        m_RotationAction.performed += OnRotationUpdate;
        m_RotationAction.Enable();
    }

    void OnPositionUpdate(InputAction.CallbackContext context)
    {
        var vec3Control = context.control as Vector3Control;
        if (vec3Control != null)
            transform.localPosition = vec3Control.ReadValue();
    }

    void OnRotationUpdate(InputAction.CallbackContext context)
    {
        var quatControl = context.control as QuaternionControl;
        if (quatControl != null)
            transform.localRotation = quatControl.ReadValue();
    }
}

`

**Comment by Rene-Damm** [comment]
Turned out to be a bug in the layout merging machinery which lost the usage data.

**Comment by Rene-Damm** [comment]
Fixed in https://github.com/Unity-Technologies/InputSystem/commit/ac93004a5a921a65c4f88ac5ddbb160e6f17f994.
