### ISSUE TITLE
XR : Haptics didn't work when using OpenVR driver

### ISSUE THREAD

**Issue by KospY** [Unity-Technologies/InputSystem#128]
XRControllerWithRumble.SetIntensity() seem to only work with Oculus touch and the Oculus unity driver.
As soon as we use the OpenVR driver in Unity haptic do not work anymore for both Oculus and Vive controllers.

**Comment by StayTalm** [comment]
This is being fixed :). 
It's on it's way into the 2018.2 unity beta, it was a mistake on my part, sorry.
I'll update with the beta version once I know it.

**Comment by KospY** [comment]
Thanks! So if I understand correctly it's a problem from Unity 2018.2 b5? So that will be fixed in 2018.2 b6 right?

**Comment by StayTalm** [comment]
You are so optimistic :)
Due to various processes internally, it just got resolved and ready to ship, and will be ready for 2018.2 b8.

**Comment by KospY** [comment]
Yeah I was a little bit optimistic :)
Good news anyway! Thanks!

**Comment by borishsu** [comment]
Does anyone still get this issue? I tried out the XRHaptics scene in Assets/QA/Tests/XRHaptics. Both of the Vive controllers are detected, but neither of them responses. Did I miss something to make it work? I am using Unity 2018.2.0f2 with the commit b679522.

Update: Sometimes one of the controllers rumbles, but the rumple period seems to be random and the interval is also unexpected.

**Comment by jackpr-unity** [comment]
Issue still present with Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c

**Comment by jackpr-unity** [comment]
Still present on 2018.3.0b2 with 0.0.7-preview

**Comment by jackpr-unity** [comment]
This seems to be fixed in 0.2.1-preview (Editor 2019.1.0b8).

@KospY can you confirm?

**Comment by JiaUnity** [comment]
@jackpr-unity if this is fixed for you, close it.

**Comment by JiaUnity** [comment]
Seems fixed. Close.
