### ISSUE TITLE
Support plain USB devices on OSX

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#13]
On OSX, supporting USB devices that aren't HIDs would allow talking to XInput devices without requiring 3rd party drivers (https://github.com/360Controller/360Controller). On Windows, we'd not gain as much by supporting straight USB but it might still be a nice thing to have (would allow talking to completely custom USB devices that aren't implementing any of the USB device class interfaces).

**Comment by JiaUnity** [comment]
Last time I checked, this is done
