### ISSUE TITLE
InvalidOperationException: Cannot go from 'Performed' to 'Performed'

### ISSUE THREAD

**Issue by KospY** [Unity-Technologies/InputSystem#130]
If an error happen in the method (or any called methods) used for the InputAction event, the corresponding Input stop working definitely and the error : InvalidOperationException: Cannot go from 'Performed' to 'Performed'; must be 'Waiting' or 'Started' (action: <Unnamed>, interaction: ) spam the log

Obviously we can avoid errors by using try catch block each time, but it's more like a workaround than a solution.
I thinks it's important to fix this before production use, it will make the system more robust to use and avoid case where the player need to restart the game in case of any error.

**Comment by Rene-Damm** [comment]
Should be fixed by https://github.com/Unity-Technologies/InputSystem/commit/92a7359a75b8eeaf58d4c26a70d9423c0521fca3.
