### ISSUE TITLE
XInputControllerOSX doesn't work in OSX

### ISSUE THREAD

**Issue by GuardHei** [Unity-Technologies/InputSystem#131]
Cannot respond to events, including triggers, shoulders
Respond to events weirdly and fail to function, including sticks, buttons

**Comment by Rene-Damm** [comment]
Did you install the Xbox controller driver from https://github.com/360Controller/360Controller?

What kind of XInput controller are you using?

What do you mean by "respond to events weirdly"?

**Comment by GuardHei** [comment]
I did not use a Xbox 360, I used Xbox one via Bluetooth. However, the result was the same even using Xbox One Controller in Products -> Gamepad. Totally no results from any of the two models. However, the left stick seems to be responsive to "start to move" event sometimes, about once in hundreds of input. By the way, my os version is 10.12.

**Comment by Rene-Damm** [comment]
Is this in the editor or in the player or both?

It turns out there was an error that resulted in the native new input system backed to be disabled in OSX players (and players only, not editor) in 2018.2 and that embarrassingly was caught nowhere (we're still struggling to adapt our automation infrastructure to the reality of packages).

**Comment by GuardHei** [comment]
I've tested it in the editor, haven't try the player yet.

Maybe Bluetooth causes the problem?

**Comment by Rene-Damm** [comment]
I see. Could be. Definitely needs more digging.

**Comment by douglas-piconi** [comment]
@GuardHei 0.2.0-preview has a few fixes to the Xinput.   Are you still seeing this problem with latest update?

**Comment by gegagome** [comment]
In my case I see the xbox one controller in my Input Debugger but no response from any input whatsoever.

I do have successful keyboard events working as expected.

**Comment by JiaUnity** [comment]
Verified fix on 2019.1.0b9 with Develop (af5d4c1)

**Comment by gegagome** [comment]
Will the fix make it on 2018.3?
Or when will the fix be public in 2019.1?

Thanks!

**Comment by gegagome** [comment]
I saw 2019.1.0b9 but not develop on the unity download website. Where do you download develop from?

Thanks

**Comment by JiaUnity** [comment]
@gegagome Hey, you can install released package following the instruction here: https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/Documentation~/Installation.md
Or you can just download the Develop branch: https://github.com/Unity-Technologies/InputSystem/tree/develop and copy the new input folder in the Packages folder to your project Packages folder.
