### ISSUE TITLE
Input debugger remote connection does not survive domain reload

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#138]
1. Build, start, and connect to player
2. Verify in Input Debugger that player is connected
3. Make a change to the project's source code in the editor
4. Switch back to the editor to initiate a domain reload

After the reload is complete, remote devices no longer receive input from the player.

**Comment by douglas-piconi** [comment]
The keyboard and mouse are now surviving domain reload.  However, the Xinput device I am testing with disappears from the remote list and shows up on the local list as device1.  I'm looking into this issue now.

**Comment by JiaUnity** [comment]
Verified fix on Trunk 2019.2.0a8. Close.
