### ISSUE TITLE
[Android][Mouse] mouse.delta is stuck at (0, 0)

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#139]
Found using 25ad430

The value is not changing even though the mouse is being moved

**Comment by todi1856** [comment]
@Rene-Damm Deltas should be calculated in C# side and not in native backend, right?

**Comment by Rene-Damm** [comment]
@todi1856 ATM this differs between touch and mouse. For both, delta accumulation and resetting happens automatically but only `Touchscreen` currently computes deltas. `Mouse` expects deltas to be present in the source. For the sake of consistency, may make sense to switch all deltas to being automatically computed.

**Comment by todi1856** [comment]
@renaldasrep this was fixed in 2019.1.0a12

**Comment by renaldasrep** [comment]
Verified
