### ISSUE TITLE
IEditorPlayerConnection cannot be accessed because of it's protection level

### ISSUE THREAD

**Issue by StephenHodgson** [Unity-Technologies/InputSystem#14]
Couldn't compile the project in 2018.1.0b2 nor 0b4.

`IEditorPlayerConnection` cannot be accessed because of it's protection level.

No download link for 2018.1.0b1 in beta archive for the current project editor version.
Is this editor version required?

**Comment by Rene-Damm** [comment]
ATM the native changes required to run the project have not yet landed in a public Unity release. I.e. The current 2018.1 beta is *not* compatible with the project. There's a preview build [here](http://beta.unity3d.com/download/4f520c3a3153/public_download.html) that works with the master branch (which, however, is starting to fall behind).

We're working on having the native changes be part of a Unity release.

**Comment by StephenHodgson** [comment]
Sorry, I somehow missed that custom editor build link on the readme.

**Comment by Rene-Damm** [comment]
No worries. Sorry about the clunky setup ATM. Hopefully we'll be rid of the custom build requirement soon.

**Comment by StephenHodgson** [comment]
I tried downloading from the link provided but I'm getting a 404 error from the windows installer.

**Comment by Rene-Damm** [comment]
Ah darn, I think that goes back to some infrastructure crash we had the other day. Let me investigate.

**Comment by Rene-Damm** [comment]
Could you give it another try? Are you still getting 404s? I've tried things on my end and could successfully download the installer and install Unity from it. Browsed around some to see if there's infrastructure that's still struggling but it appears everything should be working.

**Comment by StephenHodgson** [comment]
It's back up.  Thanks for checking this out.

**Comment by Rene-Damm** [comment]
Ok, awesome.

**Comment by StephenHodgson** [comment]
Still some issues compiling with that editor build.

Am I missing anything else to get started?  I pulled the latest from your dev branch.

**Comment by Rene-Damm** [comment]
Ah, hmm, I should have put something in the README about that. Sorry about that. Only the master branch is compatible with the preview build. The develop branch requires some native API changes that have happened in the meantime. My thought was to provide an updated preview build sometimes in the near future which should bridge things over until things are usable with normal Unity releases. At this point, I don't expect the native API to change anymore.
