### ISSUE TITLE
[Android][Mouse] mouse.scroll glitches when moving mouse after scrolling a bit

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#140]
Found using 25ad430

1. Move mouse around (don't touch the scroll wheel)
Result: mouse.scroll stays at (0, 0)

2. Scroll a bit and then move mouse around (don't touch the scroll wheel)
Result: mouse.scroll.y goes to some value on and off again when moving mouse (negative, if it was scrolled down/ positive, if it was scrolled up)

**Comment by todi1856** [comment]
Fixed in 31f0ca701d6df5d232f4378ce0dc758207b141cb unity repo

**Comment by JiaUnity** [comment]
This bug also happens in Windows and MacOS standalone build, but it does not happen to Touchpad, probably because Touchpad is not recognized as a mouse.
![mousescrollyy](https://user-images.githubusercontent.com/33637761/41484565-3ba3573c-7092-11e8-990f-9ee86565cc2d.gif)
