### ISSUE TITLE
[Editor] TouchControl.pressure is not initialized

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#141]
Try to do Touchscreen.current.touches[0].pressure.ReadObject() in Editor, run it on touch screen monitor, the returned pressure will be not initialized value, it should be either 1.0 (if pressure is not supported) or should vary beween [0..max value]

**Comment by Rene-Damm** [comment]
There shouldn't be any uninitialized memory (state memory is MemCleared immediately after allocation) so I'm wondering whether we're actually receiving some garbage data here.

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/editor-touch-touchcontrol-dot-pressure-is-not-initialized
