### ISSUE TITLE
[MacOS] [Keyboard] When Caps Lock is active, the key is always read as pressed.

### ISSUE THREAD

**Issue by JiaUnity** [Unity-Technologies/InputSystem#143]
The Control.ReadValue() is always bigger than 0 for Caps Lock key when the cap lock is active, which also affects the Control.isPressed.
This is different from the Windows standalone build.
![maccaplock](https://user-images.githubusercontent.com/33637761/41484998-a3e9a20a-7093-11e8-82dd-530667ffd147.gif)
Note: The Caps lock key was NOT held down. It was only pressed at the beginning and end of the gif.

**Comment by Rene-Damm** [comment]
Not sure we'll be able to get a different read here. Pretty sure that on the OS side, given that it's a key with a "lock" state, the press and release we get is for the lock state and not the key press. But maybe we can drop a level lower and look at the actual key state to still read press and release.

**Comment by JiaUnity** [comment]
Closing as By Design.
