### ISSUE TITLE
[Windows][Mouse] The delta value is very small comparing to the MacOS build.

### ISSUE THREAD

**Issue by JiaUnity** [Unity-Technologies/InputSystem#144]
When the resolution settings are comparable, the delta value for Windows standalone build is much smaller than the Mac build.

**Windows:**
![posdeltawin](https://user-images.githubusercontent.com/33637761/41488700-2dd85480-70a2-11e8-9f0c-b569bd942aaa.gif)
![winposdelta](https://user-images.githubusercontent.com/33637761/41488919-e688ebca-70a2-11e8-84d4-ace58a430020.jpg)

**MacOS:**
![posdeltamac](https://user-images.githubusercontent.com/33637761/41488690-22715b50-70a2-11e8-81f4-c50348db1298.gif)
![macposdelta](https://user-images.githubusercontent.com/33637761/41488714-36932780-70a2-11e8-8d06-7c5c5ded4856.jpg)

**Comment by douglas-piconi** [comment]
Fixed with sensitivity bug fix.
