### ISSUE TITLE
Input event time doesn't correlate with Time.realtimeSinceStartup

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#147]
(Moving internal discussion to here)

Basically when app starts, and you'll look at the Time.realtimeSinceStartup and received input event time, you'll see that on some platforms input event time is way ahead. This might a problem because if you want to code a game which expects fast inputs and you want to compare time values - you cannot, because it's not clear what is the origin time of input event.

Maybe we should sync input event time with Time.realtimeSinceStartup? So let's say if you make a click after 20 seconds from the application start, event time will really be around 20 seconds.

**Comment by Rene-Damm** [comment]
Public event time is now on same timeline as `Time.realtimeSinceStartup` as of latest head.
