### ISSUE TITLE
InputActionManager does not flush reliably when mixed updates are enabled

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#151]
This may be me not using the new InputActionManager correctly, but I'm reading from my Input binding class and preparing to write events into an ECS World using a JobComponentSystem/Barrier combo.

Before I got too deep, I added some logging using StringBuilder to ensure everything is reading correctly.

Every so often I see something like what's below where the Events seem like identical. Is there something I should be manually flushing? 

Gist of files involved and my log comparison is here:
https://gist.github.com/periodyctom/1b53795fad63797a6f3366ea30f64f68

I can setup a min-repro project if needed.

**Comment by Rene-Damm** [comment]
I think this is probably a bug in `InputActionManager.OnBeforeInputSystemUpdate` where it decides whether to flush. Looking at that method, the logic seems suspicious to me.

**Comment by Rene-Damm** [comment]
One thing you could try is to just turn this method into
```
        private void OnBeforeInputSystemUpdate(InputUpdateType type)
        {
            Flush();
        }
```

Starting to think this is actually what this method should amount to.

**Comment by periodyctom** [comment]
I'll give that a try later and report what happens. It's like 1 out of every 5-7 updates it happens so it's very much a timing fluctuation thing

**Comment by Rene-Damm** [comment]
Sorry, with a clearer head now, I realize the above code snippet as is will probably destroy the usefulness of `InputActionManager` for you. Could you give it a try together with `InputSystem.updateMask = InputUpdateType.Dynamic;` to make sure that dynamic updates are the only ones that are running?

**Comment by periodyctom** [comment]
Ok, I'll try it today.

**Comment by periodyctom** [comment]
That seems to work, thanks. Let me know when I can remove my hack.

**Comment by periodyctom** [comment]
Latest changes seem to work just setting the update type to `InputUpdateType.Dynamic` without the flush hack, I'm in the middle of a hefty refactor to improve the ECS handling of a few things, but I'll double check it again after that and if I don't find it again, I'll let you know.

**Comment by Rene-Damm** [comment]
Obsolete by way of `InputActionManager` being no more. As of https://github.com/Unity-Technologies/InputSystem/commit/1f8e4e052c3375fabb14475d8332a8206e5a0262 the mechanism has been replaced with a simplified `InputActionEventQueue` which can be flexibly hooked up to actions and action maps and which puts flushing under user control rather than trying to automatically synchronize to update boundaries.
