### ISSUE TITLE
[Mac OS X] Seeing duplicate/extra USB devices on OS X editor.

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#152]
I'm seeing this on 25ad430d08d01b213209ada6d322d375d9202706, Unity 2018.2b7 Mac OS X.
When I plug in my controller, it adds 2 identical XBox Controller devices, but with different Ids. If I unplug the gamepad, only one of the devices seems to register as removed. 

I'm using the changes described in issue #151 if that makes any difference, but I noticed the issue occuring before I applied them.

I haven't tested any other gamepads yet.

**Comment by periodyctom** [comment]
Looking at it a bit more, I think the "Editor Only" or a previous version of the device is surviving the domain reload. It doesn't seem to produce any events per-frame during play mode.

**Comment by periodyctom** [comment]
Just did some additional tests. It only seems to happen if I startup the editor with a controller plugged in. If I start without a controller plugged in, then plug it in afterwards (in edit or play mode), it behaves correctly so far. I'll update this if I find any more repo cases.

**Comment by periodyctom** [comment]
After doing some refactoring and additional debugging with other devices, this seems to affect not just my XBOX One controller, but also a USB mouse I use with my macbook pro. I suspect the issue is probably specific to USB devices, as the built-in devices don't seem to have the problem.
Attached is an image from my debugging session.

<img width="1440" alt="duplicateusbdevices" src="https://user-images.githubusercontent.com/6497295/42854418-a70d974a-89f0-11e8-8187-f51d1a242f00.png">

The IBCF-5 is an Anker mouse.

**Comment by Rene-Damm** [comment]
Should be fixed as of 2018.2.5.
