### ISSUE TITLE
The error when disable an InputControls.

### ISSUE THREAD

**Issue by watsonsong** [Unity-Technologies/InputSystem#154]
I come from this url:
https://forum.unity.com/threads/i-met-an-error-when-i-disable-an-inputcontrols.537858/
InputManager.Remove seems missing a null check:
public void Remove(IInputStateChangeMonitor monitor, long monitorIndex)
{
                if (listeners == null)
                    return;
 
                ////REVIEW: would be better to clean these up implicitly during the next traversal
                for (var i = 0; listeners != null && i < listeners.Length; ++i)
                    if (ReferenceEquals(listeners[i].monitor, monitor) && listeners[i].monitorIndex == monitorIndex)
                    {
                        ArrayHelpers.EraseAt(ref listeners, i);
                        ArrayHelpers.EraseAt(ref memoryRegions, i);
                        signalled.SetLength(signalled.length - 1);
                    }
}

**Comment by Rene-Damm** [comment]
Should be fixed in https://github.com/Unity-Technologies/InputSystem/commit/03b89a7706cb5e0bc6d6ff368486fa22e2a6c858.
