### ISSUE TITLE
Chain binding modifier does not function as expected

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#155]
Expected Behavior: When a binding is set to be changed, the action will not trigger unless both controls are activated

Observed Behavior: The chaining does not occur.  Either individual control will trigger the action

![untitled](https://user-images.githubusercontent.com/36174025/42039456-a9ae8430-7aed-11e8-8d5e-a111f896eb20.png)

**Comment by Rene-Damm** [comment]
Obsolete as the new UI does not include the switch.
