### ISSUE TITLE
InputActionListTreeView does not contains a definition for "foldoutOverride"

### ISSUE THREAD

**Issue by bet0v** [Unity-Technologies/InputSystem#156]
When using the last package of branch asset-editor in Unity, the script  _InputSystem/Editor/InputActionAsset/InputActionListTreeView.cs_ tries to access **foldoutOverride** definition of InputActionListTreeView  that does not exist.

**Comment by periodyctom** [comment]
Same, I have to roll back to 2a152fe4d45e16e4a7fbea0d630171b37a3863a3 for the error to go away.

**Comment by Rene-Damm** [comment]
Crap, we soon need to have a better structure for dealing with different versions of the Unity runtime and for verifying things against the *actual* public release version. Sorry about that.

I've commented out the line in https://github.com/Unity-Technologies/InputSystem/commit/48a0ef565230043b210cdac0b8c87adb8523bb7d.

The code is part of a new action editor UI that isn't functional yet so no loss of functionality ATM.

**Comment by bet0v** [comment]
Thanks !
Looking forward to see this new UI ;)

**Comment by Rene-Damm** [comment]
Solved as of https://github.com/Unity-Technologies/InputSystem/commit/5c83f129a8b7e4e18e9e9de8749675e3e18c9b93.
