### ISSUE TITLE
The OnScreenStick send Vector3 type may incorrect.

### ISSUE THREAD

**Issue by watsonsong** [Unity-Technologies/InputSystem#157]
I try to use the OnScreenStick to bind the UGUI joystick to gamepad with the control path: /<GamePad>/LeftStick

But the `SendValueToControl(newPos);` send a Vector3 so the control cast in SendValueToControl will failed.
I change the `SendValueToControl(newPos);` into `SendValueToControl(new Vector2(newPos.x, newPos.y));` to resolve this problem, but it seems not a right way to do this.

And there is another thing is OnScreenControl use OnEnable and OnDisable to add and remove a on screen device. But sometime, for example the joystick is disabled in normal time, enable only when the player touch it. So it could be better to change the OnEnable and OnDisable to Awake and OnDestroy.

**Comment by Rene-Damm** [comment]
Should be fixed in https://github.com/Unity-Technologies/InputSystem/commit/15cc5b4f11d611ac42bbb0ff3765fdc6e2ee47c6.
