### ISSUE TITLE
[Performance] Too much time spent during domain reloads

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#158]
`InputManager.OnAfterDeserialize` can easily add 200ms just by itself to a domain reload (and that doesn't even count the overhead we add to serialization in terms of size and time). On top, there's the cost paid for `InitializeOnLoad`. Overall, the system simply adds too much work to reloads.

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/performance-too-much-time-spent-during-domain-reloads
