### ISSUE TITLE
Input system 1.5 TestFramework.Player compile errors

### ISSUE THREAD

**Issue by TheXRMonk** [Unity-Technologies/InputSystem#1642]
Input system 1.5 TestFramework.Player compile errors;
InputTestFixture.cs
[line 94](https://github.com/Unity-Technologies/InputSystem/blob/45932af58fe4b1e7dccd239265c32eda8a1078f6/Packages/com.unity.inputsystem/Tests/TestFixture/InputTestFixture.cs#L94)
and
[line 168](https://github.com/Unity-Technologies/InputSystem/blob/45932af58fe4b1e7dccd239265c32eda8a1078f6/Packages/com.unity.inputsystem/Tests/TestFixture/InputTestFixture.cs#L168)
is calling methods in InputSystem.cs that's under #if DEVELOPMENT_BUILD

**Comment by TheXRMonk** [comment]
Just to be clear; this will only compile if making development builds - releases won't compile.

**Comment by andrew-oc** [comment]
Hi there

Thanks a million for the bug report and sorry to hear you're having issues. However we don't track bug reports through GitHub issues anymore. If you're issue is still on-going, we'd really appreciate a bug report using the instructions here https://unity3d.com/unity/qa/bug-reporting. This issue will now be closed.

Thanks
The Unity Input System Team
