### ISSUE TITLE
InputAction Array renders wrong element name on first element in the Inspector

### ISSUE THREAD

**Issue by RobinMeow** [Unity-Technologies/InputSystem#1647]
Using Version: 1.4.4

![image](https://user-images.githubusercontent.com/111490292/219654873-32e5e71e-2c73-423c-aec1-58eb4114c960.png)
![image](https://user-images.githubusercontent.com/111490292/219654957-14c02a47-a34b-4492-ae14-f3f01928ddb7.png)

"Element 0 0" should be called "Input Action 0". 
When I swap the elements around, it is always the first element which is called "Element 0 0"

It doesnt bother me, just thought I leave it here, so you at least know.

**Comment by andrew-oc** [comment]
Hi there

Thanks a million for the bug report and sorry to hear you're having issues. However we don't track bug reports through GitHub issues anymore. If you're issue is still on-going, we'd really appreciate a bug report using the instructions here https://unity3d.com/unity/qa/bug-reporting. This issue will now be closed.

Thanks
The Unity Input System Team
