### ISSUE TITLE
[Windows Standalone] Provide Support for multiple mice and keyboards via PointerId

### ISSUE THREAD

**Issue by petersvp** [Unity-Technologies/InputSystem#166]
In InputSystem/Devices/Mouse.cs it's clearly seen that **pointerId is not used** for mice while technically this is possible and used in games like Trine. Everybody would love playing point-and-click multiplayer game with multiple mice connected. And in case with Trine, on our huge desks we can play with three KB+M combos :)

[InputControl(name = "pointerId", layout = "Digital", offset = InputStateBlock.kInvalidOffset)] // Will stay at 0.

Example for multiple mice can be found into my pastebin, here:

C++ DLL: https://pastebin.com/0Szi8ga6 - (replace HWND_DESKTOP with HWND_MESSAGE to disable focus-control)
C# MouseInputManager that uses this lib: https://pastebin.com/4h3CqpYy

**Comment by todi1856** [comment]
Wait, wouldn't that be two seperate mouse devices, at least on Android you can already hook two mice, and you would access them via InputSystem.devices of typeof(Mouse) ?

**Comment by petersvp** [comment]
Yes, they are two separate device but I think that the code does not treat them as separate. On Windows by using RawInput it is perfectly possible to track two mice independently. That is why I am firing the issue. Having this supported in Unity on Windows will be heaven for local coop out of the box! Check the pastebin sample for multi-mice manager implementation I used before :)

**Comment by Rene-Damm** [comment]
Yes, there's no support for pointerId yet in the Windows backend. It's on the list. It's made trickier by the fact that the pointer API for Windows is 8+ yet we still support Windows 7 (we just relatively recently got rid of XP and Vista).

**Comment by petersvp** [comment]
@Rene-Damm RawInput works on Windows 7 too! And on XP. At least this API was the only API back at the days at XP when I "played" (the C++ way) with multiple mice and multiple keyboards on a custom made game engine. 

RawInput was partially lacking documentation, though, but they eventually documented it completely. And Unity is using it! (I had issues with Play mode killing my DLL and afterwards notices that Unity is itself using RawInput under the hood somehow). Back at the days there were commercial apps doing that. On the other side UWP does not support multiple mice yet (but I don't care about UWP at all) - you can still add this to Standalone :) And I hope you will, again, bledd the local multiplayer. Especially for games that are only to be played with mice, this could make things more interesting and more unique (and I hope you seen my working example in the request).

I really hope that the Input system will be the best possible engineered feature in Unity. I have serious issues with other Unity systems like, the PhysX support (lack of articulations and lack of true soft bodies), and I will really love to see that Unity is going the correct way now, thanks to people like you that want to put theirs best effort on their job :)  (I work in an IT company too and know how big enterprises work)

**Comment by Compsciler** [comment]
@petersvp Do you know where to paste these scripts for multiple mice inputs in Unity? Thanks!

**Comment by petersvp** [comment]
@Compsciler "where to **paste**" ? Well, you need to compile the C++ code as a DLL, know what a DLL is and then tweak A LOT my C# code to fit in your project. I merely provided this sample to Rene-Damm to investigate and eventually include in the New Input System. 
 
@Rene-Damm any update on this? Again, RawInput works the same way on Windows 7 with almost no changes, it just wasnt documented back in the days :)

**Comment by Rene-Damm** [comment]
We have multi-pointer&keyboard support on the list for features to consider once we get back to feature work (when 1.0 is in safe waters). It's high on the list. (Internal ticket ISX-275)

As part of migrating away from GitHub issues, I'll go close this one here. No worries, though, we have this one on the radar.

On the managed side, everything is ready as the system doesn't care how many mice/pens/touchscreens/keyboards there are but on the native side we definitely have work to do.
