### ISSUE TITLE
[Enhancement] Restart the editor when changing the Active Input Handling player setting

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#167]
When you change the Scripting Runtime Version in player settings (between 3.5 and 4.X), the editor prompts you to restart.

When changing Active Input Handling, it notifies you that you must restart, but does not default to doing so.

I suggest mimicing the Scripting Runtime Version setting functionality.

**Comment by douglas-piconi** [comment]
I'll look into this

**Comment by douglas-piconi** [comment]
Fix is in editor code.  Creating PR for trunk.

**Comment by douglas-piconi** [comment]
PR in flight
