### ISSUE TITLE
[Windows Standalone][Stylus] Stylus touch.type input is detected as "Direct" instead of "Stylus"

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#168]
Found using: b0c8fc2
Device: Microsoft Surface Pro (Model: 1796) + Microsoft Surface Pen (Model: 1776)

Stylus input is detected as "Direct" instead of "Stylus"

**Comment by Rene-Damm** [comment]
Think we should be able to deduce this from the `hSource` field in `TOUCHINPUT` in some way (hopefully without also having to rely on the Windows 8+ pointer API).

**Comment by renaldasrep** [comment]
Now it's detecting it as "Indirect", shouldn't it be "Stylus" ?

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/windows-touch-stylus-touch-dot-type-input-is-detected-as-direct-instead-of-stylus
