### ISSUE TITLE
[Windows Standalone][Stylus] touch.radius values are 0 or very exaggerated

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#169]
Found using: b0c8fc2
Device: Microsoft Surface Pro (Model: 1796) + Microsoft Surface Pen (Model: 1776)

Radius values are 0 or very exaggerated:
1. A tap with the stylus reports radius roughly as (5.8M, 42.9M) (M as in Million) when in Play mode
2. A tap with the stylus reports radius as zeros and flickering millions when built for standalone and in full-screen mode
3. A tap with the stylus reports radius as zeros when built for standalone and in windowed mode

**Comment by renaldasrep** [comment]
Still an issue

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/windows-touch-stylus-touch-dot-radius-values-are-0-or-very-exaggerated
