### ISSUE TITLE
[Windows Standalone][Stylus] A new touchId isn't assigned after the "Ended" state if between taps the distance between the screen and the pen is very little

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#170]
Found using: b0c8fc2
Device: Microsoft Surface Pro (Model: 1796) + Microsoft Surface Pen (Model: 1776)

There's this special behaviour with surface pro, where it detects input even if the stylus is not touching the screen directly (dot shaped cursor)

When you stop touching (with the distance between the screen and pen being up to 1cm or so) it switches to "Ended". BUT, when you touch again, it gets the same ID, unless you make the aforementioned distance larger (and the dot shaped cursor disappears) then touch again.

I'm not sure if it's intended

**Comment by Rene-Damm** [comment]
ATM we don't really have stylus support/handling in the Windows touch input code path. So, not surprised that we're getting into issues when the "touches" are actually coming from the pen. Anyway, ultimately the code should handle that reliably so the reuse of IDs here is likely to be an issue we want fixed.

**Comment by renaldasrep** [comment]
still an issue

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/windows-touch-a-new-touchid-isnt-assigned-to-stylus-input-after-the-ended-state
