### ISSUE TITLE
[Windows Standalone][Stylus/Touch] touch.pressure is always reported as 0

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#171]
Found using: b0c8fc2
Device: Microsoft Surface Pro (Model: 1796) + Microsoft Surface Pen (Model: 1776)

Pressure is always reported as 0

**Comment by renaldasrep** [comment]
Same with touch (Do I open a new issue for it?)

**Comment by Rene-Damm** [comment]
The Windows 7 touch API does not support pressure. I think what we ultimately want is Windows 8+ pointer API-based touch support. Unfortunately, as long as we haven't dropped Win 7 support (which likely won't be the case for quite a while), that'll mean that the touch codepath will get split in two, making it quite likely the old Win7 codepath will break more often.

Anyway, something to look into. For now, as long as we support pressure on pens, I'm not terribly concerned about not supporting pressure on touch.

**Comment by renaldasrep** [comment]
now it seems to be either 0 or some cosmical number like 8.884232E-43

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/windows-touch-touch-dot-pressure-is-always-reported-as-0
