### ISSUE TITLE
[Windows Standalone][Stylus/Touch] touch.phase hardly ever switches to "Stationary"

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#172]
Found using: b0c8fc2
Device: Microsoft Surface Pro (Model: 1796) + Microsoft Surface Pen (Model: 1776)

State hardly ever switches to "Stationary"
While it's pretty easy to see the state switch to "Stationary" on both Android and iOS, I've only seen a couple of flickers of it using the Surface PRO, even if the other values are still it reports as "Moved"

**Comment by renaldasrep** [comment]
still an issue

**Comment by JiaUnity** [comment]
@renaldasrep I don't see this bug repro with Touch.
Is this the case for Stylus only?

**Comment by JiaUnity** [comment]
Filed in FB. Closing.
