### ISSUE TITLE
[Android][GamePad] Neither of triggers are working when using NVidia Shield Controllers

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#174]
Found using: b0c8fc2
Device: Samsung Galaxy S9+ (Model: SM-G965U1) using NVidia Shield Controller (Model: P2920) and NVidia Shield Controller (Model: P2570)

Neither gamepad.leftTrigger nor gamepad.rightTrigger values are changing when pressing the buttons on the controller

**Comment by todi1856** [comment]
Works on my machine, waiting for follow up
