### ISSUE TITLE
Gamepad doesn't contain controls for left or right thumbs

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#178]
Most gamepads have input events (leftThumb/rightThumb) when you click on left or right sticks.

Seems like this wasn't added, probably an oversight. Adding issue so this won't be forgotten

**Comment by Rene-Damm** [comment]
There's `Gamepad.leftStickButton` and `Gamepad.rightStickButton`. Naming of button needs to be revisited and standardized (whether it should be `xxxPress` or `xxxButton') but the buttons are there.
