### ISSUE TITLE
When i try renaming the action composite 2d/4d on new editor.

### ISSUE THREAD

**Issue by GilbertoBitt** [Unity-Technologies/InputSystem#182]
**InvalidOperationException: TreeView: 'rootItem.children == null'. Did you forget to add children? If you intend to only create the list of rows (not the full tree) then you need to override: BuildRows, GetAncestors and GetDescendantsThatHaveChildren.**

**Comment by tomekpaszek** [comment]
Won't repro. Did you try it after latest changes?

**Comment by GilbertoBitt** [comment]
@tomekpaszek after recent updates it's fixed.
