### ISSUE TITLE
KeyNotFoundException: Could not find an action map called 'main' in asset 'CA

### ISSUE THREAD

**Issue by GilbertoBitt** [Unity-Technologies/InputSystem#183]
Here is the files and here is the code i'm using to test it. this occur with any of the composites.

```
public class CharacterController : MonoBehaviour
	{
		public Vector2 PlayerInputValue;
		public CA CActions;

		private void OnEnable(){
			
			CActions.main.walking.performed += ctx => { PlayerInputValue = ctx.ReadValue<Vector2>(); };
			CActions.main.walking.Enable();
		}

		private void OnDisable()
		{
			CActions.main.walking.Disable();
		}
		
	}

```
Here is the InputActions File. 
[InputActions.zip](https://github.com/Unity-Technologies/InputSystem/files/2216638/InputActions.zip)

**Comment by Rene-Damm** [comment]
Hmm, not sure yet what's happening there. I've tried `CharacterController` with the asset from the zip and everything seems to be working fine.

I'm wondering whether this is actually coming from the asset editor. It has some problems ATM with how it handles and saves its data and my guess is it's been making changes to the imported asset.

We'll keep digging.

**Comment by GilbertoBitt** [comment]
@Rene-Damm can be an error generate because I'm using ecs/incremental compiler?

**Comment by Rene-Damm** [comment]
I think that's probably unlikely.

If you right-click the asset and select "re-import" and then close and re-open the project and don't open the asset editor and go straight into play mode, do you still get the error?

**Comment by GilbertoBitt** [comment]
@Rene-Damm i try and it work the error doesn't appear but the i still unable to receive any value when pressing the buttons of keyboard.

**Comment by GilbertoBitt** [comment]
I Changed the script to AxisComposite and i i'm receiving this errors. now

![image](https://user-images.githubusercontent.com/1363635/43227859-5a95c292-9036-11e8-8dfc-5d9adf5e0a6c.png)

![2018-07-25_18-10-55](https://user-images.githubusercontent.com/1363635/43227785-16ddbab4-9036-11e8-94e2-b24a311a2cc3.png)

```
public class CharacterController : MonoBehaviour
	{
		public CA CActions;
		public float VerticalWalkingAxis;
		

		private void OnEnable(){
			CActions.main.VerticalWalking.performed += ctx => { VerticalWalkingAxis = ctx.ReadValue<float>(); };
			CActions.main.VerticalWalking.Enable();
		}

		private void OnDisable()
		{
			CActions.main.VerticalWalking.Disable();
		}
		
	}
```

**Comment by GilbertoBitt** [comment]
I removed the enable from the OnEnable to the Awake and then it started to work again without errors.
