### ISSUE TITLE
Please fix the warnings of the InputSystem

### ISSUE THREAD

**Issue by watsonsong** [Unity-Technologies/InputSystem#184]
When I import this project, there still a lot of warning report:

> Packages/com.unity.inputsystem/InputSystem/Editor/InputActionAsset/ActionInspectorWindow.cs(59,24): warning CS0618: `UnityEditor.EditorWindow.title' is obsolete: `Use titleContent instead (it supports setting a title icon as well).'

> Packages/com.unity.inputsystem/InputSystem/Editor/InputActionAsset/PropertyLists.cs(29,62): warning CS0252: Possible unintended reference comparison. Consider casting the left side expression to type `string' to get value comparison

> Packages/com.unity.inputsystem/InputSystem/Editor/InputActionAsset/PropertyLists.cs(56,62): warning CS0252: Possible unintended reference comparison. Consider casting the left side expression to type `string' to get value comparison

> Packages/com.unity.inputsystem/InputSystem/Editor/InputControlPicker.cs(97,22): warning CS0414: The private field `UnityEngine.Experimental.Input.Editor.InputControlPicker.m_FirstRenderCompleted' is assigned but its value is never used

> Packages/com.unity.inputsystem/InputSystem/State/InputStateHistory.cs(55,21): warning CS0414: The private field `UnityEngine.Experimental.Input.InputStateHistory.m_Head' is assigned but its value is never used

> Packages/com.unity.inputsystem/InputSystem/State/InputStateHistory.cs(56,21): warning CS0414: The private field `UnityEngine.Experimental.Input.InputStateHistory.m_Tail' is assigned but its value is never used

> Packages/com.unity.inputsystem/Tests/InputSystem/CoreTests_Editor.cs(271,13): warning CS0219: The variable `flags' is assigned but its value is never used

**Comment by Rene-Damm** [comment]
Yup, there's been the occasional pass to purge them but ATM we have no automation in place yet to make sure they're permanently kept out. But it'll happen.

**Comment by douglas-piconi** [comment]
Fixed and tests added to check for warnings.
