### ISSUE TITLE
Using gamepad/dpad breaks Dualshock 4 support

### ISSUE THREAD

**Issue by EmiMidnight** [Unity-Technologies/InputSystem#185]
As stated in the title, if i bind the Dpad from the generic gamepad template to an action, it renders the Dualshock 4 unusable and spams the console with the following error:

`NotImplementedException: state change detection on multi-bit fields
UnityEngine.Experimental.Input.InputManager.ProcessStateChangeMonitors (System.Int32 deviceIndex, System.IntPtr newState, System.IntPtr oldState, System.UInt32 newStateSize, System.UInt32 newStateOffset) (at Packages/com.unity.inputsystem/InputSystem/InputManager.cs:2136)`

It doesn't matter whether it's the whole dpad or a single direction. 

This issue does not occur on the Xbox One controller.
I'm using Win10 Pro with all updates, Unity 2018.2 updated yesterday.

**Comment by Rene-Damm** [comment]
Ah indeed, unlike the Xbox controller, the DualShock uses an enum instead of a bitfield representation. I'll add support for this in the state change detection code.

**Comment by Rene-Damm** [comment]
Should be fixed as of https://github.com/Unity-Technologies/InputSystem/commit/6642e44359488c4a76a776fd805de8da7d3e730a.
