### ISSUE TITLE
[Actions] InputActionMap property on component results in broken inspector

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#189]
https://forum.unity.com/threads/inspector-issue-inputactionmap-elements-repeat-redundant-bindings-array.542767/

Not a supported workflow ATM. We either should support it (could be useful) or make it clearly unsupported (no broken inspector).

**Comment by tomekpaszek** [comment]
Input action map inspector is now supported

**Comment by Albarnie** [comment]
It currently doesn't work in 2019.3.0f3. the dropdown is blocked and so you can't edit bindings on an inputAction.
![image](https://user-images.githubusercontent.com/31121467/71300739-c6ee1580-23eb-11ea-9370-bb59e079555b.png)
EDIT:
It does work, but only if you click directly on the text and not the dropdown, and only works when the action is not selected in the inspector.
