### ISSUE TITLE
Mouse Pointer Offset

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#19]
On my 3440x1440 screen, putting the mouse in the upper right corner of the screen reports a position of (-7.0, -7.0) in the Input Debugger Pointer. This also occurs on my 2560x1440 screen.  Will report what happens after reboot...

**Comment by jackpr-unity** [comment]
Still occurs after reboot.

**Comment by jackpr-unity** [comment]
@Rene-Damm does this belong here, or attached to the PR?

**Comment by jackpr-unity** [comment]
After further inspection, it appears that Pointer position as reported by the Input Debugger is relative to Pointer window.  Is this intended?

**Comment by jackpr-unity** [comment]
I'm convinved this is fine and working as intended. Closing issue.

**Comment by Rene-Damm** [comment]
Yup, Mouse.current.position is meant to correspond to Input.mousePosition in player code. In OnGUI() code it's meant to be relative to the current EditorWindow, though.
