### ISSUE TITLE
HID generated control layouts are not overridable

### ISSUE THREAD

**Issue by james7132** [Unity-Technologies/InputSystem#193]
Due to how MatchPercentage and HID generated control layouts are created, it is currently impossible to create an override. The HID generated control layouts always has a 100% match, and is seemingly loaded before any overrides are. This causes `TryFindMatchingLayout` to always choose the HID generated layout over the override.

I do see that in `InputManager.TryFindMatchingControlLayout`, there is a TODO to support this use case. Is this planned to be implemented in the near future?

A quick and dirty workaround would be to change the `>` in `TryFindMatchingLayout` to `>=`, to take the last listed layout instead of the first, though that might not be preferable for other reasons. EDIT: This does not work.

**Comment by Rene-Damm** [comment]
Yeah, there's multiple issues around this ATM. Basically, the only clean way to do this ATM is to `RegisterControlLayout()` your layout, let Unity recompile, and then restart Unity. After the restart, auto-generation of a HID layout should no longer occur for your device.

This should be fixed such that if you add a `RegisterControlLayout()` call in your code and it matches any device that is currently matched by an auto-generated HID layout, it should switch to your layout. I'm thinking of automatically boosting the match score of every layout that isn't generated by a layout builder by 1. So even if your layout only produces a 0.75 match as such, it'd automatically be boosted to 1.75 by virtue of not being auto-generated and would thus supersede the 1.0 matching score of the generated HID layout.

**Comment by Rene-Damm** [comment]
Could you give the latest head of the develop branch a go?

What should happen now is that

1. Whenever you call `RegisterControlLayout()` with a layout that has a device matcher, the system will re-recreate any existing device that is better matched by your layout than an existing layout.
2. All layouts registered with `RegisterControlLayout()` receive a matching boost over all layouts registered with `RegisterControlLayoutBuilder()`. This will make manually created layouts always out-score auto-generated layouts.

**Comment by james7132** [comment]
Looks like it worked! It sticks to the layout loaded. Now to figure out how to properly debug the controller mapping, it doesn't seem to update as regularly as the HID setup did, but that's a separate issue.

Closing the issue as this seems to be largely resolved for now.

**Comment by Rene-Damm** [comment]
>Now to figure out how to properly debug the controller mapping, it doesn't seem to update as regularly as the HID setup did, but that's a separate issue.

Another user reported strange update problems with a HID so could be a bug here.

One thing that can help figure out control mappings and state change problems is the event trace in the device debugger window. You can double-click state ('STAT') events which will open a separate window showing the data in the event. That view you can toggle between a raw memory dump and the control tree showing how what values controls read out of the memory. The event sequence and the raw memory views are often quite useful in figuring out what the HID is sending us and how to interpret it.
