### ISSUE TITLE
[XR] Joystick Y values do not adhere to InputSystem convention

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#195]
Our Input Requirements Matrix specifies:
"Gamepad.leftStick.y` is bottom to top [-1..1] with centerpoint at 0"
and is consistent on this point throughout. Our current XR implementations are inverted from this standard.

**Comment by jackpr-unity** [comment]
Migrating issue from a fork to this repository.

Former issue, now closed: https://github.com/StayTalm/InputSystem/issues/10

**Comment by jackpr-unity** [comment]
Verified as still existing using Unity 2018.2.1f1 and InputSystem commit e1bc70c2283aaf17d767053628adfea78b3e4902

**Comment by jackpr-unity** [comment]
Present on:
- OpenVR with Oculus Rift
- OpenVR with Vive Wand

**Comment by Dianna3D** [comment]
Confirmed present on Oculus Rift with Oculus SDK

**Comment by jackpritz** [comment]
19.1+ Fixed with PR https://ono.unity3d.com/unity/unity/pull-request/76756/_/xr/input/2d-axis-flip-y

The InputSystem currently targets a minimum of 18.3, so this issue must remain open.

**Comment by jackpr-unity** [comment]
InputSystem movement to 19.1+ is imminent. Closing this now.
