### ISSUE TITLE
[XR] The Oculus Touch Controller template has inconsistent capitalization of controls.

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#196]
All controls for the Oculus Touch controller are lower case except for:
- primaryTouched 
- secondaryTouched
- indexTouched
- thumbNearTouched
- thumbrestTouched
which are pascal case.

**Comment by jackpr-unity** [comment]
Issue verified with Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c2283aaf17d767053628adfea78b3e4902

**Comment by jackpritz** [comment]
Observed fixed looking at commit 5d0704c82a8f50459536f736c965b48e35a4c636
