### ISSUE TITLE
[XR] OpenVR + Vive controller velocity is wrong

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#199]
Values ARE NOT correct in 2018.2
Values ARE correct in 2018.3

Requires backport of https://fogbugz.unity3d.com/f/cases/1028211/

**Comment by jackpr-unity** [comment]
Issue verified with Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c2283aaf17d767053628adfea78b3e4902

**Comment by StayTalm** [comment]
Closing this, it works in 2018.3, and we are setting our support target for 2018.3
