### ISSUE TITLE
Rift devices doubling each restart

### ISSUE THREAD

**Issue by joelpryde** [Unity-Technologies/InputSystem#20]
Running with the Rift on Win8 using XRUtilsForInputSystem fork and xr/sdk/input-subsystem so YMMV.

Repro Steps:
1. Start app with Rift connected and Oculus enabled in VR Settings.
2. Open up XRFT debugger.
3. Play.  Stop.  Repeat.

Result:
Every time an entire new set of existing devices are added.  First run you get 2, then 4 on second run, then 8 and so on.

**Comment by StayTalm** [comment]
This can be closed down, this ended up being a screw up with the XR Backend not disconnecting devices properly.
