### ISSUE TITLE
[XR][Haptics] OpenVR + Vive controller does not rumble

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#200]
Migrating https://github.com/StayTalm/InputSystem/issues/4 to here.  Last communication from Tom on that issue is:

"The now cast properly as having rumble, but they won't yet rumble until some minor native changes make it to trunk, so I'll keep this open until then."

**Comment by jackpr-unity** [comment]
Issue verified with Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c2283aaf17d767053628adfea78b3e4902

**Comment by borishsu** [comment]
Duplicate of #128

**Comment by borishsu** [comment]
Duplicate of #128

**Comment by jackpr-unity** [comment]
Yep, this is a duplicate. Closing.
