### ISSUE TITLE
[XR] OpenVR Knuckles controllers are not supported

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#201]
This requires a template fix for the EV2 model and possibly native changes.

**Comment by jackpr-unity** [comment]
Knuckles EV2 are out. They require work at the very start of our input pipe to get working.

**Comment by KospY** [comment]
Just received the Knuckles EV3, and unfortunately they are not fully supported.
Below the inputs working and not working. Hope that will help!
![image](https://user-images.githubusercontent.com/2311302/48904882-292ebc80-ee60-11e8-987e-7337a63b2409.png)

**Comment by jackpr-unity** [comment]
Fixed in #378. Support was removed until we integrate SteamVR 2.0
