### ISSUE TITLE
[XR] Vive Tracker trigger does not update in the InputDebugger

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#203]
The tracker reports as an OpenVRController, but the trigger does not update when used in conjunction with the HyperBlaster peripheral we have in the office.

**Comment by jackpr-unity** [comment]
The Vive Tracker identifies as an OpenVRController, but OpenVRController does not appear as an option when trying to bind an input action in the UI
![untitled](https://user-images.githubusercontent.com/36174025/43598635-0a5de462-963a-11e8-8ede-9fa5e4e8fe3e.png)

**Comment by jackpritz** [comment]
From #378, which was merged before all issues were resolved:

* The Vive tracker pro has "VIVETrackerPRO" in its name, but the non-pro version's name just seems to be a serial number. Can this be fixed?
