### ISSUE TITLE
[XR] Oculus Rift remote support is not complete

### ISSUE THREAD

**Issue by Dianna3D** [Unity-Technologies/InputSystem#205]
Issue confirmed from StayTalm Branch: https://github.com/StayTalm/InputSystem/issues/29
Unity Editor 2018.2.1f1  InputSystem Commit e1bc70c2283aaf17d767053628adfea78b3e4902 

It does a decent job of mapping. However it maps the "select" button in the center to "start." Should this map to "PrimaryButton" instead?

In a component's public InputAction bindings UI, there is no option for the Oculus Remote

**Comment by jackpr-unity** [comment]
Would someone please add the tag [XR] to the title?

**Comment by Dianna3D** [comment]
Updated

**Comment by jackpr-unity** [comment]
Fixed in #378

**Comment by jackpr-unity** [comment]
@Rene-Damm as an admin, can you close this issue?

**Comment by jackpr-unity** [comment]
@Dianna3D can you close?
