### ISSUE TITLE
[XR] Oculus SDK + Oculus Rift primary and secondary button touch states are inconsistent

### ISSUE THREAD

**Issue by Dianna3D** [Unity-Technologies/InputSystem#206]
Issue confirmed from StayTalm branch : https://github.com/StayTalm/InputSystem/issues/31

 Unity Editor 2018.2.1f1 InputSystem Commit e1bc70c2283aaf17d767053628adfea78b3e4902

Touching Primary and Secondary buttons on Oculus remotes do not register touch in HUD but register in debugger.

Touch yellow appears to flicker at random times in HUD but is not consistent with touching the buttons

**Comment by jackpr-unity** [comment]
Would someone please add the tag [XR] to the title?

**Comment by Dianna3D** [comment]
Updated

**Comment by jackpr-unity** [comment]
Still exists in 2018.3.0b2 and package version 0.0.7-preview

InputDebugger:
xtouched and ytouched, the inputs which shouldn't exist, are driven correctly. PrimaryTouched and SecondaryTouched are not driven

InputActions:
InputActions bound to primaryTouched and secondaryTouched do not fire.

**Comment by jackpr-unity** [comment]
Still exists in 2019.1.0a11 with package version 0.0.11-preview.

As of this moment 0.0.12-preview and 0.0.13-preview are available, but the editor crashes if I try to update to them.

**Comment by jackpr-unity** [comment]
Fixed in #378

**Comment by jackpr-unity** [comment]
Fixed in #378

**Comment by jackpr-unity** [comment]
@Dianna3D can you close?
