### ISSUE TITLE
[XR] The Vive Pro doesn't have any InputActions

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#207]
Possible solutions:
- Have the Vive Pro trigger ViveHMD InputActions (which may or may not scale pending exposure of camera features?)
- Add the Vive Pro as a device in a component's public InputAction bindings list
![untitled](https://user-images.githubusercontent.com/36174025/43614646-1dc90818-9669-11e8-91b2-2a642b619423.png)

**Comment by jackpr-unity** [comment]
Migrated https://github.com/StayTalm/InputSystem/issues/33 to here

**Comment by jackpr-unity** [comment]
Issue verified with Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c

**Comment by jackpr-unity** [comment]
No no, this one stays open.  My mistake.

**Comment by jackpr-unity** [comment]
Still present on 18.3.0b2 and InputSystem package 0.0.7-preview

**Comment by jackpritz** [comment]
From #378, which was merged before all issues were resolved:

The actions not fire when the Vive Pro is being used, but not when the Vive is being used. My Vive's name is "Vive. MV"

**Comment by jackpr-unity** [comment]
Verified fixed with editor 2019.1.0b78 and 0.2.1-preview
