### ISSUE TITLE
[Standalone] Mouse positition is tied to only Display 1, does not work properly on multi-monitor devices

### ISSUE THREAD

**Issue by james7132** [Unity-Technologies/InputSystem#208]
When a build is started on a display other than Display 1, it uses the position of the mouse on Display 1 instead of the display the game is displayed on.

Used in Windowed mode, have not tried full-screen.

Tested: Unity 2018.2.0f2, Commit: c123c11c46e46d8c6d1cf1776ce0fdeec7d40a98, Windows Standalone

**Comment by JiaUnity** [comment]
This should have been fixed in the past updates. I don't see it on 2019.1 with 0.2.0-preview. 
Closing.
