### ISSUE TITLE
[iOS] Event time offset to Time.realtimeSinceStartup is very high

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#209]
Found using: 40613f9
Unity version: 2018.3.0a8_021de34a6a02

Devices:
Samsung Galaxy S9
Apple iPhone 8+

Android (expected _-ish_ behaviour)
(I suppose it's expected that it's not **exactly** the same as Time.realtimeSinceStartup?):
<img width="592" alt="screen shot 2018-08-06 at 18 06 15" src="https://user-images.githubusercontent.com/39190411/43759332-99cfe6c2-9a27-11e8-8e97-065fb3a2b13c.png">

iOS (actual behaviour):
<img width="648" alt="screen shot 2018-08-06 at 18 13 15" src="https://user-images.githubusercontent.com/39190411/43759347-a3cf4802-9a27-11e8-8740-cd707a7b3c3c.png">

**Comment by todi1856** [comment]
Looking into it

**Comment by todi1856** [comment]
@renaldasrep should be fixed in 2018.3.0a7

**Comment by Rene-Damm** [comment]
Tomas's changes together with latest develop branch should result in 0 offset now.

**Comment by renaldasrep** [comment]
Verified as fixed
