### ISSUE TITLE
Pulling this project and naming its containing folder "InputSystem" results in a Visual Studio error.

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#21]
![capture](https://user-images.githubusercontent.com/36174025/36056202-3e33c27c-0db7-11e8-9441-eedc2a45cec6.PNG)

This is because Visual Studio creates a project named after the containing folder.  I recommend naming the dlls generated from this project something a little more obscure, but still recognizable.  For example: Unity_InputSystem, UnityProvided_InputSystem, or UnityInternal_InputSystem

**Comment by Rene-Damm** [comment]
This will be fixed as part of conforming to Unity package guidelines. These mandate naming of assemblies, .asmdef files, and folders (IIRC) which should fix this.

**Comment by Rene-Damm** [comment]
Should be fixed.
