### ISSUE TITLE
[XR] GearVR/Go Integration is not complete

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#211]
as of Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c

Remote

- The Remote touchpad is called "joystick," though it is a touchpad
- The Remote has a combinedTrigger. Is this valid? The combined Trigger does not work properly for left hand. It should produce a negative value when the controller is set to left hand, but the value is observed to remain positive.
- Oculus Go does not have its own entry in the InputAction binding devices list. Should it?

**Comment by jackpr-unity** [comment]
Migration of Oculus Go issues from https://github.com/StayTalm/InputSystem/issues/19

**Comment by jackpr-unity** [comment]
Still present as of 2018.3.0b2 and package version 0.0.7-preview

**Comment by jackpritz** [comment]
From #378, which was merged before all issues were resolved:

* The Oculus Go still doesn't have an entry in the InputActions table.  Should it?  We know that it's equivalent to GearVR, but how are users supposed to know?

**Comment by jackpr-unity** [comment]
Oculus Go hmd now has an entry, but Oculus Go controller does not

**Comment by jackpr-unity** [comment]
Moved to https://fogbugz.unity3d.com/f/cases/1139056/
