### ISSUE TITLE
[XR][WMR] Running WMR in editor results in error spam and no input

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#214]
Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c

Console hits an error every frame
XRInputDeviceState: Failed to set the value at featureIndex [4].

**Comment by jackpr-unity** [comment]
Nevermind, I was set to Android.

**Comment by StayTalm** [comment]
This is actually a known issue though, it definitely occurs.

I have a PR to fix this in native.

**Comment by jackpr-unity** [comment]
Verified - error occurs with WMR via OpenVR.

Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit e1bc70c

**Comment by jackpr-unity** [comment]
This error no longer occurs with 0.0.7-preview and editor 2018.3.0b2
