### ISSUE TITLE
[XR] InputDebugger window not updating consistently to reflect movement and interaction

### ISSUE THREAD

**Issue by Dianna3D** [Unity-Technologies/InputSystem#217]
InputDebugger window does not reflect the movement and interaction with GearVR HMD, controller or Daydream HMD.

Unity Editor 2018.2.1f1 and Unity-Technologies/InputSystem commit 420c36161d35b8d441427c9bb81e55a039304606 

InputDebugger shows occasional inconsistent frames of HMDs and Controllers positions/updates, but does not update real time. (Daydream controller is noted not to be supported in this version of 2018.2 and is supported in 2018.3)

With Android Studio on, it does read the movement and interactions, but does not translate into the debugging window.

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/xr-inputdebugger-does-not-update-consistently-to-reflect-movement-or-interaction
