### ISSUE TITLE
The InputAction binding add button hitbox is incorrectly sized

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#227]
When trying to add an InputAction binding in the inspector, the hitbox for the (+) button is very small and offset on the button.  The attached screen capture shows the portion of the button that is clickable in red.

![hitbox](https://user-images.githubusercontent.com/36174025/44483980-5bcade00-a601-11e8-9168-2aa441aef300.PNG)

**Comment by jackpr-unity** [comment]
These issues were observed with InputSystem package version 0.0.6-preview and Unity Editor Trunk build dfb7f9251d9f (tagged 2018.3.0a10)

**Comment by borishsu** [comment]
A temporary workaround is to hit the button with mouse right click. It works for me.

**Comment by tomekpaszek** [comment]
No applicable in the latest version
