### ISSUE TITLE
Custom InputAction bindings added in the inspector don't stick.

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#228]
When I try to add custom binding to an InputAction in the inspector, it does not stick.  It looks like it adds correctly, but if I click away from the GameObject and then back again the custom binding has cleared.  Selecting a binding from the explicit list is not affected by this.

@StayTalm verified that this binding should be valid
<XRController>{LeftHand}/{DevicePosition}

Here is a gif of it not sticking.

![bindingsdontstick](https://user-images.githubusercontent.com/36174025/44484370-794c7780-a602-11e8-8308-b218b7cf1d4d.gif)

**Comment by jackpr-unity** [comment]
These issues were observed with InputSystem package version 0.0.6-preview and Unity Editor Trunk build dfb7f9251d9f (tagged 2018.3.0a10)

**Comment by tomekpaszek** [comment]
Fixed in f9b87af
