### ISSUE TITLE
Keyboard.onTextInput does not report delete

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#23]
Keyboard.onTextInput does not report the delete key.  It does report the backspace key, so it should also report the delete key.

**Comment by Rene-Damm** [comment]
Which OS? Windows?

**Comment by Rene-Damm** [comment]
Hmm, thinking about this more, I'm not so sure. Report how? I assume you mean that it reports a Unicode backspace character for the backspace key and should report a Unicode delete character for the delete key?

I wonder whether representing editing operations as characters is a good idea. Both the backspace and the delete key depend on the current cursor position. It seems to me that editing keys (arrows, return, backspace, delete, home, end, etc) should be separate from the text input string.

**Comment by jackpr-unity** [comment]
What is the purpose of onTextInput?  My interpretation of it is "this reports printable characters."  As a user, if I am interested in getting printable characters, I am probably also interested in getting both backspace and delete (maybe I am doing my own special textbox or something like that).

**Comment by Rene-Damm** [comment]
Yup, that interpretation is correct. But backspace and delete are not printable characters :)

For doing your own text boxes, it would need to listen for editing keys like return etc. separately and perform the corresponding text edit operation.

**Comment by jackpr-unity** [comment]
https://docs.unity3d.com/ScriptReference/Input-inputString.html

^ This function from the legacy input system seems to closely resemble onTextInput.  It only reports printable characters, backspace, and newline (although the example also seems to handle carriage return...why?).  Matching this function is good enough for me, through we could take this opportunity to expand functionality.
