### ISSUE TITLE
Helpers for Gyro functionality

### ISSUE THREAD

**Issue by Chippit** [Unity-Technologies/InputSystem#236]
Gyro functionality often requires the same sorts of calibration across devices in all games that use it, to set sensitivities and comfortable neutral positions.

It might make sense that the input system provides some set of helpers or general APIs that can allow a user to specify a new neutral position (from which all future gyro readings are relative to) and some functionality for rescaling or remapping the input, so that the system can provide normalized orientation values against some user-defined thresholds. Some deadzoning and such would also be useful.

For example, a user might define a casual holding position as the zero point, and a pitch threshold of 30 degrees, and if I user pitches the device, say, 15 degrees forward from that neutral position, you might receive a normalized vector with a pitch value of 0.5, rather than what might be an absolute pitch of -5 degrees.

**Comment by Rene-Damm** [comment]
I've gone ahead and migrated this to our internal tracking system to make sure it gets taken into consideration when looking for more feature work after 1.0 is in safe waters. (internal ticket ISX-272)

As part of us migrating away from GitHub issues, I'll go close this one. But no worries, doesn't mean it's forgotten :)
