### ISSUE TITLE
Defining an input device using XRSDK managed providers, Input Debugger information doesn't update

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#238]
I have a custom device defined through XRSDK in the attached project. This project uses InputSystem 0.0.6-preview

How to reproduce:
- Open the attached project in 18.3.0a9
- Open the single scene in the project
- Open the input debugger
- press play
- In the input debugger, expand "MyInputDrivenDevice"

Expected:
The position and rotation values should update in the input debugger

Observed:
Events come in reporting control value changes, but the displayed state value does not change.

**Comment by JiaUnity** [comment]
@jackpr-unity If this still repro, please file it to FogBugz, thanks!
