### ISSUE TITLE
[XR] Redefining an input device that uses XRSDK managed providers requires an editor reboot

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#239]
Steps to reproduce:
- Open the attached project in 18.3.0a9
- Open the single scene in the project
- Open the input debugger
- press play
- In the input debugger, expand and observe the definition of "MyInputDrivenDevice"
- exit playmode
- Open Packages/MyInputProvider/Runtime/MyInputProvider.cs
- Change the device role or add/remove a control feature
- press play again
- In the input debugger, expand and observe the definition of "MyInputDrivenDevice"

Expected:
The input debugger shows the new device definition

Observed:
The input debugger shows the initial device definition until the editor is rebooted. This slows down iteration time, and Tom says he has been meaning to remove the way the system currently caches XR device definitions.

**Comment by jackpr-unity** [comment]
https://github.cds.internal.unity3d.com/jackpr/xr.mockinputprovider

**Comment by Rene-Damm** [comment]
@StayTalm Is the issue specific to the XR side or is this a core issue with the layout stuff?

**Comment by StayTalm** [comment]
This is XR only, and is fixed in https://github.com/Unity-Technologies/InputSystem/pull/378

**Comment by jackpr-unity** [comment]
Is it fixed in #378? It's not on the list of bugs that PR fixed.

**Comment by JiaUnity** [comment]
@jackpr-unity if this still repro, please file it into the FogBugz. Thanks!
