### ISSUE TITLE
[HID] Weird behaviour and no more deadzones on DualshockGamepadHID since commit f5cceae

### ISSUE THREAD

**Issue by bet0v** [Unity-Technologies/InputSystem#241]
The fusion of the two branches in commit **f5cceaeb7450e90415d51b470ab6311db09fc26d [f5cceae]**
causes the DualShockGamepadHID to no longer have deadzones and default stick values.
The problem then persists for every other recent update

**Comment by JiaUnity** [comment]
Dualshock controller should work on Windows and OSX, unless connected via bluetooth, then it has all kinds of issues. 
Deadzone is not implemented for the time being, so it is by design if it doesn't work.
Closing.
