### ISSUE TITLE
Inconsistent event data

### ISSUE THREAD

**Issue by jonasmora** [Unity-Technologies/InputSystem#242]
I'm receiving multiple PointePhase.Began, the second one with a doubtful internal time.

Could you confirm you are having the same issue?

I'm using Unity 2018.2.5f1, running on Android.
InputSystem commit ea1cd24b6bdb119eb25cf55bc482ab1df046b08c.

Code after this line:
https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/InputSystem/InputManager.cs#L1960
```cs
var diff = InputRuntime.s_Instance.currentTime - currentEventTimeInternal;
if (!Application.isEditor) Debug.Log("[InputManager.OnUpdate] currentTime: " + InputRuntime.s_Instance.currentTime + ", currentEventTimeInternal: " + currentEventTimeInternal + ", diff: " + diff + ", currentEventType: " + currentEventType);
```

Code after this line:
https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/InputSystem/InputManager.cs#L2323
```cs
var diff = InputRuntime.s_Instance.currentTime - internalTime;
Debug.Log("[InputManager.FireStateChangeNotifications] currentTime: " + InputRuntime.s_Instance.currentTime + ", internalTime: " + internalTime + ", diff: " + diff + ", time: " + time + ", InputRuntime.s_CurrentTimeOffsetToRealtimeSinceStartup: " + InputRuntime.s_CurrentTimeOffsetToRealtimeSinceStartup);
```

Handler code:
```cs
inputActionMap = new InputActionMap("gameplay");
inputActionMap.AddAction("touchPhase", "/<touchscreen>/phase").performed += ctx => {
    var phase = (ctx.control as PointerPhaseControl).ReadValue();
    Debug.Log("[touchPhase] phase: " + phase);
};
```

Output:
> [InputManager.OnUpdate] currentTime: 105.550129647017, currentEventTimeInternal: 105.545781731002, diff: 0.00377234294823836, currentEventType: STAT

> [InputManager.FireStateChangeNotifications] currentTime: 105.55160568899, internalTime: 105.545781731002, diff: 0.00582057193200569, time: 103.38249017005, InputRuntime.s_CurrentTimeOffsetToRealtimeSinceStartup: 2.16329156095162
[touchPhase] phase: Began

> [InputManager.FireStateChangeNotifications] currentTime: 105.571139854961, internalTime: 103.407801888068, diff: 2.16333234193735, time: 101.244510327117, InputRuntime.s_CurrentTimeOffsetToRealtimeSinceStartup: 2.16329156095162
> [touchPhase] phase: Began

**Comment by jonasmora** [comment]
Here's a more extreme case. This happened running on iOS. This is not a case of duplicated PointerPhase.Began but of a great difference in the context time.

These are two consecutive prints from the event handler.

> [touchPhase] ctx.time: 30.6926669990644, InputRuntime.s_Instance.currentTime: 32.4096879996359, InputRuntime.s_CurrentTimeOffsetToRealtimeSinceStartup: 0.858501000329852, Time.realtimeSinceStartup: 31.55119

> [touchPhase] ctx.time: 829257.503760375, InputRuntime.s_Instance.currentTime: 32.4100770000368, InputRuntime.s_CurrentTimeOffsetToRealtimeSinceStartup: 0.858501000329852, Time.realtimeSinceStartup: 31.55158

**Comment by jonasmora** [comment]
I think the ctx.time on iOS is not working at all, could you confirm?

**Comment by todi1856** [comment]
There was a bug in native implementation where time for input events on iOS was taken as it is without making it relative to Unity application start.

Sadly it's only fixed in 2018.3, not sure if that's what you're seeing

**Comment by jonasmora** [comment]
Where can I find that Unity version?

**Comment by todi1856** [comment]
The 2018.3 alpha version is only available for alpha group users.  But as far as I know, it should hit beta any day now.

**Comment by Rene-Damm** [comment]
@todi1856 Can we backport the fix to 2018.2?

**Comment by todi1856** [comment]
The fix was backported to 2018.2.11f1

**Comment by jonasmora** [comment]
I'll check it out

**Comment by Rene-Damm** [comment]
Sounds like this was fixed and the native changes have made their way back.
