### ISSUE TITLE
Devices created very late in initialization

### ISSUE THREAD

**Issue by StayTalm** [Unity-Technologies/InputSystem#245]
After the domain reload refactor, devices are not initialized and added until the first update loop.

This means that any initialization code in Monobehaviours (Awake, Start, OnEnable) cannot  get access to any devices like the keyboard or mouse until after the first update has passed, which makes for very awkward initialization.

**Comment by mdsitton** [comment]
I'm seeing this issue on Mac in the editor but not on Windows.

**Comment by douglas-piconi** [comment]
Fixed in develop, will make it to 0.0.15-preivew
