### ISSUE TITLE
Massive performance loss when moving the mouse around

### ISSUE THREAD

**Issue by mwojtyna** [Unity-Technologies/InputSystem#258]
I have no code that references the new input system and I'm getting a significant performance loss when moving the cursor around.
Unity version: 2018.3.0b2

[profileData.zip](https://github.com/Unity-Technologies/InputSystem/files/2408807/profileData.zip)
![profilerimage](https://user-images.githubusercontent.com/31010630/45929320-39a1e400-bf50-11e8-9d0d-cd0a797117ee.PNG)

**Comment by Rene-Damm** [comment]
There's a couple features here and there to finish up but plan is to go into feature freeze by around end of October. Proper performance pass is high in priority after that. Processing loop ATM is definitely gobbling up more than its allotted share. The core of its operations is cheap but the stuff around it has accumulated way more overhead than it should have.

**Comment by Rene-Damm** [comment]
The stuff above has been addressed, though we still have some performance tweaking to do there.

However, there's a larger issue that still needs to be addressed. With mice sampling at high frequencies, we end up with huge event loads as resolutions increase. For example, at 4k and the mouse sampling at 120Hz, each frame will see a huge number of mouse movement events with tiny deltas.

Whatever solution for this we settle on will probably have to go all the way down to the platform backend. Collapsing events could be one way though I'm a little concerned about the data loss implied in that. If we go for this, the collapsing threshold should be accessible to the user.

Another option would be to design a bulk event format that can send a large number of state changes for the same device packed into a single event. Also has downsides, though.

Not sure yet which way is best to go.

**Comment by JiaUnity** [comment]
This issue doesn't happen for on 2019.1 with the latest Develop (d4c0de0)
As for other performance improvement is not specifically related to this bug. 
Closing.

**Comment by neitron** [comment]
But it definitely happens in 2019.3.10 and I use the latest version 1.0.0 (7)
