### ISSUE TITLE
Cannot interact with UI using a mouse or keyboard

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#26]
This is true in Windows Editor playmode and in Windows Standalone Player builds.

Tested UnityEngine.UI button, dropdown, slider, scrollbar, and inputfield.

This is a duplicate of Ono PR issue 31176.  Moving it here so all bugs are visible in one place, per our recent conversation.

**Comment by Rene-Damm** [comment]
The UI system is not yet supported. We will need an input module to be written against the new system. ATM the UI system only picks up input from the old system (which is disabled in the GitHub project here; to re-enable, switch the input backend to "Both" in player settings).

**Comment by jackpr-unity** [comment]
Ok, good to know about this workaround.  This will not block the Ono PR.

**Comment by jackpr-unity** [comment]
Still observed with 2018.3.5f1 and commit 5d0704c82a8f50459536f736c965b48e35a4c636

**Comment by JiaUnity** [comment]
this is done.
