### ISSUE TITLE
[Android][Pen] Input no longer detected neither using Pen nor Touch classes

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#264]
Found using d9b7c25

Device: Samsung Galaxy Note

Android stylus input no longer detected neither using Pen nor Touch classes
while iOS Apple Pen input is detected via Pen class

**Comment by todi1856** [comment]
@renaldasrep can't reproduce this with Version 2019.1.0a8 (4329b1257f5f) and latest develop https://github.com/Unity-Technologies/InputSystem/commit/d8f0920cba32fdf2d826395fa79c61c0d12bf9e1

**Comment by renaldasrep** [comment]
It's now under touch, verified
