### ISSUE TITLE
[iOS][Pen] Phase doesn't go past Began (Is either None or Began, never Stationary or Moved)

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#265]
Found using d9b7c25

Device: iPad Pro using Apple Pen

**Comment by renaldasrep** [comment]
Now it's always stuck on None 
Version 2019.2.0a7 (dddf9ae2be01)
Wed, 20 Feb 2019 14:24:01 GMT
Branch: trunk

Package github [b223957](https://github.com/Unity-Technologies/InputSystem/commit/b2239576178eaf44fc7c1e770f16ac0113aa6bce)

**Comment by todi1856** [comment]
@Rene-Damm Native PenInputState doesn't have phase variable, but in C# we have this code
in Pen.cs

        // "Park" unused controls.
        [InputControl(name = "radius", layout = "Vector2", usage = "Radius", offset = InputStateBlock.kInvalidOffset)]
        [InputControl(name = "pointerId", layout = "Digital", offset = InputStateBlock.kInvalidOffset)] // Will stay at 0.
        [InputControl(name = "phase", layout = "PointerPhase", offset = InputStateBlock.kInvalidOffset)] ////TODO: this should be used
        

Please advise

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/ios-pen-phase-doesnt-go-past-began
