### ISSUE TITLE
[iOS][Pen] Tilt is not normalized

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#267]
Found using d9b7c25

Device: iPad Pro using Apple Pen

Actual behaviour:
`Pen.twist` is always 0
`Pen.tilt.y` values is hanging when Pen is rotated, but the range is something like  [-3.1 ... 3.1] (might not exactly be that, but that's what I detected visually)

Expected behaviour:
`Pen.twist` (if supported) is 0 when the pen's rotation faces up and away from the user
`Pen.twist` (if supported) increases as the pen is rotated clockwise around itself
`Pen.twist` (if supported) is ~1 when the pen has been rotated one turn

**Comment by Rene-Damm** [comment]
`twist` doing nothing is to be expected. There's few pens that support this. Actually, the only one I'm aware of is the Wacom Art Pen.

`tilt` should be normalized so that's a thing.

**Comment by todi1856** [comment]
This is actually a duplicate of https://github.com/Unity-Technologies/InputSystem/issues/266.

P.S I don't think you can normalize tilt, if pen is fully perpendicular to the screen, where in that case tilt will be (0, 0). 

If tilt would be 3D vector, then it would be (0, 0, 1)

**Comment by JiaUnity** [comment]
This bug is marked as Won't Fix on FB side. Can close.

**Comment by renaldasrep** [comment]
Verified as fixed

Version 2019.2.0a6 (d24f6c6b0098)
Thu, 21 Feb 2019 15:09:23 GMT
Branch: input/new/ios

Github package  b223957
