### ISSUE TITLE
[iOS][Android][Keyboard] Keyboard.current.keyboardLayout is always empty

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#269]
Found using d9b7c25

Device: Google Pixel 2

Expected result:
On windows standalone it returns a number which represents a layout and the number changes when keyboard layout is changed

**Comment by todi1856** [comment]
I guess we could use https://stuff.mit.edu/afs/sipb/project/android/docs/reference/android/view/InputDevice.html#getKeyboardType(), but that will not say what language layout this is

**Comment by Rene-Damm** [comment]
What about https://stackoverflow.com/questions/16484007/how-to-get-current-keyboard-language?

**Comment by renaldasrep** [comment]
still an issue

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/ios-android-keyboard-keyboard-dot-current-dot-keyboardlayout-is-always-empty
