### ISSUE TITLE
[Android][Keyboard] KeyControl.isPressed gets stuck on True sometimes, resets when any key is pressed

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#270]
Found using d9b7c25

Device: Google Pixel 2 using a Keyboard connected through USB

Does not happen on iOS
However on iOS only one key can be isPressed = true, is that a bug?

**Comment by renaldasrep** [comment]
Still reproducible

Version 2019.2.0a7 (dddf9ae2be01)
Wed, 20 Feb 2019 14:24:01 GMT
Branch: trunk

Package github  b223957

**Comment by todi1856** [comment]
Can't reproduce, @renaldasrep can you try to take latest develop branch? It seems you took stable

**Comment by renaldasrep** [comment]
No longer reproducible 9d9a4e8
Version 2019.2.0a7 (dddf9ae2be01)
Wed, 20 Feb 2019 14:24:01 GMT
Branch: trunk
