### ISSUE TITLE
[Android][Keyboard] OS keyboard layout for physical keyboard does not affect KeyControl.displayName like it does on Mac standalone

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#272]
Found using d9b7c25

Device: Google Pixel 2 using a keyboard connected through USB

Expected result:
On Mac editor pressing digit1, digit2, digit3 when language is set to English displayNames are: 0, 1, 2
and when language is set to, for example, Lithuanian displayNames are: ą, č, ę

Actual result: displayNames are 0, 1, 2 using both English and Lithuanian layout on Android

(When pressing the same keys somewhere in OS (e.g. a browser) keystrokes result in correct values: 0, 1, 2 for English layout and ą, č, ę for Lithuanian

**Comment by todi1856** [comment]
Probably won't fix, alternatively maybe I can simply return this InputDevice getKeyboardType

**Comment by Rene-Damm** [comment]
Assigning to you @todi1856. Think we discussed this at some point but don't recall where we landed on.

**Comment by renaldasrep** [comment]
Still reproducible 9d9a4e8
Version 2019.2.0a7 (dddf9ae2be01)
Wed, 20 Feb 2019 14:24:01 GMT
Branch: trunk

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/android-keyboard-os-keyboard-layout-for-physical-keyboard-does-not-affect-keycontrol-dot-displayname
