### ISSUE TITLE
[iOS][Android][Sensors] Cannot set samplingFrequency, trying to set it breaks sensor on iOS

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#280]
Found using: d9b7c25

Expected result
```
InputSystem.EnableDevice(Accelerometer.current);
// Accelerometer.current.acceleration works fine
Accelerometer.current.samplingFrequency = 30.0f;
// Accelerometer.current.samplingFrequency returns 30.0f
// Accelerometer.current.acceleration works fine and samples in frequency that is set
```

Actual result:
**on iOS:**
```
InputSystem.EnableDevice(Accelerometer.current);
// Accelerometer.current.acceleration works fine
Accelerometer.current.samplingFrequency = 30.0f;
// Accelerometer.current.samplingFrequency returns 0
// Accelerometer.current.acceleration stops updating,  disabling/enabling doesn't help
```
The issue here is that samplingFrequency returns 0 instead of actual frequency and that it breaks the sensor

**on Android:**
```
InputSystem.EnableDevice(Accelerometer.current);
// Accelerometer.current.acceleration works fine
Accelerometer.current.samplingFrequency = 30.0f;
// Accelerometer.current.samplingFrequency returns 0
// Accelerometer.current.acceleration works fine (can't tell if sampling frequency actually changed though)
```
The issue here is that samplingFrequency returns 0 instead of actual frequency and **possibly** doesn't set frequency to the wanted value?

The same happens with all the other sensors

**Comment by renaldasrep** [comment]
Apparently happens only if old Input is also enabled

**Comment by Rene-Damm** [comment]
In that case, we may be able to punt on this one. Verdict is still out whether we will ship with the ability to run both systems in parallel. Now that we have UI support, we don't have a hard requirement anymore for this to work.

**Comment by todi1856** [comment]
@renaldasrep this was fixed here - https://ono.unity3d.com/unity/unity/pull-request/78822/_/input/new/android

**Comment by renaldasrep** [comment]
No longer reproducible 9d9a4e8
Version 2019.2.0a7 (dddf9ae2be01)
Wed, 20 Feb 2019 14:24:01 GMT
Branch: trunk
