### ISSUE TITLE
XR : Usage {Primary2DAxisClick} didn't work

### ISSUE THREAD

**Issue by KospY** [Unity-Technologies/InputSystem#285]
Usage {Primary2DAxisClick} referenced in https://docs.google.com/spreadsheets/d/1XqSzYRHGAbzW9uRi_8t2Xm_zfBEJHCS2Bp3dkAYsOQc/edit#gid=0 didn't work.
This has been tested on Oculus Rift and HTC Vive (don't know if it work on WMR).
Using Unity 2018.2.11.

**Comment by StayTalm** [comment]
There was a typo in that spreadsheet.  Both the Click and Touch usages should have been in hte past tense: e.g. {Primary2DAxisClicked} {Primary2DAxisTouched}.

Updated the spreadsheet, sorry.

**Comment by jackpr-unity** [comment]
{Primary2DAxisClick} and {Primary2DAxisTouch} are actually correct.

They are verified to function correctly with 2019.1.0b8 and package commit 717086861b14d71bca05636c5d6af72491820040
