### ISSUE TITLE
[Editor] InputSystem.devices.Count returns 0 on Start

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#295]
Hey,

so in the past there was similar issue, but only in players, but not in Editor - https://github.com/Unity-Technologies/InputSystem/issues/87 which was fixed ! :D

Now it's happening in Editor, but not in players.

[CODE]
public class Devices : MonoBehaviour
{
    private int deviceCount;
    // Start is called before the first frame update
    void Start()
    {
        deviceCount = UnityEngine.Experimental.Input.InputSystem.devices.Count;
    }

    void OnGUI()
    {
        GUILayout.Label("Device count on start: " + deviceCount);
        GUILayout.Label("Device count now: " + UnityEngine.Experimental.Input.InputSystem.devices.Count);
    }
}

[/CODE]
In Editor this will display:
Device count on start: 0
Device count now: 4

In Standalone:
Device count on start: 4
Device count now: 4

Again, because this is inconsistent between player and Editor, I think this is a bug.

Tested with Version 2019.1.0a8 (838432b9642d) & https://github.com/Unity-Technologies/InputSystem/commit/b0794e4c3c1a5c8379acf529c869e645c3cf94d4

**Comment by douglas-piconi** [comment]
Fix under code review.  Will most likely land in 0.0.14 preview.
