### ISSUE TITLE
Compilation error on initial import

### ISSUE THREAD

**Issue by MeikelLP** [Unity-Technologies/InputSystem#296]
Tested with:
* 2019.1.0a7
* 2018.2.14f1

`Packages\com.unity.inputsystem\InputSystem\Utilities\ArrayHelpers.cs(6,38): error CS0234: The type or namespace name 'Net35Compatibility' does not exist in the namespace 'UnityEngine.Experimental.Input' (are you missing an assembly reference?)`

Removing this `using` statement makes it compile. The using is useless in my opinion - why is it even there?

**Comment by garettbass** [comment]
Please surround this `using` statement as elsewhere in the code base:
```cs
#if !(NET_4_0 || NET_4_6 || NET_STANDARD_2_0 || UNITY_WSA)
using UnityEngine.Experimental.Input.Net35Compatibility;
#endif
```

**Comment by MeikelLP** [comment]
Yeah, that would work too.

I just want to not have to adjust this code^^

**Comment by garettbass** [comment]
I mean to suggest that is how the team should fix this issue :)

**Comment by Rene-Damm** [comment]
Fixed as of https://github.com/Unity-Technologies/InputSystem/commit/963382a5db61bc2bb0fc8ae28c9491341fc5a816.
