### ISSUE TITLE
Spam Warnings after compile

### ISSUE THREAD

**Issue by Racot007** [Unity-Technologies/InputSystem#297]
Unity v2018.2.11f1 Input system v0.0.9 preview package

LOG TEXT
`-----CompilerOutput:-stdout--exitcode: 0--compilationhadfailure: False--outfile: Temp/Unity.InputSystem.dll
Compilation succeeded - 12 warning(s)
-----CompilerOutput:-stderr----------
[my project path]/Packages/com.unity.inputsystem/InputSystem/Actions/InputActionProperty.cs(10,19): warning CS0660: `UnityEngine.Experimental.Input.InputActionProperty' defines operator == or operator != but does not override Object.Equals(object o)
[my project path]/Packages/com.unity.inputsystem/InputSystem/Actions/InputActionProperty.cs(10,19): warning CS0661: `UnityEngine.Experimental.Input.InputActionProperty' defines operator == or operator != but does not override Object.GetHashCode()
[my project path]/Packages/com.unity.inputsystem/InputSystem/Plugins/UI/UIActionInputModule.cs(88,21): warning CS0114: `UnityEngine.Experimental.Input.Plugins.UI.UIActionInputModule.OnDestroy()' hides inherited member `UnityEngine.EventSystems.UIBehaviour.OnDestroy()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
W:/Programs/2018.2.11f1/Editor/Data/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll (Location of the symbol related to previous warning)
[my project path]/Packages/com.unity.inputsystem/InputSystem/Plugins/UI/UIActionInputModule.cs(99,21): warning CS0114: `UnityEngine.Experimental.Input.Plugins.UI.UIActionInputModule.OnEnable()' hides inherited member `UnityEngine.EventSystems.BaseInputModule.OnEnable()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
W:/Programs/2018.2.11f1/Editor/Data/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll (Location of the symbol related to previous warning)
[my project path]/Packages/com.unity.inputsystem/InputSystem/Plugins/UI/UIActionInputModule.cs(105,21): warning CS0114: `UnityEngine.Experimental.Input.Plugins.UI.UIActionInputModule.OnDisable()' hides inherited member `UnityEngine.EventSystems.BaseInputModule.OnDisable()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
W:/Programs/2018.2.11f1/Editor/Data/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll (Location of the symbol related to previous warning)
[my project path]/Packages/com.unity.inputsystem/InputSystem/Editor/InputActionAsset/PropertyLists.cs(30,62): warning CS0252: Possible unintended reference comparison. Consider casting the left side expression to type `string' to get value comparison
[my project path]/Packages/com.unity.inputsystem/InputSystem/Editor/InputActionAsset/PropertyLists.cs(57,62): warning CS0252: Possible unintended reference comparison. Consider casting the left side expression to type `string' to get value comparison
[my project path]/Packages/com.unity.inputsystem/InputSystem/InputManager.cs(2831,42): warning CS0168: The variable `exception' is declared but never used
[my project path]/Packages/com.unity.inputsystem/InputSystem/Editor/InputBindingDrawer.cs(156,47): warning CS0649: Field `UnityEngine.Experimental.Input.Editor.InputBindingDrawer.ModifyPopupWindow.onApplyCallback' is never assigned to, and will always have its default value `null'
[my project path]/Packages/com.unity.inputsystem/InputSystem/Editor/InputControlPicker/InputControlPickerPopup.cs(26,22): warning CS0414: The private field `UnityEngine.Experimental.Input.Editor.InputControlPickerPopup.m_FirstRenderCompleted' is assigned but its value is never used
[my project path]/Packages/com.unity.inputsystem/InputSystem/State/InputStateHistory.cs(57,21): warning CS0414: The private field `UnityEngine.Experimental.Input.InputStateHistory.m_Head' is assigned but its value is never used
[my project path]/Packages/com.unity.inputsystem/InputSystem/State/InputStateHistory.cs(58,21): warning CS0414: The private field `UnityEngine.Experimental.Input.InputStateHistory.m_Tail' is assigned but its value is never used
-----EndCompilerOutput---------------
- Finished compile Library/ScriptAssemblies/Unity.InputSystem.dll
Symbols will be read from Temp\Unity.InputSystem.dll.mdb
Script Module: Unity.InputSystem.dll`

**Comment by douglas-piconi** [comment]
These have all been resolved in commit a57d1da7af1a49c576fe503410d09b1c25c63986 , and officially will show up in the .11 preview package.
