### ISSUE TITLE
Creating new action map clears all bindings

### ISSUE THREAD

**Issue by Wahooney** [Unity-Technologies/InputSystem#304]
In 0.0.11-preview clicking Add Action clears all other actions' bindings.

**Comment by Rene-Damm** [comment]
Hmm, that is odd. I'm not seeing the same. Could you post the .inputactions file you're seeing the problem with and/or maybe a screenshot of before and after? Just wondering whether there's something additional playing into this.

**Comment by Wahooney** [comment]
Here's a gif of my exact process after creating a new Input Action asset from the context menu.
https://www.dropbox.com/s/wukle3mn7fk6sq4/Input%20System%20Bug.gif

This is the latest version from the develop branch.

**Comment by Rene-Damm** [comment]
Thank you for the GIF! Always super helpful to see the steps.

So far, still couldn't repro. Tried the exact same steps twice but didn't get the same result. However, I've only tried latest head and on Mac so far. Will keep digging.

**Comment by Wahooney** [comment]
I'm on 2018.3b9 if that helps.

Edit: I've tried deleting the library folder on my existing project and tried it in a brand new project, still there.

**Comment by JiaUnity** [comment]
I cannot repro this on 0.2.0-preview.
