### ISSUE TITLE
Interaction defocuses while changing values

### ISSUE THREAD

**Issue by Wokarol** [Unity-Technologies/InputSystem#309]
While changing thos evalues:
![image](https://user-images.githubusercontent.com/38141841/48796559-43ea1f80-ed00-11e8-87d9-42174cbd8bb4.png)
"Hold" defocuses.

For some reason pressing "," or "." in "duration" causes this too.
I can't set duration to values like 0.5 due to this.

**Comment by Rene-Damm** [comment]
Confirmed. Should be slightly better on latest head of the develop branch but we still lose editing state when saving.

**Comment by Rene-Damm** [comment]
Should be fixed in https://github.com/Unity-Technologies/InputSystem/commit/78e8afe25e8b87fee7aac01cf9b49d6485771831.
