### ISSUE TITLE
Leaked Native Collection every frame in v0.0.10-preview.

### ISSUE THREAD

**Issue by james7132** [Unity-Technologies/InputSystem#313]
```
A Native Collection has not been disposed, resulting in a memory leak. It was allocated at D:\Users\James\Git\FantasyCrescendo\Library\PackageCache\com.unity.inputsystem@0.0.10-preview\InputSystem\Utilities\ArrayHelpers.cs:307.
```

This is occurring at every possible frame on a project I have been working on. Previous version of the input system didn't have these issues when used.

Unity: 2018.3b11.

**Comment by Rene-Damm** [comment]
@james7132 Are you still seeing the problem on 0.0.13-preview?

**Comment by james7132** [comment]
This is still occurring in 0.0.13-preview.

**Comment by JiaUnity** [comment]
@james7132 Do you still see the same leak on 0.2.0-preview? 
If so, you can file a bug through Unity Bug Reporter, so that you can attach a minimal repro project for us to see the problem. We haven't seen it on our end.

**Comment by JiaUnity** [comment]
Didn't hear back from the user about the issue. Closing. 
If anyone still runs into this issue on the latest Stable, please file a bug through Unity Bug Reporter. An attached minimum repro project would help us to identify the issue, since we don't see it on our end.
