### ISSUE TITLE
unsafe keyword compile error in Users_CanPairDevice_WhenDeviceNeedsPlatformLevelUserAccountSelection

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#321]
When I do a fresh pull with the latest from github + 2018.3 beta (.NET 4.6/Std 2.0 w/ C# 7.3), I get the following error:

Packages\com.unity.inputsystem\Tests\InputSystem\Plugins\UserTests.cs(143,18): error CS0214: Pointers and fixed size buffers may only be used in an unsafe context

The error comes from Users_CanPairDevice_WhenDeviceNeedsPlatformLevelUserAccountSelection

Remove the unsafe block from the lambda and making the entire function unsafe seems to fix it.

Has occurred at least since last week, and I've repro'd it consistently on 2 different Windows boxes. Haven't tested Mac OSX yet.

**Comment by periodyctom** [comment]
Addendum: this was in both beta 10 and beta 12

**Comment by Rene-Damm** [comment]
Thanks for the report. Applied the change you mentioned (https://github.com/Unity-Technologies/InputSystem/commit/744640d0d13cbef3da1f6898e2280ec16037caab).
