### ISSUE TITLE
[TOUCH SCREEN] Binding Actions to <Touchscreen>/touch from editor does not work on device

### ISSUE THREAD

**Issue by dave24BG** [Unity-Technologies/InputSystem#332]
If you use the Input Action Editor and create a binding for Touch Screen touch, the bind that it generates is `'<Touchscreen>/touch',` however if you use this on a device the touch does not seem to work, only if you click the 'v' and manually add the binding as `<touchscreen>/<touch>` will the touches work on device. 

Expected behavior: Create a binding using the editor window for Abstract Devices > Touch Screen > touch and have it auto generate the control path. 
Current behavior: The path of `<Touchscreen>/touch` does not work on touch devices 
Work Around : Manually set the binding path to `<touchscreen>/<touch>` from Properties Tab under General in Asset Editor window.

**Comment by JiaUnity** [comment]
Closing. For it is tracked: https://issuetracker.unity3d.com/issues/ui-the-binding-option-touch-touchscreen-does-not-work
