### ISSUE TITLE
Will there be option to get event on controll change?

### ISSUE THREAD

**Issue by Wokarol** [Unity-Technologies/InputSystem#342]
Is there (or will be) an option to get event when user picks up gamepad instead of keyboard?

**Comment by Rene-Damm** [comment]
We still have to wrap this in nicer APIs, properly debug this, and also properly document this, but yes, the basic functionality is there. Essentially, this is `InputUser.onUnpairedDeviceUsed`. There's some code doing what you have in mind [here](https://github.com/Unity-Technologies/InputSystem/blob/develop/Assets/Demo/DemoGame.cs#L342).

Eventually, I hope we will have much higher-level wrappers and take the tedium out of settings this up.

**Comment by Wokarol** [comment]
I need to check this InputUser class, I didn't noticed it at first when I was trying to understand how this system is working

**Comment by Rene-Damm** [comment]
One thing that *might* help while there isn't any docs yet is looking at the [tests](https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/Tests/InputSystem/Plugins/UserTests.cs) for `InputUser`.
