### ISSUE TITLE
Assign gamepad to players

### ISSUE THREAD

**Issue by Wokarol** [Unity-Technologies/InputSystem#343]
How to assign particular gamepad to particular player for local coop games?

**Comment by Rene-Damm** [comment]
This is one of the core functions of the `InputUser` API. Still missing docs, however.

The idea is that you `Instantiate` your actions and have each `InputUser` receive its own set of actions. By pairing specific devices to each user, the actions are restricted to just those devices.

The WIP (and ATM non-functional) demo does that [here](https://github.com/Unity-Technologies/InputSystem/blob/develop/Assets/Demo/DemoGame.cs#L511) and [here](https://github.com/Unity-Technologies/InputSystem/blob/develop/Assets/Demo/DemoPlayerController.cs#L361).

We're still missing nice high-level wrappers to make this quick and easy.

**Comment by Wokarol** [comment]
I need to dive deep into this demo yet again. But without documentation it's still chaos.

**Comment by Rene-Damm** [comment]
Yup, indeed. Docs are sorely lacking. Also, the demo is in shambles right now which doesn't help either. By end of January, we will be in much better shape. Both with docs and the demo.

**Comment by Wokarol** [comment]
So I am at this point:
`    private void AddDevice(InputDevice device) {
        if (createUsers) {
            Debug.Log($"New device named: {device.displayName} : {device.layout} has been added");

            var user = InputUser.PerformPairingWithDevice(device);

            var actions = new CoopPlayerActions(); 
            user.AssociateActionsWithUser(actions);
            actions.Character.Enable();

            var player = new GameObject().AddComponent<Player>();
            player.Setup(actions);

            users.Add(user); 
        }
    }`
And I have no idea how to properly instantiate CoopPlayerActions :/

**Comment by Wokarol** [comment]
I've tried
```cs
CoopPlayerActions actions = playerActions.Clone() as CoopPlayerActions;
```
It still don't work

**Comment by Wokarol** [comment]
For some reason every player is controlled by last device

**Comment by Wokarol** [comment]
I've done this:
```cs
CoopPlayerActions actions = new CoopPlayerActions(Instantiate(playerActions.asset));
```
now every player is controlled by every device

**Comment by jordanhe2** [comment]
Is it possible to get the UserInput system working in its current state? Also, is the demo not working due to the API being broken or does the demo need to be updated to follow changes in the API? 

The code I'm writing mostly follows what the demo code has, so I'm looking for a workaround to get a game to support multiple input devices.

**Comment by Wokarol** [comment]
@jordanhe2 // I managed to make it work, somewhat... where you have a problem? Maybe I can help

**Comment by jordanhe2** [comment]
Hey @Wokarol,
I'm not really sure what I'm missing.
I'm setting `InputUser.listenForUnpairedDeviceActivity = true;`, adding an event listener to `InputUser.onUnpairedDeviceUsed` that calls `InputUser.PerformPairingWithDevice`, I'm calling `MakePrivateCopyOfActions` from the generated C# code of the `InputActionAssetReference` and then setting the callbacks for each unique player, then I run `InputUser.AssociateActionsWithUser` with the InputAction asset I've created and call `InputUser.ActivateControlScheme` with a control scheme I've set up within the asset.

With all of this, it appears that the callbacks are not being called even when my keyboard has been paired with the player's `InputUser`.

Does this sound similar to what you did?

**Comment by Wokarol** [comment]
Take a look at my "demo"
https://github.com/Wokarol/LocalCoopInputSystem
If you press "enter" or "start" on pad you will (hopefully) add a new player controller by said device. Passing "backspace" or "Y" on pad will delete player. 
I'll probably rewrite it some day and make it better.

**Comment by jordanhe2** [comment]
Thanks @Wokarol for the reference, I'll be sure to use it if I run into any more issues!

I seem to have found my issue. For some reason, the Unity editor for the Input Actions was putting a ; before the group label. So if my group was called: `Keyboard` the editor had put `;Keyboard` in my `.inputactions` file for my asset. Apparently the InputSystem didn't like that and didn't include the binding in the `Keyboard` group. I was able to fix it by removing the ; in front of the group name.
