### ISSUE TITLE
XBox One Controller throws exception after a while when tap used on shoulder buttons.

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#346]
On Win10, 2018.3, .NET 4.X, C# 7.3.

Using an XBox One Gamepad, on package from 0.1.2-preview from package manager.

Attached is Editor Log file, InputActions file and source code of the file reading the trace.
[PhaseEditorBug.zip](https://github.com/Unity-Technologies/InputSystem/files/2704869/PhaseEditorBug.zip)

Haven't tested on another machine yet.

I've tested with jamming the stick/dpad and face buttons, haven't gotten it to trigger.

REPRO: 7/7

ADDENDUM:
Seems to happen with the keyboard mapping too IFF the gamepad is plugged in/active, even if it's not being touched. DIsconnect the gamepad and the issue doesn't repro.

**Comment by periodyctom** [comment]
Further ADDENDUM:
* Only happens when both shoulder buttons have tap and are assigned to the same action. If I only have one button with tap assigned to the action, issue doesn't occur.

**Comment by douglas-piconi** [comment]
I'm gonna start looking at this one.

**Comment by douglas-piconi** [comment]
@periodyctom  Lots of complete rework in this area in 0.2.0-preview.  Would you be able to see if you are still seeing this issue?  (I'm having a little trouble reproducing on my windows machine).

**Comment by periodyctom** [comment]
I'll take a look tonight or tomorrow.

**Comment by periodyctom** [comment]
Issue is resolved on my end as of 2019.1b3/b4 and preview 0.2.0-preview
