### ISSUE TITLE
The name 'InputSettingsProvider' does not exist in the current context

### ISSUE THREAD

**Issue by filod** [Unity-Technologies/InputSystem#348]
![image](https://user-images.githubusercontent.com/679897/50483714-f14f0200-0a27-11e9-8366-64dea271a1e8.png)

I think i got this error because `InputSettingsProvider` is only available when define [UNITY_EDITOR && UNITY_2018_3_OR_NEWER](https://github.com/Unity-Technologies/InputSystem/blob/fde6b76552fb683ad8a738b60dc6699e715ca0c2/Packages/com.unity.inputsystem/InputSystem/Editor/InputSettingsProvider.cs#L1)

but i'm still using 2018.2

**Comment by Rene-Damm** [comment]
2018.2 is no longer supported. Sorry about that :( We were stretching ourselves too thin trying to support 2018.2, 2018.3, and 2019.1 while still in development so 2018.2 ended up on the chopping block recently.
