### ISSUE TITLE
When a TouchControl is finished, it's phase becomes "Ended" and stays that way.  Should it eventually revert back to "None"?

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#35]
I was testing Touchscreen by querying Touchscreen.current.touches.  Per Rene's direction, valid touches have phase marked as something other than "None."  After a touch is first recorded, it will never return to the "None" phase.  Instead, when a touch is done it's phase will change to "Ended" and remain in that state.  Is it designed that way, or should a touch's state eventually return to "None"?

**Comment by Rene-Damm** [comment]
Together with the recent API changes, I think this is fine. `.touches` now returns active touches only. Going to `.allTouchControls` will include all ten controls and these do have the `Ended` behavior. Seems fine to me. `None` means there wasn't ever a touch reported on the control. `Ended` means that was one but it has ended.
