### ISSUE TITLE
Plans to support ECS?

### ISSUE THREAD

**Issue by VR-Architect** [Unity-Technologies/InputSystem#350]
Is there any plans to provide a sample using ECS? Can this new system leverage ECS? 

We are starting a new project and would like to use as much pure ECS as possible.

**Comment by Rene-Damm** [comment]
>Can this new system leverage ECS?

ATM no. There are some features (like the system's manual update mode) meant to make use outside of a GameObject world easier but there's nothing directly targeted at ECS at this point. The most sensible option for now is to pick up input in a ComponentSystem's `OnUpdate` method (ideally by running manual input updates right there) and marshal the data into whatever format works best for you (e.g. by translating the action state into structs) and then take it from there. There's bits and pieces (like `InputActionTrace`) that might help.

There's work happening to figure out what form input will take in the ECS world but I don't expect the results of this to hit until later this year.

**Comment by VR-Architect** [comment]
Thanks for the info. It was a big help.
