### ISSUE TITLE
Actions UI does not handle "infinity"

### ISSUE THREAD

**Issue by adamzl** [Unity-Technologies/InputSystem#351]
Issue: if you enter "infinity" into a text field of an action binding a FormatException will continuously occur, only recovery is to delete the binding.

Reproduction Steps:
1. Create an action
2. Create "binding"
3. Add interaction "Press"
4. Click "Press" interaction to highlight it.
5. Enter "Infinity" in the "Press Point" field

Interestingly this only seems to occur with the value "infinity", not "a" or "i".

**Comment by RRickkert** [comment]
Can confirm this issue.
Changing the value from "Infinity" to a value like 0.00001, will automatically change the text to "1e-05", resulting in the same error.

**Comment by JiaUnity** [comment]
Fixed. Closing
https://issuetracker.unity3d.com/issues/editor-ui-input-action-ui-does-not-handle-infinity-or-e-notation
