### ISSUE TITLE
Input System Not Working

### ISSUE THREAD

**Issue by XZcutable** [Unity-Technologies/InputSystem#352]
I am using 2018.3.0f2 of Unity and imported the InputSystem v0.1.2-Preview through the package manager. I used this [Brackeys tutorial](https://www.youtube.com/watch?v=Pzd8NhcRzVo) as a reference and streamed my experience on my [twitch channel](https://www.twitch.tv/z_doctor).

I spent 2 and a half hours trying various ways to get it working, and I am fairly confident that I implemented it as intended, but regardless of what I try to do, the input actions are never triggered and no errors are ever thrown.

I tried: removing the package, adding it back in, and restarting Unity multiple times.

If any other info is needed let me know.

**Comment by RRickkert** [comment]
Currently also dealing with this issue. Still trying to look into it, but the events don't seem to be called. Same Unity version (2018.3.0f2).

**Comment by RRickkert** [comment]
For me it worked again after restarting my Unity editor. I remembered it warning that it needed an Editor restart, but 'assumed' it automatically restarted. Seems to work fine after that.

**Comment by XZcutable** [comment]
I had already restarted but that didn't fix my issue. However, the issue was found. I simply did not call enable. derp
