### ISSUE TITLE
Actions originating from Scriptable Objects are not Invoked

### ISSUE THREAD

**Issue by XZcutable** [Unity-Technologies/InputSystem#353]
Unity Version: 2018.3.0f2
InputSystem Version: 0.1.2

Trying to integrate the new InputSystem into my project me and my viewers stumbled across some odd behavior. Actions originating from Scriptable Objects are not Invoked. 

After some testing here are some conclusions and solutions we found. 1) If you create a Scriptable Object and use this system, and enable it on OnEnable, it will work as expected the first time you play but will stop working after. 2) You can enable the InputSystem within the scriptable object, and it will work as expected in outside scripts as if they enabled it, regardless of if the scriptable object was just created or not.

Solution/Workaround: You can store the InputSystem reference in a monobehavior and pass it to the scriptable object.

**Comment by JiaUnity** [comment]
Verified fix on 2019.1.0b9 with Develop (af5d4c1)
