### ISSUE TITLE
IndexOutOfRangeException with Multiple Action Maps 

### ISSUE THREAD

**Issue by XZcutable** [Unity-Technologies/InputSystem#358]
The error occurs at InputSystem/Actions/InputActionMapState.cs:845.
The Line is: "var action = map.m_Actions[actionIndex - mapIndices[trigger.mapIndex].actionStartIndex];"

The issue is that you are subtracting the actionStartIndex from the action index. It seems that this is either done somewhere else or that the actionIndex no longer has to take that into account. With my setup, the index ended up being -5. (Action index was 2, and the actionStartIndex was 7)

I replaced the line with "var action = map.m_Actions[actionIndex]" but there is still an issue. It seems that the action index is decremented by one when the trigger.mapIndex is 0, but not otherwise. So I replaced it with the following "var action = map.m_Actions[actionIndex - (trigger.mapIndex == 0 ? 0 : 1)];" and the error was resolved.

I also test a third Map Action. No errors were thrown, however, the actions were only invoked when I held down the key, regardless of what interaction I used.

Edit: Seems to happen in the second action map I have too, its weird because it doesn't always happen and acts like the position is corrupted as in it doesn't matter was is used it affects any key put there. Through some testing, I found that it is not tied to the key being used elsewhere. This should be another issue but since it can only be replicated when the original issue is fixed, I'll just note it here.

**Comment by Rene-Damm** [comment]
Should be fixed on latest develop and in next package release.
