### ISSUE TITLE
IndexOutOfRangeException with multiple action maps

### ISSUE THREAD

**Issue by Aresak** [Unity-Technologies/InputSystem#359]
An error occurs when I press the binded key in any action map and have multiple action maps setup. After that the whole action system will stop working and never ever respond to any new events.

Latest unity package version and 2018.3.0f2
`IndexOutOfRangeException: Array index is out of range.
UnityEngine.Experimental.Input.InputActionMapState.GetActionOrNull (UnityEngine.Experimental.Input.TriggerState& trigger) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:985)
UnityEngine.Experimental.Input.InputActionMapState.GetActionOrNoneString (UnityEngine.Experimental.Input.TriggerState& trigger) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:954)
UnityEngine.Experimental.Input.InputActionMapState.ThrowIfPhaseTransitionIsInvalid (InputActionPhase currentPhase, InputActionPhase newPhase, UnityEngine.Experimental.Input.TriggerState& trigger) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:941)
UnityEngine.Experimental.Input.InputActionMapState.ChangePhaseOfAction (InputActionPhase newPhase, UnityEngine.Experimental.Input.TriggerState& trigger, InputActionPhase phaseAfterPerformedOrCancelled) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:837)
UnityEngine.Experimental.Input.InputActionMapState.ChangePhaseOfInteraction (InputActionPhase newPhase, UnityEngine.Experimental.Input.TriggerState& trigger, Boolean remainStartedAfterPerformed) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:790)
UnityEngine.Experimental.Input.InputInteractionContext.Performed () (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputInteractionContext.cs:95)
UnityEngine.Experimental.Input.Interactions.PressInteraction.Process (UnityEngine.Experimental.Input.InputInteractionContext& context) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/Interactions/PressInteraction.cs:38)
UnityEngine.Experimental.Input.InputActionMapState.ProcessInteractions (Int32 mapIndex, Int32 controlIndex, Int32 bindingIndex, Double time, Int32 interactionStartIndex, Int32 interactionCount) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:624)
UnityEngine.Experimental.Input.InputActionMapState.ProcessControlStateChange (Int32 mapIndex, Int32 controlIndex, Int32 bindingIndex, Double time, InputEventPtr eventPtr) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:546)
UnityEngine.Experimental.Input.InputActionMapState.UnityEngine.Experimental.Input.LowLevel.IInputStateChangeMonitor.NotifyControlStateChanged (UnityEngine.Experimental.Input.InputControl control, Double time, InputEventPtr eventPtr, Int64 mapControlAndBindingIndex) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionMapState.cs:455)
UnityEngine.Experimental.Input.InputManager.FireStateChangeNotifications (Int32 deviceIndex, Double internalTime, UnityEngine.Experimental.Input.LowLevel.InputEvent* eventPtr) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/InputManager.cs:2963)
UnityEngine.Experimental.Input.InputManager.OnUpdate (InputUpdateType updateType, UnityEngine.Experimental.Input.LowLevel.InputEventBuffer& eventBuffer) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/InputManager.cs:2693)
UnityEngine.Experimental.Input.LowLevel.NativeInputRuntime+<>c__AnonStorey0.<>m__0 (NativeInputUpdateType updateType, Int32 eventCount, IntPtr eventPtr) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/NativeInputRuntime.cs:110)
UnityEngineInternal.Input.NativeInputSystem.NotifyUpdate (NativeInputUpdateType updateType, Int32 eventCount, IntPtr eventData) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:91)`

**Comment by Rene-Damm** [comment]
Think I finally caught this one. There's two places where `InputBindingResolver` sets up things wrong causing both `actionIndex` in `bindingStates` to be wrong and indices in `controlIndexToBindingIndex` to be wrong. Will push a fix.

**Comment by Rene-Damm** [comment]
Should be fixed on latest develop and in next package release.
