### ISSUE TITLE
Only the most recent touch is reported

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#36]
Expected Behavior: Multiple touches are reported independently in Touchscreen.current.touches.
Observed Behavior: The most recent touch is reported in Touchscreen.current.touches[0].  All other touches are not reported.

You can observe this behavior using the QA touch test scene in Assets/QA/Tests/Touch/ISX_Touch.unity. 
 This scene is a part of this PR: https://github.com/Unity-Technologies/InputSystem/pull/33

**Comment by Rene-Damm** [comment]
Yup, turns out the backend isn't setting stateOffset when sending delta events so all state writes go to the first touch. Needs to be fixed in native.

**Comment by Rene-Damm** [comment]
Fixed on trunk.
