### ISSUE TITLE
UIActionInputModule Inspector bugginess

### ISSUE THREAD

**Issue by scdrumz** [Unity-Technologies/InputSystem#360]
I'm seeing a weird issue in the UI Input module.  Sometimes if I wait, it'll clear itself up, but basically trying to manipulate the actions in the inspector causes a drawing issue:
![image](https://user-images.githubusercontent.com/4335834/50571129-9130d500-0e06-11e9-9d3b-49695c16edb4.png)

This doesn't seem to happen using InputActions in my other behaviors, so not sure what's up, but it seems the PropertyDrawers are a bit buggy still :)

**Comment by scdrumz** [comment]
Using Unity 2018.3.0f2 btw

**Comment by PlanetVaster** [comment]
I can confirm that I've seen similar bugginess (usually placeholder text overlapping regular text). I'm using Unity 2018.3f2, Windows 10, Nvidia 1060/Intel i5-7600k.

**Comment by JiaUnity** [comment]
@scdrumz Is this still the case for 0.2.0-preview?

**Comment by JiaUnity** [comment]
No reply. Cannot repro. Close.
