### ISSUE TITLE
[Actions] IndexOutOfRangeException reading Vector2 from Axis composite

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#361]
https://forum.unity.com/threads/indexoutofrange-on-axis-action.601777/

Should throw an exception that properly points out the problem, not just cause some incorrect indexing somewhere.

**Comment by Rene-Damm** [comment]
Also, shouldn't even allow making the incorrect binding in the first place. That's what the `InputControl` attributes on the composites are for.

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/scripting-when-using-readvalue-with-a-mismatched-value-type-a-wrong-exception-is-thrown
