### ISSUE TITLE
[Editor] NullReferenceException on mouse movement

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#362]
https://forum.unity.com/threads/nullreferenceexception-object-reference-devicetobuffermapping-deviceindex-2.604303/

**Comment by JiaUnity** [comment]
I cannot repro this on 2019.1.0b4 with 0.2.0-preview.

**Comment by Rene-Damm** [comment]
I think I've still seen this one lately. But it seems to only happen when "certain" things happen with devices and/or update types. But yeah, not sure it makes sense to keep the ticket open without having some firmer details.

**Comment by JiaUnity** [comment]
Without more detail how to repro this, there is no way to tell what the cause is. 
Suggest close this bug and file better ones in FB when we run into it again.

**Comment by Rene-Damm** [comment]
Ok let's do that.
