### ISSUE TITLE
[UI] "dpad" not listed for action of type Vector2

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#365]
1. Create action
2. Set type to "Vector2"
3. Create binding
4. Filter for dpad in the control picker

Dpad is a Vector2 and should be included but is not listed.

**Comment by douglas-piconi** [comment]
Are you still seeing this?  I can't repro with 0.1.2 on 2018.3.   Looks like its working now. 
![untitled](https://user-images.githubusercontent.com/24575155/51561874-60b4e780-1e56-11e9-8232-9284e9c41319.png)

**Comment by Rene-Damm** [comment]
@douglas-piconi You'll have to use the asset editor to see this one, I think. The problem is only there if you set the type of an action which I think you can't do in the embedded UI. Once you set the type, the control picker starts filtering controls. Looks like it's incorrectly filtering out `dpad` when the type is `Vector2`.

**Comment by Rene-Damm** [comment]
Ah, taking a second look, found the problem. `LayoutMatchesExpectedControlLayoutFilter` checks inheritance on the *control* type, not on the value type. So `DpadControl` would have to be a `Vector2Control` for this to work. Will take another look tomorrow to see which way this should go. Technically, `DpadControl` *should* be a `Vector2Control`. Think the only reason it's not is that it will get an X and a Y control, too, and currently the state system isn't easily coaxed into synthesizing that axis from two buttons.

**Comment by JiaUnity** [comment]
Verified fix on 2019.1.0b9 with Develop (af5d4c1)
