### ISSUE TITLE
InputTestFixture is not accessible through package

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#366]
1. Add input system package to project.
2. Create a test assembly
3. Try to reference Unity.InputSystem.Tests (might or might not show)
4. Add a class to the test assembly that uses InputTestFixture
5. Build is broken as InputTestFixture can't be found

**Comment by jechter** [comment]
This seems to work for me.

**Comment by JiaUnity** [comment]
Fixed long time ago? @Rene-Damm

**Comment by Rene-Damm** [comment]
Something *may* have landed in 2019.1 (or only 2019.2) that addresses this problem. I talked to the guys working on this some time ago and a solution was being worked on. Chances are it has happened by now. However, that solution required action on our side to make it work.

I think we shouldn't close this ticket until someone has gone in and verified that it indeed works with a public 2019.1 release and why.

**Comment by JiaUnity** [comment]
This exact issue doesn't occur anymore. Other related issue has already been filed separately. Closing.

**Comment by builder-main** [comment]
I'm having this exact issue, package does not show up in assembly explorer and references can't resolve. 2019.3.0f3 - package 1.0.0-preview

```c#
using UnityEngine.InputSystem;

    [TestFixture]
    public class BindingInputTest : InputTestFixture
```

![image](https://user-images.githubusercontent.com/32265170/71562462-bd664c80-2a80-11ea-910c-165580248dfe.png)

![image](https://user-images.githubusercontent.com/32265170/71562467-cbb46880-2a80-11ea-90c4-a1be792b0c71.png)

![image](https://user-images.githubusercontent.com/32265170/71562474-d40ca380-2a80-11ea-829e-d48317f896ef.png)
