### ISSUE TITLE
[UI] Icons are blurry

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#367]
The device and control icons shown in the debugger and elsewhere appear blurry. We're probably not picking the right size and get artifacts from the editor UI automatically scaling them to size.

**Comment by JiaUnity** [comment]
I can help with this since I have Photoshop on my machine.

**Comment by Rene-Damm** [comment]
My guess is this comes down to a code issue. The icons that Hugo provided come in various resolutions and we're probably just not picking the right size and thus get some automatic downscaling that makes things look blurry.

**Comment by JiaUnity** [comment]
Hmm, I just haven't seen any blurry icon, not even after I change the monitor resolution. 
Could you point me to where to look? If it is a bug, we should have a better filing on FB.

**Comment by Rene-Damm** [comment]
Should be fixed.
