### ISSUE TITLE
Input Interactions not working when using Input Action Assset

### ISSUE THREAD

**Issue by agent-reed** [Unity-Technologies/InputSystem#368]
After following the current documentation for a basic setup of the Input system, I've discovered that interactions such as "Press and Release" no longer function when utilizing the Input Action Asset.

With the basic component setup as pictured here. "Press and Release" successfully waits for me to release the "A" key on my keyboard before firing the action.
![simpleworking](https://user-images.githubusercontent.com/10404138/50700838-d9b7e080-1008-11e9-954d-65217c3d440d.PNG)

However, when using the InputAction Asset and creating an Action Map that should act identically, the system no longer waits for me to release the "A" key.  Instead it fires the action immediately upon pressing.
![inputassetnotworking](https://user-images.githubusercontent.com/10404138/50700899-11268d00-1009-11e9-9648-a66cff268bd1.PNG)

I'm wondering if there might be an issue regarding the C# class and Interfaces that were generated alongside the InputAction Asset during its creation?  Not sure why else the system would catch the Input in one setup but miss it in the other.

**Comment by JiaUnity** [comment]
This has been changed. No repro.
