### ISSUE TITLE
Library\PackageCache\com.unity.inputsystem@0.1.2-preview\InputSystem\NativeInputRuntime.cs(167,33): error CS0117: 'Application' does not contain a definition for 'focusChanged'

### ISSUE THREAD

**Issue by ohlawdie** [Unity-Technologies/InputSystem#369]
I am using Unity 2019.1.0a7.

Library\PackageCache\com.unity.inputsystem@0.1.2-preview\InputSystem\NativeInputRuntime.cs(167,33): error CS0117: 'Application' does not contain a definition for 'focusChanged'

I can navigate to the file, glance at the #if Unity_2019_OR_NEWER directive (above the 3 lines of code (that are classified as dead code in Jetbrains Rider))...so if I change the focus out of Unity I am unable to compile? I am not even able to compile if I grab the package out of the package manager and I don't leave Unity.

I am not exactly sure what this means for me but any help would be appreciated, thanks!

**Comment by StayTalm** [comment]
It will be made available in 2019.1.0a15 , but we don't have any more precision in the defines.  I'll look into disabling this for now until that alpha version is available.

**Comment by ohlawdie** [comment]
Okay, thanks Tom!

**Comment by JiaUnity** [comment]
Don't see this on 0.2.0-preview with 2019.1.0b6. Closing.
