### ISSUE TITLE
'Run in background' doesn't work

### ISSUE THREAD

**Issue by flame99999** [Unity-Technologies/InputSystem#370]
Unity 2018.3.0f2  and inputsystem 0.1.2
I'm using InputSystem.QueueStateEvent to feed mouse delta event manually(event data received from remote server). It works fine when Unity has current focus. But when Unity is in background, Vector2 got from CallbackContext.ReadValue is always (0,0). Run in background is already checked.

**Comment by StayTalm** [comment]
A backport is on it's way.  
Right now it will be first available in 2019.1.0a15, and I will update this once it's available in a 2018.3 version.

**Comment by h8672** [comment]
@StayTalm Is it currently on by default in 2019.1.0a++? I get wrong results in Ubuntu 18.04 when using keys with Keyboard .wasPressedThisFrame and .wasReleasedThisFrame on Update or FixedUpdate methods.

**Comment by JiaUnity** [comment]
RunInBackground feature is removed. Closing.
