### ISSUE TITLE
NullReferenceException with HTC Vive

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#371]
https://forum.unity.com/threads/matches-existing-device-but-failed-to-instantiate.609133/

Looks like there's two things here:

1) the core machinery not dealing properly with a layout builder not putting in any information for the device name (for some reason the Vive layout manages to bypass the logic that falls back to just taking the name of the layout), and
2) the XR layout builder not providing the information.

**Comment by jackpr-unity** [comment]
I can't seem to reproduce this with preview0.2.6 and editor 2019.1.0b8. (We only support 2019.1+ now, right?)

**Comment by JiaUnity** [comment]
Closing.
