### ISSUE TITLE
[Windows] Can't hide cursor

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#372]
https://forum.unity.com/threads/cant-hide-the-cursor.607762/

**Comment by JiaUnity** [comment]
Cannot repro on 2018.3.7f1 with Develop.
[CursorLock.txt](https://github.com/Unity-Technologies/InputSystem/files/2886848/CursorLock.txt)

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/windows-cursor-does-not-lock-or-hide-when-using-only-isx
