### ISSUE TITLE
[UI] Undo doesn't work for parameters

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#374]
1. Add Press interaction to a binding
2. Set "Press Point" to 2.
3. Hit Undo

"Press Point" should revert back to 0 but stays at 2.

**Comment by JiaUnity** [comment]
This doesn't repro on 2018.3.8f1 anymore.

**Comment by JiaUnity** [comment]
Also no repro on 2019.1.0b7. Pretty this is fixed somewhere in the past.
