### ISSUE TITLE
Parsing all keyboard controls with Key values 0.1.2 preview

### ISSUE THREAD

**Issue by h8672** [Unity-Technologies/InputSystem#375]
So I cant get keyboard keys from InputControl in 0.1.2 preview using Key enum. They are all available in Keyboard layout, but it's such a pain to go through them...  So I made my own fix (if you can call it that).

~~***Keyboard.current.allControls[0].stateBlock.BitOffset*** contains *a value* that can be cast to **Key**.~~
~~Then **cast** the correct InputControl to KeyControl.~~
Get the right key with Keyboard.current[**Key.Space**] (returns KeyControl, updated script)
```csharp
public struct KeyboardKey
{
    public string name;
    public Key key;
}
KeyboardKey[] _keyboardBinds;
public void BindKeyboardKeys()
{
    List<KeyBind> binds = new List<KeyBind>();
    /* Found better way to get the right KeyControl
    foreach ( InputControl control in _kb.allControls )
    {
        foreach ( KeyboardKey press in keyboardKeys )
        {
            if ( ( (Key) control.stateBlock.bitOffset ).Equals(press.key) )
            {
                binds.Add(new KeyBind((UnityEngine.Experimental.Input.Controls.KeyControl) control, press));
                //Debug.Log(press.name + ": " + control.displayName);
            }
        }
    }*/

    // WARNING Might return null if custom keyboard?
    foreach ( KeyboardKey press in keyboardKeys )
        binds.Add(Keyboard.current[press.key]);

    _keyboardBinds = binds.ToArray();
    binds.Clear();
    Debug.Log("Binded " + _keyboardBinds.Length + " keys that are going to be checked.");
}
void Update()
{
    // For demonstration...
    if ( _keyboardBinds[0].isPressed ) Debug.Log("Key pressed");
}
```
In linux downside is that it doesn't fix how keyboard works. It toggles randomly when pressed. Seems to be known issue in 2019.1.0a13

**Comment by Rene-Damm** [comment]
Not sure I follow what you're asking for TBH.

To turn a KeyControl instance into a Key value, you can use the `keyCode` property. And you can look up keys by name.

```
Keyboard.current["Space"].keyCode; // --> Key.Space
```

**Comment by h8672** [comment]
There was no question, just my observations for finding the right controls using keycode from current Keyboard. I had trouble getting my inputs to work after expanding ActionMaps through current UI. ~~And I don't think there was documentation for it.~~
I was wrong, based on documentation you could also use:
- Keyboard.current[**Key.Space**] to get the right key control... So that makes my demo code useless.
- Gamepad.current[**...LowLevel.GamepadButton.X**] for Gamepad.
- ~~Mouse.current[**...LowLevel.MouseButton.Left**]~~ seems not to be implemented yet.

Also had some trouble getting the new input manager to work so I tried to go through all the keyboard controls to find the right **Key** so I could later change them in game using enum values.

I had some problems using new inputs UI view because:
- Controls bugged in **2019.1.0a13**. They started to work when I downgraded to **2018.3.1f1**
- Controls still bugged in **2019.1.0a14** version.
- I forgot to add the control scheme to InputManager. (No warning)
- I didn't add controls to scheme group. (No warning)
- ~~I Tried to InputMaster.Enable(), but I had 4 different ActionMaps.~~
- ~~Some Actions had no methods connected yet.~~

Still trying to check some of these. I get lots of errors when I enable all action maps, but it seems to work using the one I have already implemented.

I'm still not used to the interface, but it is very promising :+1:. I've been following the forums for long time, but it's better to get some touch in it to see the progress (= troubling the devs :yum: )

**Comment by Rene-Damm** [comment]
Closing this as part of us cleaning out and closing the issue section in order to migrate fully to FogBugz.

>I forgot to add the control scheme to InputManager. (No warning)
>I didn't add controls to scheme group. (No warning)

Yup there's definitely still work to do in helping to diagnose incorrect setups better.
