### ISSUE TITLE
WebGL Keyboard Input doesn't work at all

### ISSUE THREAD

**Issue by RedactedProfile** [Unity-Technologies/InputSystem#381]
![image](https://user-images.githubusercontent.com/1039911/51241262-4b116080-1932-11e9-99ce-d424693c1ed4.png)

When exported for WebGL, and launched in a server, the game fails to capture keyboard input, even with focus. 

In my configuration, WASD nor ArrowKeys work

**Comment by RedactedProfile** [comment]
Hello? I'm not quite sure what to do about this..

**Comment by jechter** [comment]
This is a bug in Unity, where Input data is not correctly transferred to managed code on 32-bit platforms. Fixed in Unity 19.2.

**Comment by mrdev023** [comment]
Not work on Unity 2019.2.0a6

**Comment by jechter** [comment]
The fix should ship in 2019.2a7

**Comment by mrdev023** [comment]
It work on 2019.2.0a7. But Application crash when enter in fullscreen with unityInstance.SetFullscreen(1).

**Comment by JiaUnity** [comment]
No repro for 19.1 or 19.2. Closing.
