### ISSUE TITLE
Keys in Input Manager

### ISSUE THREAD

**Issue by Baste-RainGames** [Unity-Technologies/InputSystem#382]
![image](https://user-images.githubusercontent.com/12800067/51426735-05cd8700-1bef-11e9-9bed-37106f37c8db.png)

There's a bunch of standard editor keys that works in the Input Manager - ctrl+d duplicates an action or action map, and ctrl+x,c,v works as expected.

The delete button doesn't do anything, though. I believe it should, and it should (obviously) delete the selected action or map.

I'd also love it if the Input Manager intercepted ctrl+s to save, and ctrl+n to create a new map or action (depending on what was last selected?). Right now those buttons save the current scene and create a new scene respectively.

**Comment by jechter** [comment]
I'm not sure about this. I'm on a mac, and Cmd-delete deletes an action, as expected, same as for deleting objects in the hierarchy. This should work on windows as well, just not sure what the convention for the right key combination is there - but it should be the same as for deleting objects in the hierarchy window? Or are you saying that it works there for some key combo, but not in the Action map editor?

As for "Save" and "New" commands - we could make those work, and I can see how that would be desirable. At the same time: In unity, unlike Copy/Paste/Duplicate/Delete, "Save" and "New" are generally not context sensitive. For example, Cmd-N will not create a new Game Object if you have the Hierarchy view focused. Maybe it would make sense for this to be context sensitive, and for specific windows to intercept and these and do custom implementations. But as this is not the case today for any other windows/editors, I believe that UX consistency with the rest of Unity is a higher priority then convenience here.

**Comment by JiaUnity** [comment]
I think Rene mentioned Ctrl + s is reserved by Editor, so he had to use Alt + S as Save.
Also, Ctrl + C, V, D, X works as Copy, Paste, Duplicate and Delete on Windows.
I think we can close this for now.
