### ISSUE TITLE
InputActionAssetReference fields are untyped

### ISSUE THREAD

**Issue by Baste-RainGames** [Unity-Technologies/InputSystem#384]
I've got an input action asset that generates a C# script:

![image](https://user-images.githubusercontent.com/12800067/51427070-5f37b500-1bf3-11e9-8b4f-4686961d4281.png)

I've got a script with a public field of that type:

![image](https://user-images.githubusercontent.com/12800067/51427073-7ecedd80-1bf3-11e9-9d9f-03e8d343f1c2.png)

When assigning the field, I think I should only be able to assign the same input action asset that the type defines, but I can assign all of them:

![image](https://user-images.githubusercontent.com/12800067/51427084-a8880480-1bf3-11e9-8bd7-d51cca3bec85.png)

That shouldn't be possible, right? If I assign menu input there, I get all kinds of trouble:

`KeyNotFoundException: Could not find an action map called 'KnightMap' in asset 'MenuControls (UnityEngine.Experimental.Input.InputActionAsset)'
UnityEngine.Experimental.Input.InputActionAsset.GetActionMap (System.String name) (at Library/PackageCache/com.unity.inputsystem@0.1.2-preview/InputSystem/Actions/InputActionAsset.cs:318)
KnightControls.Initialize () (at Assets/Input/KnightControls.cs:22)
KnightControls.get_KnightMap () (at Assets/Input/KnightControls.cs:114)
InputTester.Awake () (at Assets/InputTester.cs:15)
`

**Comment by JiaUnity** [comment]
Closing for it is tracked: https://issuetracker.unity3d.com/issues/scripting-inputactionassetreference-fields-are-untyped
