### ISSUE TITLE
[Actions] "C# Class File# property on .inputactions importer is relative to project root

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#386]
This property should be relative to Assets/, not relative to the project root.

https://forum.unity.com/threads/input-system-update.508660/page-9#post-4119712

**Comment by jechter** [comment]
Fixed by https://github.com/Unity-Technologies/InputSystem/pull/422

**Comment by JiaUnity** [comment]
There is some issue about the file path, but this one is fixed.
