### ISSUE TITLE
Pressing duplicate in Input Manager causes ID's to duplicate.

### ISSUE THREAD

**Issue by Baste-RainGames** [Unity-Technologies/InputSystem#387]
Using Ctrl+D in the Input Manager duplicates input actions exactly, causing them to have the same ID. This causes very hard to track down bugs where lookups that should be targeting one input instead targets another.

I've attached a zip with a video showing a repro that should be pretty easy to follow.
[Input Bug thing.zip](https://github.com/Unity-Technologies/InputSystem/files/2780541/Input.Bug.thing.zip)

**Comment by JiaUnity** [comment]
Confirm fixed for 0.2.6-preview.
