### ISSUE TITLE
After domain reload, sometimes all devices disappear

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#39]
Sometimes, it seems after running tests or when making changes to the system, all devices are suddenly gone. Seems like there's a bug in the domain reload survival logic.

**Comment by Rene-Damm** [comment]
I think this is happening when there is a script recompile while the tests are running. The system domain reload logic is preserving the state during tests then rather than the state that was saved before tests were started.

**Comment by Rene-Damm** [comment]
Seems to only happen when running multiple tests. It almost seems like the test cleanup code after the last test is not run and the input system remains in the state of the last test.

**Comment by periodyctom** [comment]
Have seen something simliar on one Windows box (but oddly not on another). Issue occurs on 2018.3b12 (latest as of this writing) using latest commits. Issue doesn't seem to occur on an older version of my project on 2018.3b10 using InputSystem/develop commits from about a month or so ago.

EDIT: To add a bit more clarity, 0 devices appear and no events are captured by the game side. The editor interface appears unaffected.

Attaching current log, will restart with diagnostics on and add more logs if I see it again:
[Editor.log](https://github.com/Unity-Technologies/InputSystem/files/2635703/Editor.log)

**Comment by periodyctom** [comment]
Unable to create a reliable repro, but it seems to happen most often when debugging and changing code from my IDE (in this case, rider). I'm not writing running Unit tests for the latest changes I've been making yet.

**Comment by periodyctom** [comment]
Seems to happen after recompiling about 4-7 times

I'm using the following setup:
Windows 10
2018.3b12
InputSystem package manually copied from github (will switch to url/official packages later)
Rider 2018.2 stable, C# 7.3 override applied
.NET 4.6, Incremental compiler package at latest on staging.
using latest ECS, burst, math packages.

**Comment by periodyctom** [comment]
I'm not seeing this anymore on 2018.30f2 using 0.1.2-preview from the Package manager.

**Comment by douglas-piconi** [comment]
@periodyctom Do you think we can close this?

**Comment by periodyctom** [comment]
@douglas-piconi - yeah I haven't seen it in 2018.3 or 2019.1a for a while now. I'll reopen if I see it again.

**Comment by Rene-Damm** [comment]
Yup, not seeing it either anymore. Closing this one for now.
