### ISSUE TITLE
Inputmanager when Join behavior is set "When Join Action Is Trigger" pair every device connected to only first user. 

### ISSUE THREAD

**Issue by GilbertoBitt** [Unity-Technologies/InputSystem#392]
After adding the InputSystem i add PlayerInput and Create a Prefab with the PlayerInput script then when i press start (Join action) or Keyboard Enter (Join action) my player is instanciate but on input debugger the user has both keyboard and mouse and joystick has pair devices and becouse of that i can't add more users becouse InputManager add all devices to user1.

so in resume i have 3 devices a keyboard, mouse and joystick(xbox one/Xinput), and when keyboard join i want to add mouse to this user but left joystick unpaired, but all devices are being connected to the only one user no matter if i press join on keyboard first or joystick.

**OBS: this only occur when Join Behavior is set to "Join Players When Join Action  Is Trigger"**

[Chiisaii.zip](https://github.com/Unity-Technologies/InputSystem/files/2798482/Chiisaii.zip)

Here a simple video trying to explain the better the problem: [video file](https://drive.google.com/file/d/1a-cIzOwnDVi_9H5IHZY9D2kumu_O80h0/view?usp=sharing)

**Comment by GilbertoBitt** [comment]
The problem only occur when player input is using Invoke Unity Events

**Comment by hadesfury** [comment]
It is happening again : https://forum.unity.com/threads/players-join-when-join-action-is-triggered-not-working-when-using-a-reference-input-action.795537/

**Comment by Vladyslav25** [comment]
Same here! Its still happening, when you use a Reference. When you create a custom Action or custom Actios (without a Ref) it works.

**Comment by FancyFurret** [comment]
I have the exact same problem!

I have found two workarounds for this:
    1) Clone the action and tell the input manager to use the cloned action for the join action:
    ```_playerInputManager.joinAction = new InputActionProperty(_playerInputManager.joinAction.action.Clone());```
    2) Use a completely separate InputActions asset for actions that shouldn't be tied to players. This is what I've done. I've named that asset "GlobalInputActions" and included actions for player joining, opening my debug console, pausing and ui controls.

Hopefully this helps you guys until Unity fixes it!
