### ISSUE TITLE
OnScreenButtonEditor script causes errors as soon as you add OnScreenButton component

### ISSUE THREAD

**Issue by kakysha** [Unity-Technologies/InputSystem#393]
making `public class OnScreenButtonEditor` not derive from `OnScreenControlEditor` fixes all of them

**Comment by Rene-Damm** [comment]
Confirmed. Looking at it, the entire OnScreenControlEditor code has bitrotted and needs an update.

**Comment by Rene-Damm** [comment]
Should be fixed on latest head.
