### ISSUE TITLE
UIActionInputModule - multitouch support

### ISSUE THREAD

**Issue by kakysha** [Unity-Technologies/InputSystem#396]
I have put two onscreen sticks on canvas and map them to gamepad sticks and they work perfectly. When I run my game in Editor, I can use mouse to manipulate both of the onscreen sticks, its perfectly good. Problem arise on touchscreen devices (iPhone), i can't use both sticks at the same time. It looks like new Input System can't handle multiple touches. Or, more likely, its the UIActionInputModule and it's 'touches' feature is not capable for multitouch. 
When I enable old Input System support and replace UIActionInputModule with Standalone Input Module for my EventSystem, everything is good even on touchscreen. But I do want to abandon old Input System completely, especially when new one has all the components to replace old ones. They just don't work correctly or its me who do not know how to setup UIActionInputModule correctly.

**Comment by JiaUnity** [comment]
@kakysha The touch is still being actively worked on, and this issue may have been resolved or will be in the future. 
However, without an repro project, it is very hard for us to determine the issue. 
Please feel free to file this through the Bug Reporter in Editor, so you can attach a minimal repro project, and it can be properly verified by our QA. 
Thanks.
