### ISSUE TITLE
[Actions] Stick not triggering action after button is pressed

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#397]
I have an action bound to leftStick [Gamepad] with no Interactions and no Processors as well as an action bound to buttonSouth [Gamepad] with an interaction of PressAndRelease and no Processors. In my game, using the Interface callbacks, if I hold the stick in a direction and then hold the button, I lose input from the stick. I'm not getting the callback for it at all until I move it in a different direction.

https://forum.unity.com/threads/a-couple-of-issues-trying-out-the-new-inputsystem-on-2018-3-3f1.619534/

**Comment by JiaUnity** [comment]
No repro for me.
