### ISSUE TITLE
[Actions] ArgumentNullException when right-clicking unfocused action asset editor

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#399]
1. Create action map with an action in the editor.
2. Click the action to select it.
3. Click in another of Unity's window (e.g. project browser) to put focus away from action editor.
4. Right-click action.
5. Observe exception in log.

Tested on OSX.

**Comment by Nikaas** [comment]
There are 3 errors actually if there is no action element focused, i.e. the Map/action window is just opened and nothing selected.

The first one is GUILayout problem if you right-click on an action.
The second one is Null exception if you right-click on the empty space below actions.
Third one happens rarely and I can't figure exactly when but it's something about right-clicking on different elements in the Actions menu after losing focus ( it is - ArgumentException: Getting control 9's position in a group with only 9 controls when doing mouseDown Aborting). This third error can sometimes be accompanied by the first error.

**Comment by jechter** [comment]
Fixed by https://github.com/Unity-Technologies/InputSystem/commit/e28d02cad

**Comment by Nikaas** [comment]
The 0.2.0 from package manager still have the problems.

**Comment by JiaUnity** [comment]
No repro on Develop (7170868). Confirm fixed.
