### ISSUE TITLE
Memory leak error

### ISSUE THREAD

**Issue by Arcnor** [Unity-Technologies/InputSystem#404]
In one part of my game I call `InputSystem.FindControls(binding.path)` to show the current binding in my UI. However, after doing that Unity started warning me about some memory leak:

```
A Native Collection has not been disposed, resulting in a memory leak. It was allocated at .../Packages/com.unity.inputsystem/InputSystem/Utilities/ArrayHelpers.cs:380.
```

I'm using HEAD of `develop` as of today (7a2afc9f)

**Comment by Rene-Damm** [comment]
`InputControlList` needs to be disposed. It allocates unmanaged memory to avoid generating garbage yet still be able to have arbitrary-sized lists. If the use is purely local, the best pattern usually is to employ `using`.

```
using (var controls = InputSystem.FindControls(binding.path))
{
    //...
}
```

It's also possible to turn binding paths directly into strings. See `InputControlPath.ToHumanReadableString()` or the various extraction methods in `InputControlPath` (such as `InputControlPath.TryGetDeviceLayout`.

Once we have better support for rebinding UIs, this all will hopefully get much simpler.

**Comment by Arcnor** [comment]
Thank you very much, and sorry, I didn't realize `InputControlList` needed disposal.

More than turning into strings I want to get the device & key/button for it from the binding itself, but in any case, I guess this is not a real issue, although I'll eagerly wait that rebinding UI support :)
