### ISSUE TITLE
[Debugger] Events are shown out of order

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#408]
The input event trace in the input debugger seems to be buggy. Events sometimes disappear or appear out of order.

To reproduce, bring up input debugger for mouse and check the event log while moving the mouse around. After a while, you should see disappearing events or events appearing out of order (check the IDs and timestamps; neither should go back to lower values).

I'm pretty sure that `InputEventTrace` has at least one bug in either the recording or in traversal.

**Comment by manablight** [comment]
Is it possible to use the data from InputEventTrace to implement an input buffer, or will their be built in functionality for the public API?

**Comment by Rene-Damm** [comment]
> Is it possible to use the data from InputEventTrace to implement an input buffer, or will their be built in functionality for the public API?

It is possible to use it for that. Basically, `InputEventTrace` allows you to maintain a record of input that's been coming in. Either on a specific device or generally in the system.

There's also thoughts about building a more easily accessible mechanism through `InputStateHistory` which would allow you to keep arbitrary history of input state. However, that part isn't functional yet.

**Comment by JiaUnity** [comment]
Fixed. Closing.
