### ISSUE TITLE
[Linux Editor] Dead Keys like Circumflex (AZERTY, QWERTY) doesn't work

### ISSUE THREAD

**Issue by mrdev023** [Unity-Technologies/InputSystem#409]
The keys "^" on azerty or "`", " ' " on qwerty don't work because is waiting press on another key.
And if i press on ^ key all key doesn't work as long as I do not press another key again.

**Comment by mrdev023** [comment]
Edit: This bug appear when compiling Mac, Linux, and Windows version on Linux.

**Comment by Rene-Damm** [comment]
Forum thread: https://forum.unity.com/threads/dead-keys-like-circumflex-azerty-doesnt-work.625951/

@JiaUnity could you give this a look?

**Comment by JeromyStroh** [comment]
https://issuetracker.unity3d.com/issues/linux-keyboard-dead-keys-are-not-reported-in-new-input-system

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/linux-keyboard-dead-keys-are-not-reported-in-new-input-system
