### ISSUE TITLE
[XR] WMR - Haptic intensity can't be changed

### ISSUE THREAD

**Issue by KospY** [Unity-Technologies/InputSystem#412]
Using SendImpulse(intensity, duration), the intensity parameter doesn't have any effect.
Intensity always stay the same.

Tested on Samsung Odyssey+
Last repo update (2019-02-08)
Unity 2018.3.2

**Comment by jackpr-unity** [comment]
2019.1.0b8, package version 0.2.1-preview
WMR haptics straight up don't work for me.

**Comment by JiaUnity** [comment]
Filed in FB. Closing.
