### ISSUE TITLE
Distrubuting through source control (Perforce) the .inputactions file is unreadable.

### ISSUE THREAD

**Issue by tgienger** [Unity-Technologies/InputSystem#413]
After getting a fresh copy of the depot the .inputactions file is unreadable by Unity, showing the action map cannot be found in 'null'.

This was repeatable by myself with a second copy and my coworkers with their own workspaces as well.

**Comment by douglas-piconi** [comment]
It sounds like perforce is treating that file as a binary.  Your going to have to setup your perforce repository to treat the inputaction files as text.

**Comment by douglas-piconi** [comment]
@tgienger You can configure file types in Perforce.  They can be changed after the initial commit, so they are not locked.

https://www.perforce.com/manuals/v16.2/cmdref/file.types.html

**Comment by tgienger** [comment]
It was a text file, the real problem and answer is to add the .cs file to the ignore list so that Perforce no longer locks it. It will get overwritten whenever changes are made.
