### ISSUE TITLE
composite axis doesn't return to zero

### ISSUE THREAD

**Issue by YLlywelyn** [Unity-Technologies/InputSystem#415]
I have a composite axis set up for player movement.  When pressing buttons the value goes to 1 or -1, but it never goes back to zero when the buttons are released, causing my player to keep moving endlessly.

The expected behaviour should be for the axis to report 0 when the assigned controls aren't being pressed, unless there's something I'm missing?

**Comment by douglas-piconi** [comment]
I haven't seen this, but I will try to repro with latest version and get this fixed.  Your right its should be 0 or 1 or 0 or -1.  0.7 for diagonal.

Not sure if it matters @JMSams but what buttons and axis are you using so that I can replicate.

**Comment by YLlywelyn** [comment]
I was using A/D, arrow keys, XInput DPad and XInput Thumbstick, all setup as composite axis.

**Comment by douglas-piconi** [comment]
@JMSams Would you be willing to send me your scripts, and info on what platforms you are seeing this,  ie Android/Mac?   or is it all platforms?   I am having trouble reproducing, but we have had multiple users report a similar issue so I think there really is a problem somewhere.  Just need a few more specifics to help find it.

**Comment by douglas-piconi** [comment]
@JMSams actually I have it reproducing now thanks.  I think I misinterpreted your original description.   I can repro now, `        moveAction = new InputAction("move", binding: "<Gamepad>/leftStick");
        moveAction.performed += ctx => move = ctx.ReadValue<Vector2>();
        moveAction.AddCompositeBinding("Dpad").With("Up", "<Keyboard>/w")
                                                .With("Down", "<Keyboard>/s")
                                                .With("Left", "<Keyboard>/a")
                                                .With("Right", "<Keyboard>/d");`  

then when I hit D, I get 1,0 and it stays that way forever.  never going back to 0,0.

**Comment by douglas-piconi** [comment]
regression introduced in 0.2.0.   Works in 0.1.2

**Comment by douglas-piconi** [comment]
@JMSams  ok, there has been a bit of a redesign with latest code and 0.2.0-preview with some breaking changes with actions.     In addition to performed, you'll have to account for cancelled  with something like `moveAction.cancelled += ctx => move = Vector2.zero;`  to reset the state of your move/look actions back to zero.


Excerpt from latest release notes that explains this.

Actions:

Bindings that have no interactions on them will trigger differently now. This is a breaking change.
Previously, these bindings would trigger performed on every value change including when going back to their default value. This is why you would see two calls of performed with a button; one when the button was pressed, another when it was depressed.
Now, a binding without an interaction will trigger started and then performed when a bound control is actuated. Thereafter, the action will remain in Started phase. For as long as the control is actuated, every value change will trigger performed again. When the control stops being actuated, it will trigger cancelled and the action will remain in Waiting state.
Control actuation is defined as a control having a magnitude (see InputControl.EvaluateMagnitude) greater than zero. If a control does not support magnitudes (returns -1 from EvaluateMagnitude), then the control is considered actuated when it changes state away from its default state.
To restore the previous behavior, simply change code like
  myAction.performed += MyCallback;
to
  myAction.performed += MyCallback;
  myAction.cancelled += MyCallback;
Alternatively, enable passThrough mode on an action. This effectively restores the previous default behavior of actions.
    new InputAction(binding: "<Gamepad>/leftTrigger") { passThrough = true };

**Comment by douglas-piconi** [comment]
@JMSams you can also set it as a passthru if you do not want to deal with the cancelled action.   new         moveAction = new InputAction("move", binding: "<Gamepad>/leftStick") { passThrough = true }; 
        moveAction.performed += ctx => move = ctx.ReadValue<Vector2>();
        moveAction.AddCompositeBinding("Dpad").With("Up", "<Keyboard>/w")
                                                .With("Down", "<Keyboard>/s")
                                                .With("Left", "<Keyboard>/a")
                                                .With("Right", "<Keyboard>/d");

**Comment by YLlywelyn** [comment]
Cool, thanks for the help.  Note to self: read the change notes when updating plugins.
