### ISSUE TITLE
[Windows] Unplugging keyboard crashes Unity

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#423]
https://forum.unity.com/threads/input-system-update.508660/page-9#post-4219033

**Comment by JiaUnity** [comment]
I tried unplug/plug keyboard the other day for another bug, didn't see any crash.
Is this fixed?

**Comment by JiaUnity** [comment]
This crash does not happen on my end. Without more specific information, it is very hard to tell what the issue is.
If anyone experiences this crash, please file through Bug Reporter in the Unity Editor.
