### ISSUE TITLE
Plugging in 8Bitdo gamepad results in error spam

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#424]
>- Plugging in an 8Bitdo Gamepad, i get these weird characters (probably a fallback from Chinese) in the Unsupported devices list which causes A LOT of errors

https://forum.unity.com/threads/input-system-update.508660/page-9#post-4219033

**Comment by JiaUnity** [comment]
Unless we get exactly the same device for this, I don't see how to test this.

**Comment by douglas-piconi** [comment]
I was able to test an 8BitDo SN30.   This seems to work now.

**Comment by JiaUnity** [comment]
> I was able to test an 8BitDo SN30. This seems to work now.

Hooray!..... and closing.
