### ISSUE TITLE
[Windows Editor] Alpha 9 key pressed always return alpha 8 key

### ISSUE THREAD

**Issue by mrdev023** [Unity-Technologies/InputSystem#428]
When i pressed on Alpha 9 keys, Input Debug and Game (In Editor, Build) always pressed the alpha 8 and not alpha 9.

Edit:
I tested on QWERTY US, QWERTY UK and AZERTY layout

Key pressed (AZERTY) :
![event](https://user-images.githubusercontent.com/11292703/53175535-70a61f80-35ec-11e9-964a-c448c2f5bffc.PNG)

Result when Alpha 8 and 9 is pressed:
![key](https://user-images.githubusercontent.com/11292703/53175526-6d129880-35ec-11e9-99f5-7ed270f499b8.PNG)

**Comment by douglas-piconi** [comment]
ok found the problem, the code with the bug is in the editor.  Fix will show up in Unity Editor 2019.2 alpha, 2019.1 beta.  Will try for 2018.3 release.   Will update this bug report with the exact releases once fix has landed to public version of the Editor.

**Comment by mrdev023** [comment]
Ok but this appear also on build from Unity 2018.3 release. It's normal?

**Comment by douglas-piconi** [comment]
@mrdev023 Yep, the bug goes all the way back a year or so even in 2018.1 and 2018.2.    It is definitely broken in 2018.3 and we will get it patched.

**Comment by douglas-piconi** [comment]
Exact release of fix will be in Unity 2019.2.0a9 and 2019.1.0b8
