### ISSUE TITLE
Input Debugger is unusably slow

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#431]
Trying to debug Windows Player from macOS editor
(I tap the Surface screen at the beginning of the video)
[video.zip](https://github.com/Unity-Technologies/InputSystem/files/2893606/video.zip)

**Comment by JiaUnity** [comment]
@renaldasrep is this still the case?
I can debug Windows Player from Windows Editor without issue.

**Comment by renaldasrep** [comment]
Yeah, I think it was due to 32-bit platforms being broken
