### ISSUE TITLE
[iOS][Pen] New InputSystem does not detect the new iPencil (the magnetic one)

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#432]
Version 2019.2.0a7 (dddf9ae2be01)
Wed, 20 Feb 2019 14:24:01 GMT
Branch: trunk

Package github [b223957](https://github.com/Unity-Technologies/InputSystem/commit/b2239576178eaf44fc7c1e770f16ac0113aa6bce)

**Comment by JiaUnity** [comment]
@renaldasrep Please file this bug in FogBugz. Thanks!

**Comment by JiaUnity** [comment]
Filed in FB. Closing.
