### ISSUE TITLE
Gamepad Dpad doesn't report values if a LeftStick is also assigned to the same DPad Action

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#433]
So during some testing this evening on other issues I discovered an interesting issue. (May be related to #325 ).

If I setup a single DPad Action, and then bind both the gamepad DPad and gamepad leftstick to the dpad directions, the physical Dpad will only report values IFF I rotate the dPad around. If I just press and release one of the Dpad buttons, the action doesn't seem to fire.

This is only when the Continuous flag is false. If true, issue #325 the stick causes constant noise since it's never in "neutral".

would the "pass through" flag solve this or is it just a normal bug?

On 2019.1b3/4, Windows 10.

**Comment by danielheim** [comment]
I'm experiencing issues reading any values from a direct Dpad binding. I've listed a bug under [#438](https://github.com/Unity-Technologies/InputSystem/issues/438).
However, I find I can retrieve values when binding via a Vector2 composite.
Hope that helps.

**Comment by JiaUnity** [comment]
I cannot repro this exact bug on 2019.1 with Develop (7170868)
@periodyctom Please see SimpleDemo in the project to filter out stick noise.

**Comment by periodyctom** [comment]
It's no longer a problem with the Fall through flag. Closing.
