### ISSUE TITLE
[Ubuntu] Cannot delete/cut/copy/paste/duplicate/rename action maps or actions by right click menu

### ISSUE THREAD

**Issue by surGeonGG** [Unity-Technologies/InputSystem#435]
The right click menu in the input screen does not work except for creating action maps and bindings.

* Ctrl+c, ctrl+v, ctrl+d still works. 
* Double clicking name to rename still works. 
* Del key does nothing. 
* Right click menu in the rest of unity still works fine.

I use ubuntu.

Is there a hotkey for deleting action maps/bindings that I can use to tide me over? Del key does not work.

I get these errors:
`ArgumentException: GUILayout: Mismatched LayoutGroup.mouseDown
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at /home/builduser/buildslave/unity/build/Modules/IMGUI/GUILayoutUtility.cs:311)`

`ArgumentException: GUILayout: Mismatched LayoutGroup.ignore
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at /home/builduser/buildslave/unity/build/Modules/IMGUI/GUILayoutUtility.cs:311)`

**Comment by mrdev023** [comment]
Same issue

**Comment by JiaUnity** [comment]
The right click menu works for me on Ubuntu 18.04 with 0.2.8-preview. 
This probably not an issue anymore.
