### ISSUE TITLE
[Actions] Not getting disabled automatically when exiting play mode

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#436]
Automatic cleanup of actions (i.e. disabling them and releasing all their unmanaged memory) does not seem to work reliably and lead to errors about unmanaged memory being leaked.

https://forum.unity.com/threads/errors-with-new-input-system-when-exiting-play-mode-solved.632644

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/editor-input-action-does-not-disable-automatically-when-existing-play-mode
