### ISSUE TITLE
InputSystem is stripped out when built to iOS if it’s not referenced anywhere in script, even if related classes like Touchscreen or Gamepad are referenced, causing them to not work

### ISSUE THREAD

**Issue by robertas-unity** [Unity-Technologies/InputSystem#44]
For example, trying to get Touchscreen.current or Gamepad.current without referencing InputSystem somewhere in the script, will return nulls every time.

This can be worked-around by referencing InputSystem somewhere in the script (for example, call InputSystem.devices.Count in Start function).

**Comment by Rene-Damm** [comment]
Looks like we have a problem with the build pipeline not properly respecting `RuntimeInitializeOnLoadMethod`. Talking to the scripting people to get more clarity.

**Comment by Rene-Damm** [comment]
Should be fixed by https://github.com/Unity-Technologies/InputSystem/commit/d4d70ce89c21e6d1ef0741b6f70bd044ecd2c18a.
