### ISSUE TITLE
[Android][Keyboard] Logitech (K270) wireless keyboard is not recognized as a Keyboard device

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#441]
Found using: 9d9a4e8
Happens when connecting: Logitech (K270) via Logitech Unifying Receiver (usb dongle)

Expected result:
When this keyboard is connected, the InputSystem identifies it as a Keyboard and other devices if need be

Actual result:
When this keyboard is connected, the InputSystem identifies it as Joystick and Mouse, but not Keyboard

**Comment by renaldasrep** [comment]
@Rene-Damm can you please assign this to @todi1856 ? Thanks!

**Comment by JiaUnity** [comment]
@renaldasrep file this in fogbugz, please. Thanks!

**Comment by JiaUnity** [comment]
Filed in FB. Closing.
