### ISSUE TITLE
Crash on 2019.1.0b4

### ISSUE THREAD

**Issue by gotenxds** [Unity-Technologies/InputSystem#460]
Hello, I tried to use the new input setting in my project, I made sure to set the input setting to both,
made sure I'm using .net 4, made no code changes and ran the game.
Unity crashed.

![image](https://user-images.githubusercontent.com/3519520/54157593-4e682a80-4451-11e9-9cca-b7aaa047ec4e.png)

I attached a zip file with the crash dump and logs.

[Crash_2019-03-10_204501899.zip](https://github.com/Unity-Technologies/InputSystem/files/2954166/Crash_2019-03-10_204501899.zip)

**Comment by Rene-Damm** [comment]
@gotenxds Any chance you're using input actions in your project. We had a memory corruption introduced in 0.2-preview which has since been fixed (will be part of next package). If actions are in play here, it's a very likely source of the problem as the corruption has led to various crashes.

**Comment by gotenxds** [comment]
I think you may be right, anyway for now I've moved back to 2018 7f1 (as 8f1 seems to have the same issue.)

**Comment by JiaUnity** [comment]
@gotenxds Hey, have you tried the 0.2.6-preview with 2019.1.0b9? Is the crash still an issue? I cannot repro this on my side.

**Comment by JiaUnity** [comment]
No repro and no more information provided by user. Closing.
