### ISSUE TITLE
[UI] Errors about leaked memory when using interactive pick button

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#467]
When using the interactive pick button in the action editor, sometimes there are errors in the console about leaked native memory. I think the cause is simply that m_RebindOperation in the code is not disposed of in time.

**Comment by JiaUnity** [comment]
Closing for it is tracked here: https://issuetracker.unity3d.com/issues/ui-using-detect-input-to-bind-to-an-action-sometimes-generates-an-error-about-leaked-memory
