### ISSUE TITLE
enabling events are inconsistent 

### ISSUE THREAD

**Issue by gotenxds** [Unity-Technologies/InputSystem#472]
Working on macos, unity 2018.3.7f1 input system 0.2.1

This may be related to #261 but a bit different.

If you keep presing a button while enabling/disabling it you will get different results and different times:

1. press button (and hold it)
2. disable event
3. enable event => event is called (button is still pressed)
4.disable event
5. enable even => event is not called this time (button is not pressed.)

Edit, so I made more checks And wrote a simple as I could make it code example and found even more weird stuff here:

`            controls.Player.first.performed += _ => Debug.Log("Entered First");
            controls.Player.first.cancelled += _ => Debug.Log("cancelled First");
            controls.Player.second.performed += _ =>
`

`

            {
                if (controls.Player.first.enabled)
                {
                    Debug.Log("Disable");
                    controls.Player.first.Disable();
                }
                else
                {
                    Debug.Log("Enable");
                    controls.Player.first.Enable();
                }
            };`

So using this code in Awake of a game Object I get the following results.

![image](https://user-images.githubusercontent.com/3519520/54476140-508c0980-4802-11e9-90ea-50e3c6546c7b.png)

This is the log I got from preforming the following key strokes: 
1. first
2. letgo of first
3. first
4. let go of first
5. second and let go of second
6. first and let go of first
7. second and let go (enabling first again)
8. first and let go (no event fired)

**Comment by Rene-Damm** [comment]
Confirmed. Looking into it.

**Comment by Rene-Damm** [comment]
Should be fixed by #523.
