### ISSUE TITLE
Events are being called for any key on first input in play mode

### ISSUE THREAD

**Issue by gotenxds** [Unity-Technologies/InputSystem#473]
Working on macos, unity 2018.3.7f1 input system 0.2.1

So I encountered an odd issue where any events that I have might get called for any button I press on the keyboard, for example, I have the following actions: 

![image](https://user-images.githubusercontent.com/3519520/54477070-d44af380-480c-11e9-9b69-e90fc8315343.png)

As you can see I have move and roll actions
the roll action is bound to left shift (and only left shift!)

When I start play mode and press any key, for example '8', the preformed event for roll will get fired!
`
            controls.Player.Roll.performed += ctx =>
            {
                Debug.Log("Roll");
            };
`

If I inspect the ctx on debug I can see it thinks the shift key got pressed: 
![image](https://user-images.githubusercontent.com/3519520/54477576-cf3c7300-4811-11e9-97ba-2e58bfb7a769.png)
But I pressed '8'.

![image](https://user-images.githubusercontent.com/3519520/54477706-d617b580-4812-11e9-80aa-a72cd6760c34.png)

This happens only for the the first input, after this happens it wont happen again until I restart the play mode.

**Comment by Rene-Damm** [comment]
Sounds like a stuck key.

@JiaUnity Does this repro for you?

**Comment by gotenxds** [comment]
@Rene-Damm I thought at first that this might be a stuck key, but I checked multiple times, non of my keys are stuck, also it happens only for the first input, a stuck key would not wait for the first input of a game.

Furthermore, this reproduces on my windows pc which has a different keyboard.

**Comment by JiaUnity** [comment]
I cannot repro this with 2019.1.0b9 with Develop (7170868)

**Comment by JiaUnity** [comment]
Still no repro
@gotenxds does this happen if you bind to another key other than left shift?

**Comment by JiaUnity** [comment]
No repro. Closing.
