### ISSUE TITLE
[XR] WindowsMR controls do not respond

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#479]
Check this function using Assets/QA/Tests/XRDeviceActions/WMR/WMRActions.unity

Most WindowsMR controls trigger actions, however the following do not:
- right joystick axis2d
- left trigger button
- left device position

These controls react appropriately in the Input Debugger.

**Comment by jackpr-unity** [comment]
This affects both WindowsMR and OpenVR+WindowsMR

**Comment by jackpr-unity** [comment]
Found using Unity 2019.1.0b8 and package version 0.2.1-preview

**Comment by JiaUnity** [comment]
@jackpr-unity File bugz in FogBugz please, thanks!

**Comment by jackpr-unity** [comment]
Moved to https://fogbugz.unity3d.com/f/cases/1139047/
