### ISSUE TITLE
More recents previews builds?

### ISSUE THREAD

**Issue by glaporte** [Unity-Technologies/InputSystem#48]
Hello, is there a most recent preview build for input system than 2018.1.0b1 ?

Thank you,
Grégoire

**Comment by Rene-Damm** [comment]
Unfortunately no, not ATM. Instead of doing another preview build, we've decided to push as hard as we can on getting our native changes into Unity so that normal public releases can be used to run the InputSystem project. We hope to have news very soon.

**Comment by glaporte** [comment]
yes cool on 2018.1.0f1? it should work ?

**Comment by Rene-Damm** [comment]
No, the 2018.1 line won't have support for the new input system. Our target is the 2018.2 line. If the gap is getting too wide and the interest is there, a 2018.1-based preview build to bridge things over may end up being a thing.

**Comment by glaporte** [comment]
could be very interesting, to test on a more stable build.

**Comment by glaporte** [comment]
Hello again i downloaded develop branch of this repo, i show version of unity is m_EditorVersion: 2018.2.0a6

this version can be downloaded ?
Thank you

**Comment by Rene-Damm** [comment]
The alphas aren't public but the betas will be. First beta should be available very soon.

**Comment by Rene-Damm** [comment]
@glaport Dang, forgot to ping this issue when the beta went public. Sorry. In any case, if you haven't yet, check the README for instructions on how to use this with the latest public 2018.2 beta.
