### ISSUE TITLE
XR - WMR Haptics do not fire

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#480]
Found with 2019.1.0b8 and package version 0.2.1-preview

Use the XRHaptics scene in this repository to reproduce

**Comment by JiaUnity** [comment]
@jackpr-unity file this bug in FogBugz. Thanks!

**Comment by jackpr-unity** [comment]
Moved to fogbugz https://fogbugz.unity3d.com/f/cases/1139045/
