### ISSUE TITLE
[UI] Starting rename while rename is already in progress breaks rename field

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#489]
Repro:

1. In action editor, double-click action to start renaming
2. Double-click action map to start renaming action map
3. Start typing

Expected: Renaming of action is aborted, renaming of action map is started and behaves normally
Actual: Renaming of action is not aborted, renaming of action map seemingly is started as normal but any typed character overwrites the current name so that in effect the name is only a single character long.

**Comment by JiaUnity** [comment]
Closing. It is tracked: https://issuetracker.unity3d.com/issues/ui-re-naming-action-map-after-starting-to-re-name-an-action-breaks-the-process
