### ISSUE TITLE
InputActions for keyboards and gamepads do not have a modifier that corresponds to Input.GetButtonUp

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#49]
Keyboard keys and gamepad buttons both have a "pressed" action.  This action is the equivalent of Input.GetButtonDown.

There is not currently an equivalent action to Input.GetButtonUp.

**Comment by Rene-Damm** [comment]
The equivalent is `wasJustReleased`. `Input.GetButtonDown` is equivalent to `wasJustPressed`.

`isPressed` is equivalent to `Input.GetButton`.

**Comment by jackpr-unity** [comment]
I'm referring to action modifiers. See the attached image
![untitled](https://user-images.githubusercontent.com/36174025/37627432-98ec5f56-2b91-11e8-96a5-f95e6ca9f9d7.png)

**Comment by jackpr-unity** [comment]
I guess the correct verbage is: InputActions do not have a modifier that corresponds to Input.GetButtonUp

**Comment by Rene-Damm** [comment]
Yup corect, not ATM. Would be easy to add a "Release" modifier for buttons though I'm a little unsure when exactly it'd be useful.

To some extent even the "Press" modifier seems like it shouldn't be there. Seems odd that the system doesn't understand button presses out of the box but needs an explicit modifier to handle those properly.

**Comment by jackpr-unity** [comment]
I've used OnButtonUp many times in games.  Here are some use cases:
- Any UI button.  Buttons don't usually engage their action until you release your click.
- Press action to begin charging, release to fire a charged shot.
- press to begin holding an object, release to let it go.

**Comment by Rene-Damm** [comment]
Makes sense. And maybe it's okay requiring explicit "Press" and "Release" modifiers for these to work properly with button controls.

**Comment by Rene-Damm** [comment]
There's a `PressAndRelease` interaction now. Action goes into `Started` when the button is pressed and `Performed` when it is released.

https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/InputSystem/Actions/Interactions/PressAndReleaseInteraction.cs
