### ISSUE TITLE
If PS4 DualShock is plugged into PC, read input action path assignment is always angularVelocity

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#494]
If I have a PS4 DualShock plugged in and use the input reading assignment feature, it always assigns to angularVelocity within a second and overrides any other input that may occur, including keyboard presses.

Win10 64, PS4 DualShock, 0.2.6-preview

**Comment by Rene-Damm** [comment]
Should be fixed as part of #508. The DualShock stuff shouldn't have been in that PR but oh well, there it is :)

There were a couple problems here.

1) The DualShock sensor controls weren't been marked as noisy. Thus the rebinding stuff thought them good data and picked them up.
2) The DualShock sensors used to be defined all the way up at `DualShockGamepad`. Theoretically that makes sense but in practice we're not at this point supporting the sensors other than on the PS4 itself. What you got on the PC was all random garbage. I moved the controls to being confined to `DualShockGamepadPS4` for now until we have proper support across platforms.
3) Finally, I realized that being noisy didn't propagate down the hierarchy. So marking a Vector3 control noisy didn't make X, Y, and Z noisy, too. That, too, is changed now.
