### ISSUE TITLE
Old version needs some love, gamepad collision please send help

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/InputSystem#495]
hello, our game use version 0.0.7 (cant upgrade, it breaks or send help ?), we have a problem where we have two gamepads over an internet session colliding code wise, how to differenciate them ? help appreciated :/ also help appreciated in migrating the input system because we are stuck at this old version

(and it happens 100% for example if both players have an xbox 360 controller, we're using quantum for network but clients use inputsystem)

**Comment by exiledgamesstudio** [comment]
(and it happens 100% for example if both players have an xbox 360 controller, we're using quantum for network but clients use inputsystem

**Comment by ghost** [comment]
Hello ? Anyone reading ? i am serious i do need help :/

**Comment by JiaUnity** [comment]
I'm sorry, but we are not going to do bug fix for preview package.
Depends on your Unity version, 0.2.0-preview should work for 2018.3, and the latest update 0.2.6-preview works for 2019.1.0b8.

**Comment by ghost** [comment]
even if not a bug fix, is there a guide to upgrade ? the code relays on internals/api... i can try 0.2.0 but is gamepad collision fixed in there ?? thats the main issue i think

(had tried to upgrade tho and had issues with the code)

**Comment by JiaUnity** [comment]
@exiledgamesstudio 
You can update package by using Package Manager: https://docs.unity3d.com/Packages/com.unity.package-manager-ui@2.1/manual/index.html
If you download from here, just copy the "com.unity.inputsystem" folder from Packages into your own project's Packages folder. But again, depends on your Unity version, the latest release only supports 2019.1.

**Comment by ghost** [comment]
Well, as i did told you already, this don't work as the game calls are made trough the API directly and the upgrade do break, again i would need a guide on how to upgrade the code....

Anyway, sorry but need a quick solution, we are going to use InControl.
