### ISSUE TITLE
PlayerInput with UnityEvents broken

### ISSUE THREAD

**Issue by zadirion** [Unity-Technologies/InputSystem#500]
PlayerInput line 688 tries to find action by id
`var action = m_Actions.FindAction(id);`
id is a guid without being enclosed in curly braces
FindAction fails because of this. It calls TryGetActionIndex inside, which figures out whether the passed parameter is an action name or an id, distinguishing them by whether they start with a curly brace. See InputActionMap.cs line 213:
`var isReferenceById = nameOrId[0] == '{';`

Thus FindAction thinks an action name has been passed, not an id, and thus fails the find, and initialization of PlayerInput with UnityEvents breaks because of this

The PlayerInputEditor also suffers from this issue in PlayerInputEditor.cs line 395:
`var action = asset.FindAction(guid);`
resulting in the actions not being saved

Also PlayerInputEditor line 407 
`newActionEvents.Add(new PlayerInput.ActionEvent(action.id));`
Adds actions that were already added from the asset (on line 398), a second time, resulting in an ever growing list of actions in the inspector, every time the editor re-executes/updates
Code should check whether it's already been added, before adding it again, to avoid duplicates.

**Comment by Rene-Damm** [comment]
Should be fixed in https://github.com/Unity-Technologies/InputSystem/pull/509.
