### ISSUE TITLE
Windows Mixed Reality/HoloLens support

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Unity-Technologies/InputSystem#51]
Are there any plans to integrate HoloLens/Windows MR support into this system?

As I understand it now, adding a new input device like that requires changes on the native side, is that right?
If that's the case, will there be a possibility to add such functionality via a plugin or some hypothetical extension API into this project without requiring Unity to make any changes?

**Comment by Rene-Damm** [comment]
Yup, there's both plans and work being done.

For one, the XR team is working on backend support for Windows MR. This will give you Windows MR support out of the box alongside other XR-related backend support.

Additionally, you always have the option of feeding your own data into the system the same way these backends do. On the user side, the result is indistinguishable from what is coming through from Unity native.

A PR to land initial XR support in the project is in the making. Starting from there, the XR-related APIs should starting shaping up relatively quickly.

**Comment by Holo-Krzysztof** [comment]
That sounds awesome, I'm looking forward to it.

Is there any approximate timeframe for the initial PR, e.g. 1-2 months or something? It'd be good to have at least a rough estimate on when Windows MR can be tested on a preview build.

**Comment by Rene-Damm** [comment]
The PR into this repo is going to land in the next 1-2 weeks. However, the native backend will take a little longer to be in everyone's hands. We're expecting to hit the 2018.2 beta with the first wave of platform support which will allow running the InputSystem project directly with a normal Unity build.

**Comment by Holo-Krzysztof** [comment]
Alright thanks.
So it won't work with the current 2018.1b1-based preview build, is that correct?

**Comment by Rene-Damm** [comment]
Yup correct. The current 2018.1b1-based preview has no XR support.

**Comment by Rene-Damm** [comment]
PR with WindowsMR support has landed.
