### ISSUE TITLE
[Actions] Exceptions and errors in console when editing .inputactions while in play mode

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#512]
1. Open SimpleDemo
2. Go into play mode
3. Open SimpleControls.inputactions
4. Change the assignment of the W key to H
5. Save the asset
6. Focus the game view

There will be a long list of exceptions and errors in the console.

First reported by user here: https://forum.unity.com/threads/input-system-bugs.647611/#post-4344859

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/ui-actions-exceptions-and-errors-are-generated-constantly-if-an-input-action-asset-is-edited-and-saved-during-play-mode
