### ISSUE TITLE
2019.1.0b10 Compatibilty / Demo Project

### ISSUE THREAD

**Issue by eblabs** [Unity-Technologies/InputSystem#518]
Hi,

Im just getting started with using the new Input System. I cant seem to get any of the demo projects to work with 2019.1.0b10. So I just wanted to check if this version of Unity was in fact compatible with the latest preview version of the Input System.

I had import errors on "DemoControls.inputactions" and nothing seems to happen when in playmode. Not even buttons are responsive to mouse clicks. 

I setup a new/empty unity project just for testing this, but so far it doesnt seem to be working at all.

Thanks for any ideas!

All the best,

Eric

**Comment by Rene-Damm** [comment]
There shouldn't be import errors but the `Demo.unity` scene ATM isn't functional. Bit confusing ATM but in the repo, only `SimpleDemo` is expected to work. The full Demo is currently slow getting off the ground.

**Comment by eblabs** [comment]
Thanks for the info @renedamm ! Ill give it another try and reply back...

**Comment by eblabs** [comment]
https://www.youtube.com/watch?v=axekv9D3ID0

Hi,

I just made a quick video showing how I setup the Input System in a new Unity Project. I couldnt get it working and had several errors, but please let me know if Im missing anything!

Steps I took:
* create new project
* get latest Input System from the package manager
* copy in the Assets from the repo
* this is where I start to run into problems.

Thanks,

Eric

**Comment by Rene-Damm** [comment]
You need to restart the editor for input to work. It mentions it in the dialog that popped up but it's hardly ideal. It should just force a restart automatically if you click "Okay". Something to improve.

As for the import errors, we'll have a look. Not sure what's happening there.

**Comment by eblabs** [comment]
Thanks Rene-Damm. 

I went back and tried restarting before importing the assets and then restarting again after. Unfortunately, the same error messages came up and I wasn't able to get anything to run. 

I also deleted the Tests folder, that cleared up a few errors, but still had issues with the SimpleDemo scene. 

Thanks for any more ideas!!

**Comment by JiaUnity** [comment]
The 0.2.6-preview update breaks InputAction asset from previous versions sometimes.
One way to fix it is to find the SimpleControl.inputaction asset in the SimpleDemo folder. Open it with any text editing tool, like Notepad, then add an empty line at the very beginning of the file.
Then you can drag and drop the SimpleControl file into the script again. 
Hope this helps.

**Comment by eblabs** [comment]
Thanks @JiaUnity, that was the trick, the demo asset imported successfully. I'll test it more thoroughly and reply back. 
Thanks again!!

**Comment by Rene-Damm** [comment]
I'm pretty sure the root of the problem causing the errors here is #555. The fact that editing the file fixes the problem is that it triggers a reimport. Manually triggering a reimport from inside Unity using the right-click menu should similarly do the trick.

**Comment by eblabs** [comment]
Looks like there have been many updates to the demo scene files and Im up and running as well. Thanks for everyone's help! Closing :)
