### ISSUE TITLE
Getting Interaction Behavior in Event

### ISSUE THREAD

**Issue by VR-Architect** [Unity-Technologies/InputSystem#521]
How do we get the interaction behavior for a mouse button click event? I am able to see in Visual Studio while debugging the value of obj.interaction.behavior which is PressOnly or ReleaseOnly, etc. 

However, VS2019 doesn't recognize the behavior command. For example:

private void MouseLeft_performed(InputAction.CallbackContext obj)
{
        var f = obj.interaction.behavior; // No definition
}

**Comment by Rene-Damm** [comment]
You would have to cast the interaction like so

```
private void MouseLeft_performed(InputAction.CallbackContext obj)
{
    var f = ((PressInteraction)obj.interaction).behavior;
}
```

Overall, the idea is that the callback shouldn't normally have to care. The actions are meant to act as an abstraction over the actual input with interactions describing the input patterns that lead to the action being triggered.

**Comment by VR-Architect** [comment]
Cool, I should have thought of that. 

BTW, I was trying to do this as a temp hack around for the hold button issue
https://github.com/Unity-Technologies/InputSystem/issues/519 

Now I know how to use the hold button, I will not be using this approach. However, you code snippet would be great for the docs when they come. Thanks again!
