### ISSUE TITLE
Error installation 0.2.6

### ISSUE THREAD

**Issue by maxouhouh** [Unity-Technologies/InputSystem#522]
Hello,
Just want to share you a bug report on version of Unity 2019.1.0b5 on windows 10 
I tried to install the version 0.2.6 and got this error, so I came back to 0.2.1 version for now and It work:

error cs0117: 'nativeinputsystem' does not contain a definition for 'onshouldrunupdate' 

If you want me to test something let me now.

Best regards.
Max.

**Comment by Rene-Damm** [comment]
Hi, the minimum requirement ATM is 2019.1b8.

Sorry that we're not handling this better ATM :/ The package manager shouldn't even allow installing the package when the min version isn't met. Sorry for the confusion.
