### ISSUE TITLE
wasJustPressed and wasJustReleased stick

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#53]
Based on our discussion in this issue: https://github.com/Unity-Technologies/InputSystem/issues/49

Expected: Keyboard.current.aKey.wasJustPressed functions equivalently to Input.GetButtonDown, Keyboard.current.aKey.wasJustReleased functions equivalently to Input.GetButtonUp.
Observed: wasJustPressed and wasJustReleased stick.  WasJustPressed will continue to be true every Update loop as a key is held down.  WasJustReleased will continue to be true after a key is depressed until it is pressed again.

I presume this happens because wasJustPressed and wasJustReleased directly check state, and state is only updated on a physical control update.

**Comment by Rene-Damm** [comment]
Good find. Confirmed. And yup, you're right, it's the state looking at just the previous and current state and it won't change unless there's stuff coming in. Incidentally, the current test for this functionality misses this rather crucial aspect of behavior entirely :)

**Comment by Rene-Damm** [comment]
Should be fixed in https://github.com/Unity-Technologies/InputSystem/commit/98b5cb3d54afee8c33e2661592fb0e2d371c99fa.
