### ISSUE TITLE
Get simple "Face to Cursor" back to work

### ISSUE THREAD

**Issue by ManuelRauber** [Unity-Technologies/InputSystem#532]
Hi,

I've a simple Update function:

```csharp
private void Update()
{
    Debug.Log($"{Camera.ScreenToWorldPoint(Input.mousePosition)} || ${Camera.ScreenToWorldPoint(Mouse.current.position.ReadValue())}");
    WeaponMotor.FaceTo(Camera.ScreenToWorldPoint(Input.mousePosition));
}
```

```csharp
// WeaponMotor
public void FaceTo(Vector2 faceTo)
{
    var position = transform.position;
    var zRotation = Mathf.Rad2Deg * Mathf.Atan2(
                        faceTo.y - position.y,
                        faceTo.x - position.x
                    );

    transform.rotation = Quaternion.Euler(0, 0, zRotation);
}
```

When using `Camera.ScreenToWorldPoint(Input.mousePosition)` the weapon will always face the cursor as expected. 
When using `Camera.ScreenToWorldPoint(Mouse.current.position.ReadValue())` instead, the y-position is not correct.

Sample log entries:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/740791/55910408-a6c05280-5bde-11e9-83df-949d53793ffc.png">

X and Z positions are correct, but the Y position is not correct for the new input system.

Definition of the Input System:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/740791/55910276-52b56e00-5bde-11e9-8dc5-abb7eea5c79f.png">

<img width="926" alt="image" src="https://user-images.githubusercontent.com/740791/55910284-5943e580-5bde-11e9-8101-20fa3b1ea701.png">

Do I have to do anything else to make it work correctly, or is this a bug?

**Comment by Rene-Damm** [comment]
`Mouse.position` is expected to be equivalent to `Input.mousePosition`. So yup, that'd be a bug. What's the platform?

**Comment by ManuelRauber** [comment]
Platform: macOS
Unity: 2019.1.0f1
Input System Package Version: 0.2.6

**Comment by JiaUnity** [comment]
This issue happens mainly in Editor. The standalone build is not impacted for the most part, but if user switches between fullscreen and windowed mode, the X is different.

**Comment by JiaUnity** [comment]
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1145645/
Closing.
