### ISSUE TITLE
Generated C# Class in Wrong Folder

### ISSUE THREAD

**Issue by eblabs** [Unity-Technologies/InputSystem#535]
Hi,

I'd like to report a bug, it looks like the auto generated C# class ends up being put in a duplicate nested folder. I didn't see a mention of this on the other issues. My apologies if its already been brought up!

Thanks!

Should be created in this folder:
/Assets/FREERIDE/Modules/Controls

Ends up being created in:
/Assets/Assets/FREERIDE/Modules/Controls

![image](https://user-images.githubusercontent.com/5941510/56016299-a1cbd380-5cb0-11e9-9a78-5a643a21bfbe.png)

**Comment by douglas-piconi** [comment]
@Rene-Damm I did notice this in my testing as well.   I'll put in a fogbugz ticket.

**Comment by eblabs** [comment]
Thanks!

**Comment by douglas-piconi** [comment]
Moving bug to bug tracking system https://fogbugz.unity3d.com/f/cases/1145602/ for 2019.1 0.2.6-preview
