### ISSUE TITLE
Device Request: MIDI Controllers

### ISSUE THREAD

**Issue by rsodre** [Unity-Technologies/InputSystem#537]
MIDI is a simple protocol, used not only for music, but for any kind of interactive performance and underexplored in games.

As an example see [50 Best MIDI Controllers In The World Today](https://blog.landr.com/50-best-midi-controllers/).

**Comment by JimmyCushnie** [comment]
Are there plans to support this?

**Comment by Rene-Damm** [comment]
Not ATM.

However, I've added the request to the stack of things we'll evaluate once 1.0 is in safe waters and we can go work on features again. (internal ticket ISX-270)

As part of us migrating away from GitHub issues, I'll go close this one. But no worries, doesn't mean it's forgotten :)
