### ISSUE TITLE
MacOS always handles new and old input system, even if only new Input System is selected in player settings

### ISSUE THREAD

**Issue by ManuelRauber** [Unity-Technologies/InputSystem#539]
I've a game which uses the new input system. In Unity settings I switched the active input handling to the new system only:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/740791/56081547-dc4b8280-5e0e-11e9-938f-120dc8649168.png">

By that, a `Input.mousePosition` should not work anymore. However, on macOS it still works as expected. But if you build the game for Windows, `Input.mousePosition` is not working anymore (which is expected).

If you change the active input system to use both, then it works on both platforms.

The bug happens in editor and in the player.

I'd expect, that when using the new input system only, that `Input.mousePosition` should not work on macOS as well.

**Comment by JiaUnity** [comment]
Feel free to vote at: https://issuetracker.unity3d.com/product/unity/issues/guid/1147574/
Filed and closing.
