### ISSUE TITLE
Causing an Interaction/Processor value to update closes the foldout

### ISSUE THREAD

**Issue by MetaflameDragon** [Unity-Technologies/InputSystem#540]
Any input that would change a value in the settings of an Interaction/Processor immediately closes the foldout.

![2019-04-14_22-13-17](https://user-images.githubusercontent.com/19003569/56098634-86580700-5f02-11e9-93ff-0e47a65fc25e.gif)
Notice that writing anything that *wouldn't* change the value (like extra zeroes or a decimal dot) does not cause this.

This issue occurs on any change (including booleans and other values).

**Comment by JiaUnity** [comment]
Known bug: https://issuetracker.unity3d.com/issues/ui-the-items-in-interactions-and-processors-keep-losing-focus-during-editing
Already fixed in the latest Develop branch. The fix should be in the next package release (0.3.0-preview).
