### ISSUE TITLE
Using a PS4 controller connected via bluetooth to a game on Android and playing in editor via Unity Remote doesn't work

### ISSUE THREAD

**Issue by DavidCodesDev** [Unity-Technologies/InputSystem#553]
The gamepad.current gives a nullreference error, but whenever I build the game and play it on my android phone it works perfectly. I assume this is not intended/ a bug and is supposed to work with the unity remote too? (because it did with the old input manager)

**Comment by JiaUnity** [comment]
Unfortunately, this is a known bug that DualShock controller, when connected via bluetooth, doesn't work on Desktops, including Windows, OSX and Linux.
The only way around is to connect the DualShock controller with cable. But we'll address this issue for sure.
