### ISSUE TITLE
[Actions] Icons set by importer don't work on initial import

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#555]
The icons are that the importer sets on the root `InputActionAsset` and the contained `InputAction` objects are loaded through `EditorGUIUtility.Load` which, for things not coming from the editor asset bundle, falls back to querying the asset database. This won't work on the initial import as the .png icons will be importer *after* `.inputactions` files.

Repro:

1. Delete Library/ folder on InputSystem project
2. Open Unity

See errors in log and generic icons on .inputactions files in the project.

**Comment by JiaUnity** [comment]
@Rene-Damm Can you take a screenshot of the error?
I don't encounter any persistent error msg after deleting the Library folder.

**Comment by JiaUnity** [comment]
![Error](https://user-images.githubusercontent.com/33637761/56448619-64c19b80-62c5-11e9-8276-e471c7e52e80.JPG)
Is this the error msg?

**Comment by Rene-Damm** [comment]
@JiaUnity Yup, that's the error message. My guess is that it comes from the failed access to icons that don't yet exist.

If you hit "Reimport" on an .inputactions asset after the initial import, everything will be fine. The correct icons will appear on the assets and no errors will show up in the log.

**Comment by JiaUnity** [comment]
Filed in Fogbugz: https://issuetracker.unity3d.com/product/unity/issues/guid/1152967/
Closing
