### ISSUE TITLE
[0.2.8-preview] Can't get Mouse position with Press Interaction

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/InputSystem#567]
Hello !

I've setup a simple scheme, with a "Sign" action, bind on "position [Mouse]". I've set the interaction to Press.

![2019-04-27 10_37_30-Unity 2019 1 0f2 Personal -  PREVIEW PACKAGES IN USE  - SampleScene unity - Inpu](https://user-images.githubusercontent.com/12472504/56847220-9d223480-68d8-11e9-89da-8d3c907fcc84.png)

But the event is only trigger once the game view get the focus, when I click on Left Mouse Button. When I click elsewhere in Unity and click again in the game view, the event is triggered, but only once, even if I keep clicking in the game view.

_(Edited to precise what I think should be the intented behaviour)_
What I expect is the event to be triggered each time I click on the left mouse.

Here's a simple Unity project to test : [InputSystem.zip](https://github.com/Unity-Technologies/InputSystem/files/3123693/InputSystem.zip)

**Informations :**

- Unity 2019.1.0f2
- InputSystem 0.2.8-preview
- Scripting Runtime : .NET 4.x with Mono backend and API Compatibility Level .NET 4.x
- No other package installed
- Tested on Windows 10 64 bits (Pro, v1809)

**Comment by JiaUnity** [comment]
[InputSystem.zip](https://github.com/Unity-Technologies/InputSystem/files/3292621/InputSystem.zip)
How to achieve it.
Also recommend to visit our forum for alternative solution: https://forum.unity.com/forums/new-input-system.103/
