### ISSUE TITLE
Can't interact with UI elements

### ISSUE THREAD

**Issue by GoncaloRod** [Unity-Technologies/InputSystem#568]
When I enable input system I can no longer interact with UI elements. Is it not implement yet or am I missing some configuration?

**Comment by Rene-Damm** [comment]
We're currently working on UI support. An initial version is already in the package in the form of `UIActionInputModule` (meant to replace `StandaloneInputModule`) but it requires a bit of manual setup. We'll have a simpler setup procedure soon.

**Comment by kartikey0303** [comment]
@GoncaloRod I tried using the both option in Player Input Settings. After restarting the editor the UI Buttons did work and even the `OnScreenButton` script worked. I think this is a viable work around for the mean time.

**Comment by JiaUnity** [comment]
Feel free to file a bug either here or through Bug Reporter if this is still an issue.
Closing.
