### ISSUE TITLE
CallbackContext.duration is computed incorrectly in the editor

### ISSUE THREAD

**Issue by mstevenson** [Unity-Technologies/InputSystem#576]
The `CallbackContext` object passed to an `InputAction.performed` event handler includes an incorrect `duration` value. It appears that `CallbackContext.startTime` is approximately equal to `Time.time`, however `CallbackContext.time` is precisely equal to `EditorApplication.timeSinceStartup`.

Thus the `duration` value is computed as the time since the editor was launched minus the time since play mode was started, which is a nonsensical value.

- Unity 2019.1.0f2
- Input System 0.2.8-preview

**Comment by JiaUnity** [comment]
Finally filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1164162/
Closing.
