### ISSUE TITLE
Simulate Gamepad/LeftStick using a Vector2 composite (WASD)?

### ISSUE THREAD

**Issue by perrauo** [Unity-Technologies/InputSystem#577]
Currently my composite strictly results in value 0, 1 with no in between. I want to the value to lerp from 0 to one 1 shortly after the WASD keys are pressed.

![image](https://user-images.githubusercontent.com/24371247/57056225-00acb900-6c6f-11e9-8cec-796b4161c597.png)

What I have currently with WASD
![image](https://user-images.githubusercontent.com/24371247/57056247-21750e80-6c6f-11e9-8eef-b339cfa6f97f.png)

What I have currently with LeftStick ( I want to simulate with WASD)
![image](https://user-images.githubusercontent.com/24371247/57056258-3782cf00-6c6f-11e9-9dce-6bc041cc1ae3.png)

**Comment by Rene-Damm** [comment]
Unfortunately, we don't have support for "gravity" yet. It's on the list but likely won't make it for 1.0.

**Comment by perrauo** [comment]
Thanks, I understand
