### ISSUE TITLE
When / Where to Register Custom Input Processors

### ISSUE THREAD

**Issue by s-ol** [Unity-Technologies/InputSystem#578]
How should Custom Input Processors be registered in order to show up in the Input Actions UI as well as be present at load time, especially when the 'Generate C#' option is being used?

It seems that [`InputSystem.RegisterControlProcessor`](https://github.com/Unity-Technologies/InputSystem/blob/642b85ca5ad26540edb767d703a70268c1eda003/Packages/com.unity.inputsystem/InputSystem/InputSystem.cs#L407) should be called, but from where?

**Comment by Rene-Damm** [comment]
Recommended to use `InitializeOnLoad` (editor) and `RuntimeInitializeOnLoadMethod` for these registrations.
