### ISSUE TITLE
Input system reads my nine as a 8

### ISSUE THREAD

**Issue by perrauo** [Unity-Technologies/InputSystem#584]
WIth the latest release of the package (0.2.1-preview), the [Keyboard] 9 reads my 9 as a 8. Can someone please confirm? Thanks

![image](https://user-images.githubusercontent.com/24371247/57146320-0dc2c880-6d93-11e9-949e-1bc948c09b34.png)

![image](https://user-images.githubusercontent.com/24371247/57146382-3054e180-6d93-11e9-854a-8c1701f9efc2.png)

**Comment by JiaUnity** [comment]
This is a known bug fixed in later version. 
Please update your Input System package to the latest version (0.2.8-preview)
