### ISSUE TITLE
[0.2.8-preview] Events list keeps growing each time I open it

### ISSUE THREAD

**Issue by colin-young** [Unity-Technologies/InputSystem#585]
Unity 2019.1.0f2, OS X (also seeing same with 2019.2.0a14)

Reproduction: 

1. Open new project, add preview input system, set active input handling to Input System (Preview).
2. Add player input component to Main Camera
3. Select "Create Actions" and set behavior to "Invoke Unity Events"
4. Expand Events and note there is one event for each of the Actions in the Input Actions
5. Select another game object (e.g. Directional Light), then select the Main Camera again
6. Expand Events and note there are now 3 events for each of the Actions in the Input Actions. Each time you repeat steps 5 and 6 you will get 2 more events for each Action.

**Comment by Rene-Damm** [comment]
Yup, indeed buggy. Thanks for reporting. Fixed in https://github.com/Unity-Technologies/InputSystem/commit/3d02ada09f1257f6a56897e09aa30fa0e17abbbf.
