### ISSUE TITLE
Simple and easy to use API.

### ISSUE THREAD

**Issue by BjarkeCK** [Unity-Technologies/InputSystem#587]
I realize that this is not done yet :) But I did find everything quite frustrating. I tried the input system today and after two or three hours without getting a single thing to work, I gave up. 

I wish there where an easy way of just getting a list of all input devices, and from there go thought the API and map everything myself. Just give me the data! Without requiring me to use components, scriptable objects, or any advanced and hard to set-up systems that is so convoluted because it tries to cover all possible use cases.

Forgive me if I'm stupid and that is already something you can do.

**Comment by Rene-Damm** [comment]
There is zero-setup API. See [here](https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/Documentation~/QuickStartGuide.md#getting-input-directly-from-an-input-device).

```
// Get all devices.
foreach (var device in InputSystem.devices)
    /* ... */;

// Read left stick from current gamepad.
var v = Gamepad.current.leftStick.ReadValue();
```

But without specifics it is hard to know what exactly you're after.

**Comment by BjarkeCK** [comment]
Thanks! 

I tried tho, but it didn't list any devices at all, so thought I was missing some sort of setup. Bought rewired and it listed all devices correctly.
