### ISSUE TITLE
Input system and XR dependency

### ISSUE THREAD

**Issue by Racot007** [Unity-Technologies/InputSystem#588]
Unity 2019.1.1.f1
I removed "com.unity.modules.xr": "1.0.0" and "com.unity.xr.legacyinputhelpers": "2.0.2" from [ProjectPath]/Packages/Manifest.json and have some errors from input system package (see attached files below)

![InputSystemDepe](https://user-images.githubusercontent.com/6072592/57195496-013d9c00-6f5c-11e9-90cb-9082d17540bd.png)
![InputSystemXRDependency](https://user-images.githubusercontent.com/6072592/57195497-026ec900-6f5c-11e9-8fe4-51fa845062a4.png)

**Comment by Rene-Damm** [comment]
@mattdatwork This should be fixed by #574, right?

**Comment by mattdatwork** [comment]
yep!

**Comment by Rene-Damm** [comment]
Should be fixed on latest head.

**Comment by interior-night** [comment]
@Rene-Damm I also don't have any XR in my manifest and I'm getting something similar with 2019.3.0f0 and Input System 1.0.0 preview 3:

`Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/InputSystem.cs(2921,13): error CS0234: The type or namespace name 'XRSupport' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)
`
