### ISSUE TITLE
[Editor] Interactions are resetting when set using InputAction Inspector

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#593]
Interactions are resetting when set using Inspector of `InputAction`, works fine when set using `InputActionAsset`

Example:
![ezgif-1-1d09c84ba681](https://user-images.githubusercontent.com/39190411/57304233-a2a52900-70e7-11e9-8d77-cab01b0fb4cd.gif)

Found using:

Package 3a3988db (develop)

Version 2019.3.0a3 (e289e67be1a5)
Sun, 05 May 2019 08:44:27 GMT
Branch: trunk

**Comment by JiaUnity** [comment]
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1152997/
Feel free to vote on the issue.
Closing.
