### ISSUE TITLE
[0.2.8-preview] Build queues input while not in focus.

### ISSUE THREAD

**Issue by SKroell** [Unity-Technologies/InputSystem#594]
We got multiple game events that is triggered by the user pressing a specific key. Currently we got RunInBackground disabled in the Player settings hoping that the game won't react to input while not in focus, but this doesn't seem to be the case. 

Using the simple code below, we got a TestAction thats setup to trigger when pressing the 'A' key on the keyboard (press-only). If you alt-tab out of the game and press A multiple times, the log will quickly populate with "TestAction Performed!". 

```csharp
private void Start()
{
    TestControls input = new TestControls();
    input.TestActionMap.TestAction.performed += TestActionOnPerformed;     
    input.Enable();
}

private void TestActionOnPerformed(InputAction.CallbackContext obj)
{
    Debug.LogError("TestAction Performed!");
}
```

In 0.2.1 there was an toggle in the input settings "RunInBackground", but I can't recall if that was working. Has the setting been moved to somewhere else? Disabling and Enabling action maps in OnApplicationFocus gives the same result aswell. 

Repo:
- Extract InputInBackground.zip & open it with Unity 2019.1.0f2
- Build with development build enabled
- Open the executable and alt-tab to loose focus
- Press 'A' one or multiple times
- Re focus the window and look in error log (should have "TestAction Performed!" printed for everytime you pressed 'A'

[InputInBackground.zip](https://github.com/Unity-Technologies/InputSystem/files/3154232/InputInBackground.zip)

**Comment by JiaUnity** [comment]
Not sure if the Run In Background is working yet.
@Rene-Damm Could you answer this question?

**Comment by JiaUnity** [comment]
Bug filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1153515/
Feel free to vote on the issue.
Closing.
