### ISSUE TITLE
InvalidOperationException: Handle is not allocated

### ISSUE THREAD

**Issue by IronWarrior** [Unity-Technologies/InputSystem#605]
When running my project, often after I stop running I will get the following error:

![image](https://user-images.githubusercontent.com/12469377/57576126-e365b080-740d-11e9-9e27-de561337332a.png)

With the following stack trace:

![image](https://user-images.githubusercontent.com/12469377/57576128-ecef1880-740d-11e9-9647-c706ecb7ff06.png)

Which points to the following block of code:

```
       private void RemoveMapFromGlobalList()
        {
            var count = s_GlobalList.length;
            for (var i = 0; i < count; ++i)
                if (s_GlobalList[i].Target == this)
                {
                    s_GlobalList[i].Free();
                    s_GlobalList.RemoveAtByMovingTailWithCapacity(i);
                    break;
                }
        }
```

With this line being the offender `s_GlobalList[i].Free();`

[According to the docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.gchandle.free?view=netframework-4.8#System_Runtime_InteropServices_GCHandle_Free), GCHandle.Free throws an exception if you attempt to free a non-allocated handle, which is what I assume is happening here.

After this error has occured, no input from my XR device (Oculus Rift Touch Controllers) is listened to. Input from my gamepad and keyboard is correctly listened to. I've attached my relevant Input files below. I only started working with this system yesterday, so I doubt I'm doing anything super out of the ordinary.

[Input.zip](https://github.com/Unity-Technologies/InputSystem/files/3169569/Input.zip)

**Comment by IronWarrior** [comment]
An update: started deleting everything one by one and was able to narrow down the cause. The exception is thrown whenever you have more than one instance of an `IInputActionCollection` instantiated _and_ enabled.

Below is a very minimal project that reproduces the bug locally in 2019.1.2f1. I am running Windows 10. The exceptions I have in the image in my initial post get thrown roughly three quarters of the time, so running the main scene 2-3 times is enough to witness it. Deleting either of the `InputTest` objects results in the errors not being thrown.

If I make a workaround I will follow up with it here.

[InputError.zip](https://github.com/Unity-Technologies/InputSystem/files/3169781/InputError.zip)

**Comment by IronWarrior** [comment]
As a temporary fix, I use a singleton MonoBehaviour to manage a single instance of my InputActions that other classes retrieve at runtime. Using a MonoBehaviour (rather than a non-MB singleton) allows it to be destroyed at end of scene, clearing all of the events in it.

**Comment by JiaUnity** [comment]
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1156869/
Closing.
