### ISSUE TITLE
UI Left doesn't work with xbox controller

### ISSUE THREAD

**Issue by IsaacInsoll** [Unity-Technologies/InputSystem#624]
Running Unity 2019.1.3 and PlayerInput 2.10-preview
Primary development environment: 2013 Mac Pro + Xbox One Controller (USB)
"Intermediate" Development Environment: Base model Surface pro (2017) + Xbox One Controller (USB)
Testing Machine: Xbox One S with Elite Controller connected wirelessly. 
---
WHAT WORKS: 
All in-game controls work correctly (IE: left joystick and all buttons operate character correctly) on all platforms. 
WHAT DOESN'T WORK
When I pause the game it brings up a canvas with a few buttons. I can also switch scenes to the main menu which is also a canvas with a few buttons. On Mac this all works correctly (IE: left joystick to navigate between items and 'a' to select it). On the Surface Pro (inside unity) and Xbox (deployed as universal windows app via visual studio 2017) the joystick right moves to the next item and 'a' still selects but joystick left doesn't work. It's strange as it works to control player but just not in menus. 

I am happy to provide any diagnostic data or do anything to test this further so please let me know how I can help resolve this. Thanks

**Comment by IsaacInsoll** [comment]
It also appears that 'down' doesn't work on windows/xbox when navigating UI, only 'up' and 'right' work. All work on mac and in game.

**Comment by JiaUnity** [comment]
I'm not certain UI is fully supported yet. 
@Rene-Damm could you confirm if this is correct?

**Comment by Rene-Damm** [comment]
I believe this part of the UI functionality is expected to work in 0.2.10. @jechter?

**Comment by jechter** [comment]
Yes, this should work in 0.2.10. Could we get a repro project to look at?

**Comment by IsaacInsoll** [comment]
Thanks for the info @jechter . 
I've created a new project which is available as a 26kb ZIP file here:
https://drive.google.com/file/d/1Uy-TAvBkoMmaxcizrj_b4bz_NpT5kDo8/view?usp=sharing 

Created on windows in 2019.1.3 and 2.10 InputSystem. 
- Added new PlayerInput via Package Manager. Switched to using it. 
- Added a Canvas, Panel, a few buttons. 
- I was prompted to add the new InputSystem UI manager, said yes
- Added a cube with a PlayerInput as well (just to simulate a real game) and it also asked me to create an input file so I said yes and left it all as defaults. 
Ran it on the windows machine and i can use left stick to move right between buttons but i can't go back left. 
- Copied ZIP to my mac, opened it, and it's working perfectly with left and right.

**Comment by IsaacInsoll** [comment]
Hi @jechter is there anything else I can do to help diagnose or resolve this issue? I've had a quick look at the xbox files in this project and can't see any obvious error that I could try to fix it.

**Comment by jechter** [comment]
@stefanunity could you check if you can repro this (and create a fogbugz case is appropriate)?

**Comment by stefanunity** [comment]
Made a new case, further investigations tbd
https://issuetracker.unity3d.com/product/unity/issues/guid/1160074/

**Comment by IsaacInsoll** [comment]
> Made a new case, further investigations tbd
> https://issuetracker.unity3d.com/product/unity/issues/guid/1160074/

Thanks Stefan!

**Comment by Luminoth** [comment]
I'm also having the issue with the left stick down not working (up does work, however). I've copied the DefaultInputActions asset to one I can modify and added DPad directions as a composite Vector2 as well and the down works fine with that so it seems like it's something about the stick in that direction specifically.

**Comment by IsaacInsoll** [comment]
> I'm also having the issue with the left stick down not working (up does work, however). I've copied the DefaultInputActions asset to one I can modify and added DPad directions as a composite Vector2 as well and the down works fine with that so it seems like it's something about the stick in that direction specifically.

Hi, could you attach the exact changes you've made? I'd love to just copy that to get me going for now until the issue is actually fixed. 

Thanks

**Comment by Luminoth** [comment]
> > I'm also having the issue with the left stick down not working (up does work, however). I've copied the DefaultInputActions asset to one I can modify and added DPad directions as a composite Vector2 as well and the down works fine with that so it seems like it's something about the stick in that direction specifically.
> 
> Hi, could you attach the exact changes you've made? I'd love to just copy that to get me going for now until the issue is actually fixed.
> 
> Thanks

As best as I can remember the steps were:

- Copy PackageCache\com.unity.inputsystem@0.2.10-preview\InputSystem\Plugins\PlayerInput\DefaultInputActions.inputactions into the project and make it not read-only
- In the UI Action Map of the new asset add another 2D vector Composite under Navigate and assign it the dpad/up, dpad/down, dpad/left, dpad/right paths, making sure to check the Gamepad control scheme checkbox. Basically this should look exactly like the leftStick 2D Vector composite but for the dpad.
- Hook the new input actions up to your UIInputModule Actions Asset in place of the default one

It still has the issue with the left stick, but the dpad should become functional for navigating buttons and what not.

**Comment by JiaUnity** [comment]
Bug is filed and fix is on its way. Closing.
