### ISSUE TITLE
Only able to use a maximum of four XBox controllers at once

### ISSUE THREAD

**Issue by JOrbits** [Unity-Technologies/InputSystem#625]
Hi,

I'm using Unity 2019.1.0f2 and Input Sytem 0.2.10. I tried connecting 5 XBox controllers and a maximum of 4 get detected within Unity, but I was able to use 4 XBox controllers and one PS4 controller successfully. I suspect it's a limitation of XInput, is there a workaround?

**Comment by Rene-Damm** [comment]
This is an unfortunate limitation of XInput. It has a cap on four controllers [hardcoded into the API](https://docs.microsoft.com/en-us/windows/desktop/api/xinput/nf-xinput-xinputgetstate). The PS4 controller is picked up with a different API (HID) which doesn't have the limitation.

Hopefully, in the not too distant future we can unify parts of our implementation between UWP and classic Win32 and move over to using Windows.Gaming.Input which doesn't have this problem. For now, we'll probably have to live with it.

It is technically possible to pick up Xbox controllers on Windows as HID, too, (like the PS4 controller) but the HID driver made the unfortunate choice of combining the gamepad triggers into a single control. So, unfortunately that's not a very usable fallback.
