### ISSUE TITLE
Querying pencil position in editor window doesn't work correctly. 

### ISSUE THREAD

**Issue by H3idi-X** [Unity-Technologies/InputSystem#629]
When we call Pen.current.position.ReadValue() in Editor Window, it returns relative position from GameView. It should return the position relative to the Editor Window.

The attached is the screenshot of the issue. I pointed the red dot position with a pencil.
![image](https://user-images.githubusercontent.com/4477357/58052734-93ff4d00-7b90-11e9-8c3f-06c551ba2c55.png)

The following is a test code.
https://oc.unity3d.com/index.php/s/iLj3Gqrd1lFZh8D

**Comment by JiaUnity** [comment]
Filed: https://issuetracker.unity3d.com/issues/pen-editor-pen-position-is-not-consistent-with-mouse-position-in-custom-editor-window
Closing.
