### ISSUE TITLE
Querying mouse position in Editor Window causes corruption of GameView. 

### ISSUE THREAD

**Issue by H3idi-X** [Unity-Technologies/InputSystem#630]
When we call Mouse.current.position.ReadValue() in Editor Window, it causes GameView screen curruption. The attached is the screenshot of the issue.
![image](https://user-images.githubusercontent.com/4477357/58053215-d4ab9600-7b91-11e9-8054-b3dcf5c01799.png)

The following is a test code.
https://oc.unity3d.com/index.php/s/sNJPJXIl5KwL9zV

**Comment by JiaUnity** [comment]
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1157144/
Closing.
