### ISSUE TITLE
[TOUCH][RANDOM] released touch, the touch is always press

### ISSUE THREAD

**Issue by mrdev023** [Unity-Technologies/InputSystem#644]
When i touch screen with multi finger and i release. Randomly, application keep finger pressed. But when i touch screen, this finger is released and when i released again, The finger is press again.

**Comment by JiaUnity** [comment]
The touch is under development. Will check this once update is out.

**Comment by mrdev023** [comment]
When will the release be ready?
 It's urgent.

**Comment by JiaUnity** [comment]
If it is urgernt, the release probably won't be able to make it. It needs at least another 2-3 weeks. 
You can try the Develop branch on this github. It is the non-broken branch devs actively working on. 
If this doesn't work, it may be the best to use the old input instead.

**Comment by mrdev023** [comment]
It's resolve in 3.1.0
