### ISSUE TITLE
[0.2.6]->[0.2.10] How to access InputActions after upgrading? [inputActions no longer Serializable]

### ISSUE THREAD

**Issue by eblabs** [Unity-Technologies/InputSystem#652]
Hi,
I just upgraded from [0.2.6] and it seems like its no longer possible to drag the ##.inputActions file from the project into a field in the inspector. Are .inputAction files no longer a serializable type?

How is this now handled?

![image](https://user-images.githubusercontent.com/5941510/58682497-a06c6e00-8325-11e9-963b-3ddb3e208d41.png)

![image](https://user-images.githubusercontent.com/5941510/58682599-17096b80-8326-11e9-85fa-41417ba21667.png)

Here is a screengrab from the inspector with v0.2.6:
![image](https://user-images.githubusercontent.com/5941510/58682942-5dab9580-8327-11e9-8ce9-3ca9d8afa0ad.png)

Thanks for any ideas!

**Comment by eblabs** [comment]
Just doing some additional digging, it looks like the type of script auto generated has changed:
![image](https://user-images.githubusercontent.com/5941510/58683283-c7786f00-8328-11e9-8b8c-474f18349c11.png)
Still not any closer to figuring this out...

**Comment by Wokarol** [comment]
I figured it out. You don't have to do this because asset is just a template. You can just do 
```cs
controls = new InputControls();
```

**Comment by eblabs** [comment]
Hi, thanks @Wokarol. 

I did notice that method in the new examples. Although I have several game objects that need to reference the same controller and it doesn't make sense to create a new instance everytime its needed, and Id prefer not to manage assigning it manually in every case.

Up until 0.2.8, this was working. Actually the way it was working was very similar to the Scriptable Object workflow, of having an asset that you can simply drag into a slot in the inspector. Is there anyway we can get this working again?

Thanks!

**Comment by Wokarol** [comment]
Only way I can think of is using lightweight pattern and create some class that will just create instance. That way you will just do something like `InputControlsUtils.Instance`, you can use extensions method to do `InputControls.Instance()`

**Comment by eblabs** [comment]
Thanks @Wokarol. Yes, for sure, I could do a singleton pattern. Although there are some great benefits to using a ScriptableObjects-type workflow that allows for better interchangeability/hot-swapping and asset based management. 

Hi @Rene-Damm, do you have any thoughts on the change from "InputActionAssetReference" to  "inputActionCollection"? We seemed to have lost the ability to drag the inputActions asset into a slot in the inspector (similar to how Scriptable Objects work). I noticed you might be involved in this one.

Thanks!!

**Comment by Wokarol** [comment]
You can use ScriptableObjects to hold input actions, it's like any other class. It's better that way because before you had only one ScriptableObject in assets folder anyways (It would break otherwise), so hot swapping wasn't possible.

**Comment by eblabs** [comment]
A gif of the previous behavior, no longer possible.
![AssignInputActionAsset](https://user-images.githubusercontent.com/5941510/58744771-d714b800-83fb-11e9-8c7d-b0ca9bcc03f1.gif)

@Wokarol, Sorry I don't follow, would you mind illustrating your example. One of the problems is that its no longer possible to display a field for the controller in the inspector. So I'm not sure how using an additional ScriptableObject would be any different. Thanks!

**Comment by Wokarol** [comment]
@eblabs // In previous version you had InputControls asset, but you were had to have **only one** InputControls asset. So there was not a single benefit from that.
Now you can do script like that:
```cs
using UnityEngine;

[CreateAssetMenu]
public class InputControlsReference : ScriptableObject {
   public readonly InputControls Value = new InputControls();
}
```
(should work, but keep in mind I typed this on phone)
Then just do InputControlsReference field in script

**Comment by eblabs** [comment]
Hi @Wokarol, 

Thanks again for your reply. Just to give you the backstory, in my case, I have multiple scripts that are referencing the same InputControls asset. That's why there was such a benefit in this workflow. I haven't gotten into hot swapping yet...

I'll give your idea it a try. This could mimic the workflow possible previously, unfortunately it adds an additional wrapper level and I'd need to manage an additional asset. But it's a good possible work around, Ill let you know how it goes.

I'd also love to hear from the developers on this as to what their design intent was or if they had considered this issue.

Thanks everyone!!

**Comment by eblabs** [comment]
Hi @Wokarol, here's what ended up working. Thanks for the suggestion!

Ill leave this open for the developers to respond.

Thanks everyone!

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(menuName = "MyGame/Controls/InputControlTemplateSO")]
public class InputControlsTemplate : ScriptableObject
{
    public InputControls instance;
    public void OnEnable()
    {
        instance = new InputControls();
        Debug.Log("Creating New InputControl Instance, yay!");
    }
}
```
