### ISSUE TITLE
C# script is in wrong folder

### ISSUE THREAD

**Issue by Wokarol** [Unity-Technologies/InputSystem#653]
C# Class File on ActionMap has "Assets.." in front of it, and because of that it creates Assets folder inside normal assets folder
![image](https://user-images.githubusercontent.com/38141841/58722228-39a78d00-83d7-11e9-8e43-84ce2e6dc4de.png)

**Comment by Wokarol** [comment]
![image](https://user-images.githubusercontent.com/38141841/58722216-30b6bb80-83d7-11e9-9e94-cccbc57811a3.png)

**Comment by eblabs** [comment]
https://github.com/Unity-Technologies/InputSystem/issues/535
https://fogbugz.unity3d.com/f/cases/1145602/ 
^^ Also mentioned here.

**Comment by Wokarol** [comment]
Oh, I searched for that and not noticed that one
