### ISSUE TITLE
Coop controls with schemes

### ISSUE THREAD

**Issue by Wokarol** [Unity-Technologies/InputSystem#654]
Is there a way to do it cleaner?
https://gist.github.com/Wokarol/d2fccafb7df0c1aa8e335a45e3bffe63 
It creates new user with assigned device and control scheme everytime "Act" has been pressed

**Comment by JiaUnity** [comment]
Please try the forum: https://forum.unity.com/forums/new-input-system.103/
The community may be able to help more.
