### ISSUE TITLE
Not able to disable Physics 2D Unity module

### ISSUE THREAD

**Issue by CarpetHead** [Unity-Technologies/InputSystem#661]
TrackedDeviceRaycaster.cs has a dependency on Physics2D, but the entire rest of our project does not - it would be great to totally strip out Physics2D

**Comment by Rene-Damm** [comment]
Indeed, these should be #if'd. Added a ticket ([1191392](https://issuetracker.unity3d.com/product/unity/issues/guid/1191392/)).

We're in the process of migrating all our bugtracking to FogBugz and standard Unity bug reporter procedures. So, I'll go close this one out here. But no worries, doesn't mean it's forgotten. We're just consolidating all the info we have.
