### ISSUE TITLE
Bad axis center values -1 1

### ISSUE THREAD

**Issue by DFlame69** [Unity-Technologies/InputSystem#664]
I'm getting an X and Rz range value where centered is either -1 or 1. Then when moving the stick it will iterate to 0. So the Input system is outputting 1 and -1 for center and 0 at the extents.
The Y seems to correctly range from -1, 0, 1.

On my Logitech G13, in joystick mode. the /stick/xy is correct, but is there another set of /xy that is also doing the -1 1 center thing.

Microsoft Siderwinder Force Feedback 2 Joystick
VID 0x45E, PID 0x1B, 0x30 (X) Logical Min, Max -512, 511 Physical 0, 1023 -- 0x31 (Y) Logical Min, Max -512, 512  Physical 0, 1023 -- 0x35 (Rz) Logical -32, 31 Physical 0, 63

Logitech G13, listed as ''
VID 0x46D, PID 0xC2AB, 0x30 (X) Logical Min, Max -127, 127 Physical 0, 65535 -- 0x31 (Y) Logical Min, Max -127, 127 Physical 0, 65535

Windows 10 64bit
Unity Input System v0.2.10

**Comment by JiaUnity** [comment]
If it is a joystick instead of gamepad/controller, it is not yet supported.
~~But it will be once we are out of preview for 1.0 release.~~
Not the case. Will be supported in future release.
