### ISSUE TITLE
[0.2.10] API Changed Issue

### ISSUE THREAD

**Issue by SardineFish** [Unity-Technologies/InputSystem#666]
After upgrade from inputsystem@0.2.1 with Unity 2018.3.12f1 to inputsystem@0.2.10 with Unity 2019.1.4f1, my project failed to compile due to the API changes in InputSystem.
The code which was generated from InputAssets failed to compile since class `InputActionAssetReference` no longer exiests, BUT it cannot regenerate due to the compiling failure. So it goes into a infinite loop :(

If possible, please leave a change log in the repo of InputSystem, and mark discarded API as `[Deprecated]` without directly delete it :)

**Comment by Rene-Damm** [comment]
During the preview cycle, we allowed ourselves to be a bit more liberal with breaking APIs as carrying APIs forward during development inflicts a good amount of pain. However, going forward, I expect we'll invest more effort into easing migration between versions.
