### ISSUE TITLE
[macOS][X360] Gamepad buttons are always pressed

### ISSUE THREAD

**Issue by fabiopicchi** [Unity-Technologies/InputSystem#670]
My setup is a macbook Air with a wired Xbox 360 gamepad connected to it (using [this driver](https://github.com/360Controller/360Controller)).

When running the game inside the Editor or when building a player with Mono, everything works as intended. However, when building with **IL2CPP**, for the following buttons the property `isPressed` is always `true`:
* DPad (all directions)
* North
* Select

Please note that I am using raw input reading here so this state comes directly from `Gamepad.current[GamepadButton.North].isPressed`

**Comment by JiaUnity** [comment]
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1162935/
Closing.
