### ISSUE TITLE
Add a way to generate a C# class in a path relative to its input actions asset

### ISSUE THREAD

**Issue by Ramobo** [Unity-Technologies/InputSystem#671]
Right now, the only way that I could find of generating a C# class in a folder outside of the assets folder ~~--~~ packages, in this case ~~--~~ is by providing an absolute path, which won't work unless the package user has their project in the exact same folder as you.

**Comment by JiaUnity** [comment]
Hey. There is really no good reason to not put the generated C# class from InputAsset within the Assets folder. 
Please let us know the reason for it, if you'd like us to change current design.

**Comment by JiaUnity** [comment]
There is really no good reason to store generated C# class outside Assets folder. 
Please let us know the reason behind it, so we can evaluate a design change.

**Comment by Ramobo** [comment]
As I mentioned, this can be used for packages. You could generate it in the assets folder and then move it to your package folder, but it's a nice quality of life feature to have the possibility to generate it in a path relative to the input actions asset.

**Comment by Rene-Damm** [comment]
Oh right, packages. Yeah, agree it should handle that and default to just placing it alongside the .inputactions file wherever it is.

Not a fix but relative paths should still work ("../Packages/.."). Minus the bug on Windows where it does "Assets/Assets" (will be fixed in next package).

**Comment by Ramobo** [comment]
I did try relative paths before, which didn't work. I tried it again now with "../Scripts/Input.cs" and "/../Scripts/Input.cs", neither of which are working. The file just doesn't generate. No errors.

**Comment by Ramobo** [comment]
I just realized that using a relative path like above caused the script to be generated at "C:\Scripts\Input.cs".

**Comment by Rene-Damm** [comment]
Should be addressed in https://github.com/Unity-Technologies/InputSystem/pull/722. Starting the path with either `./` or `../` (backslashes are fine, too) will make it relative to the location of the .inputactions file.

**Comment by Ramobo** [comment]
I can confirm that it's working in 0.9.0-preview.
