### ISSUE TITLE
Dualshock 4 controller not working on android

### ISSUE THREAD

**Issue by JustGamingLTD** [Unity-Technologies/InputSystem#674]
When using a dualshock 4 controller on android (either via bluetooth or via usb) the input mapping is totally wrong. Switching all the inputs to the AndroidGamepadDualshock also doesn't help, any ideas?

**Comment by fabiopicchi** [comment]
Probably a duplicate of https://github.com/Unity-Technologies/InputSystem/issues/656

**Comment by JustGamingLTD** [comment]
Kinda, 

> Probably a duplicate of #656

Kinde, but that one was just referring to Bluetooth and this issue is also for via USB

**Comment by JiaUnity** [comment]
Hey, can you tell us the model of your device? Thanks!

**Comment by JustGamingLTD** [comment]
Hi, I'm using a Huawei mate 20

**Comment by Rene-Damm** [comment]
Fixed AFAIK. @JustGamingLTD if this is still in issue, could you file a ticket through the Unity bug reporter?
