### ISSUE TITLE
NullReferenceException in Input Editor Settings Repaint()

### ISSUE THREAD

**Issue by Kleptine** [Unity-Technologies/InputSystem#681]
If I have the Editor Preferences window open, and I exit play mode, I get the following NullReferenceException. It's is 100% reliable in my project, but only happens if the Editor Preferences window is already open (I usually have it docked).

```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.SettingsProvider.Repaint () (at C:/buildslave/unity/build/Editor/Mono/Settings/SettingsProvider.cs:123)
UnityEngine.Experimental.Input.Editor.InputSettingsProvider.OnSettingsChange () (at C:/FastProjects/Clockwork/InputSystem/Packages/com.unity.inputsystem/InputSystem/Editor/Settings/InputSettingsProvider.cs:295)
UnityEngine.Experimental.Input.InputManager.ApplySettings () (at C:/FastProjects/Clockwork/InputSystem/Packages/com.unity.inputsystem/InputSystem/InputManager.cs:2202)
UnityEngine.Experimental.Input.InputSettings.OnChange () (at C:/FastProjects/Clockwork/InputSystem/Packages/com.unity.inputsystem/InputSystem/InputSettings.cs:302)
UnityEngine.Experimental.Input.InputSystem.OnPlayModeChange (UnityEditor.PlayModeStateChange change) (at C:/FastProjects/Clockwork/InputSystem/Packages/com.unity.inputsystem/InputSystem/InputSystem.cs:1681)
UnityEditor.EditorApplication.Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange state) (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:302)
```

Unity version: 2019.1.1f1
InputSystem version: stable branch, commit 289025f5a09aa71af96625056b47807ae36ad773

**Comment by Racot007** [comment]
Unity v2019.1.7 Input system v0.2.10
Same error BUT other callstack.
Reproduced after modify any asset (create, rename).

> `NullReferenceException: Object reference not set to an instance of an object
> UnityEditor.SettingsProvider.Repaint () (at C:/buildslave/unity/build/Editor/Mono/Settings/SettingsProvider.cs:123)
> UnityEngine.InputSystem.Editor.InputSettingsProvider.ForceReload () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Editor/Settings/InputSettingsProvider.cs:351)
> UnityEngine.InputSystem.InputSystem.OnProjectChange () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/InputSystem.cs:1692)
> UnityEditor.EditorApplication.Internal_CallProjectHasChanged () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:242)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
> `

**Comment by JiaUnity** [comment]
Huh, weird.
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1164144/
Closing.

**Comment by Kleptine** [comment]
Thanks for the filing! Should I expect to be able to visit that link, or is it Unity internal?

**Comment by JiaUnity** [comment]
Nah. It is the public tracking. 
Usually the server needs some time to update the public side. Should be there tomorrow for sure.
