### ISSUE TITLE
Thrustmaster HOTAS input not working

### ISSUE THREAD

**Issue by tkideneB** [Unity-Technologies/InputSystem#682]
Unity 2019.3.0a5
Input System 0.2.10

I tried using the Thrustmaster HOTAS (both throttle and joystick) but no axis and no button seems to work. They are detected through the **Binding -> Path -> Listener**. I tested my system with keyboard input and it functioned. 

I only have this joystick / HOTAS so it might be a joystick related error.

**Comment by JiaUnity** [comment]
Unfortunately, joysticks are not yet supported on current ISX.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
