### ISSUE TITLE
XRControllerWithRumble.SendImpulse() blocks for the entire impulse time.

### ISSUE THREAD

**Issue by Kleptine** [Unity-Technologies/InputSystem#683]
![image](https://user-images.githubusercontent.com/1078792/59707491-97015380-91b7-11e9-8b7c-1cd872146be0.png)

I'm not entirely sure if this is a bug, or an underlying issue with the Oculus SDK, but if I trigger a 100ms impulse through the XRControllerWithRumble.SendImpulse function, the code hangs and blocks until that impulse is finished.

Even if the impulse is small, there should be no reason to block!

**Comment by Kleptine** [comment]
Oculus Rift Touch Controller, 2019.1.1f1, latest InputSystem stable branch.

**Comment by jackpr-unity** [comment]
Hi Kleptine,

I cannot reproduce what you are seeing.  This repository has a XR Haptics test located at \Assets\QA\Tests\XRHaptics\XRHaptics.unity.  Please let me know if you can reproduce it there.

**Comment by Kleptine** [comment]
Hi Jack, 

I'll take a look again and see if I can get a repro -- I'm on the develop branch, now, as well, so perhaps it's fixed.

**Comment by Kleptine** [comment]
Cannot repro anymore, so assuming fixed! Thanks!
