### ISSUE TITLE
NullReferenceException UnityEditor.SettingsProvider.Repaint [Input System + Quick Search]

### ISSUE THREAD

**Issue by Racot007** [Unity-Technologies/InputSystem#690]
Unity v2019.1.8f1 Input system v0.2.10

Quickest way to reproduce this in a fresh project is to install Input System along with Quick Search, then drag and drop an empty GO from Hierarchy to Project Window (attempting to create a prefab).

Hot Fixed after recompile scripts (for example reimport script with RMB menu).
Issue is appear with Input system v0.2.10 package

NullReferenceException: Object reference not set to an instance of an object UnityEditor.SettingsProvider.Repaint () (at C:/buildslave/unity/build/Editor/Mono/Settings/SettingsProvider.cs:123) UnityEngine.InputSystem.Editor.InputSettingsProvider.ForceReload () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Editor/Settings/InputSettingsProvider.cs:351) UnityEngine.InputSystem.InputSystem.OnProjectChange () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/InputSystem.cs:1692) UnityEditor.EditorApplication.Internal_CallProjectHasChanged () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:242) UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by JiaUnity** [comment]
Issue for two Unity packages? ~Fight! Fight! Fight!~ I mean, fix, fix, fix.
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1166784/
Closing.

**Comment by tettogreen** [comment]
It's 16 days after the issue fix already and still no update. It's a major severity issue because it passively breaks Project view, preventing it from repainting the file hierarchy each time a new file is created or added, please release a new version of the package with the bugfix.
