### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by SnugglePilot** [Unity-Technologies/InputSystem#691]
The documentation linked to in readme.md is missing. I have no idea how to get started using the package!

**Comment by SKroell** [comment]
Looks like the file was renamed without updating the README, the renamed file can be found here https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/Documentation~/TableOfContents.md

**Comment by Rene-Damm** [comment]
Good catch. We missed updating that after a recent change to the doc structure. Fixed in #722.
