### ISSUE TITLE
[Linux] [Editor] No keyboard event work

### ISSUE THREAD

**Issue by mrdev023** [Unity-Technologies/InputSystem#693]
Unity 2019.3.0a6
InputSystem 0.2.10-preview
Kernel : 4.19.49-1-MANJARO
Manjaro : 18.0.4
Deepin Desktop : 15.10.2

I'm try to press key but doesn't work but on Mac and Windows project work perfectly. I'm check all settings but is good.

**Comment by JiaUnity** [comment]
It seems keyboard does not work for ISX when Input Handling is set to "both", but when set to Input System (preview), it does seem to work for me.
A friendly reminder, Unity only officially support Ubuntu 16 & 18 and CentOS.

**Comment by JiaUnity** [comment]
Filed: https://issuetracker.unity3d.com/product/unity/issues/guid/1167013/
Closing.
