### ISSUE TITLE
[android] Cant add devices from native 

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#694]
While adding devices from native land (Android Mono ARM7) getting this
`
2019/06/27 16:53:31.850 26880 26922 Error Unity: Could not create a device for 'sec_virtual-e-pen (Android)' (exception: System.NullReferenceException: Object reference not set to an instance of an object
2019/06/27 16:53:31.850 26880 26922 Error Unity: at UnityEngine.InputSystem.LowLevel.InputStateBlock.Write (System.Void* statePtr, UnityEngine.InputSystem.Utilities.PrimitiveValue value) [0x000cf] in D:\Projects\InputSystem\Packages\com.unity.inputsystem\InputSystem\State\InputStateBlock.cs:386 
2019/06/27 16:53:31.850 26880 26922 Error Unity: at UnityEngine.InputSystem.InputManager.InitializeDefaultState (UnityEngine.InputSystem.InputDevice device) [0x00070] in D:\Projects\InputSystem\Packages\com.unity.inputsystem\InputSystem\InputManager.cs:1838 
2019/06/27 16:53:31.850 26880 26922 Error Unity: at UnityEngine.InputSystem.InputManager.AddDevice (UnityEngine.InputSystem.InputDevice device) [0x0009c] in D:\Projects\InputSystem\Packages\com.unity.inputsystem\InputSystem\InputManager.cs:975 
2019/06/27 16:53:31.850 26880 26922 Error Unity: at UnityEngine.InputSystem.InputManager.AddDevice (UnityEngine.InputSystem.Utilities.InternedString layout, System.Int32 deviceId, UnityEngine.InputSystem.Layouts.InputDeviceDescription deviceDescription, 
`
I think it's not really a null reference exception, most likely an alignment issue. But can't test on ARM64, due il2cpp error 
`
Failed running D:\Projects\input-new-android\build\WindowsEditor\Data\il2cpp\build/UnityLinker.exe -out=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed/tempStrip -x=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed/../platform_native_link.xml -x=C:/Users/tomas/AppData/Local/Temp/tmp466ddf5d.tmp -x=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed/TypesInScenes.xml -d=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed --include-unity-root-assembly=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed/Assembly-CSharp.dll --include-unity-root-assembly=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed/Unity.InputSystem.dll --dotnetruntime=il2cpp --dotnetprofile=unityaot --use-editor-options --include-directory=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed --editor-settings-flag=Development --rule-set=Conservative --editor-data-file=D:/Projects/InputSystemPlayground/Temp/StagingArea/assets/bin/Data/Managed/EditorToUnityLinkerData.json --platform=Android --architecture=ARM64 --enable-engine-module-stripping --engine-stripping-flag=EnableUnityConnect --engine-stripping-flag=EnableCrashReporting --engine-modules-asset-file=D:/Projects/input-new-android/build/AndroidPlayer/Whitelists/../modules.asset

stdout:
Fatal error in Unity CIL Linker
System.InvalidOperationException: Failed to resolve type for type in scene information : [Unity.InputSystem.dll] UnityEngine.InputSystem.InputSystemObject
   at Unity.Linker.EngineStripping.EngineStrippingAnnotations.AddTypeInScene(TypeInSceneData typeInSceneData)
   at Unity.Linker.Steps.InitializeEngineStrippingStep.LoadEditorData(UnityLinkContext context)
   at Unity.Linker.Steps.InitializeEngineStrippingStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Unity.Linker.UnityDriver.Run()
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling()
   at Unity.Linker.UnityDriver.RunDriver()
stderr:

`

**Comment by mrdev023** [comment]
Bug is encountered also on IOS

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
