### ISSUE TITLE
Input Debugger does not re-connect properly

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#70]
1. Connect a remote player
2. Disconnect the player in the profile by switching to the editor
3. The remote player's device disappear
4. Switch back to the player in the profiler
5. The remote player's devices do not reappear

**Comment by douglas-piconi** [comment]
taking a look.  was able to repro 100%

**Comment by JiaUnity** [comment]
Verified fix on Trunk 2019.2.0a8. Close.
