### ISSUE TITLE
No more UnityEngine.Experimental.Input;

### ISSUE THREAD

**Issue by AHSUnityDev** [Unity-Technologies/InputSystem#704]
I really don't know what I'm doing and every video I have seen so far has had "using UnityEngine.Experimental.Input" in there using area, but I don't have that showing up. Now they could have updated it to some other using but I wouldn't know that if they did. If anyone could help me It would be appreciated

**Comment by Regday** [comment]
Just use UnityEngine.InputSystem

**Comment by AHSUnityDev** [comment]
Thank you that worked!
