### ISSUE TITLE
Develop branch uses 2018.2a8 and cant be tested by any users as result

### ISSUE THREAD

**Issue by isurfraz** [Unity-Technologies/InputSystem#71]
Please dont commit using versions of unity users cannot get to, otherwise there is no point this being on github.

recommit a version using 2017.4.1 or the latest **accessible** beta

**Comment by Rene-Damm** [comment]
2018.2 beta will be available soon.

**Comment by isurfraz** [comment]
okay thanks for the speedy reply. We are very interested in using this for R&D for projects moving forward so keen to get early as possible access.

**Comment by Rene-Damm** [comment]
We'll post an update as soon as it's possible to run the develop branch. Wasn't intended to be such a long delay between the preview build and the next usable build but the beta hit some delays. Sorry for the inconvenience and thanks for the interest :)

**Comment by Rene-Damm** [comment]
Hey @isurfraz, you can now download the first 2018.2 beta at  https://unity3d.com/unity/beta-download. For more details, see https://forum.unity.com/threads/input-system-update.508660/page-4#post-3466745.

**Comment by isurfraz** [comment]
Many Thanks for updating me on this!
