### ISSUE TITLE
Can't find a way to bind UI actions

### ISSUE THREAD

**Issue by kakysha** [Unity-Technologies/InputSystem#712]
Trying to solve basic problem of implementing a Pause menu in my game, targeting touch, kb/mouse and gamepad platforms.

I have a "pause" button on my screen for touch/mouse input. I suppose I have to somehow configure `InputSystemUIInputModule` of my `EventSystem` object for UI clicks to work on this button. 
Also, I have one big input action looking like this:
![image](https://user-images.githubusercontent.com/822721/60736654-5dbf3680-9f60-11e9-8227-41ea7bccaa24.png)

![image](https://user-images.githubusercontent.com/822721/60736662-64e64480-9f60-11e9-9ea7-7a9d106244a4.png)
with two actin maps for player and for hud controls.

Player controls are working perfectly, with PlayerInput component on my Player object with scripts handling messages from it. I just chose `playercontrols` as default action map and thats it.

Now, problem arises for my pause menu. I want it to be invoked by pressing ESC button throughout the game, by clicking pause button on my screen using mouse/touch or by pressing 'start' button on gamepads. For it I configured `hudcontrols` action map with those bindings (look at screenshot). Now I can't figure out how to make my UI pause button to work.

Here is the screenshot of my EvenSystem:
![image](https://user-images.githubusercontent.com/822721/60736858-31f08080-9f61-11e9-8494-4ef83b45e738.png)

Main question is: how to make UI pause button work along with keyboard/ESC and gamepad/start buttons? Should I add another `PlayerInput` to, e.g. Camera which will handle `hudcontrols` action map for kb/gamepad?
Second question: why should I setup bindings again in `InputSystemUIInputModule` (`Cancel` in my case), if I already bound buttons to pause action through actions asset? 
Third question: why is there an `UI Input Module` field on Player Input component?

**Comment by JamhammerRob** [comment]
@kakysha I found that if you put your OnPause wherever your other callbacks are, it calls the UI one also. 

![image](https://user-images.githubusercontent.com/12954767/61814596-65af1f80-ae16-11e9-8e17-3d865776d6dd.png)

This is my input asset

![image](https://user-images.githubusercontent.com/12954767/61814620-73fd3b80-ae16-11e9-9d15-4b33939e58f5.png)

This is on my player, which uses the playerinput module, see how OnGoBack is there, under behaviour.

**Comment by DataGreed** [comment]
So how do you listen to Pause button on other objects that do not have PlayerInput component attached?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
