### ISSUE TITLE
HoldAndRelease ?

### ISSUE THREAD

**Issue by gotenxds** [Unity-Technologies/InputSystem#713]
Hello, I'm trying to implement some kind of a combo system where 2 taps and then tap/hold can make a 3 hit combo

tap -> tap -> tap  == 3hit combo
tap -> tap -> hold  == 3hit combo with strong attack at the end.
This works fine with how the current hold interaction works.
What I want to add is someway of knowing if hold action ended early and thus run the animation faster and make a weaker hit

Currently we can only set hold time, so hold time = 0.2

start will fire for both hold and tap
preformed will fire for tap pretty much instantly if button in not held
preformed will fire for hold after 0.2 seconds
cancel will fire for hold only if released before 0.2 seconds.

I cant know when is the button released, I only know that it was held for at least 0.2 seconds.

There are workarounds for this, I cant create timers and do my own logic, but I think the input system should allow something more suitable for this as I think it'l be a common use case.
Making the cancel event fire on release (which is what I expected tbh) would be one way of doing this.

Currently hold `started` event gets fired not matter what and just get `canceled` instantly if released.
Instead I think we should be able to set how long until started `minHoldTime`
so lets say `minHoldTime = 0.2`
after 0.2s `started` event gets fired as the hold interaction just started (after the defined time)
`canceled` should be fired when the button is released.
I dont see a good usage for the `preformed` event as this is preformed as long at the button is pressed just like the name "hold" suggests.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
