### ISSUE TITLE
[Linux] SwitchProControllerHIDInputState could not be found

### ISSUE THREAD

**Issue by JeromyStroh** [Unity-Technologies/InputSystem#715]
On the develop branch I'm getting the following error on Linux:

`Packages/com.unity.inputsystem/InputSystem/Plugins/Switch/NPad.cs(768,44): error CS0246: The type or namespace name 'SwitchProControllerHIDInputState' could not be found (are you missing a using directive or an assembly reference?)`

This is due to:
`#if UNITY_EDITOR || UNITY_STANDALONE_OSX || UNITY_STANDALONE_WIN || UNITY_WSA`

Should just be UNITY_STANDALONE instead of UNITY_STANDALONE_OSX | UNITY_STANDALONE_WIN.

**Comment by stefanunity** [comment]
I can reproduce this and we're not tracking it at https://issuetracker.unity3d.com/product/unity/issues/guid/1174452/
