### ISSUE TITLE
InvalidOperationException during event processing of Fixed update; resetting event buffer

### ISSUE THREAD

**Issue by insanepure** [Unity-Technologies/InputSystem#717]
Hey,

I'm getting this error while rapidly assigning and unassigning a player (which happens in a player selection screen).

You can see this in the video I made at the end (~ 5-10 minutes before the end). https://www.youtube.com/watch?v=pxqbyDos-yQ

Callstack is
InvalidOperationException during event processing of Fixed update; resetting event buffer
0x00007FF62E78FBAC (Unity) StackWalker::GetCurrentCallstack
0x00007FF62E793011 (Unity) StackWalker::ShowCallstack
0x00007FF62CFC6DE5 (Unity) GetStacktrace
0x00007FF62F3BF750 (Unity) DebugStringToFile
0x00007FF62E7C77D7 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000012061B6959B (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000012061B6945B (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x0000012061B68AF1 (Mono JIT Code) [Logger.cs:61] UnityEngine.Logger:Log (UnityEngine.LogType,object) 
0x0000012061B6875D (Mono JIT Code) [Debug.bindings.cs:127] UnityEngine.Debug:LogError (object) 
0x00000120064ACBDB (Mono JIT Code) [NativeInputRuntime.cs:63] UnityEngine.InputSystem.LowLevel.NativeInputRuntime/<>c__DisplayClass6_0:<set_onUpdate>b__0 (UnityEngineInternal.Input.NativeInputUpdateType,UnityEngineInternal.Input.NativeInputEventBuffer*) 
0x00000120064AC417 (Mono JIT Code) [Input.cs:121] UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate (UnityEngineInternal.Input.NativeInputUpdateType,intptr) 
0x00000120064AC613 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_int_intptr (object,intptr,intptr,intptr)
0x00007FFF1F8CBC80 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FFF1F851D92 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FFF1F85AD8F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF62E715931 (Unity) scripting_method_invoke
0x00007FF62E70F7AF (Unity) ScriptingInvocation::Invoke
0x00007FF62E7095F5 (Unity) ScriptingInvocation::Invoke<void>
0x00007FF62BB65861 (Unity) ScriptingInvocation::Invoke<void>
0x00007FF62BBBF6E0 (Unity) Scripting::UnityEngineInternal::Input::NativeInputSystemProxy::NotifyUpdate
0x00007FF62C06B714 (Unity) SendInputEventsToScript
0x00007FF62C05D2EF (Unity) `InternalInitializeModule_Input'::`2'::FixedUpdateNewInputFixedUpdateRegistrator::Forward
0x00007FF62E1CEB57 (Unity) ExecutePlayerLoop
0x00007FF62E1CECA0 (Unity) ExecutePlayerLoop
0x00007FF62E1D3E82 (Unity) PlayerLoop
0x00007FF62C6F05AB (Unity) PlayerLoopController::UpdateScene
0x00007FF62C6EE2F4 (Unity) Application::TickTimer
0x00007FF62CFE987D (Unity) MainMessageLoop
0x00007FF62CFF0C98 (Unity) WinMain
0x00007FF62FD6FFA2 (Unity) __scrt_common_main_seh
0x00007FFF54624034 (KERNEL32) BaseThreadInitThunk
0x00007FFF57023691 (ntdll) RtlUserThreadStart

I'm also getting another error together with this:

InvalidOperationException: Handle is not allocated

InvalidOperationException: Handle is not allocated
System.Runtime.InteropServices.GCHandle.get_Target () (at <a8ed250850854b439cedc18931a314fe>:0)
UnityEngine.InputSystem.InputActionState.CompactGlobalList () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Actions/InputActionState.cs:3149)
UnityEngine.InputSystem.InputActionState.AddToGlobaList () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Actions/InputActionState.cs:3123)
UnityEngine.InputSystem.InputActionState.Initialize (UnityEngine.InputSystem.InputBindingResolver resolver) (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Actions/InputActionState.cs:129)
UnityEngine.InputSystem.InputActionMap.ResolveBindings () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Actions/InputActionMap.cs:857)
UnityEngine.InputSystem.InputActionMap.ResolveBindingsIfNecessary () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Actions/InputActionMap.cs:749)
UnityEngine.InputSystem.InputActionMap.Enable () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Actions/InputActionMap.cs:302)
PlayerComponent.ActivateActionMap (System.String _name) (at Assets/Game/Player/PlayerComponent.cs:55)
PlayerSelectionComponent.OnPlayerAdded (PlayerComponent obj) (at Assets/Game/UI/PlayerSelection/PlayerSelectionComponent.cs:41)
PlayerManager.AddPlayer (UnityEngine.InputSystem.Plugins.Users.InputUser _input) (at Assets/Game/Player/PlayerManager.cs:84)
PlayerManager.OnUnpairedInputDeviceUsed (UnityEngine.InputSystem.InputControl control) (at Assets/Game/Player/PlayerManager.cs:105)
UnityEngine.InputSystem.Plugins.Users.InputUser.OnDeviceChange (UnityEngine.InputSystem.InputDevice device, UnityEngine.InputSystem.InputDeviceChange change) (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Plugins/Users/InputUser.cs:1651)
UnityEngine.InputSystem.InputManager.OnUpdate (UnityEngine.InputSystem.InputUpdateType updateType, UnityEngine.InputSystem.LowLevel.InputEventBuffer& eventBuffer) (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/InputManager.cs:2682)
UnityEngine.InputSystem.LowLevel.NativeInputRuntime+<>c__DisplayClass6_0.<set_onUpdate>b__0 (UnityEngineInternal.Input.NativeInputUpdateType updateType, UnityEngineInternal.Input.NativeInputEventBuffer* eventBufferPtr) (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/NativeInputRuntime.cs:59)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass6_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:120)

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
