### ISSUE TITLE
Provide runtime API/define to see what input system is enabled.

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#724]
Currently from runtime there's no way to tell if new or old system is enabled.

If you're transitioning your application from old system to new system, and have code for both systems, it would be useful to enable/disable those code pieces depending on what system is enabled in PlayerSettings

**Comment by Rene-Damm** [comment]
`#defines` (`ENABLE_INPUT_SYSTEM` and `ENABLE_LEGACY_INPUT_MANAGER`) have been added and backported to 2019.3 and 2019.2.
