### ISSUE TITLE
ButtonControl.wasPressedThisFrame/wasReleasedThisFrame vs Input.GetKeyDown/GetKeyup

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#725]
Heym

ButtonControl.wasPressedThisFrame/wasReleasedThisFrame behaves differently compared to Input.GetKeyDown/GetKeyUp, if key press/release happens in the same frame.

The new input system will return false for those properties, while in old system this will return true for one frame.

In this case, InputActions should be used.

As far as I understood this is by design in the new input system.

Please think about removing these properties, so users can you use InputActions instead. Otherwise there will be constant stream of bugs, while transitioning projects from old input to new, and changing Input.GetKeyDown/GetKeyUp --> Keyboard.current.<key>.wasPressedThisFrame/wasReleasedThisFrame.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
