### ISSUE TITLE
Mouse delta bug

### ISSUE THREAD

**Issue by Lowlet** [Unity-Technologies/InputSystem#727]
Hi. I encounter strange behaviour with mouse delta. Seems like its randomly produce higher values than needs to be. I made this two videos to demonstrate:
OLD INPUT
https://streamable.com/38q6r
NEW INPUT SYSTEM
https://streamable.com/fzm6n
Mouse look code is the same in both cases and this behaviour stays with any sensitivity

**Comment by Sonorpearl** [comment]
Same issue here. More info here:
https://forum.unity.com/threads/mouse-delta-input.646606/

**Comment by Sonorpearl** [comment]
Any updates?

**Comment by Lowlet** [comment]
@Sonorpearl have you tried 0.9.0? Updating to this version has fixed the issue for me.

**Comment by Sonorpearl** [comment]
Still there for me. Already on Version 0.9.0 and 2019.1.11f1.

**Comment by popcron** [comment]
Can you provide info on the two versions to check against? @Lowlet

**Comment by JimmyCushnie** [comment]
Wait, what are you guys talking about with version 0.9.0? The package manager shows 0.3.0 as the latest version for me.
![image](https://user-images.githubusercontent.com/32693298/64405793-192e4500-d04e-11e9-9edc-4d7033b9c64e.png)

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
