### ISSUE TITLE
Input System fails to handle Oculus Touch Controllers on Oculus Quest

### ISSUE THREAD

**Issue by TomasRiker** [Unity-Technologies/InputSystem#730]
I got the Input System working on PC with mouse and keyboard. But when I target Oculus Quest, I can't get any kind of input from the Oculus Touch Controllers, no matter how I try to bind my actions (I tried the obvious choice "OculusTouchController", but also hand-specific variants, normal joystick, Android joystick, gamepad joystick, XR controller, ...). Using the traditional input manager, I have no problem accessing these controllers.

The W, A, S, D controls are working (on PC), the thumbstick isn't (on Oculus Quest):

![image](https://user-images.githubusercontent.com/295205/61387442-698eef00-a8b6-11e9-8633-5fb186e87591.png)

Is this a known bug/limitation, or am I doing something wrong?

**Comment by TomasRiker** [comment]
I got it working now! The path needs to be like `OculusQuestControllerRight/thumbstick`. It doesn't appear in the UI though, so you have to enter it manually by clicking the little button next to the path combo box.

**Comment by smasson99** [comment]
How do you know what to write after **OculusQuestControllerRight/** or **OculusQuestControllerLeft/** ?
It seems like the Oculus Documentation (https://developer.oculus.com/documentation/unity/latest/concepts/unity-ovrinput/) doesn't have a page for the mapping you're using.

Could you please send a screenshot of your bindings? This would really help my project :)

**Comment by TomasRiker** [comment]
I don't remember how I found it. The string "OculusQuest" doesn't even appear anywhere in the Input System's source code. But the `OculusQuestControllerLeft` and `OculusQuestControllerRight` seem to support the same controls as the `OculusTouchController`, which does appear in the UI.

![image](https://user-images.githubusercontent.com/295205/63000961-bee8fc80-be72-11e9-8c37-653220a45a4b.png)

**Comment by yobazar** [comment]
It does not work for me with triggerPressed ... Am I the only one ?
Do you use VIU in your project ?

**Comment by dariol** [comment]
Did this wind up being the Quest android manifest issue? (required entries to support Go apps)

**Comment by JohannesDeml** [comment]
This is still a problem for `preview.1 - 1.0.0`.
I tried using strings for the triggers, but sadly without luck. I tried the following:
* `OculusQuestControllerRight/triggerPressed`
* `<OculusTouchController>{RightHand}/triggerPressed`

As a side note, the suggested path `OculusQuestControllerLeft/thumbstick/X` still works.

Any idea on where I can find a documentation, or if there will be proper Oculus Quest Touch Controller support soon?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

This specific issue is going to be tracked at https://issuetracker.unity3d.com/product/unity/issues/guid/1249047/ in the future.

For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
