### ISSUE TITLE
InputDeviceDescription.deviceClass get empty with Xbox One Controller

### ISSUE THREAD

**Issue by SardineFish** [Unity-Technologies/InputSystem#732]
Got an empty string from device.description.deviceClass with Xbox One controller, which should be "Gamepad"

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
