### ISSUE TITLE
2D Vector composite not working (0.9.0)

### ISSUE THREAD

**Issue by Lucipetus** [Unity-Technologies/InputSystem#735]
A minimal project to reproduce this would be an input actions asset containing a Keyboard scheme and necessarily a Gampad scheme, and a map of an only action with WASD 2d vector and leftStick [Gampad] bindings. 
Now do some WASD-maneuver with the keyboard, you'll see the events (started, performed, canceled) aren't firing as expected (or at all, after a few presses).

This worked at v0.2.10.

-- update --
Actually only one key (any except Up) needs to be pressed. _Canceled_ never fires until game exits.
Tested on 2019.1.0f2 and 2019.1.11f1.

**Comment by ndossche** [comment]
It sounds to me like this is the same thing I recently noticed as well.
I submitted a bug report in Unity and it can be found here: https://issuetracker.unity3d.com/issues/callbackcontext-is-not-called-when-two-buttons-are-pressed-or-released

**Comment by Lucipetus** [comment]
> 
> 
> It sounds to me like this is the same thing I recently noticed as well.
> I submitted a bug report in Unity and it can be found here: https://issuetracker.unity3d.com/issues/callbackcontext-is-not-called-when-two-buttons-are-pressed-or-released

In my case, only one key (any except Up) needs to be pressed. _Canceled_ never fires until game exits.
And WASD works well alone. It only breaks if I add an extra binding (having so far tried leftStick [Gamepad] and ↑←↓→ [Keyboard]).

**Comment by gj52** [comment]
Same with 1D vector,   the value clamped at upper limit and never comes back. Canceled event is never sent. After one key press to go up, the binding is lost.

**Comment by juschu** [comment]
I also noticed this with the 1D vector.
And I managed to reproduce that it's always the first binding in the list that's blocking the whole action. I changed the composite part from positive to negative and vice versa and it was still the first of the two. Then I moved the lower binding to the top and it was still the first one.
It does not depend on positive or negative, w key or s key, but only on the position in the list of the two bindings.

**Comment by juschu** [comment]
I noticed that the action becomes functional again when you disable and then enable the actionmap of that action.
Perhaps this could be a temporary workaround as long as you only need the started callback.

**Comment by juschu** [comment]
It looks like with the 2D vector it's completely the opposite than with the 1D vector. The binding on the top of the list is the only one that won't consistently block the whole action.

**Comment by nicksundermeyer** [comment]
Having this same issue since updating, using 2019.2 and the 0.9.0 Input System. Movement using 2D vectors works once and then stops working completely

**Comment by juschu** [comment]
> Having this same issue since updating, using 2019.2

I already had this problem with 2019.1. I only took a brief look at the InputSystem before 0.9.0 and didn't use composite bindings before.
