### ISSUE TITLE
[0.9.0] Input debugger shows event time of -4293049s 

### ISSUE THREAD

**Issue by SKroell** [Unity-Technologies/InputSystem#737]
On one of my test machine input isn't working, while it works everywhere else. The only anomaly I can find is that the input debugger show the time of the event as being a very large negative value? (See attached screenshot) 

InteractiveRebinding works fine, but no other events are called.
![KeyboardTiming](https://user-images.githubusercontent.com/9059997/61985797-2e559400-b00b-11e9-840e-729a8d813bb3.png)

**Comment by SKroell** [comment]
Upon more investigation this is related to how long the system has been turned on. Rebooting fixes this instantly and keeping the computer running for some time (multiple days) makes the issue return. This breaks input in both editor and build, and does not require the build or the editor to be open.

**Comment by mariandev** [comment]
> Upon more investigation this is related to how long the system has been turned on. Rebooting fixes this instantly and keeping the computer running for some time (multiple days) makes the issue return. This breaks input in both editor and build, and does not require the build or the editor to be open.

If this fix doesn't work for you and you are on Windows you should try disabling the `hybrid boot` option because otherwise the shutdown button will actually do hibernate. I had an uptime of 26 days before disabling it and doing a proper shutdown.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
