### ISSUE TITLE
Ability to specify XInput DeviceSubType for Control Schemes

### ISSUE THREAD

**Issue by mdsitton** [Unity-Technologies/InputSystem#738]
I am a developer of a popular rhythm game Clone Hero, and we are investigating switching to the new input system however we need support for XInput DeviceSubType for ControlSchemes to be able to differentiate the guitar controllers from normal xinput gamepads.

**Comment by Rene-Damm** [comment]
Add this somewhere in your startup (e.g. in some `InitializeOnLoad` code)

```
InputSystem.RegisterLayout(@"
    {
        ""name"" : ""Guitar"",
        ""extend"" : ""XInputControllerWindows"",
        ""device"" : {
            ""interface"" : ""XInput"",
            ""capabilities"" : [ { ""path"" : ""subType"", ""value"" : ""6"" } ]
        }
    }
");
```

This *should* do the trick. There should be a new "Guitar" layout under XInputController in the control picker. Let me know how it goes.
