### ISSUE TITLE
Inconsistency in binding path formating

### ISSUE THREAD

**Issue by juschu** [Unity-Technologies/InputSystem#739]
When you get the path for a binding over `UnityEngine.InputSystem.InputBinding.path` it will look something like `<Mouse>/delta`.
When you get it over `UnityEngine.InputSystem.InputAction.CallbackContext.control.path` it will look something like `/Mouse/delta`.
Those are actually the same paths and I think it would make sense to format them in the same way. That way it would be easier to compare them to each other without regular expressions.

**Comment by Rene-Damm** [comment]
That's intended. `<Mouse>/delta` is sort of like an "abstract" path, akin to a regular expression or a file system path like `C:\*.txt`. At runtime, there may be arbitrary many actual controls that correspond to that path. Just like there may be arbitrary many files matching `C:\*.txt`.

However, `InputControl.path` is a "concrete" path of an actual control. It's like `C:\Notes.txt`. The fact that `/Mouse/delta` looks so close to `<Mouse>/delta` is more incidental. A mouse device could just as well be called "LogitechMXMaster" and then it'd be `/LogitechMXMaster/delta`.

So, it's not so much about formatting than it is about these being two different things.
