### ISSUE TITLE
Input buffer should be flushed when the game starts

### ISSUE THREAD

**Issue by juschu** [Unity-Technologies/InputSystem#740]
If have a small example where I can look around like in an FPS game. When I click the play button in Unity and move the mouse around while unity is still loading the game, all those movements get executed when the game starts. That's not very helpful when you want the player to look in a certain direction when the game starts.

**Comment by Rene-Damm** [comment]
Agree. Annoying behavior.

**Comment by Rene-Damm** [comment]
Migrated to FogBugz as [1191342](https://issuetracker.unity3d.com/product/unity/issues/guid/1191342/).

I'll close this one out here but no worries, not forgotten. We're in the process of migrating all bug tracking over to FogBugz and standard Unity bug reporting/tracking mechanisms.
