### ISSUE TITLE
MyInputActionClass.Enable() enables previously disabled actionmaps

### ISSUE THREAD

**Issue by juschu** [Unity-Technologies/InputSystem#741]
The generated Class of the input asset has an Enable function. Unless I call it I won't get anything from my actions.
It also makes sense to call Enable and Disable on the MyInputActionClass object in MyScript.OnEnable and MyScript.OnDisable, so the whole system gets disabled when I disable my MonoBehaviour with all the callbacks.
However, the function MyInputActionClass.Enable also re-enables all previously disabled action maps. But that's not its job and when I want those actionmaps disabled they should stay disabled until I enable them. To en-/disable action maps those actions maps have their own functions that should be used for that.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
