### ISSUE TITLE
Rift S - can't read controllers Input in Editor play mode

### ISSUE THREAD

**Issue by nukadelic** [Unity-Technologies/InputSystem#743]
I can track the position and rotation of the HMD & the controllers, but i can't get any sort of input from the controllers. Using `TryGetFeatureValue` for both scenarios. The funny part is once building the project into standalone windows executable everything works as expected. It's the editor that fails to register controller inputs. This applied only to UnityXR input system and not the oculus SDK since I can get controller feedback if I would to download the OculusUnitySDK manually both in editor and in build mode using their example scenes. 

I have tried it on multiple unity versions, also did try installing older oculus sdk versions and openVR. But nothing  

`TryGetFeatureValue` with the exception to the position and rotation, the method always returns true for being valid - but the output variables are always equal to default values ( false, 0.0f, Vector2.zero, ... ) 

### Edit
Just found out after covering the brightness sensor, the inputs will start working in edit mode as well. 
I have disassembled my Rift S to make it easier for quick prototyping, seems like my device is going to get some electrical tape on top of the sensor until the issue is resolved.  

P.S. all the inputs that have been made via the controller prior to covering the sensor will be immediately received the moment the controller becomes "reactive" so don't get surprised if you happened to log input changes as it will flood the console. Same thing applies to haptic feedback, any outputs made to the device ( impulse / vibration ) will be executed in the same time. 

**Edit 2**
After any one of the controllers became reactive for the first time ( cover the sensor and activate the screen ), it doesn't meter if you would reconnected the controllers any amount of time, or the brightness sensor lose focus ( blanking out the screen ) - the controllers will always be reactive even tho the HMD screen will be competently blank, or you would reconnect the device while the screen is blank and the inputs would still be captured... very strange, seems like something is preventing partial controller input communication ( since the rotation and position of the device that was accessed via the `TryGetFeatureValue` always worked both for the headset and the controller even before the initial controller input reaction )

**Comment by nukadelic** [comment]
**Update**
Regarding haptics and vibration : after the device became reactive, i could control the impulse force and vibration duration of the haptics. When taking off the headset - unlike the remote controllers, the haptics will not be reactive no matter what while the HMD screen is blank, further more any interrupted impulse message will continue as soon as the HMD is mounted ( covering the sensor )

**Comment by justgos** [comment]
also experiencing this thingy.
Unity 2019.3.0b10

getting only the controller's pose in the editor, but all the buttons are ok on Oculus Quest

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
