### ISSUE TITLE
Hierarchical actionmaps

### ISSUE THREAD

**Issue by juschu** [Unity-Technologies/InputSystem#751]
As far as I understood actionmaps they should be used to differentiate between modes like walking and driving. But some actionmaps could still be subdivided into other actionmaps like driving a car, truck, motorcycle or forklift. Some actions like accelerating or steering would still be the general driving actions but others should be different than in the other driving actionmaps. For example you can't do a wheely with a truck and you can't lift cargo up with a car.

Where would this hierarchy actually change something?
When you disable the parent actionmap the child actionmaps don't get disabled but as long as any parent is disabled they won't fire anything even if they're enabled. Just like child gameobjects get implicitly disabled when a parent gets disabled.

**Comment by Rene-Damm** [comment]
I think there's no set way in which this is best done as a rule. Really depends on the game how to most usefully slice your actions and when to enable and disable specific maps and in what combination.

As a general guideline, I'd say that what makes sense in terms of how you would present the actions to the user in UIs such as for rebinding or control help screens, probably also makes sense for general organization in maps. Could be that for a specific game it really makes most sense to have separate "Forklift" and "MonsterTruck" action maps but for most games it probably doesn't make sense to go that fine-grained.

So, IMO really depends. There's not really anything in the system itself, though, that implements any specific multi-map management scheme.
