### ISSUE TITLE
Actionmap groups where only one can be enabled

### ISSUE THREAD

**Issue by juschu** [Unity-Technologies/InputSystem#752]
The title basically says it all.
In the SteamVR Inputsystem you have the option to disable all other actionsets (they call it sets) when you enable an actionset. That's already useful but I think it could be even better when you can define groups in which only one actionmap can be enabled at a time and not actually all other actionmaps get disabled when you enable it.

**Comment by Rene-Damm** [comment]
Higher-level action management IMO best remains with the game. Could be there's some preset schemes that turn out to be generally useful for PlayerInput to provide at some point but for now, I'd lean towards leaving this within an application's domain. The action system has already evolved into quite the beast as it is :/

**Comment by Rene-Damm** [comment]
Think that for PlayerInput after 1.0, it makes sense to have a look at whether it can be equipped with better means of coordinating things between multiple action maps. Made a note of that.
