### ISSUE TITLE
Can't bind arrow keys on AZERTY keyboard

### ISSUE THREAD

**Issue by Kawottex** [Unity-Technologies/InputSystem#755]
Here's a detailed description of the bug: https://forum.unity.com/threads/cant-bind-arrow-keys-on-azerty-keyboard.711260/

Repro case:

1. Create an InputAction which will listen to any button performed (like in the piece of code written in the forum post).
2. Print the key performed in the callback function (for example: obj.control.ToString())
3. When the game is launched, press an arrow key: the printed key in the callback function is "/Keyboard/printScreen" (for any arrow key).
4. Try to quickly alternate between two different arrow: one print is "/Keyboard/printScreen", the other one print the correct arrow key.

I'm on Windows 10 Pro, Unity version 2019.1.5f1, Input System v0.9.0, AZERTY french keyboard.

Thanks,
Kevin B.

**Comment by Rene-Damm** [comment]
Sounds like one more problem we have with the dreaded PrintScreen key and the RawInput API.

When you go to the input debugger (`Window >> Analysis >> Input Debugger` in the editor main menu), double-click the keyboard device, and then press and hold one of the arrow keys, do *both* the print-screen and the correct arrow key change their value to 1?

**Comment by Kawottex** [comment]
Hello,
When I hold an arrow key in the Input Debugger, the value of printScreen is still to 0 (but the arrow key and anyKey are at 1).

**Comment by Kawottex** [comment]
I've updated the package to version 0.9.6 and it seems to work now.
Thanks for your work !
