### ISSUE TITLE
[0.9.0][Linux] Keyboard input not working unless Input Debugger Window is focused

### ISSUE THREAD

**Issue by dave24BG** [Unity-Technologies/InputSystem#756]
Input System 0.9.0 
Unity 2019.2.0f1
OS: Ubuntu 

No keyboard inputs work, unless the Input Debugger Window is open and in focus. 

Upon losing focus with input debug window, keyboard input stops working. 

Mouse inputs had no issues like this.

**Comment by stefanunity** [comment]
Can you check if you are experiencing this issue: https://issuetracker.unity3d.com/product/unity/issues/guid/1167013/ ?

**Comment by dave24BG** [comment]
Yes, that seems to be it. When I set Active Input Handling to Input System (Preview ) it works. 

It seems that it only breaks when it is on Both. 

I can close this if it is the same issue. Cheers
