### ISSUE TITLE
"Should not get here" spam when switching Input Action Maps

### ISSUE THREAD

**Issue by Chifilly** [Unity-Technologies/InputSystem#757]
I have an issue that when I switch from my `Player` input actions to my `UI` input actions and back again, I get endless spam whenever I move my mouse. 

It's spamming the following error repeatedly:
```
Should not get here
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)
```

This only started happening when I used `InputSystemUIInputModule`, and it causes the editor to slow to a crawl, since it throws an error every frame I move my mouse.

I use the code `inputScript.SwitchCurrentActionMap("UI");` to switch to the `UI` input actions, and then when I go back into play mode I use `inputScript.SwitchCurrentActionMap("Player");`. It's only after I've switched from UI to Player (or to any other input action) that this issue starts.

EDIT:
Just found out that all actions cause the spam, not just the mouse, I just hadn't noticed it before since WASD are an "on-off" system whereas mouse movement is pretty much triggers constantly when moving the mouse

After more testing, it doesn't happen if I start on the UI map, then switch to Player, I can do this as much as I want and it's fine, but if I start on Player then switch to UI then back to Player, the issue happens

**Comment by Rene-Damm** [comment]
Should be fixed in `1.0.0-preview.1` by #883. Some state was set up incorrectly when composites were used and there was more than one map.
