### ISSUE TITLE
`new` modifier on PlayerInput.camera produces a warning at build time

### ISSUE THREAD

**Issue by amechtley** [Unity-Technologies/InputSystem#759]
https://github.com/Unity-Technologies/InputSystem/blob/eb5b812b1324edb8aa51c9d2d7982e5fab1cbe66/Packages/com.unity.inputsystem/InputSystem/Plugins/PlayerInput/PlayerInput.cs#L400

Presumably as a result of build-time stripping, the `new` modifier results in the following warning at build-time:

```
Library\PackageCache\com.unity.inputsystem@0.2.10-preview\InputSystem\Plugins\PlayerInput\PlayerInput.cs(399,27): error CS0109: The member 'PlayerInput.camera' does not hide an accessible member. The new keyword is not required.
```

As such, this file will fail CI for any projects that produce a build when they have warnings-as-errors enabled. See the following log from [Unity Physics CI](https://yamato.prd.cds.internal.unity3d.com/jobs/112-Unity.Physics/tree/loader-controller-navigation/.yamato%252Fupm-ci.yml%2523windows_2019.1_standalone_mono/308125/job) (2019.1 Windows/Mono)

[logs.zip](https://github.com/Unity-Technologies/InputSystem/files/3467246/logs.zip)

If there's not a simple fix here, consider just renaming this member.

**Comment by stefanunity** [comment]
This is now tracked internally. The case will show up at https://issuetracker.unity3d.com/product/unity/issues/guid/1174688/ soon.
