### ISSUE TITLE
Cannot specify directory when setting file name for actions code-behind file

### ISSUE THREAD

**Issue by Rene-Damm** [Unity-Technologies/InputSystem#78]
1. Add a path such as "MyDirectory/MyActions.cs" in the "Wrapper Code Path" field of DemoControls.inputactions
2. Hit apply

Editor throws exceptions.

**Comment by Rene-Damm** [comment]
Also, the path is relative to the project root folder rather than Assets/. That doesn't make sense.

**Comment by JiaUnity** [comment]
This is fixed in https://github.com/Unity-Technologies/InputSystem/pull/422
Can close.
