### ISSUE TITLE
Argument Exception when input manager analysis window open [2019.3.0a7 - 0.9.2 ]

### ISSUE THREAD

**Issue by JamhammerRob** [Unity-Technologies/InputSystem#783]
I get this error when I have the 

`ArgumentException: Expecting name at position 0 in ','
Parameter name: text
UnityEngine.InputSystem.Utilities.NameAndParameters.ParseNameAndParameters (System.String text, System.Int32& index) (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Utilities/NameAndParameters.cs:82)
UnityEngine.InputSystem.Utilities.NameAndParameters.ParseMultiple (System.String text, System.Collections.Generic.List`1[UnityEngine.InputSystem.Utilities.NameAndParameters]& list) (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Utilities/NameAndParameters.cs:51)
UnityEngine.InputSystem.Utilities.NameAndParameters.ParseMultiple (System.String text) (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Utilities/NameAndParameters.cs:31)
UnityEngine.InputSystem.Editor.InputDebuggerWindow+InputSystemTreeView.AddActionItem (UnityEditor.IMGUI.Controls.TreeViewItem parent, UnityEngine.InputSystem.InputAction action, System.Int32& id) (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Editor/Debugger/InputDebuggerWindow.cs:825)
UnityEngine.InputSystem.Editor.InputDebuggerWindow+InputSystemTreeView.AddUser (UnityEditor.IMGUI.Controls.TreeViewItem parent, UnityEngine.InputSystem.Users.InputUser user, System.Int32& id) (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Editor/Debugger/InputDebuggerWindow.cs:562)
UnityEngine.InputSystem.Editor.InputDebuggerWindow+InputSystemTreeView.BuildRoot () (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Editor/Debugger/InputDebuggerWindow.cs:427)
UnityEditor.IMGUI.Controls.TreeView+TreeViewControlDataSource.FetchData () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewControl/TreeViewControlDataSource.cs:53)
UnityEditor.IMGUI.Controls.TreeViewDataSource.ReloadData () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewDataSource.cs:53)
UnityEditor.IMGUI.Controls.TreeView+TreeViewControlDataSource.ReloadData () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewControl/TreeViewControlDataSource.cs:25)
UnityEditor.IMGUI.Controls.TreeViewController.ReloadData () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewController.cs:289)
UnityEditor.IMGUI.Controls.TreeView.Reload () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewControl/TreeViewControl.cs:105)
UnityEngine.InputSystem.Editor.InputDebuggerWindow+InputSystemTreeView..ctor (UnityEditor.IMGUI.Controls.TreeViewState state) (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Editor/Debugger/InputDebuggerWindow.cs:359)
UnityEngine.InputSystem.Editor.InputDebuggerWindow.Initialize () (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Editor/Debugger/InputDebuggerWindow.cs:150)
UnityEngine.InputSystem.Editor.InputDebuggerWindow.OnGUI () (at Library/PackageCache/com.unity.inputsystem@0.9.2-preview/InputSystem/Editor/Debugger/InputDebuggerWindow.cs:180)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <a8ed250850854b439cedc18931a314fe>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <a8ed250850854b439cedc18931a314fe>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <a8ed250850854b439cedc18931a314fe>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:367)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:361)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:337)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:392)
UnityEditor.DockArea.OldOnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:358)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:280)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

**Comment by Rene-Damm** [comment]
Yup, that's my bad. Sorry about that. Fixed by #778. Should be available in package shortly.

**Comment by Rene-Damm** [comment]
Should be fixed as of 0.9.3.
