### ISSUE TITLE
[0.9.3] [Question] How to add continuous action?

### ISSUE THREAD

**Issue by KorDum** [Unity-Technologies/InputSystem#790]
In 0.2.* InputAction has `continuous`, but from 0.9.* it was removed.  
How to add continous action?  
i.e if I press W button, character move. If I release W button, character move stop.  
I did not find this in the documentation.

I created simple Input asset:

![image](https://user-images.githubusercontent.com/1331559/63162059-4d53ae80-c02a-11e9-9855-6d091e49833f.png)

![image](https://user-images.githubusercontent.com/1331559/63162289-c8b56000-c02a-11e9-95a5-2c7c94d6c53f.png)

![image](https://user-images.githubusercontent.com/1331559/63162299-d23ec800-c02a-11e9-90a2-7bfd07d1c5d4.png)

Added `PlayerInput` script to Player game object:

![image](https://user-images.githubusercontent.com/1331559/63162140-7bd18980-c02a-11e9-8ee5-93fbf0905ff2.png)

```csharp
public class MoveController : MonoBehaviour
{
    public void OnMove(InputAction.CallbackContext context)
    {
        Debug.Log(context);
    }
    // ...
}
```
```
action=Player/Move[/Keyboard/w,/Keyboard/s,/Keyboard/a,/Keyboard/d,/Keyboard/upArrow,/Keyboard/downArrow,/Keyboard/leftArrow,/Keyboard/rightArrow] phase=Started time=3,9031931000136 control=Key:/Keyboard/d value=(1.0, 0.0) interaction=
action=Player/Move[/Keyboard/w,/Keyboard/s,/Keyboard/a,/Keyboard/d,/Keyboard/upArrow,/Keyboard/downArrow,/Keyboard/leftArrow,/Keyboard/rightArrow] phase=Performed time=3,9031931000136 control=Key:/Keyboard/d value=(1.0, 0.0) interaction=
action=Player/Move[/Keyboard/w,/Keyboard/s,/Keyboard/a,/Keyboard/d,/Keyboard/upArrow,/Keyboard/downArrow,/Keyboard/leftArrow,/Keyboard/rightArrow] phase=Canceled time=5,16919310001686 control=Key:/Keyboard/d value=(0.0, 0.0) interaction=
```

Performed only one time.

**Comment by Rene-Damm** [comment]
The recommended way is to use `InputAction.ReadValue()` in `Update` or `FixedUpdate` for value-type actions and `InputAction.triggered` for button-type actions.

Alternatively, cache the value from the callback and use it in `Update` or `FixedUpdate`.

```
public class MoveController : MonoBehaviour
{
    private Vector2 m_Move;
    public void OnMove(InputAction.CallbackContext context)
    {
        m_Move = context.ReadValue<Vector2>();
    }
    protected void Update()
    {
        //process move...
    }
}
```

**Comment by KorDum** [comment]
Thanks for reply!
