### ISSUE TITLE
Input Actions: When multiple actions are selected, Unity will duplicate multiple times

### ISSUE THREAD

**Issue by HeyItsLollie** [Unity-Technologies/InputSystem#794]
Present in Preview 0.9.3
(Windows 10, 64-bit. Unity 2019.2.0f1)

If you duplicate two actions simultaneously, Unity will duplicate both actions twice. Three times for three, four for four, etc.

Simple to reproduce: Create an Input Actions file, then create two or more actions (no bindings required). Select two or more, then right-click > "Duplicate"

**Comment by Rene-Damm** [comment]
Thanks for reporting. Fixed in #908.
