### ISSUE TITLE
On-Screen Stick does not work on iOS device

### ISSUE THREAD

**Issue by harrison-drift** [Unity-Technologies/InputSystem#799]
I'm unable to test this on anything other than an iPhone XS and iPad Pro but on both devices the built-in on-screen stick script does not work properly.

I've confirmed it's the package and not my own scene by downloading this repo and running the OnScreenControlsSample scene on my devices and the same issue is present there.

The `OnPointerDown` and `OnPointerUp` events of the OnScreenStick script do work however the `OnDrag` event is not firing at all. I've confirmed this by writing in `Debug.Log`'s to each function and under no circumstances on-device does the `OnDrag` fire but `OnPointerDown` and `OnPointerUp` do. 

Interestingly in the editor on desktop, they work just fine. As does the OnScreenButton script.

**Comment by harrison-drift** [comment]
Managed to get the `OnDrag` event to fire on the device by calling it in the `OnPointerDown` function, but it only fires that once and doesn't continue to run.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
