### ISSUE TITLE
Submit and Cancel button from Input System UI Input Module issue

### ISSUE THREAD

**Issue by sergiregi88** [Unity-Technologies/InputSystem#808]
Hi 
When I tried to configure the navigation UI with the Input System UI System Module and Event System. I map the Submit And Cancel Buttons with Custom InputActionAsset. The Actions Submit And Cancel  responds few times after that doesn't responds anymore.
Here my CusomInputAsset and the InputSystemUISystemModule

![image](https://user-images.githubusercontent.com/3923675/63797366-3e151080-c908-11e9-8b49-242eb0e6a12a.png)

![image](https://user-images.githubusercontent.com/3923675/63797410-55ec9480-c908-11e9-8809-d252e06f8df3.png)

Thanks
Sorry For My English.

**Comment by Rene-Damm** [comment]
Hey @sergiregi88, sorry for the ridiculously long delay here.

Is this still an issue for you with the latest package (1.0-preview)? If so, could you file a bug with your project through the Unity bug reporter? We will take a look. From the sound of it, seems like some state get stuck.

**Comment by Krischkros** [comment]
I also have this issue.
Just got OnSubmit to work but OnCancel works once and randomly.

How i fixed OnSubmit? Just add an listener on onClick. Kinda dirty.

For example (one-time & random log entries):
`public void OnCancel(BaseEventData eventData)
    {
        print("Hola");
    }`

I hope a quick solution can be found.

**Comment by mkdior** [comment]
Remove the "Press" interaction from your "escape" / "enter" actions. With the press interaction added it just listens for one activation.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
