### ISSUE TITLE
multiple controller input using PlayerInputManager stops working after multiple disconnects

### ISSUE THREAD

**Issue by jacobblyons** [Unity-Technologies/InputSystem#809]
Hello, I noticed a bug where player one cant move unless player two is moving. this happens when the controllers are disconnected and reconnected multiple times. usually occurs after 2 disconnects, but sometimes after just one. seems like some sort of state issue in ```PlayerInput``` or ```InputUser```. 
works fine before the disconnects.

here is the stripped down code I tested with and screenshots of the inspector:
```
public class Player : MonoBehaviour
{
    public void OnMovement(InputValue v) {
        gameObject.transform.Translate(v.Get<Vector2>());
    }
}
```
![image](https://user-images.githubusercontent.com/45246570/63801652-a42c7400-c8c5-11e9-9997-5853e6e033a2.png)
![image](https://user-images.githubusercontent.com/45246570/63801624-970f8500-c8c5-11e9-864a-4e8efb7eca2a.png)
![image](https://user-images.githubusercontent.com/45246570/63801686-b4445380-c8c5-11e9-9a71-a7eb0822671f.png)
![image](https://user-images.githubusercontent.com/45246570/63801711-be665200-c8c5-11e9-8766-021dde383cd8.png)

using Xbox one controllers if that makes any difference.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
