### ISSUE TITLE
[FeatureRequest] Allow function hookups to InputActions through component UI similar to how UI Buttons does.

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#81]
![capture](https://user-images.githubusercontent.com/36174025/39158884-645aa1ac-4717-11e8-99a5-eb82ea4a2179.PNG)

The Unity UI allows you to hook up functions to fire when button events occur.  This would be a nice feature for the Unity users who are not programmers that know about hooking up events.

**Comment by Rene-Damm** [comment]
Not sure about this one yet. It would mean tying InputActions to the UnityEvent API. I think to a large part it will depend on what happens around how we respond to action changes. The current callback-based API is likely to either be entirely superseded or, if not, at least supplanted by an additional event-based API.

In short, probably something to revisit later.
