### ISSUE TITLE
When setting a binding on a component's public InputAction, opening or closing a branch in the Control selection tree causes a user to lose their place

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#82]
![capture](https://user-images.githubusercontent.com/36174025/39216813-06b6a76a-47d2-11e8-8864-31d4cfa2ce5b.PNG)

In this screen capture I am selecting a control binding.  If I open the Joystick tree branch or close the Keyboard tree branch the Controls selection panel will reset the view to be scrolled all the way up.  This makes tree navigation difficult because every time a branch is opened or closed the user must scroll to find their place again.

**Comment by Rene-Damm** [comment]
Confirmed. No clue why the TreeView is doing that. Will look into it.

**Comment by Rene-Damm** [comment]
On a related note, the picker also doesn't preserve the expansion state of nodes -- which I find highly annoying.

**Comment by jackpr-unity** [comment]
Agreed about not preserving the expansion state being really annoying

**Comment by tomekpaszek** [comment]
tree view state should be preserved now
