### ISSUE TITLE
Add a ClearCallbacks generated interface method

### ISSUE THREAD

**Issue by Ramobo** [Unity-Technologies/InputSystem#823]
This method does the exact opposite of `SetCallbacks` ~~--~~ unsubscribes the given instance from the callbacks ~~--~~, although it might have some design issues.

The reason I need this is to be able to make a global input manager instead of having several instances of a generated class all over my code. A global input manager should make it easier to control action maps. However, to do this, I need to be able to unsubscribe classes from the events in `OnDisable`. Right now, we can just disable the action map in the instance, but there's no practical way to unsubscribe from the events.

Actually, now that I think about it, there might not actually be many problems with it. I might try to implement it myself.

**Comment by Ramobo** [comment]
My quick implementation appears to work, but calling `SetCallbacks` clears the callbacks for what previously called it. I see two ways of going about this:
1 - Remove the check entirely and leave it up to the user to track subscriptions. Not great and most people won't agree for good reason;
2 - Turn `IActions m_ActionsCallbackInterface` into `List<IActions> m_ActionsCallbackInterfaces` and add subscriptions to it. Check if the list contains the instance and if so, store it in a local variable and unsubscribe it. This is what I have so far:
```CSharp
// Menu
// ...
private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
// ...
public struct MenuActions
{
    /* ... */
    public void SetCallbacks(IMenuActions instance)
    {
        if (m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance))
        {
            IMenuActions instanceInCallbackInterfacesList = m_Wrapper.m_MenuActionsCallbackInterfaces.Find(item => item == instance);

            OpenClose.started -= instanceInCallbackInterfacesList.OnOpenClose;
            OpenClose.performed -= instanceInCallbackInterfacesList.OnOpenClose;
            OpenClose.canceled -= instanceInCallbackInterfacesList.OnOpenClose;
        }
        m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
        if (instance != null)
        {
            OpenClose.started += instance.OnOpenClose;
            OpenClose.performed += instance.OnOpenClose;
            OpenClose.canceled += instance.OnOpenClose;
        }
    }
    public void ClearCallbacks(IMenuActions instance)
    {
        if (instance != null)
        {
            OpenClose.started -= instance.OnOpenClose;
            OpenClose.performed -= instance.OnOpenClose;
            OpenClose.canceled -= instance.OnOpenClose;
        }
    }
}
```
It appears to work, at first, but on performing the action, I get two errors which are probably related to the system not being architected to work this way, which occur only if I do clear the callbacks on performing the action:
```
ArgumentOutOfRangeException thrown during execution of 'Started' callback on action 'Menu/OpenClose[/Keyboard/escape]'
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:117)
```
```
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

Parameter name: index
UnityEngine.InputSystem.Utilities.InlinedArray`1[TValue].get_Item (System.Int32 index) (at Library/PackageCache/com.unity.inputsystem@0.9.5-preview/InputSystem/Utilities/InlinedArray.cs:66)
UnityEngine.InputSystem.InputActionState.CallActionListeners (System.Int32 actionIndex, UnityEngine.InputSystem.InputActionMap actionMap, UnityEngine.InputSystem.InputActionPhase phase, UnityEngine.InputSystem.Utilities.InlinedArray`1[System.Action`1[UnityEngine.InputSystem.InputAction+CallbackContext]]& listeners) (at Library/PackageCache/com.unity.inputsystem@0.9.5-preview/InputSystem/Actions/InputActionState.cs:1612)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:117)

```
What do you think about the general design? And any clue on these errors?

**Comment by Ramobo** [comment]
After some more testing, I'll add that the errors persist with the first method, the no check one, and 0.9.6-preview.

**Comment by Ramobo** [comment]
Since there were no replies to this, I was going to just open a pull request with those changes, but then I realized that we don't have write permissions. What's the point of having code in this repository then?

**Comment by Rene-Damm** [comment]
`SetCallbacks(null)` should do what you're looking for. I.e. clear callbacks and then do nothing.

Are you getting the aforementioned errors also if you call `SetCallbacks(null)`?

**Comment by Ramobo** [comment]
That does fix them, but as I said, another requirement of mine is the ability to subscribe multiple interface instances to the same wrapper instance so that I can manage global action map toggling more easily, like disabling everything else when opening a menu. Basically, what I need is an input "singleton", though I recently pruned global state in preparation for 2019.3. If that is to be added, we're back to square one, since a simple `SetCallbacks(null)` wouldn't work when you have multiple subscribed instances.

**Comment by Ramobo** [comment]
Well. Turns out that those errors were caused by an overlook: I forgot to remove the instance from the callback interfaces list when unsubscribing it. Now it works. Too bad we can't open pull requests since the repository is read-only to us, and there's no license anyway. See #824.

**Comment by Rene-Damm** [comment]
>Too bad we can't open pull requests since the repository is read-only to us

Anyone can open PRs from forks.

>there's no license anyway

There is a license on the package that applies to all source code in the repo. We have an open PR that copies the license to the repo root so it's visible on the GitHub license tab.

**Comment by Ramobo** [comment]
Wait, what? Gah, I forgot about forks.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
