### ISSUE TITLE
Support for mice with more than one scroll wheel

### ISSUE THREAD

**Issue by JimmyCushnie** [Unity-Technologies/InputSystem#825]
Some mice, such as [this one](https://www.amazon.com/dp/B000HCT12O), have more than one scroll wheel. It would be great to read from the different wheels individually.

**Comment by Rene-Damm** [comment]
This should be supported. At least the two wheels on that mouse. The top one should come out as `scrollWheel/y` and the side wheel should come out as `scrollWheel/x`. (and I'm not aware of a mouse that has more than a horizontal and a vertical wheel)

**Comment by JimmyCushnie** [comment]
My apologies - I discovered this after making this issue, but I forgot to close it.
