### ISSUE TITLE
InputDebugger does not populate in Windows Editor with an XBox One controller plugged in

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#83]
found in commit 7172618277802e5ad095de776d1d4771779fd3bd

Stack Trace:

IndexOutOfRangeException: Array index is out of range.
(wrapper stelemref) object:stelemref (object,intptr,object)
UnityEngine.Experimental.Input.Utilities.ArrayHelpers.AppendWithCapacity[Gamepad] (UnityEngine.Experimental.Input.Gamepad[]& array, System.Int32& count, UnityEngine.Experimental.Input.Gamepad value, Int32 capacityIncrement) (at Packages/com.unity.inputsystem/InputSystem/Utilities/ArrayHelpers.cs:113)
UnityEngine.Experimental.Input.Gamepad.OnAdded () (at Packages/com.unity.inputsystem/InputSystem/Devices/Gamepad.cs:231)
UnityEngine.Experimental.Input.InputDevice.NotifyAdded () (at Packages/com.unity.inputsystem/InputSystem/Devices/InputDevice.cs:346)
UnityEngine.Experimental.Input.InputManager.AddDevice (UnityEngine.Experimental.Input.InputDevice device) (at Packages/com.unity.inputsystem/InputSystem/InputManager.cs:729)
UnityEngine.Experimental.Input.InputManager.RecreateDevicesUsingLayout (InternedString layout, Boolean isKnownToBeDeviceLayout) (at Packages/com.unity.inputsystem/InputSystem/InputManager.cs:339)
UnityEngine.Experimental.Input.InputManager.PerformLayoutPostRegistration (InternedString name, System.String baseLayout, Nullable`1 deviceMatcher, Boolean isReplacement, Boolean isKnownToBeDeviceLayout) (at Packages/com.unity.inputsystem/InputSystem/InputManager.cs:256)
UnityEngine.Experimental.Input.InputManager.RegisterControlLayout (System.String json, System.String name, System.String namespace, Nullable`1 matcher) (at Packages/com.unity.inputsystem/InputSystem/InputManager.cs:206)
UnityEngine.Experimental.Input.InputSystem.RegisterControlLayout (System.String json, System.String name, Nullable`1 matches) (at Packages/com.unity.inputsystem/InputSystem/InputSystem.cs:122)
UnityEngine.Experimental.Input.Plugins.XInput.XInputSupport.Initialize () (at Packages/com.unity.inputsystem/InputSystem/Plugins/XInput/XInputSupport.cs:26)
UnityEngine.Experimental.Input.InputSystem.PerformDefaultPluginInitialization () (at Packages/com.unity.inputsystem/InputSystem/InputSystem.cs:1031)
UnityEngine.Experimental.Input.InputSystem.InitializeInEditor () (at Packages/com.unity.inputsystem/InputSystem/InputSystem.cs:963)
UnityEngine.Experimental.Input.InputSystem..cctor () (at Packages/com.unity.inputsystem/InputSystem/InputSystem.cs:926)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for UnityEngine.Experimental.Input.InputSystem
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:93)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Rene-Damm** [comment]
Should be fixed in https://github.com/Unity-Technologies/InputSystem/commit/a357d9d004297ddc591eb45568efe9c21fff97da.
