### ISSUE TITLE
InputActionReference should set m_Action to null in SetInternal

### ISSUE THREAD

**Issue by cgbeutler** [Unity-Technologies/InputSystem#830]
I was reviewing the `InputActionReference` and noticed an issue.

The getter for `Action` checks if `m_Action` is `null` as a way of lazy-caching the result:
https://github.com/Unity-Technologies/InputSystem/blob/a37a3801e190d1eb2c871ee221ea08415cedfdd4/Packages/com.unity.inputsystem/InputSystem/Actions/InputActionReference.cs#L36-L51

The setter function never clears `m_Action` back to `null`, so `Action` will return the old value forever and never get reset to the newly set value.
https://github.com/Unity-Technologies/InputSystem/blob/a37a3801e190d1eb2c871ee221ea08415cedfdd4/Packages/com.unity.inputsystem/InputSystem/Actions/InputActionReference.cs#L81-L93

**Comment by cgbeutler** [comment]
FYI: This seems like a fairly major problem with anything that uses an ActionReference and then switches what it refers to. You will basically never see that switch take effect when going through `action`.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
