### ISSUE TITLE
TrackedDeviceRaycaster component cannot be added

### ISSUE THREAD

**Issue by m4ff** [Unity-Technologies/InputSystem#834]
The TrackedDeviceRaycaster component cannot be added to a game object, even if the XR module is enabled. I'm using version 0.9.5 with Unity 2019.2.0f1.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
