### ISSUE TITLE
"Usage entry is empty" logged multiple times when entering play mode

### ISSUE THREAD

**Issue by m4ff** [Unity-Technologies/InputSystem#841]
The following error message is logged every time I enter play mode (package version 0.9.5, Unity version 2019.2.0f1). The number of times the error is logged seems to increase over time. It started with 10 logs, now it is printed about 300 times.

```
Usage entry is empty
UnityEngine.InputSystem.InputManager:OnNativeDeviceDiscovered(Int32, String)
UnityEngineInternal.Input.NativeInputSystem:NotifyDeviceDiscovered(Int32, String) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:129)
```

**Comment by Rene-Damm** [comment]
Are you using an XR device by chance? (Oculus etc)

**Comment by m4ff** [comment]
Yes. It happens with both Oculus and OpenVR.

**Comment by kahunamoore** [comment]
FYI: I'm getting this as well. Yes, I too am using XR devices.

**Comment by Rene-Damm** [comment]
Hi, would you mind filing a ticket with the Unity bug reporter? Thanks :)

**Comment by ROBYER1** [comment]
Getting this also, it's causing an immense performance dip - using Oculus Quest with Oculus Link

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
