### ISSUE TITLE
InputAction.md in the docs features outdated code

### ISSUE THREAD

**Issue by interior-night** [Unity-Technologies/InputSystem#845]
I think `using UnityEngine.Experimental.Input;` should probably read `using UnityEngine.Input;`

**Comment by Rene-Damm** [comment]
Good catch. Will fix. Thanks for reporting.

**Comment by rhiannanberry** [comment]
Unsure if I should make a new issue, but this error also appears in QuickStartGuide.md

**Comment by Rene-Damm** [comment]
Fixed in #907.
