### ISSUE TITLE
Vector2 never returns zero

### ISSUE THREAD

**Issue by graferowy** [Unity-Technologies/InputSystem#847]
Hi.
I am trying to make a basic player movement with new input system and I cannot figure it out. 
I have a Action of Action Type "Value" and Value Type "Vector2". I've added to it 2D Vector Composite of type normalized Vector2. The problem is it returns only a value when any of the keys was pressed. There's no Vector2.zero value when keys are released to cancel the movement. When I try to change it somehow to "Press and release" it returns vector zero, but it does not read 2 keys pressed at the same time, so I cannot move diagonally. What's the solution?

**Comment by EricBoiseLGSVL** [comment]
@graferowy 

Try setting continuous in Action
![InputHelp01](https://user-images.githubusercontent.com/45106230/66443771-2b0c5a80-e9f5-11e9-818c-ffbe404e7381.PNG)

On each axis use Hold and Press Interactions.
![InputHelp02](https://user-images.githubusercontent.com/45106230/66443790-411a1b00-e9f5-11e9-9c8c-785ad442b219.PNG)

In your class assign events like so
```
controls.Camera.Direction.started += ctx => directionInput = ctx.ReadValue<Vector2>();
controls.Camera.Direction.performed += ctx => directionInput = ctx.ReadValue<Vector2>();
controls.Camera.Direction.canceled += ctx => directionInput = Vector2.zero;
```

Hope this helps

**Comment by Rene-Damm** [comment]
@graferowy When you release the keys, you should see "canceled" get triggered with a zero vector (and ReadValue on the action returning a zero vector).

@EricBoiseLGSVL The continuous flag has been removed some time ago.

**Comment by EricBoiseLGSVL** [comment]
@Rene-Damm 

Yeah, we have been trying to update but keep running into issues. Looking forward to using the latest.  The new Input is excellent and keeps getting better. Thanks for the hard work
