### ISSUE TITLE
Document correct usage of InputSystem.RegisterProcessor<T>

### ISSUE THREAD

**Issue by apkd** [Unity-Technologies/InputSystem#849]
The [processors documentation page](https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/Documentation%7E/Processors.md#writing-custom-processors) instructs:

> Now, you need to tell the Input System about your processor. So, somewhere in your initialization code, you should call:
> ```csharp
> InputSystem.RegisterProcessor<MyValueShiftProcessor>();
> ```

It is not clear to me what *somewhere in your initialization code* refers to, especially since I haven't encountered any "best practices" advice about how to reliably ensure initialization code is correctly executed when:

- The game/editor is opened
- The editor assemblies are reloaded during script recompilation
- The editor assemblies are reloaded when entering/exiting play mode
- Entering/exiting the play mode *without* reloading assemblies when using the experimental "Enter Play Mode" settings - what *is* the correct behavior here?

Using a naive `[RuntimeInitializeOnLoadMethod]` solution, my custom input processor is displayed as "obsolete" after script recompilation.

I do realize that the solution is out there and probably involves using one or more of the following:
- [[UnityEngine.RuntimeInitializeOnLoadMethodAttribute]](https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html)
- [[UnityEditor.Callbacks.DidReloadScripts]](https://docs.unity3d.com/ScriptReference/Callbacks.DidReloadScripts.html)
- [[UnityEditor.InitializeOnLoadAttribute]](https://docs.unity3d.com/ScriptReference/InitializeOnLoadAttribute.html)
- [[UnityEditor.InitializeOnLoadMethodAttribute]](https://docs.unity3d.com/ScriptReference/InitializeOnLoadMethodAttribute.html)

But I'd love to find out what the recommended approach is and I think the documentation is lacking in that regard.

**Comment by Rene-Damm** [comment]
Good point. I'll flesh out the section.

`RuntimeInitializeOnLoadMethod` is player-only and will not give the desired result in the editor. Usually requires a combination with `[InitializeOnLoad]`.

```
#if UNITY_EDITOR
[InitializeOnLoad]
#endif
public class CustomInputThing : ...
{
    #if UNITY_EDITOR
    static CustomInputThing()
    {
        Initialize();
    }
    #endif

    [RuntimeInitializeOnLoadMethod]
    static void Initialize()
    {
        InputSystem.Register...<CustomInputThing>();
    }
}
```

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
