### ISSUE TITLE
Turning Vive Wands Off and On causes no input and other issues that can't be fixed without restarting

### ISSUE THREAD

**Issue by badbort** [Unity-Technologies/InputSystem#853]
I'm continually encountering inconsistent behavior when shutting down one or more vive wands and starting them up again. 

Have tried disabling and enabling action maps. Stopping and starting editor playback.

Steam VR: 1.6.10
Unity: 2019.2.4f1
Input System: 0.9.6 - preview
Devices "Up to date" on SteamVR "Update Device" window
Project Settings:
Active Input Handling: Input System (Preview)
Virtual Reality SDKs: OpenVR

[BugTest.zip](https://github.com/Unity-Technologies/InputSystem/files/3594186/BugTest.zip)

The easier way I can reproduce some of the behavior is by the following:
1. Open the project attached as .zip and open the main scene
2. Play
3. Click "Enable" to enable all action maps
4. Play with vive wands and see the input coming in and updating as you would expect. Trackpads, menu and trigger are currently mapped.
5. Power down one of the vive wands by hold the small buttons below the trackpad, and wait till it's off
6. Power on that same vive wand
7. Observe no input values coming from that wand
8. Stop and restart editor playback.
9. Click "Enable" again
10. Observe the previously shut down wand no longer provides value

When this occurs I usually see one of the devices mapped as "OpenVRControllerViveControllerMV":

![image](https://user-images.githubusercontent.com/4551792/64591268-fef0c000-d3db-11e9-8f2e-85ca174a6b6f.png)

This and similar behavior can be replicated in a build from the above project, and was reproducible on other PCs with Vives connected.

**Comment by badbort** [comment]
Here is the list of behavior I have observed. Note these are difficult to reproduce

- Shutting down vive wand and turning it on again doesn't work, but has picked up on the correct layout and started working again after I disabled and re-enabled action maps
- Action map values always return null if both wands had the same button/axis pressed and the broken one was released **last**. This can be 'fixed' by holding the same binding (i.e. both triggers) and releasing the 'broken' controller first, then release it on the working controller. Input now prints the correct values.
- Restarting the editor sometimes didn't fix things. Closed all Unity instances, shutdown both controllers, turned on both controllers, then starting editor worked


Here is an example of the InputSystem event invocations during shutdown and turning on a wand:

![image](https://user-images.githubusercontent.com/4551792/64591590-c30a2a80-d3dc-11e9-8acc-8c1a74db35da.png)

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
