### ISSUE TITLE
Cant find Gamepads on 0.9.6 at executable build

### ISSUE THREAD

**Issue by omid3098** [Unity-Technologies/InputSystem#864]
Editor can show gamepads on InputDebugger and gamepads  work in editor, but after build both for Windows and Linux, `Gamepad.all.Count` returns 0 on both runtime platforms.

OS: Linux x64
Unity 2019.2.3f1
InputSystem 0.9.6

Update: This only happens with PS3 gamepads. it works fine with PS4 gamepads.

**Comment by Rene-Damm** [comment]
Hey @omid3098, sorry for the huge lag.

Just to make sure I fully understand, by

>gamepads work in the editor

you mean that in the Unity 2019.2.3f1 version of the Linux editor, the PS3 gamepad correctly shows up. However, when you build both a Windows and a Linux player from that editor, in either player that PS3 gamepad will not show up.

Is that correct?

**Comment by omid3098** [comment]
Hi dear @Rene-Damm , 
Yes, that is correct. PS3 and PS4 gamepads both work fine in Linux editor. but only PS4 gamepads work on executable.
If you need an executable test, Check [this game](https://fossil-games.itch.io/tetris-party).
I have used UnityInputSystem V.0.9.6 and only ps4 gamepads work there.

And sorry, the issue title is wrong instead of runtime, I should say executable build.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
