### ISSUE TITLE
1.0.0 - "Invoke Unity Events" doesn't allow hooking up to functions with a CallbackContext parameter

### ISSUE THREAD

**Issue by DavidColson** [Unity-Technologies/InputSystem#874]
Noticed this issue while exploring the Simple Demo samples. Particularly the scene "UsingPlayerInput" does not allow me to hook up to a function with a CallbackContext parameter on it:

![image](https://user-images.githubusercontent.com/7236152/65391934-e9c64a80-dd66-11e9-944f-5602f870049a.png)

When the scene is first loaded, it shows that the functions are missing:

![image](https://user-images.githubusercontent.com/7236152/65391942-fcd91a80-dd66-11e9-9f0e-b1902c998a75.png)

But it does still invoke the event and the sample runs as normal.

If I remove the CallbackContext parameter then the functions can be linked, but then I have no callback context information.

I would expect that I can link functions with a CallbackContext correctly. I noticed also that the function signature as drawn in the inspector shows no parameters, whereas the pictures in the documentation show "fire(CallbackContext)" instead.

**Comment by Rene-Damm** [comment]
This was a bug introduced in 2019.3 which has since been fixed in one of the recent betas.
