### ISSUE TITLE
Bug in sample code?

### ISSUE THREAD

**Issue by rotter** [Unity-Technologies/InputSystem#891]
I was checking the sample code here on github to see how to implement the NIS on my game and stumbled upon this line. The subtraction seems to be wrong: Start - End will always yield a negative value, thus the second half of the condition on that line will always be true.

https://github.com/Unity-Technologies/InputSystem/blob/4dfc5f232ca38cbfe696209d8a11e0713753ba50/ExternalSampleProjects/TouchSamples/Assets/Scripts/Gestures/GestureController.cs#L91

**Comment by Rene-Damm** [comment]
Good catch. Will push a PR with the change. Looks like there's two places where this happens.

Thank you for the fix.
