### ISSUE TITLE
Unity.Rendering debug is trying to use old input manager

### ISSUE THREAD

**Issue by CamDHall** [Unity-Technologies/InputSystem#896]
I've been playing around with 2020.1.0a7 and the HDRP. When I added the input system package, I start getting this bug every frame. 

`InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
UnityEngine.Rendering.DebugManager.SampleAction (System.Int32 actionIndex) (at Library/PackageCache/com.unity.render-pipelines.core@7.0.1/Runtime/Debugging/DebugManager.Actions.cs:111)
UnityEngine.Rendering.DebugManager.UpdateActions () (at Library/PackageCache/com.unity.render-pipelines.core@7.0.1/Runtime/Debugging/DebugManager.Actions.cs:168)
UnityEngine.Rendering.DebugUpdater.Update () (at Library/PackageCache/com.unity.render-pipelines.core@7.0.1/Runtime/Debugging/DebugUpdater.cs:18)
`

It seems something inside Unity.Rendering is trying to use the current input manager for debugging purposes. 

I don't have anything in the scene currently.

**Comment by Rene-Damm** [comment]
Yup, starting with 2019.3, anything that uses the old input system when "Active Input Handling" is set to "Input System" in the player settings (which installing the input system package does from the dialog it pops up) will lead to errors as the old input system backends are disabled.

You can set "Active Input Handling" to "Both" to get rid of the errors.

**Comment by stephanedupont** [comment]
I'm sorry but how is this a fix and why is it marked as closed?

We should be able to only enable the new input system and not have errors. No?

**Comment by julioRZ** [comment]
How is this closed? This might be a workaround but this isn't a fix!
That being said... This issue is with the SRP and not with the Input system :/

**Comment by stephanedupont** [comment]
Because the problem is not in the input manager, but in the URP package.

This is supposedly fix in upcoming 7.2.0 version of the URP package anyway according to a post of someone @ Unity on the Unity's forum.

**Comment by julioRZ** [comment]
> Because the problem is not in the input manager, but in the URP package.
> 
> This is supposedly fix in upcoming 7.2.0 version of the URP package anyway according to a post of someone @ Unity on the Unity's forum.

I was editing my post as you posted yours, I'll keep an eye for version 7.2.0 of the URP package. Cheers.
