### ISSUE TITLE
MultiplayerEventSystem only answers to the first player's events for UI

### ISSUE THREAD

**Issue by Arumenn** [Unity-Technologies/InputSystem#897]
Each player prefab has a PlayerInput, InputSystemUIInputModule and a MultiplayerEventSystem component.

![player_components](https://user-images.githubusercontent.com/14185168/66259436-060eb200-e77f-11e9-9f64-7fc22feaa0a6.PNG)

Opening and closing each player's UI inventory menu works fine.
Initial navigation is setup like so (where _multiplayerEventSystem is the player's component) :

`_multiplayerEventSystem.playerRoot = _menu;
_multiplayerEventSystem.SetSelectedGameObject(firstButton);
_multiplayerEventSystem.firstSelectedGameObject = firstButton;`

It works very well for the very first player that joined (index 0).
But when other players open their own Inventory menu, only the player at index 0 can navigate through the UI.

I tried manually enabling/disabling  sendNavigationEvents, or the whole MultiplayerEventSystem itself, with no effect.

**Comment by Rene-Damm** [comment]
You will need to set `UI Input Module` on `PlayerInput` to the module corresponding the specific player. Without this, `PlayerInput` will not synchronize the actions of a particular player with the `InputSystemUIInputModule` that belongs to that player.

Does that fix the issue?

We hope to have better documentation and samples (and maybe also some editor magic here that guide the setup better) for 1.0 final.

**Comment by Arumenn** [comment]
I was already setting the `UI Input Module` to the corresponding player's `PlayerInput`.

However, I just noticed that the second player's `PlayerInput` is referencing a **cloned** `InputActionAsset`. And the `UI Input Module` is still using the original `InputActionAsset`.

In the inspector, the `PlayerInput` has a button offering to Fix it, but it just assings the cloned `InputActionAsset` to the `UI Input Module` while resetting all it's actions to `None`

**Comment by Uninoob** [comment]
How did you solve the problem about the cloned `InputActionAsset` ?, Im having same problem with it

**Comment by Arumenn** [comment]
I haven't found a solution to this.

**Comment by Uninoob** [comment]
:(

**Comment by Uninoob** [comment]
I finally solved; in your `InputActionAsset` you should create schemes if you are using custom `InputActionAsset`. There is a video but using defaultInputActions: [https://youtu.be/Ur2tBl58YOc](url)

**Comment by Arumenn** [comment]
I finally understood the problem and fixed it.

Since I was using the InputSystem's autojoin feature to clone my player prefabs, the cloned `InputActionAsset` was normal. It's like it's not just a config file for mappings...

The cloned asset was used in the second player's `PlayerInput`. But that player's `UIInputModule`, even when part of the player prefab that was instantiated when `OnPlayerJoined`, still had reference to the original `InputActionAsset`. This is why I was seeing the button in the editor at runtime to "Fix it". As I said previously, that "Fix it" button doesn't really work : it sets the correct `InputActionAsset` but doesn't seem to configure it correctly and no input is working for that player.

My fix was : in my `OnPlayerJoined` script, I explicitly assing the correct action asset before refencing the UI module : 

`player.GetComponent<InputSystemUIInputModule>().actionsAsset = player.GetComponent<PlayerInput>().actions;`

`player.GetComponent<PlayerInput>().uiInputModule = player.GetComponent<InputSystemUIInputModule>();`

One thing that makes it really confusing, is that once the correct cloned `InputActionAsset` is assigned to the `UIInputModule`, the inspector still shows `None` for every event.

**Comment by lejean** [comment]
This exact issue is still happening in 1.0.0. on unity 2019.4.12 LTS.

Aside from that I'm also getting MissingMethodExceptions errors 
`MissingMethodException: LocalCoop.ReadPlayerInput.OnMove Due to: Attempted to access a missing member.`
`MissingMethodException: UnityEngine.InputSystem.UI.InputSystemUIInputModule.OnCancel Due to: Attempted to access a missing member.`

Even tho I have added those functions in my player script, atleast for the first exception, I can't add functions to InputSystemUIInputModule
