### ISSUE TITLE
pen position 0,0 [Windows 10][Unity Editor 2019.3.0b5][Input System 1.0.0]

### ISSUE THREAD

**Issue by AVOlight** [Unity-Technologies/InputSystem#898]
in play mode this:
Debug.Log(UnityEngine.InputSystem.Pen.current.position.ReadValue());
always returns zero vector...

was using Input.mousePosition which worked fine with my intuos wacom tablet pen

think it might be because of a driver related issue
is there any other way to get the **cursor** position, if both Mouse.current.position and Pen.current.position give 0 vectors?

using a normal mouse works, but looking for a solution that works regardless of issues with drivers on an end users device

**Comment by Rene-Damm** [comment]
So just to make I follow correctly, you have a Wacom Intuos connected installed on a Win10 machine and it works fine in other apps but using the new input system, when you use the pen you get a `(0,0)` position on *both* `Mouse.current.position` *and* `Pen.current.position`?

Could you pop open the input debugger and double-click the Pen device and then just use the pen and see if there are events coming in? If so, is the position value in the debugger also `(0,0)`?

**Comment by AVOlight** [comment]
yes

as i use my pen only new events are showing up in the mouse panel
yes 0,0
but other stats change like press and left, right button...

![Unity_Input Debugger_position_0,0](https://user-images.githubusercontent.com/11915946/66431362-613eee00-ea78-11e9-8313-be56c1130850.png)

**Comment by Noname1122** [comment]
Just chiming in to say I'm seeing the same issue, presented in the same way. Just adding this in ase you didn't possess the means to regress this, Rene-Damm. To corroborate it's cross-machine. :)

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
