### ISSUE TITLE
Endless performed

### ISSUE THREAD

**Issue by RunninglVlan** [Unity-Technologies/InputSystem#899]
When action was `performed` and action handler disables current object and enables next one of the same type, next object's `performed` is triggered. As type is the same and the same thing happens, only in the opposite way (next object disables itself, enables previous one), this repeats as long as the key is held.
This is reproducible by adding 2 empty objects with following component, one of them needs to be disabled, they need to have references on one another:
```
using UnityEngine;
using UnityEngine.InputSystem;

public class Test : MonoBehaviour {

    [SerializeField] GameObject next;

    private InputAction goToNextAction;

    void Awake() {
        Debug.Log($"Awake: {this}");
        goToNextAction = new InputAction("goToNext", binding: "<Keyboard>/f1");
        goToNextAction.performed += _ => {
            gameObject.SetActive(false);
            next.SetActive(true);
        };
    }

    void OnEnable() {
        Debug.Log($"OnEnable: {this}");
        goToNextAction.Enable();
    }

    void OnDisable() {
        Debug.Log($"OnDisable: {this}");
        goToNextAction.Disable();
    }
}
```
As I understand, this is not expected behavior. At least we don't expect next object's action handler trigger as it was just enabled.

**Comment by RunninglVlan** [comment]
What's interesting, not even Coroutines help here - if `goToNextAction.Enable()` is delayed by a coroutine the action will still be triggered, as long as the key is held.
```
void OnEnable() {
    Debug.Log($"OnEnable: {this}");
    StartCoroutine(delayedEnable());
}

System.Collections.IEnumerator delayedEnable() {
    yield return new WaitForSeconds(0.25f);
    goToNextAction.Enable();
}
```

**Comment by Rene-Damm** [comment]
What's "Action Type" set to on the action? If it's set to `Value`, then yes, the behavior here is expected.

When enabled, a `Value` type action will perform an initial state check in the next input update and immediately react if the control is already actuated.

**Comment by RunninglVlan** [comment]
Thanks, the type was `Value`, so it behaved as expected as stated in [documentation](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/Actions.html#action-types).
My bad then, overlooked it. ;)

**Comment by Rene-Damm** [comment]
Thanks for confirming :)
