### ISSUE TITLE
Exceptions when using Input Debugger window

### ISSUE THREAD

**Issue by joelpryde** [Unity-Technologies/InputSystem#9]
I've gotten quite a few of these while using the Rift Touch controllers and trying to view input debugger information.  No exact repro steps but it seems to happen fairly often if I transfer a project with bindings between machines (for example: save a project bound to Rift controllers at home and then open the same project at work and try to use with other Touch controllers).  In addition to exceptions the debugger window for the controller is collapsed and not useful.

ndexOutOfRangeException: Array index is out of range.
ISX.Utilities.InlinedArray`1[System.Action`1[ISX.LowLevel.InputEventPtr]].Remove (System.Action`1 value) (at Assets/InputSystem/InputSystem/Utilities/InlinedArray.cs:87)
ISX.InputManager.remove_onEvent (System.Action`1 value) (at Assets/InputSystem/InputSystem/InputManager.cs:82)
ISX.InputSystem.remove_onEvent (System.Action`1 value) (at Assets/InputSystem/InputSystem/InputSystem.cs:282)
ISX.LowLevel.InputEventTrace.Disable () (at Assets/InputSystem/InputSystem/Events/InputEventTrace.cs:69)
ISX.Editor.InputDeviceDebuggerWindow.DrawEventList () (at Assets/InputSystem/InputSystem/Editor/InputDeviceDebuggerWindow.cs:159)
ISX.Editor.InputDeviceDebuggerWindow.OnGUI () (at Assets/InputSystem/InputSystem/Editor/InputDeviceDebuggerWindow.cs:96)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at D:/repo/unity-isx/Editor/Mono/HostView.cs:291)
UnityEditor.HostView.Invoke (System.String methodName) (at D:/repo/unity-isx/Editor/Mono/HostView.cs:284)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at D:/repo/unity-isx/Editor/Mono/HostView.cs:251)
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)

**Comment by Rene-Damm** [comment]
Should be fixed by https://github.com/Unity-Technologies/InputSystem/commit/9049dac7c37dd42f2aca6bb617b8bb3e0de1c018.
