### ISSUE TITLE
Expose more XR APIs

### ISSUE THREAD

**Issue by bdominguez** [Unity-Technologies/InputSystem#909]
First, I don't know where the XR APIs that were until at least version 0.9.5 went. I don't know if you have it in different packages.

In the integration of Oculus there are several APIs that I do not see being exposed in the Oculus class of the new input system.

![image](https://user-images.githubusercontent.com/7508830/66517236-0d1d2380-eae3-11e9-86f9-47bfd03e9adb.png)

In the methods that I put besides being able to obtain that information, you can obtain it in two different steps: render and physics.

Would it be possible to expose this information? Or do we still have to depend on the specific Oculus package from the Asset Store?

**Comment by Rene-Damm** [comment]
@StayTalm ^^^

>First, I don't know where the XR APIs that were until at least version 0.9.5 went.

Should be back as of `1.0.0-preview.1` (except for Magic Leap).

**Comment by StayTalm** [comment]
This information is somewhat available.
The XR Input devices are updated both at the beforeRender stage, and at the regular dynamic update stage. 
These map to the render and physics time steps.  If you look at the OculusHMD InputDevice class you should have Position, Rotation, Velocity, AngularVelocity, Acceleration, and AngularAcceleration are all present, and which version you get is dependent on when you ask for it.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
