### ISSUE TITLE
Custom OnScreenControl

### ISSUE THREAD

**Issue by pax83** [Unity-Technologies/InputSystem#912]
Hi! I written custom on screen control to handle pinch/spread gesture and it doesn't work.

```csharp
using System.Linq;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.Layouts;
using UnityEngine;
using UnityEngine.InputSystem.OnScreen;
using System.Collections.Generic;


[AddComponentMenu("Input/On-Screen Pointer Handler")]
public class OnScreenPointerHandler : OnScreenControl, IPointerDownHandler, 
       IPointerUpHandler, IDragHandler
{
    public Vector2 sensivity = new Vector2(1, 1);
    public float pinchSpreadSensivity = 1;

    class PointerInfo
    {
        public int pointerId;
        public Vector2 currentPosition;
        public Vector2 lastPosition;
        public float time;
    }

    Dictionary<int, PointerInfo> pointers = new Dictionary<int, PointerInfo>();
    int[] keys = new int[10];

    [InputControl(layout = "Vector2")]
    [SerializeField]
    private string m_PinchSpreadPath;

    protected override string controlPathInternal
    {
        get => m_PinchSpreadPath;
        set => m_PinchSpreadPath = value;
    }

    public void OnEnable()
    {
        pointers.Clear();
    }

    public void OnPointerDown(PointerEventData eventData)
    {
        if (eventData == null)
            throw new System.ArgumentNullException(nameof(eventData));

        if (pointers.Count >= 2)
        {
            var first = pointers.Values.OrderBy(t => t.time).First();
            pointers.Remove(first.pointerId);
        }

        pointers[eventData.pointerId] = new PointerInfo
        {
            pointerId = eventData.pointerId,
            lastPosition = eventData.position,
            currentPosition = eventData.position,
            time = Time.time
        };
    }

    public void OnPointerUp(PointerEventData eventData)
    {
        if (pointers.TryGetValue(eventData.pointerId, out PointerInfo pointer))
        {
            pointers.Remove(eventData.pointerId);
        }

        if (pointers.Count == 1)
        {
            pointer = pointers.Values.First();
            pointer.lastPosition = pointer.currentPosition;
        }
    }

    public void OnDrag(PointerEventData eventData)
    {
        if (eventData == null)
            throw new System.ArgumentNullException(nameof(eventData));

        if (!pointers.ContainsKey(eventData.pointerId)) return;

        RectTransformUtility.ScreenPointToLocalPointInRectangle(transform.parent.GetComponentInParent<RectTransform>(), eventData.position, eventData.pressEventCamera, out var position);

        var pointer = pointers[eventData.pointerId];

        pointer.currentPosition = eventData.position;
    }

    void Update()
    {
        pointers.Keys.CopyTo(keys, 0);

        if (pointers.Count > 1)
        {
            var first = pointers[keys[0]];
            var second = pointers[keys[1]];

            var distance = (first.lastPosition - second.lastPosition).magnitude;
            var distanceNew = (first.currentPosition - second.currentPosition).magnitude;

            var finalDistance = (distanceNew - distance) * pinchSpreadSensivity;
            var value = new Vector2(0, finalDistance);

            SendValueToControl(value);
        }

        for (int i = 0; i < pointers.Count; i++)
        {
            var pointer = pointers[keys[i]];
            pointer.lastPosition = pointer.currentPosition;
        }
    }

}
```
I use "Scroll [Mouse]" as control path and it doesn't work. Also I has second on screen control in scene - OnScreenStick. It is mapped on gamepad left stick and works. 

What I do wrong?

**Comment by pax83** [comment]
I also wanted to use the left and right shoulders of the gamepad to emulate the scroll, but I can’t do this, because OnScreenControl only manages one control.

**Comment by pax83** [comment]
Maybe ScriptExecutionOrder do bad things? I set it -1100, to handle input earlier other updates.

**Comment by pax83** [comment]
Anybody?

**Comment by Rene-Damm** [comment]
Note that OSCs will create their own devices. This means that the scroll-wheel input set up here will not come in separately on its own device.

What does the input debugger say? Is the input coming in correctly on the device set up by the OSC?

>it doesn't work

"It doesn't work" is not enough information for us to help. Best to be specific about what you expect to happen and what you see happening instead.

>I also wanted to use the left and right shoulders of the gamepad to emulate the scroll, but I can’t do this, because OnScreenControl only manages one control.

Being able to synthesize input on more than one control makes sense. Noted.

**Comment by pax83** [comment]
Hi @Rene-Damm ! Thanks for answer!

> What does the input debugger say?

I don't know, how debug it on my phone. I put Debug.Log before SendValueToControl call and value is correct. 

> "It doesn't work" is not enough information for us to help. Best to be specific about what you expect to happen and what you see happening instead.

I binded "Scroll [Mouse]" to Editor.Zoom action and read it in contoller script like this:
```
var zoomValue = MyInputActions.Editor.Zoom.ReadValue<Vector2>();
```
In Editor it works with scroll from mouse, but it not works on phone in build (IL2CPP) with custom OnScreenControl binded to "Scroll [Mouse]" too. 

Editor.Zoom action is global, I dont use control schemes.

**Comment by pax83** [comment]
It also not work with Value and PassThrough modes.

**Comment by pax83** [comment]
Got it in editor, but don't know how to reproduce it... Now OnScreenStick not working. Input debugger works and show devices, but MyInputActions.Editor.Move.ReadValue<Vector2>(); not read any value. Stick is binded to Left Stick [Gamepad]. Editor/Move is Pass Through Vector2 action.

![img-2019-10-22-04-10-22](https://user-images.githubusercontent.com/598631/67253824-70fc0080-f482-11e9-9122-f374c8bff4e9.png)

Unity 2019.2.9f1, Input System preview.1 - 1.0.0

**Comment by pax83** [comment]
I see what Input System is buggy. I roll back to the standard input system. Sorry, there is no time to be a beta tester.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
