### ISSUE TITLE
Unity input event `started` does not last a single frame

### ISSUE THREAD

**Issue by FranciscoOnt** [Unity-Technologies/InputSystem#913]
Im using a script that checks if a certain button is pressed to jump, this check happens once per frame and it used to check for `Input.GetButtonDown` before upgrading to this input system, so I tried using the following setup: 

![Screen Shot 2019-10-12 at 7 22 27 PM](https://user-images.githubusercontent.com/33066750/66709240-a5a2e600-ed25-11e9-88ec-961a107ddefb.png)

![Screen Shot 2019-10-12 at 7 20 38 PM](https://user-images.githubusercontent.com/33066750/66709221-68d6ef00-ed25-11e9-8812-857c5ad24a25.png)

with the following code 
``` cs
public void UpdateJumpInput(InputAction.CallbackContext c)
    {
        playerController.UpdateJumpInput(c.started, c.performed, c.canceled);
    }
```

However, when pressing the assigned button or key, the event gets called twice in the same frame, making `started` true on the first call but false on the second one, causing my script to get the false value on the next update

![Screen Shot 2019-10-12 at 7 17 45 PM](https://user-images.githubusercontent.com/33066750/66709260-05998c80-ed26-11e9-8e1b-f0dbe14dac97.png)

**Comment by Rene-Damm** [comment]
This is by design. You get `started` when the button goes down, `performed` when the action triggers (by default the same as when the button goes down), and `canceled` when the button goes up.

You can check the context like you already do to `if` the action to a particular phase.
