### ISSUE TITLE
MultiTap interaction does not work with multiple keys bound.

### ISSUE THREAD

**Issue by pmurph0305** [Unity-Technologies/InputSystem#922]
Input System Package Version: 1.0.0
Unity Version: 2019.1.1f1

Reproduction Steps
1. Create a new project and import Input System
2. Import "Simple Demo" into project after importing Input System
3. Load Scene "SimpleDemo_UsingPlayerInput.unity"
4. Add a new Input Action with the MultiTap interaction to SimpleControls.inputactions
5. Bind two keys to the action just created.
6. Bind new action to SimpleController_UsingPlayerInput.OnFire on Players' Player Input component.
7. Press play and press keys bound to the MultiTap action, OnFire does not shoot.
8. Remove one of the two keys assigned to the Action, save, and try again, OnFire does shoot.

Current Behaviour:
Function bound to an Action with a MultiTap interaction where multiple keys are bound is not working correctly. InputAction.CallbackContext.phase is never InputActionPhase.Performed, only InputActionPhase.Started and InputActionPhase.Canceled.

Expected:
Action with MultiTap interaction should allow multiple keys to be bound, and correctly have a InputActionPhase.Performed.

Additionally:

9. Remove MultiTap interaction from the Action and apply it to one of the keys bound to the action.
Behaviour: key with MultiTap interaction is never performed, key without MultiTap interaction works as expected.

10. Remove MultiTap interaction from Action and apply MultiTap interaction to both bound keys.
Behaviour: neither key with MultiTap interaction is performed.

Expected behaviour:
Key with MultiTap interaction bound to Action where other keys are bound should have  InputActionPhase.Performed when a MultiTap is performed.

**Comment by pmurph0305** [comment]
Looks like the only way it works as expected it by setting Action Type to Pass Through as opposed to Button. Although I'm not sure if it's intentional.

Is this because on release of the first button tap, does disambugation give control to the other unpressed key? 

With a MultiTap interaction on a Button action with multiple bound keys, the 2nd+ key-press seems to be not be processed, but all the releases are processed. The phase never goes back to the WaitingForNextRelease phase after the first press, so m_currentTapCount is never increased, and the action never performed.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
