### ISSUE TITLE
Polling API(s) are undocumented

### ISSUE THREAD

**Issue by Fishrock123** [Unity-Technologies/InputSystem#923]
I believe for my use the polling API makes more sense than the message callbacks. (Or at least I prefer "pulling" data where possible rather than having it pushed.)

However using the polling API is not exactly documented which making it a bit tricky, and relatedly programatically accessing the generate C# code for an input system is also seemingly undocumented.

Did I just miss this? I don't think so?

**Comment by Rene-Damm** [comment]
Which APIs are you referring to? [`InputAction.triggered`](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/api/UnityEngine.InputSystem.InputAction.html#UnityEngine_InputSystem_InputAction_triggered) and [`InputAction.ReadValue`](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/api/UnityEngine.InputSystem.InputAction.html#UnityEngine_InputSystem_InputAction_ReadValue__1) are documented, I believe.

**Comment by Fishrock123** [comment]
Oh. I was unaware that there was another tab at the top which went to the scripting api. The docs structure is a bit unintuitive I think.

Mentioning the polling api in the "manual" part would be appreciated.

**Comment by Rene-Damm** [comment]
`ReadValue` is documented under [Polling Actions](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/Actions.html#polling-actions) in the manual but `triggered` was indeed missing. Fixed in #932.

>The docs structure is a bit unintuitive I think.

Yup, the docs still need improvement.
