### ISSUE TITLE
Keybinding question

### ISSUE THREAD

**Issue by imnezaki** [Unity-Technologies/InputSystem#924]
Hello,
Is it possible to rebind another key to my move forward action in runtime, to be able to save and load custom bindings when game starts?

**Comment by Rene-Damm** [comment]
>Is it possible to rebind another key to my move forward action in runtime

```
myAction.ApplyBindingOverride("newpath");
```

>to be able to save and load custom bindings when game starts?

Saving and loading overrides currently requires manually reading out and restoring overrides from `InputBinding.overridePath`.
