### ISSUE TITLE
Nintendo Switch demo scene not working - expects format GPAD

### ISSUE THREAD

**Issue by dimmduh** [Unity-Technologies/InputSystem#925]
launched GamepadVisualizer scene on switch

it does not work, getting error:
`"Cannot read control '/Gamepad/dpad/right' from STAT with format NPAD; device 'Gamepad:/Gamepad' expects format GPAD"`

version preview.1 - 1.0.0

**Comment by Rene-Damm** [comment]
We're in the process of migrating from GitHub issues to standard Unity bug reporting. Please file a bug through the Unity bug reporter.
