### ISSUE TITLE
Devices not being recognized

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/InputSystem#926]
Devices like keyboard, mouse, 360 controller not being recognized...

First i thinking is because i made some mistake, but create new project and followed a tutorial and same... create a new project with other unity version aaaand same, downloaded sample from new input system and omg same!

I enter Input Debug and my keyboard and mouse not showing like the videos i've see
![image](https://user-images.githubusercontent.com/21144063/67161590-6b8fa080-f332-11e9-8a73-e8f3bf5edcb8.png)

now i dont have any ideia how to fix this.
anyone can help me?

**Comment by ghost** [comment]
I fixed the issue... in the Project Settings - Player - Configuration - Active Input Handling is set to Both
put only Input System(preview) and now is working...

but this is a bug, Both not working

**Comment by Rene-Damm** [comment]
Please report a bug through the Unity bug reporter.
