### ISSUE TITLE
[Question] Action Bindings via String

### ISSUE THREAD

**Issue by StephenHodgson** [Unity-Technologies/InputSystem#93]
Is there going to be an alternative to binding actions via strings?

**Comment by Rene-Damm** [comment]
Do you mean for making the bridge from actions to the input controls they talk or for finding actions contained in sets?

Could you elaborate a bit about your concern?

**Comment by StephenHodgson** [comment]
Just wondering if there is any plans to support concrete types for action bindings.

**Comment by Rene-Damm** [comment]
Well, you're not giving me much to work with in terms of what you have in mind :)

As for whether there's the string paths used by actions to target controls are going to be replaced or complemented by some other mechanism, no, there's no plan for that.

Among other advantages, the binding paths have the two key advantages that they can be readily persisted and that they actually comprise a regular expression-like matching language that can flexibly find controls (and eventually probably other stuff, too) in the system.

I'm not sure how C# types fit into that picture without either tying the system to implementation details in awkward/unnecessary ways or making persistence a significant problem.

Overall, though, I'd consider the control path strings mostly implementation detail. They're invisible in the UI and with some extensions to the API, they'll be largely invisible there, too, except for someone explicitly wanting to dig into that level of detail.

**Comment by StephenHodgson** [comment]
> Well, you're not giving me much to work with in terms of what you have in mind :)

Part of it is that I haven't really dug into the code enough to make an educated assessment of the implementation with strings, or alternatives. Just from a quick glance I was surprised to see it.

My only real concerns is discovering bindings and actions without having to do expensive string operations like regex; and that typos that are sometimes sometimes get skipped over until they're discovered at runtime. C# is a statically typed language, and using it in this way doesn't really play to those strengths.

Mainly it's the dynamic vs statically typed approach that I'm not so keen about.

**Comment by Rene-Damm** [comment]
>My only real concerns is discovering bindings and actions without having to do expensive string operations like regex; and that typos that are sometimes sometimes get skipped over until they're discovered at runtime.

Yup definitely a valid concern.

I think the potential for typos and similar mistakes creeping into it can largely be avoided by not manually creating the strings but having the system create them internally and automatically.

Performance-wise, the matching is certainly more expensive than a simple table lookup but is pretty fast, involves zero allocations (no temporary strings are created, for example), and is certainly tons faster than C# reflection. Also, it's a one-time step per action set. Once bindings are resolved, the system just keeps the data even if actions are disabled. As long as the control setup in the system doesn't change, it won't resolve bindings again.

>C# is a statically typed language, and using it in this way doesn't really play to those strengths.

This is data, though. Even if we make the data refer to C# types, they'd have to refer to the types by name. So you'd end up with strings again. In the end, it's not so different from C# DLLs that have to refer to types in other DLLs. It's just a string that the VM will have to look up.

The current bindings allow the system to get a lot of leverage from those simple strings. For example, `<XRController>{LeftHand}/rotation` will bind to the rotation of anything that classifies as an XR controller and is tagged as being the left hand. You could represent all this as fully typed and structured data but it'd get quite complicated fast and definitely bring an additional heap cost. The string there is a single heap object that the system can resolve without any allocations. And the action system itself isn't even aware of the matching/searching features supported by the path specs. It's just a simple string it passes into the system and it gets some controls back (or not).

**Comment by StephenHodgson** [comment]
Sounds good to me!  Thanks for clarifying this a bit more.

>They're invisible in the UI and with some extensions to the API, they'll be largely invisible there, too.

Hopefully any API that will be exposed to developers in the editor won't have to deal with the strings at all, but if that's not the case, then it's not as big of a worry.

**Comment by Rene-Damm** [comment]
>Hopefully any API that will be exposed to developers in the editor won't have to deal with the strings at all

Yup agree, I think that should be the goal.
