### ISSUE TITLE
PS4 Controller thumb sticks switched

### ISSUE THREAD

**Issue by mrford3rd** [Unity-Technologies/InputSystem#934]
![inputsystem_ps4controller](https://user-images.githubusercontent.com/14000451/67738642-6f2fc100-f9dd-11e9-93ee-63eeb23971b4.png)

I updated to the latest version of Unity and the Input System and noticed that when I use my PS4 controller through bluetooth the left and right thumb sticks are switched but work under xinput but when the controller is hooked up through usb the inputs are correctly mapped.

A screen shot is included and you will see that as the controller is hooked up through Bluetooth and I am holding the left thumb stick to the left.

**Comment by Rene-Damm** [comment]
Hey @mrford3rd, thank you for the report. Would you mind filing a ticket through the Unity bug reporter? We're in the process of migrating all our issue tracking to standard Unity processes so that we can better work together with QA.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
