### ISSUE TITLE
InputControl attribute doesn't work correctly with arrays

### ISSUE THREAD

**Issue by WI-Lee** [Unity-Technologies/InputSystem#937]
When using the dropdown or the path editor, every entry in the array is overwritten with the new value instead of just the selected one.

```csharp
using UnityEngine;
using UnityEngine.InputSystem.Layouts;

public class InputTest : MonoBehaviour
{
	[InputControl]
	public string[] Paths;
}
```

**Comment by Rene-Damm** [comment]
There's no support for arrays of control paths yet. It's on the list.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
