### ISSUE TITLE
UWP doesn't build

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#94]
found using cc6b238fa08edb48f2af17ed5adfe3566a9cf7d0

25 errors total
- InputRemoting.cs ambiguous references
- ReadOnlyArray.cs (66,21): error CS0540: 'ReadOnlyArray<TValue>.IEnumerable.GetEnumerator()': containing type does not implement interface 'IEnumerable'
- RemoteInputPlayerConnection.cs ambiguous references

**Comment by jackpr-unity** [comment]
It works fine using IL2CPP.

**Comment by StephenHodgson** [comment]
.NET is depreciated scripting backed is depreciated anyway, correct?

**Comment by jackpr-unity** [comment]
@StephenHodgson the .NET backend is depreciated in 18.2, which is required for InputSystem anyway (?).  So I suppose its fine to mark as "won't fix."

**Comment by StephenHodgson** [comment]
> which is required for InputSystem anyway

That's correct.
Just be sure to add documentation someplace for UWP folks that the new InputSystem requires IL2CPP

**Comment by douglas-piconi** [comment]
I just put in a PR to fix .Netstandard 2.0 for ambiguous references.  This should cleanup UWP errors.
