### ISSUE TITLE
default actions created by PlayerInput button is invalid

### ISSUE THREAD

**Issue by matanshukry** [Unity-Technologies/InputSystem#940]
It seems the default input actions that can be created by the button on the PlayerInput component aren't actually working. To be more explicit, when I say "aren't working" - I'm talking about without any custom handlers, just the simple mouse click that will make a button highlight.

As far as I can tell, the broken part is the "Point" action. It includes a "Position [Pointer]" binding. I'm not sure what "Pointer" means, but it seems it doesn't mean mouse, and the mouse isn't working anymore.

To reproduce the issue:
1. Install the Input System package
2. Add the "On-Screen Controls" sample. Most of the sample is irrelevant, but it's still easier to refer to things to it since it's already made.
3. Choose one of the buttons and add a PlayerInput component to it.
4. Near the actions property, choose "Create Actions..."
5. set the default scheme to "KeyboardMouse" and Default Map to "UI"
6. On the UI Input Module, set the Event System game object
  6.a. Prior to this I have a "Input System UI Input Module" component attached to the "Event System" game object. I'm not sure if it's part of the sample, but if it isn't, just add it.
7. Choose the camera for the camera property
8. Play the game.
9. If you try to press any of the buttons - you can see nothing happens. They do not show any visual representation of them being pressed. If you disable the "PlayerInput" component, they do work.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

I tried to reproduce the issue following your steps but could not do so.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
