### ISSUE TITLE
[Bug] [NativeInputSystem] "should not get here"

### ISSUE THREAD

**Issue by matanshukry** [Unity-Technologies/InputSystem#941]
I have a UI game object and attached a PlayerInput component to it.
Using the "Invoke Unity Events" Behavior, I then added 2 callbacks to my "Back" action:

(1) Deactivate the current gameobject (it's a menu, hence I'm hiding it)
(2) Activating another game object (it's the previous menu, hence I'm showing it)

At first it works; that is, the current menu isn't visible, the previous one, and the relevant game objects are activated/deactivated correctly, but then input stops working and I'm seeing this error on the console (around 60 times):

Should not get here
```
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:120)
```

Note:
I found issue #757 with same error, although different issue. Last comment in there said it should be fixed in `1.0.0.preview-1`. When looking at my package, the line in the list says `Input System                preview.1 - 1.0.0`, and the version in the package details says only `Version 1.0.0`. I believe it is the latest update and the bug still exist, but correct me if I'm wrong.

**Comment by taliyahpottruff** [comment]
Getting this same issue. Is definitely not fixed

**Comment by Twin-Stick** [comment]
I'm also getting the same issue with the same steps to reproduce.
My version is v1.0.0.preview.2

NOTE: I can clear the errors by manually disabling and re-enabling the InputSystemUiInputModule component on the event system object.

It seems that it isn't letting go of the events when the action map is changed?

**Comment by Rene-Damm** [comment]
Hi @matanshukry, could you file a ticket with the Unity bug reporter with a repro?

**Comment by Twin-Stick** [comment]
@matanshukry - if you do, can you link the ticket here so I can follow.
I'm also happy to create a project to submit too if you'd like @Rene-Damm ?

**Comment by matanshukry** [comment]
Update:
(1) @Rene-Damm I filed a ticket with details same as here. Ticket 1198889. Link: http://fogbugz.unity3d.com/default.asp?1198889_42rlsqn3me7j8p6c
(2) I updated to v1.0.0.preview.3  and verified the issue still persist
(3) While the issue still exist in preview.3, it is a bit different. It includes 2 messages.

First:
```
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
UnityEngine.InputSystem.Utilities.InlinedArray`1[TValue].get_Item (System.Int32 index) (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Utilities/InlinedArray.cs:66)
UnityEngine.InputSystem.InputActionState.CallActionListeners (System.Int32 actionIndex, UnityEngine.InputSystem.InputActionMap actionMap, UnityEngine.InputSystem.InputActionPhase phase, UnityEngine.InputSystem.Utilities.InlinedArray`1[System.Action`1[UnityEngine.InputSystem.InputAction+CallbackContext]]& listeners) (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Actions/InputActionState.cs:1609)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:120)
```

Second:
```
ArgumentOutOfRangeException thrown during execution of 'Performed' callback on action 'UI/Click[/Mouse/leftButton]'
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at C:/buildslave/unity/build/Modules/Input/Private/Input.cs:120)
```

Just to clarify on how to reproduce this issue:

(1) Make sure you have an input asset with some action that can be easily done. The easiest would be the default one with a pointer click action
(2) Create a UI button and add a PlayerInput component to it. Fill in `UI Input Module` and `Actions` with the relevant objects
(3) Set `Behaviour` to `Invoke Unity Events`
(4) Expand Events property and find the desired action (e.g. Click).
(5) Add a callback to it
(5.1) Set the callback target to be the button it self
(5.2) Set the function to be GameObject.SetActive
(5.3) Make sure the checkbox is unchecked.
(6) Run and click the button

p.s.
I didn't attach a project to my ticket because my project is big and reproducing this issue shouldn't take more than a single minute, while looking through my project would take longer.

p.s.2
Just noticed the issue now seems to combine with the other issue I posted, #942 
I'm guessing they are duplicate, but I prefer to wait when one of the issues is fixed and I can verify the other one is fixed too, at which time I'll close both.

**Comment by Chifilly** [comment]
I'd like to also mention, I am still getting this issue (I was the creator of issue #757 ) even though it is mentioned that it was fixed in 1.0.0.preview-1 and I am currently using 1.0.0.preview-3 (I've been busy and haven't been able to check whether it was fixed)

**Comment by TOBassett** [comment]
I'm also having the same problem, as per issue #757. It _seems_ to work fine in spite of the error (I admit that I haven't done a particularly in-depth test), but every single input in the initial action map causes the error to pop up after switching back to that action map.

**Comment by JamhammerRob** [comment]
Still getting this error too on preview-3

**Comment by MykeWills** [comment]
This issue is stopping my release on Steam. I'm on preview3 "I get an index was outside of bounds of the array" and "should not get here", only when disconnecting the controllers. when disconnecting 2 or more and connecting them again messes up the gamepad mapping and player 1 or player 2 will control both players but the axis will be broken on one other the players.

**Comment by trudeaua** [comment]
Same issue occurred when switching from my "UI" to "Player" action maps on 1.0.0-preview.3

I was able to follow @ScrapGames 's [solution](https://github.com/Unity-Technologies/InputSystem/issues/941#issuecomment-554208528) and work around the error by disabling then enabling the `InputSystemUIInputModule` right after switching action maps.

```
public void SwitchCurrentActionMap(string name)
    {
        PlayerInput playerInput = GetComponent<PlayerInput>();
        InputSystemUIInputModule uIInputModule = GetComponent<InputSystemUIInputModule>();
        playerInput.SwitchCurrentActionMap(name);
        uIInputModule.enabled = false;
        uIInputModule.enabled = true;
    }
```

**Comment by smeas** [comment]
Having the same issue with 1.0.0-preview5.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
