### ISSUE TITLE
Version Control Implementation

### ISSUE THREAD

**Issue by inertiave** [Unity-Technologies/InputSystem#944]
![image](https://user-images.githubusercontent.com/51351749/68109427-d98cb800-ff2d-11e9-9f34-5e6999d9a36c.png)

Please also consider projects that using version control such as p4v.
It doesn't make sense to manually check out each time to save InputActionAsset.

Thanks.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
