### ISSUE TITLE
PS Dualshock4 via bluetooth on macOS 10.14 not recognized

### ISSUE THREAD

**Issue by eetteri** [Unity-Technologies/InputSystem#950]
Vanilla project with input system preview2-1.0.0 shows the Dualshock4 controller as 'Unknown Wireless Controller' when it is connected to mac via bluetooth. When connected with wire it is recognised correctly as 'DualShock4GamePadHID'. 

Is this known issue, configuration problem on my part or something else?

**Comment by Rene-Damm** [comment]
Does it work, though? Just wondering whether we're choosing the right layout and creating a fully functional gamepad but just end up using the product string from the OS here for naming and thus end up with a less than ideal name in this case.

**Comment by eetteri** [comment]
When connected via bluetooth, it is not recognised and it is not working.

**Comment by eetteri** [comment]
Just tried with preview3-1.0.0 and now the controller seems to be recognized correctly as  'DualShock4GamePadHID'.

[EDIT]
We'll I rushed here too hastily. There's something strange happening. On some occasion when the controllers are paired (I'm having two controller now) they show up both fine and in some occasions only the other is recognized as  'DualShock4GamePadHID' and the the other shows up as 'Unknown Wireless Controller'. I'll try to dig deeper and find some logic here.

**Comment by RealitySupply** [comment]
I'm using macOS 10.14.6 and preview3-1.0.0 and own two PS4 controllers. One is the newer version (where the light bar is visible on the top of the touchpad) the other is the original design.

Both work when wired, but when connected via bluetooth only the new one can be used. Both show up as unknown wireless controller when connected via bluetooth in the input debugger, but only the newer PS4 controller is functional in my project when connected via bluetooth. Happy to to provide more details if anything would be helpful.

**Comment by shawnflanagan** [comment]
> I'm using macOS 10.14.6 and preview3-1.0.0 and own two PS4 controllers. One is the newer version (where the light bar is visible on the top of the touchpad) the other is the original design.
> 
> Both work when wired, but when connected via bluetooth only the new one can be used. Both show up as unknown wireless controller when connected via bluetooth in the input debugger, but only the newer PS4 controller is functional in my project when connected via bluetooth. Happy to to provide more details if anything would be helpful.

Being that you are on macOS 10.14, I wonder if this is in part due to [macOS not officially supporting wireless PS4 controller pairing on versions older than 10.15](https://support.apple.com/en-us/HT210414).  Are you able to test it on macOS 10.15 and see if the "unknown wireless controller" issue persists? If you don't want to upgrade your system to macOS 10.15, Apple has [this handy support article](https://support.apple.com/en-us/HT208891) that walks you through the process of installing a second copy of macOS on your machine, ideally for the purpose of testing features in newer macOS versions than the one you are currently using for production.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
