### ISSUE TITLE
Oculus Quest controllers are matched as OculusHMD

### ISSUE THREAD

**Issue by Kleptine** [Unity-Technologies/InputSystem#953]
I'm using the very latest version of the InputSystem (the preview2 branch), and I'm seeing the Oculus Quest Touch controllers properly connect, but instead of controllers, they match as OculusHMD input devices!

I suspect this is because the match regexes are not specific enough. See the code at XRSupport:295:
![image](https://user-images.githubusercontent.com/1078792/68629455-d1d29380-0498-11ea-872b-cf0fa5c69c54.png)

See how any string that matches the regex for Oculus Quest Controller (`^(Oculus Quest Controller)`) is also matched by the regex for the Oculus HMD (`^(Oculus Quest)`).

**Comment by Kleptine** [comment]
Here is the fix, verified on the Quest. I just made the headset match only the full "Oculus Quest" string. https://github.com/AStrangerGravity/InputSystem/commit/8ef1bd489d27a2327c0bb13ea4494e5407ac6ab8

Oculus Quest input on device seems to be working great now, if that fix is applied.

**Comment by Rene-Damm** [comment]
@StayTalm

**Comment by zonopus** [comment]
@Rene-Damm @StayTalm Any update on this issue?  Currently, Oculus Quest does not work with with the new input system.  Kleptine's patch appears to fix the issues.

**Comment by m4ff** [comment]
@Rene-Damm @StayTalm the new Input System is still broken on Quest (Unity 2019.2.18f1 and package 1.0.0-preview.4).

**Comment by m4ff** [comment]
I can also confirm @Kleptine's patch fixes the issue. @Rene-Damm this bug was reported almost three months ago and it hasn't even be labelled as a bug. I am aware this will be eventually removed in favour of the new XR plugins, but given how easy the fix is, would it be possible to have it fixed soon to support legacy code?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
