### ISSUE TITLE
PlayerInput using a Default Scheme triggers an IndexOutOfRangeException: Index was outside the bounds of the array 

### ISSUE THREAD

**Issue by LuisAntonCanalis** [Unity-Technologies/InputSystem#956]
Using 1.0.0 preview 3

I have two players with a PlayerInput component each one.  No Manager. I'm forcing a control scheme switch with 

playerInput.SwitchCurrentControlScheme(InputDevice.all[ layerInput.playerIndex == 0 ? 0 : 2]);

I think it's quite a hack, but I'm trying to force one player to use Keyboard (0) and the second one a PS4 dualshock (2) or any joystick connected. InputDevice[1] seems to be the Mouse (my goal is to force players to use two gamepads if available, never keyboard/mouse).

Anyway, it works (players move, there's probably a better way, but it works). But when I stop the game or destroy one of the InputComponents I get this error. It seems related to forcing a Default Scheme. If I use <Any> I don't get this error.

IndexOutOfRangeException: Index was outside the bounds of the array.
(wrapper stelemref) System.Object.virt_stelemref_class_small_idepth(intptr,object)
UnityEngine.InputSystem.Utilities.ArrayHelpers.EraseSliceWithCapacity[TValue] (TValue[]& array, System.Int32& length, System.Int32 index, System.Int32 count) (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Utilities/ArrayHelpers.cs:742)
UnityEngine.InputSystem.Users.InputUser.RemoveUser (System.Int32 userIndex) (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Plugins/Users/InputUser.cs:1008)
UnityEngine.InputSystem.Users.InputUser.UnpairDevicesAndRemoveUser () (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Plugins/Users/InputUser.cs:656)
UnityEngine.InputSystem.PlayerInput.UnassignUserAndDevices () (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Plugins/PlayerInput/PlayerInput.cs:1290)
UnityEngine.InputSystem.PlayerInput.OnDisable () (at Library/PackageCache/com.unity.inputsystem@1.0.0-preview.3/InputSystem/Plugins/PlayerInput/PlayerInput.cs:1488)

**Comment by Notnasiul** [comment]
Ok, no, it's not related to SwitchCurrentControlScheme. It happens when any of those Input

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
