### ISSUE TITLE
[Unity 2019.2.12f1] Missing 2DVector Composite binding when clicking on the + button.

### ISSUE THREAD

**Issue by MlleDR** [Unity-Technologies/InputSystem#957]
Hi, here is a shot of the bug.

![InputSystemDisplayBug](https://user-images.githubusercontent.com/27687330/69006644-3cb91a00-0932-11ea-8a5d-434b26d2323f.gif)

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
