### ISSUE TITLE
[Bug][TouchScreen] Error with TouchScreen on Android using PlayerInput Component

### ISSUE THREAD

**Issue by SardineFish** [Unity-Technologies/InputSystem#958]
Error occured in InputSystem lowlevel update when using a PlayerInput Component on Android device.
`Cannot read control '/Touchscreen/pressure' from STAT with format TOUC; device 'Touchscreen:/Touchscreen' expects format TSCR`

Only happen when there is a active PlayerInput Component in scene.

**Comment by navaem** [comment]
I had the same issue using an iPhone XR. I fixed the issue by removing the PlayerInput Component from the scene.

**Comment by imenehellali** [comment]
I had the same problem, but then it looks like i forgot to create an inputsettings.asset. Go to Project Settings -> Input System-> then generate asset there .

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
