### ISSUE TITLE
[Android] <InputDevice>.current sometimes returns not the device we would expect

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#96]
Hey, this is more a feature request.

Currently on Android we have virtual and physical devices, as far as I can tell virtual devices are used for emulating input, though I haven't really be able to use them at this point.

So my case is, NVIDIA shield has a virtual mouse, and when I hook up real Mouse, Mouse.current returns virtual mouse instead of real one.

Would it be possible to introduce some kind of logic for MakeCurrent function, like IfMakeCurrent(), for Android I would check then if the device is virtual -> don't make it current then.

Any other ideas?

**Comment by Rene-Damm** [comment]
Yeah, I think this fits in with other issues I think `.current` has ATM. I think we want several extensions to the rather "dumb" logic that drives it ATM.

A related problem is noise. A noisy gamepad like the DualShock will always push itself to the front even if it just sits there on the desk. So we need the ability to tell 'noisy changes' from 'user actually actuated some real controls'.

I think having other stuff that influences this as well -- like excluding certain devices -- could make sense.

With the Android virtual devices I'm wondering, though, whether that'd be enough / the right thing. Are these devices for when you run in an emulator? If so, it'd seem that in the emulator, you'd actually want them to take precedence.

**Comment by Rene-Damm** [comment]
Oh wait, there's one more thing that puzzles me. From what I understand, you haven't seen actual event activity on the virtual mouse? But there's event activity on the real mouse, right? Does `.current` still return the virtual one in that case?

**Comment by todi1856** [comment]
Unless there were some recent changes, I think current was returning virtual device in some cases, even though no events ever came from that device... is there code preventing that?

**Comment by Rene-Damm** [comment]
It'd be made current when the device is added (another behavior about current that I think is worth reviewing) but after that, only events should make a device current.

**Comment by Rene-Damm** [comment]
`.current` has been removed.
