### ISSUE TITLE
Generate MonoBehaviour option

### ISSUE THREAD

**Issue by Ramobo** [Unity-Technologies/InputSystem#960]
Tying in with #889, we could have an option to generate input actions classes as `MonoBehaviour`s so we don't need to make a wrapper that requires an extra access ourselves. Then we'd add anything else we need via extension methods. Theoretically very simple, but I'm not exactly qualified to evaluate that.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
