### ISSUE TITLE
Joystick.all includes Keyboard and Mouse?

### ISSUE THREAD

**Issue by LuisAntonCanalis** [Unity-Technologies/InputSystem#961]
This piece of code

    Debug.Log("Joysticks: " + Joystick.all.Count);
    for (int i = 0; i < Joystick.all.Count; i++)
    {
        Debug.Log(Joystick.all[i].name);
    }

returns

Joysticks: 2
Keyboard
Mouse

Is that the expected behaviour?

**Comment by stefanunity** [comment]
Made this into a bug, see https://issuetracker.unity3d.com/product/unity/issues/guid/1231216/

**Comment by Rene-Damm** [comment]
This is an unfortunate side effect of how static properties work. There is no `Joystick.all` so what it really accesses is `InputDevice.all`. IMO we should nuke `InputDevice.all` as it simply equates to `InputSystem.devices` and leads to confusion like this case here.
