### ISSUE TITLE
Any mobile example?

### ISSUE THREAD

**Issue by vladimirdlc** [Unity-Technologies/InputSystem#963]
Was looking into the new Input System, quite practical! Is there a mobile example somewhere or some script to make this work on mobile?

Thanks!

**Comment by Tom60chat** [comment]
Yes in the editor: Window ->Package Manager -> Input System ->Touch Samples (Import in project)

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
