### ISSUE TITLE
"Replace with InputSystemUIModule" button doesn't dirty scene

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#964]
So basically:
- Create new scene
- Add UI button
- Save scene
- Click on EventSystem in Project View
- Click "Replace with InputSystemUIModule" 
- Open some other scene & get back to your original scene
- Notice, if you click on EventSystem the changes from "Replace with InputSystemUIModule" didn't persist, in other words, it didn't dirty the scene, thus the scene was not saved

**Comment by stefanunity** [comment]
This is fixed in the latest package version.
