### ISSUE TITLE
The use of "camera" hides underlying Component property "camera" generates compiler warnings.

### ISSUE THREAD

**Issue by weiping-playnext** [Unity-Technologies/InputSystem#967]
The following line generates compiler warnings when compiling.

https://github.com/Unity-Technologies/InputSystem/blob/cceab53d22ec09458f3fa45ccc5c7f3ecef169d9/Packages/com.unity.inputsystem/InputSystem/Plugins/PlayerInput/PlayerInput.cs#L619

Projects that flags warnings as errors would fail to build.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
