### ISSUE TITLE
Pressing multiple Bindings bound to a single Action disables the Bindings

### ISSUE THREAD

**Issue by laurirasanen** [Unity-Technologies/InputSystem#968]
We have a Button type Action with 2 different Bindings for Gamepads and 1 for Keyboard. Pressing both Gamepad Bindings simultaneously causes both of them to stop working.  

![image](https://user-images.githubusercontent.com/26773737/69800879-c55f7200-11de-11ea-8b65-0151dd20d516.png)  

Afterwards pressing either the Left Trigger or Button East will do nothing.  
Auto-Switch is enabled on our Player Input component and once X is pressed on the Keyboard, the following assertion is thrown as the control scheme switches: `Action has been triggered but apparently not from an interaction yet there's interactions on the binding that got triggered?!?`.

Unity version: `2019.2.5f1`  
Input System version: `1.0.0-preview.3`

**Comment by grabermtw** [comment]
I too am having this exact issue with pressing button North and left joystick up, which are both bindings for the same action.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
