### ISSUE TITLE
[Mac OS X] Renaming has problems with delete key and starts inserting unicode/non-printing characters in 2018.2bX

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#97]
This is on Fogbugz as case #1033948, as I wasn't sure if it was tied to the input framework initially, but confirmed it via further testing. Happens only on Mac OS X, not on windows as far as I can tell.

Repro 20 / 20

Renaming has problems with delete key and starts inserting unicode/non-printing characters.

1. What happened

When I try to rename a file, folder, or use most text fields in general, I cannot use the delete key as backspace, instead it starts inserting control code characters. Trying to use arrow keys in this state puts text input into a mode that adjusts letters to unicode variants or inserts unicode characters in general.

The only way to rename properly is to start over, make sure all text is selected, and delete will ONLY work in that state.

Issue doesn't affect any other program, including editing text files and code in VS/VS Code/sublime.

The commit included actually has several control codes that slipped through in certain text files and I had to manually edit them on my windows machine as that caused the windows compiler to complain about empty text. I narrowed it down to the name entry in Hydrogen.Variables.asmdef. A few other asmdef files were affected as well.

2. How we can reproduce it using the example you attached

Try to name a new file or rename an existing one,  or edit the name field of an assembly definition file editor:
* Press delete, and/or try to use arrow keys while holding shift to try and reselect text. Starts going into some unicode character input mode.

**Comment by Rene-Damm** [comment]
Thanks for the report. Have grabbed the FogBugz case and will take a look. Seems like the new backend is doing something bad to event processing. It's supposed to be a pure observer but seems like it's actually affecting event flow.

**Comment by douglas-piconi** [comment]
Fix is pending in 2018.3 (however requires module PR to land to be compiled)
Fix is in 2019.1

Waiting for backport to 2018.2, will manually backport if I don';t hear back from Kevin Welton.
