### ISSUE TITLE
Inputs fail to send events on first press upon switching action maps

### ISSUE THREAD

**Issue by le-capitaine** [Unity-Technologies/InputSystem#970]
That is, I have to press once and then a second time for a press to register. This is on Send Unity Events. I have two action maps for player input and UI input. Debug says the presses are in fact detected. Strangely, this only applies to my pause and UI buttons (Submit/Cancel). UI buttons are set on Pass Through/Any, pause has been tried on both Pass Through and Button with the same results.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
