### ISSUE TITLE
currentTouchState[i].delta on Android is wrong

### ISSUE THREAD

**Issue by zledas** [Unity-Technologies/InputSystem#971]
On Android (Nokia 7 plus) currentTouchState[i].delta is wrong. I get such values:
```
currentTouchState[i]. delta: (0.0, 0.0); startPosition: (312.7, 700.7); position: (743.8, 663.0)
currentTouchState[i]. delta: (-0.8, NaN); startPosition: (312.7, 700.7); position: (742.3, 663.7)
currentTouchState[i]. delta: (-1.6, NaN); startPosition: (312.7, 700.7); position: (737.3, 666.7)
```
when outputting right after 
```CSharp
                        // Compute delta if touch doesn't have one.
                        if (newTouchState.delta == default)
                            newTouchState.delta = newTouchState.position - currentTouchState[i].position;

                        // Accumulate delta.
                        newTouchState.delta += currentTouchState[i].delta;

                        UnityEngine.Debug.LogError(string.Format("currentTouchState[i]. delta: {0}; startPosition: {1}; position: {2}", currentTouchState[i].delta, currentTouchState[i].startPosition, currentTouchState[i].position));
```

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
