### ISSUE TITLE
AddBinding throws ArgumentException

### ISSUE THREAD

**Issue by jamre** [Unity-Technologies/InputSystem#973]
The documentation for `InputActionSetupExtensions.AddBinding(this InputAction action, InputBinding binding = default)` includes a usage example:
```cs
fireAction.AddBinding()
    .WithPath("<Gamepad>/buttonSouth")
    .WithGroup("Gamepad");
```
However, this code throws an `ArgumentException` that "Binding path cannot be null".

If the path can't be null, then the parameter shouldn't be optional (or the default `InputBinding` shouldn't have a null path).

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
