### ISSUE TITLE
SetMotorSpeeds doesn't work after starting game second time

### ISSUE THREAD

**Issue by ericlathrop** [Unity-Technologies/InputSystem#974]
When I play my game the first time, `SetMotorSpeeds` works, but after stopping playback and restarting it, it does nothing. No errors, it just silently does nothing.

To reproduce:

1. Press "play" to start game
2. Do something in the game to call `SetMotorSpeeds` to enable rumble.
3. Press "play" to stop game
4. Do something in the game to call `SetMotorSpeeds` to enable rumble. No rumble happens.

Tested on Linux with an Xbox 360 wired controller.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
