### ISSUE TITLE
InputSystem takes over 1sec to reload after a domain reload

### ISSUE THREAD

**Issue by strich** [Unity-Technologies/InputSystem#976]
A real concern for us has been the amount of time our project takes to reload after recompiling. As part of our investigation, InputSystem is taking over 1 second to perform various things after domain reload.
This seems far too high. Please investigate ways to reduce this. 

![image](https://user-images.githubusercontent.com/987896/70616372-2dae4a80-1c06-11ea-806b-da5f9ee209e4.png)

**Comment by Rene-Damm** [comment]
Could you post a snapshot with the `Reset()` branch expanded?

We've looked at this in the past and as things stand, it's certainly not ideal. However, 1s is *way* past what I'd expect and have seen. So would be curious as to where that is accumulating in the Reset.

Going forward, we have some things on the list to get reload times down. While there's no way around the fact that with the input system now largely living in managed land, reloads are a more complicated matter than with the entire system being in native, there's definitely things that can be improved. One thing is that device creation right now is costly. There's some work planned to get that cost down.

**Comment by strich** [comment]
Sure.
![image](https://user-images.githubusercontent.com/987896/70625568-93a4cd00-1c1a-11ea-8f5e-d8c8a7e31bb8.png)

**Comment by strich** [comment]
Here is a deep profile too:
![image](https://user-images.githubusercontent.com/987896/70626344-27c36400-1c1c-11ea-8694-c27d49474d1e.png)

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

I tried to reproduce this issue but was not able too. The times I profiled were all way less to what you were seeing.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
