### ISSUE TITLE
`Mouse.current.position` will return `0, 0` until the first movement

### ISSUE THREAD

**Issue by wilsonrivera** [Unity-Technologies/InputSystem#982]
Hello,

I don't know if this is a bug or what but, I have a simple script to make the weapon orbit the player, when I click play the position returned by the input action bound to `Mouse Position` return `0, 0` and calling `Mouse.current.position.ReadValue()` would yield the same result.

At first I thought this was an issue with the editor and built the project to test it out. The behavior is the same, event when the mouse position returns `0, 0` until the first movement.

This doesn't happen when using `Input.mousePosition`, even from the first frame, this returns the actual position of the mouse.

I have tested on Windows 10 and Mac OS and both yield the same result.
The version of the package is `preview 1.0.3` and using Unity `2019.3.0f3`

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!

**Comment by stefanunity** [comment]
Also see https://issuetracker.unity3d.com/product/unity/issues/guid/1231907/
