### ISSUE TITLE
Touch input does not work with InputSystemUIModule

### ISSUE THREAD

**Issue by infinstarlight** [Unity-Technologies/InputSystem#983]
I'm working a project with URP and Unity 2019.3 beta. I've been able to get Gamepad and KB/M input working without any issues. The biggest headache is with touch support. When I first added the package, the standard UI worked for my main menu but the On Screen controls prefab didn't. I was using the input system UI module and input was ignored no matter what I tried. I was using 2019.2.x at the time.

I created a new project in the beta and used the old StandaloneInputModule and my input was being processed with the on screen controls. I also found that if the cursor is locked, touch input is ignored. Is there a solution in the works for this problem?

**Comment by Jonathen-Colon** [comment]
the same thing is happening to me it annoying

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
