### ISSUE TITLE
Need to set the Scene.isDirty bool when user replaces StandaloneInputModule with InputSystemUIInputModule

### ISSUE THREAD

**Issue by coldcalifornian** [Unity-Technologies/InputSystem#984]
Pressing the "Replace with InputSystemUIInputModule" button on the StandaloneInputModule does not set the active scene.isDirty to true and the change is not saved.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
