### ISSUE TITLE
Playstation Controller now working after minimize and focus the game

### ISSUE THREAD

**Issue by StephanSchueritz** [Unity-Technologies/InputSystem#985]
We developing a game on Windows 10 using the InputSystem.
When using the playstation controller, everytime we minimize the game and open it again, all the input of the controller is not working anymore. No Axis and no Buttons.

I checked if the gamepad is still available and it is:
+ Gamepad.current = DualShock4GamepadHID 
+ Gamepad.current.enabled is true
+ Our MonoBehaviour that controls the input is also enabled and available

I also tried to use private void to use the Application Focus to enable/deactivate the device

        private void OnApplicationFocus(bool focus)
        {
            Debug.Log("OnApplicationFocus: " + focus);

            if(focus)
            {
                InputSystem.EnableDevice(Gamepad.current);
                UpdateControlSchema(Gamepad.current);
            }
            else
            {
                InputSystem.DisableDevice(Gamepad.current);
            }
        }

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!

**Comment by StephanSchueritz** [comment]
Hey Stefan,

thank you for coming back.
We will check it starting next week, I will let you know.

Best,
Stephan

Am Fr., 27. März 2020 um 17:20 Uhr schrieb StefanUnity <
notifications@github.com>:
