### ISSUE TITLE
Custom Composites with names that are prettified with spaces do not filter their parameters correctly.

### ISSUE THREAD

**Issue by itsmeted** [Unity-Technologies/InputSystem#986]
Take for example the attached composite named "TestTestComposite".  When you select the path for "Modifier" the inputaction editor, no filter is applied.  If we change the name of this composite to "TestComposite", then the filter works.

The reason is because the display name "Test Test" is used to look into the composite map (which doesn't work since it is looking for "TestTest"), whereas "Test" works since it is looking for "Test".

InputActionTreeViewItems.cs:492 calls GetExpectedControlLayoutName() using the prettified (with spaces) composite name from the tree view `var compositeName = ((CompositeBindingTreeItem)parent).name;`. 
The subsequent call to InputBindingComposite.cs:158, GetExpectedControlLayoutName() fails to find the composite type since it is looking for "Test Test" but expects the lookup to be by "TestTest"

```
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.Utilities;

#if UNITY_EDITOR
using UnityEditor;
using UnityEngine.InputSystem.Editor;
#endif

#if UNITY_EDITOR
[InitializeOnLoad]
#endif
public class TestTestComposite : InputBindingComposite<Vector2>
{
    // In the editor, the static class constructor will be called on startup
    // because of [InitializeOnLoad].
    #if UNITY_EDITOR
    static TestTestComposite()
    {
        // Trigger our RegisterBindingComposite code in the editor.
        Initialize();
    }

    #endif

    // In the player, [RuntimeInitializeOnLoadMethod] will make sure our
    // initialization code gets called during startup.
    [RuntimeInitializeOnLoadMethod]
    private static void Initialize()
    {
        InputSystem.RegisterBindingComposite<TestTestComposite>();
    }

    [InputControl(layout = "Button")]
    public int modifier;


    public override Vector2 ReadValue(ref InputBindingCompositeContext context)
    {
        return Vector2.zero;
    }
}
```

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
