### ISSUE TITLE
Player Input assigns the same gamepad to different game objects

### ISSUE THREAD

**Issue by Dogmeat-Keush** [Unity-Technologies/InputSystem#987]
1. Connect 2 xbox controllers.
2. Install new input system preview.3 1.0.0 on Unity 2019.2.17f1
3. Restart Unity
4. Go to Edit > Project settings > Player > Other settings > Active Input Handling > Input System (preview)
5. Restart Unity
6. Create Input Actions (it can be very simple such as moving the stick or the trigger, or use the one in the Tanks Demo as an example)
7. Add a cube to the hierarchy and add "Player Input" component to it.
8. Setup as in attached screenshot. 
9. Setup a script to receive the call backs from the Actions and log something to the console.
10. Create a sphere and do steps 7, 8 and 9.
11. You can also just duplicate the cube. The issue is the same. 
12. Select game objects and look at the inspector, they will state the paired device is the same.
13. Both gamepads will send to the same object.
14.  You can also look at the Input Debug

![image](https://user-images.githubusercontent.com/26726378/71388466-1a17c200-25be-11ea-8b74-2b094802d5d8.png)

I've also tried making prefabs out of the cubes and have a script instantiate the prefabs, but still the Player Input assigns the same gamepad.

![image](https://user-images.githubusercontent.com/26726378/71388558-78dd3b80-25be-11ea-86e7-2e64b1c344c6.png)

![image](https://user-images.githubusercontent.com/26726378/71388540-69f68900-25be-11ea-8a92-496a0dc68f88.png)

What I don't get is why the example for the Tanks demo found here: https://github.com/Unity-Technologies/InputSystem/releases/download/1.0.0.0/TanksDemo-1.0.0.0.unitypackage works properly and assigns a different gamepad to each player every time. 

Am I missing anything?

**Comment by JoRouss** [comment]
I don't really undestand why yet, but I managed to get this to work by adding a "Gamepad" control sheme to the "Input Action Importer".
![image](https://user-images.githubusercontent.com/17717723/72648529-41597900-3949-11ea-8e27-a0b822643f86.png)

**Comment by interior-night** [comment]
Are you using the PlayerInputManager with PlayerInput?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
