### ISSUE TITLE
Regression of unfound test assembly - 2019.3.0f3 - package 1.0.0-preview.3

### ISSUE THREAD

**Issue by builder-main** [Unity-Technologies/InputSystem#989]
I'm having an issue with the test assembly although I followed the guide in https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/Testing.html, package does not show up in assembly explorer and references can't resolve. 2019.3.0f3 - package 1.0.0-preview.3

As a side note, the assembly is not present in Library\ScriptAssemblies. 

```c#
using UnityEngine.InputSystem;

    [TestFixture]
    public class BindingInputTest : InputTestFixture
```

![image](https://user-images.githubusercontent.com/32265170/71562462-bd664c80-2a80-11ea-910c-165580248dfe.png)

My test assembly configuration :

![image](https://user-images.githubusercontent.com/32265170/71562467-cbb46880-2a80-11ea-90c4-a1be792b0c71.png)

![image](https://user-images.githubusercontent.com/32265170/71562474-d40ca380-2a80-11ea-829e-d48317f896ef.png)

_Originally posted by @MorphiksBuilder in https://github.com/Unity-Technologies/InputSystem/issues/366#issuecomment-569538609_

**Comment by MeikelLP** [comment]
Still broken in preview 4. This is bonkers even for a preview. Quality assurance is a big topic it seems.

**Comment by Rene-Damm** [comment]
Unfortunately, due to how this works now in the package manager, it now requires a workaround that isn't mentioned in the docs page.

Basically, in your Packages/manifest.json file, you need to add

```
"testables" : [ "com.unity.inputsystem" ]
```

in order for the test framework assembly to be included in test builds.

I'll see if we can find a better solution or at least make sure this bit gets included in the docs.

**Comment by Rene-Damm** [comment]
Also just noticed that doing this now results in an integration test test from the input system showing up in user projects, too. It's the only test that gets added directly to the package ATM. Looking into it.

**Comment by MeikelLP** [comment]
@Rene-Damm your workaround `testables` does not work for me.

**Comment by Rene-Damm** [comment]
@MeikelLP Could you provide some more details? What's the error? What exactly isn't working?

I've tried the setup with 1.0.0-preview.4 and after adding the snippet to Packages/manifest.json was able to set up a test assembly just fine. Other than having to modify the manifest in the first place, only wart was the input system injecting a test into the project.

**Comment by MeikelLP** [comment]
I get the exact same error as the OP 
![image](https://user-images.githubusercontent.com/11669846/74458685-5cf16a00-4e8a-11ea-8f7a-1ecd7db7c5f2.png)

**Comment by Rene-Damm** [comment]
Is the file in a separate test assembly that references the input system test framework assembly?

**Comment by MeikelLP** [comment]
it is yes. I'm working with several assembly definition files

**Comment by Rene-Damm** [comment]
Please file a ticket with the Unity bug reporter. We'll have a look.

**Comment by MeikelLP** [comment]
So today on my personal machine I installed Unity 2019.3.1f1 and it seems to be fixed when setting the `testables` like @Rene-Damm said.

**Comment by jo3w4rd** [comment]
Would this page have helped you with your problem if you had found it?
https://docs.unity3d.com/Manual/cus-tests.html

**Comment by MeikelLP** [comment]
@jo3w4rd  I don't want to include the tests of a package. I want to use a class inside a package which wasn't possible without `testables`

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!

**Comment by builder-main** [comment]
This issue is still alive for us, unity 2019.3.11f1 and the latest package 1.0.0. We're not creating a package, simply having an asmdef for our playmode tests. 

We've added in the manifest : "testables" : [ "com.unity.inputsystem" ]

[EDIT] : We added the compile flag UNITY_INCLUDE_TESTS and it seems to work
