### ISSUE TITLE
Disabling analytics leads to compile error

### ISSUE THREAD

**Issue by skjalgsm** [Unity-Technologies/InputSystem#990]
Almost the same error as #163 

`Library\PackageCache\com.unity.inputsystem@0.2.1-preview\InputSystem\NativeInputRuntime.cs(233,13): error CS0012: The type 'AnalyticsResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Library\PackageCache\com.unity.inputsystem@0.2.1-preview\InputSystem\NativeInputRuntime.cs(242,13): error CS0012: The type 'AnalyticsResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
`

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
