### ISSUE TITLE
[1.0.0-preview.3] InputActionReference breaks when renaming action maps or actions

### ISSUE THREAD

**Issue by Ramobo** [Unity-Technologies/InputSystem#991]
Renaming them back to what it was fixes the reference, meaning that they're saved by name instead of a GUID.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
