### ISSUE TITLE
TouchSample don't work with Win32 Touchscreen

### ISSUE THREAD

**Issue by Tom60chat** [Unity-Technologies/InputSystem#992]
When I create the application on my tablet (Windows), only the mouse works, but not the touch screen, same thing when I use the simulated touch screen in the editor, but it works well on my Android device.
I see on Rolling Scene that VirtualControls remains active only on Android and iOS because of the script (which I disabled and it is the only one that works with my tablet).
Did I miss something?

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
