### ISSUE TITLE
When using PlayerInput and Input system UI input module

### ISSUE THREAD

**Issue by Jonathen-Colon** [Unity-Technologies/InputSystem#995]
I am trying to use the PlayerInput component and Input system UI input module but using on ios or simulated touchscreen the On-Screen Stick is not working. It also doesn't work with the mouse either. Please help have been trying all day.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
