### ISSUE TITLE
Rebind bug, arrows => print screen

### ISSUE THREAD

**Issue by BibaDev** [Unity-Technologies/InputSystem#996]
If we have turned off Num Lock and we click on the arrows, then put Print Screen.

At the same time, everything works fine in the editor (Shortcuts), the problem is in the Input System.

On the screenshot of tanks demo.

Bug only in InputSystem, editor normal work.

Version 1.0.0
Unity 2019.3.0f3

![image](https://user-images.githubusercontent.com/59769710/72206212-a9c5d780-34bd-11ea-89af-6ea0f6ba2dc0.png)

![image](https://user-images.githubusercontent.com/59769710/72206225-c4984c00-34bd-11ea-9531-9951043c8531.png)

**Comment by BibaDev** [comment]
I've seen the old issues, but it's not a native bug.

**Comment by BibaDev** [comment]
In the editor, if num lock is disabled and the listen button is pressed, everything works correctly

![image](https://user-images.githubusercontent.com/59769710/72206367-71bf9400-34bf-11ea-93ce-04d60139d533.png)

**Comment by lordscales91** [comment]
Not sure if you are still around but. Are you using a PS/2 keyboard by chance? I'm experiencing the same issue and that seems to be the cause.
